/** Lyoko theme color tokens */
export const THEME = {
  lyokoBlue: "#00d4ff",
  lyokoGreen: "#00ff88",
  lyokoPurple: "#a855f7",
  xanaRed: "#ff2244",
  carthageGold: "#fbbf24",
  darkBg: "#050a18",
  darkSurface: "#0a1628",
  darkCard: "#0f1f3a",
} as const;

export const SITE = {
  name: "PROJET CARTHAGE",
  title: "Formation Code Gratuite en Ligne — 1100+ Exercices | PROJET CARTHAGE",
  description:
    "Apprenez à coder gratuitement avec 1100+ exercices interactifs : HTML, CSS, JavaScript, Python, React, Node.js, C#, C++, Dart & Flutter. Formation en ligne 100% gratuite, sans abonnement, sans pub. Exercices gamifiés avec XP, badges, classement et battle code en ligne.",
  url: "https://gamematcher.fr",
  locale: "fr_FR",
  creator: "Projet Carthage",
  keywords: [
    // ── Requêtes génériques formation/code ──
    "apprendre à coder",
    "apprendre à coder gratuitement",
    "apprendre à programmer",
    "apprendre la programmation",
    "apprendre le code",
    "apprendre le code en ligne",
    "formation code",
    "formation code gratuite",
    "formation codage",
    "formation codage gratuite",
    "formation codage en ligne",
    "formation programmation",
    "formation programmation gratuite",
    "formation programmation en ligne",
    "formation développement web",
    "formation développement web gratuite",
    "formation dev web",
    "formation informatique gratuite",
    "formation informatique en ligne",
    "cours de code",
    "cours de code gratuit",
    "cours de code en ligne",
    "cours de programmation",
    "cours de programmation gratuit",
    "cours de programmation en ligne",
    "cours de codage",
    "cours de codage gratuit",
    "cours développement web",
    "cours développement web gratuit",
    "cours informatique gratuit",
    "cours informatique en ligne",
    "site pour apprendre à coder",
    "site pour apprendre à coder gratuitement",
    "site pour apprendre la programmation",
    "site pour apprendre le code",
    "plateforme apprentissage code",
    "plateforme formation code",
    "plateforme pour apprendre à coder",
    "meilleur site pour apprendre à coder",
    "meilleur site pour apprendre à coder gratuitement",
    "apprendre à coder débutant",
    "apprendre à coder de zéro",
    "apprendre à coder depuis zéro",
    "débuter en programmation",
    "débuter en code",
    "initiation au code",
    "initiation à la programmation",
    "tuto code",
    "tuto programmation",
    "tutoriel programmation",
    "tutoriel code gratuit",
    // ── Exercices interactifs ──
    "exercices de code",
    "exercices de code en ligne",
    "exercices de programmation",
    "exercices de programmation en ligne",
    "exercices de codage",
    "exercices interactifs code",
    "exercices interactifs programmation",
    "exercices code gratuit",
    "pratiquer le code en ligne",
    "s'entraîner à coder",
    "challenges de code",
    "défis de programmation",
    // ── Par langage ──
    "apprendre HTML",
    "apprendre CSS",
    "apprendre JavaScript",
    "apprendre JavaScript gratuitement",
    "cours JavaScript gratuit",
    "exercices JavaScript",
    "formation JavaScript",
    "apprendre Python",
    "apprendre Python gratuitement",
    "cours Python gratuit",
    "exercices Python",
    "formation Python",
    "apprendre React",
    "cours React gratuit",
    "exercices React",
    "formation React",
    "apprendre Node.js",
    "cours Node.js gratuit",
    "exercices Node.js",
    "formation Node.js",
    "apprendre C#",
    "cours C# gratuit",
    "exercices C#",
    "formation C#",
    "apprendre C++",
    "cours C++ gratuit",
    "exercices C++",
    "formation C++",
    "apprendre Dart",
    "apprendre Flutter",
    "cours Dart Flutter gratuit",
    "exercices Dart Flutter",
    "formation Dart Flutter",
    "apprendre HTML CSS",
    "exercices HTML CSS",
    "cours HTML CSS gratuit",
    "formation HTML CSS",
    "apprendre le front-end",
    "formation front-end",
    "apprendre le back-end",
    "formation back-end",
    "formation fullstack",
    "formation fullstack gratuite",
    "apprendre le développement mobile",
    "formation développement mobile",
    // ── Gamification / Battle ──
    "gamification programmation",
    "apprendre à coder en jouant",
    "apprendre le code en s'amusant",
    "battle code en ligne",
    "défi code en ligne",
    "compétition de code",
    "coding game gratuit",
    "jeu de programmation",
    // ── Cibles ──
    "formation code débutant",
    "formation code pour débutant",
    "apprendre à coder pour débutant",
    "apprendre à coder pour les nuls",
    "apprendre à coder adulte",
    "reconversion développeur web",
    "reconversion programmation",
    "reconversion informatique",
    "formation développeur web gratuite",
    "devenir développeur web",
    "devenir développeur",
    "devenir programmeur",
    // ── Alternatives connues ──
    "alternative Codecademy gratuite",
    "alternative OpenClassrooms gratuite",
    "comme Codecademy mais gratuit",
    "site comme OpenClassrooms gratuit",
    "Code Lyoko",
  ] as string[],
} as const;

export const MODULES = [
  {
    id: "frontend",
    name: "Front-End",
    description: "HTML, CSS, Bootstrap, Bulma, SCSS, JS DOM — 250 niveaux",
    icon: "Palette",
    color: "#e34c26",
    href: "/exercises/frontend",
    levels: 250,
    available: true,
  },
  {
    id: "javascript",
    name: "JavaScript",
    description: "Le langage du web moderne et interactif — 102 niveaux",
    icon: "Braces",
    color: "#f7df1e",
    href: "/exercises/javascript",
    levels: 102,
    available: true,
  },
  {
    id: "python",
    name: "Python",
    description: "IA, data science et automatisation — 120 niveaux",
    icon: "Terminal",
    color: "#3776ab",
    href: "/exercises/python",
    levels: 120,
    available: true,
  },
  {
    id: "csharp",
    name: "C# & .NET",
    description: "Applications desktop et serveur — 120 niveaux",
    icon: "Monitor",
    color: "#68217a",
    href: "/exercises/csharp",
    levels: 120,
    available: true,
  },
  {
    id: "dart",
    name: "Dart & Flutter",
    description: "Applications mobiles multiplateformes — 150 niveaux",
    icon: "Smartphone",
    color: "#02569B",
    href: "/exercises/dart",
    levels: 150,
    available: true,
  },
  {
    id: "react",
    name: "React",
    description: "Interfaces utilisateur modernes et réactives — 120 niveaux",
    icon: "Atom",
    color: "#61dafb",
    href: "/exercises/react",
    levels: 120,
    available: true,
  },
  {
    id: "nodejs",
    name: "Node.js",
    description: "Backend JavaScript et APIs — 120 niveaux",
    icon: "Server",
    color: "#68a063",
    href: "/exercises/nodejs",
    levels: 120,
    available: true,
  },
  {
    id: "cpp",
    name: "C / C++",
    description: "Programmation système bas niveau — 120 niveaux",
    icon: "Cpu",
    color: "#A8B9CC",
    href: "/exercises/cpp",
    levels: 120,
    available: true,
  },
] as const;

export const BLOCS = [
  {
    id: "fullstack",
    name: "Bloc Fullstack",
    description:
      "Maîtrisez le développement web complet : du front-end au back-end. Construisez les interfaces de Lyoko et les serveurs du supercalculateur.",
    color: "#00d4ff",
    icon: "Globe",
    sector: "Secteur Web",
    modules: ["frontend", "javascript", "react", "nodejs"],
  },
  {
    id: "mobile",
    name: "Bloc Mobile",
    description:
      "Développez des applications mobiles pour communiquer avec Lyoko depuis n'importe où. Le lien entre le monde réel et le virtuel.",
    color: "#00ff88",
    icon: "Smartphone",
    sector: "Secteur Mobile",
    modules: ["dart"],
  },
  {
    id: "desktop",
    name: "Bloc Desktop",
    description:
      "Programmez les logiciels du supercalculateur. Le cœur de la machine qui fait tourner Lyoko et combat XANA directement.",
    color: "#a855f7",
    icon: "Monitor",
    sector: "Secteur Système",
    modules: ["csharp", "python", "cpp"],
  },
] as const;
