/** Lyoko theme color tokens */
export const THEME = {
  lyokoBlue: "#00d4ff",
  lyokoGreen: "#00ff88",
  lyokoPurple: "#a855f7",
  xanaRed: "#ff2244",
  carthageGold: "#fbbf24",
  darkBg: "#050a18",
  darkSurface: "#0a1628",
  darkCard: "#0f1f3a",
} as const;

export const SITE = {
  name: "PROJET CARTHAGE",
  title: "PROJET CARTHAGE – Apprenez à coder dans l'univers de Code Lyoko",
  description:
    "Plateforme 100% GRATUITE de formation au code inspirée de Code Lyoko. Maîtrisez HTML, CSS, JavaScript, Python, C#, Dart & Flutter à travers 1100+ exercices gamifiés avec XP, badges et classements. Sans abonnement, sans pub.",
  url: "https://projet-carthage.fr",
  locale: "fr_FR",
  creator: "Projet Carthage",
  keywords: [
    "apprendre à coder",
    "formation développement web",
    "cours programmation gratuit",
    "formation code gratuite",
    "apprendre à coder gratuitement",
    "Code Lyoko",
    "exercices JavaScript",
    "exercices Python",
    "exercices HTML CSS",
    "exercices C#",
    "exercices Dart Flutter",
    "plateforme apprentissage code",
    "gamification programmation",
    "cours interactifs code",
  ] as string[],
} as const;

export const MODULES = [
  {
    id: "frontend",
    name: "Front-End",
    description: "HTML, CSS, Bootstrap, Bulma, SCSS, JS DOM — 250 niveaux",
    icon: "Palette",
    color: "#e34c26",
    href: "/exercises/frontend",
    levels: 250,
    available: true,
  },
  {
    id: "javascript",
    name: "JavaScript",
    description: "Le langage du web moderne et interactif — 102 niveaux",
    icon: "Braces",
    color: "#f7df1e",
    href: "/exercises/javascript",
    levels: 102,
    available: true,
  },
  {
    id: "python",
    name: "Python",
    description: "IA, data science et automatisation — 120 niveaux",
    icon: "Terminal",
    color: "#3776ab",
    href: "/exercises/python",
    levels: 120,
    available: true,
  },
  {
    id: "csharp",
    name: "C# & .NET",
    description: "Applications desktop et serveur — 120 niveaux",
    icon: "Monitor",
    color: "#68217a",
    href: "/exercises/csharp",
    levels: 120,
    available: true,
  },
  {
    id: "dart",
    name: "Dart & Flutter",
    description: "Applications mobiles multiplateformes — 150 niveaux",
    icon: "Smartphone",
    color: "#02569B",
    href: "/exercises/dart",
    levels: 150,
    available: true,
  },
  {
    id: "react",
    name: "React",
    description: "Interfaces utilisateur modernes et réactives — 120 niveaux",
    icon: "Atom",
    color: "#61dafb",
    href: "/exercises/react",
    levels: 120,
    available: true,
  },
  {
    id: "nodejs",
    name: "Node.js",
    description: "Backend JavaScript et APIs — 120 niveaux",
    icon: "Server",
    color: "#68a063",
    href: "/exercises/nodejs",
    levels: 120,
    available: true,
  },
  {
    id: "cpp",
    name: "C / C++",
    description: "Programmation système bas niveau — 120 niveaux",
    icon: "Cpu",
    color: "#A8B9CC",
    href: "/exercises/cpp",
    levels: 120,
    available: true,
  },
] as const;

export const BLOCS = [
  {
    id: "fullstack",
    name: "Bloc Fullstack",
    description:
      "Maîtrisez le développement web complet : du front-end au back-end. Construisez les interfaces de Lyoko et les serveurs du supercalculateur.",
    color: "#00d4ff",
    icon: "Globe",
    sector: "Secteur Web",
    modules: ["frontend", "javascript", "react", "nodejs"],
  },
  {
    id: "mobile",
    name: "Bloc Mobile",
    description:
      "Développez des applications mobiles pour communiquer avec Lyoko depuis n'importe où. Le lien entre le monde réel et le virtuel.",
    color: "#00ff88",
    icon: "Smartphone",
    sector: "Secteur Mobile",
    modules: ["dart"],
  },
  {
    id: "desktop",
    name: "Bloc Desktop",
    description:
      "Programmez les logiciels du supercalculateur. Le cœur de la machine qui fait tourner Lyoko et combat XANA directement.",
    color: "#a855f7",
    icon: "Monitor",
    sector: "Secteur Système",
    modules: ["csharp", "python", "cpp"],
  },
] as const;
