import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/**
 * Module C — Part 5 : pointeurs avancés, tableaux 2D, chaînes plus profondes.
 */
const exercises: Exercise[] = [
  {
    id: "c_31",
    type: "code",
    category: "Pointeurs avancés",
    title: "Arithmétique de pointeur",
    description: "Avancer un pointeur dans un tableau.",
    instruction: `À partir de <code>int t[] = {10, 20, 30, 40, 50};</code> et <code>int *p = t;</code>, affichez <code>*(p + 3)</code>.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {10, 20, 30, 40, 50};\n    int *p = t;\n    // Afficher l'élément à l'index 3 via arithmétique de pointeur\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {10, 20, 30, 40, 50};\n    int *p = t;\n    printf("%d\\n", *(p + 3));\n    return 0;\n}\n`,
    tests: [
      { type: "regex", expected: "\\*\\(p\\s*\\+\\s*3\\)|p\\[3\\]" },
      { type: "output", expected_output: "40" },
    ],
  },
  {
    id: "c_32",
    type: "code",
    category: "Pointeurs avancés",
    title: "Pointeur de pointeur",
    description: "Accéder à une valeur via int **.",
    instruction: `Soit <code>int n = 7;</code>, <code>int *p = &amp;n;</code>, <code>int **pp = &amp;p;</code>. Affichez <code>**pp</code>.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int n = 7;\n    int *p = &n;\n    int **pp = &p;\n    // Affichez **pp\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int n = 7;\n    int *p = &n;\n    int **pp = &p;\n    printf("%d\\n", **pp);\n    return 0;\n}\n`,
    tests: [
      { type: "contains", expected: "**pp" },
      { type: "output", expected_output: "7" },
    ],
  },
  {
    id: "c_33",
    type: "code",
    category: "Pointeurs avancés",
    title: "Tableau passé en argument",
    description: "Fonction qui modifie un tableau.",
    instruction: `Écrivez <code>void doubler(int *t, int n)</code> qui multiplie chaque élément par 2, testez avec <code>{1, 2, 3, 4}</code>, puis affichez les éléments séparés par espaces.`,
    code_template: `#include <stdio.h>\n\nvoid doubler(int *t, int n) {\n    // votre code\n}\n\nint main(void) {\n    int t[] = {1, 2, 3, 4};\n    doubler(t, 4);\n    for (int i = 0; i < 4; i++) printf("%d ", t[i]);\n    printf("\\n");\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nvoid doubler(int *t, int n) {\n    for (int i = 0; i < n; i++) t[i] *= 2;\n}\n\nint main(void) {\n    int t[] = {1, 2, 3, 4};\n    doubler(t, 4);\n    for (int i = 0; i < 4; i++) printf("%d ", t[i]);\n    printf("\\n");\n    return 0;\n}\n`,
    tests: [
      { type: "regex", expected: "t\\[i\\]\\s*\\*=|t\\[i\\]\\s*=\\s*t\\[i\\]\\s*\\*\\s*2" },
      { type: "output", expected_output: "2 4 6 8" },
    ],
  },
  {
    id: "c_34",
    type: "code",
    category: "Pointeurs avancés",
    title: "Pointeur sur fonction",
    description: "Variable pointant vers une fonction.",
    instruction: `Définissez <code>int carre(int x){ return x*x; }</code>, puis déclarez <code>int (*f)(int) = carre;</code> et affichez <code>f(9)</code>.`,
    code_template: `#include <stdio.h>\n\nint carre(int x) { return x * x; }\n\nint main(void) {\n    // pointeur sur fonction\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint carre(int x) { return x * x; }\n\nint main(void) {\n    int (*f)(int) = carre;\n    printf("%d\\n", f(9));\n    return 0;\n}\n`,
    tests: [
      { type: "regex", expected: "int\\s*\\(\\s*\\*\\s*f\\s*\\)" },
      { type: "output", expected_output: "81" },
    ],
  },
  {
    id: "c_35",
    type: "code",
    category: "Pointeurs avancés",
    title: "Pointeur const",
    description: "Empêcher la modification via pointeur.",
    instruction: `Déclarez <code>const int *p</code> sur une variable <code>x = 42</code> et affichez <code>*p</code>. Un pointeur <code>const int *</code> empêche la modification via *p.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int x = 42;\n    // const int *p\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int x = 42;\n    const int *p = &x;\n    printf("%d\\n", *p);\n    return 0;\n}\n`,
    tests: [
      { type: "regex", expected: "const\\s+int\\s*\\*" },
      { type: "output", expected_output: "42" },
    ],
  },
  {
    id: "c_36",
    type: "code",
    category: "Tableaux 2D",
    title: "Matrice 3×3",
    description: "Initialiser et afficher.",
    instruction: `Déclarez <code>int m[3][3] = {{1,2,3},{4,5,6},{7,8,9}};</code> puis affichez la <strong>diagonale</strong> (m[0][0], m[1][1], m[2][2]) séparée par espaces.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int m[3][3] = {{1,2,3},{4,5,6},{7,8,9}};\n    // diagonale\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int m[3][3] = {{1,2,3},{4,5,6},{7,8,9}};\n    for (int i = 0; i < 3; i++) printf("%d ", m[i][i]);\n    printf("\\n");\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "1 5 9" }],
  },
  {
    id: "c_37",
    type: "code",
    category: "Tableaux 2D",
    title: "Somme des lignes",
    description: "Total par ligne d'une matrice.",
    instruction: `Pour la matrice <code>{{1,2,3},{4,5,6}}</code>, affichez la somme de chaque ligne séparée par espace.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int m[2][3] = {{1,2,3},{4,5,6}};\n    // sommes\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int m[2][3] = {{1,2,3},{4,5,6}};\n    for (int i = 0; i < 2; i++) {\n        int s = 0;\n        for (int j = 0; j < 3; j++) s += m[i][j];\n        printf("%d ", s);\n    }\n    printf("\\n");\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "6 15" }],
  },
  {
    id: "c_38",
    type: "code",
    category: "Tableaux 2D",
    title: "Transposée 2×2",
    description: "Inverser lignes et colonnes.",
    instruction: `Transposez <code>{{1,2},{3,4}}</code> et affichez la matrice résultante ligne par ligne, valeurs séparées par espace.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int m[2][2] = {{1,2},{3,4}};\n    int t[2][2];\n    // transposition\n    for (int i = 0; i < 2; i++) {\n        for (int j = 0; j < 2; j++) printf("%d ", t[i][j]);\n        printf("\\n");\n    }\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int m[2][2] = {{1,2},{3,4}};\n    int t[2][2];\n    for (int i = 0; i < 2; i++)\n        for (int j = 0; j < 2; j++) t[j][i] = m[i][j];\n    for (int i = 0; i < 2; i++) {\n        for (int j = 0; j < 2; j++) printf("%d ", t[i][j]);\n        printf("\\n");\n    }\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "1 3 \n2 4" }],
  },
  {
    id: "c_39",
    type: "code",
    category: "Tableaux 2D",
    title: "Damier",
    description: "Générer un motif 4×4.",
    instruction: `Affichez un damier 4×4 où une case sur deux est <code>X</code> et l'autre <code>.</code> (commencez par X en haut à gauche).`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    // damier\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    for (int i = 0; i < 4; i++) {\n        for (int j = 0; j < 4; j++) putchar((i+j)%2 == 0 ? 'X' : '.');\n        putchar('\\n');\n    }\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "X.X.\n.X.X\nX.X.\n.X.X" }],
  },
  {
    id: "c_40",
    type: "code",
    category: "Tableaux 2D",
    title: "Identité 3×3",
    description: "Matrice diagonale avec 1.",
    instruction: `Générez et affichez la matrice identité 3×3, lignes séparées par retour ligne, valeurs séparées par espace.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    // matrice identité\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    for (int i = 0; i < 3; i++) {\n        for (int j = 0; j < 3; j++) printf("%d ", i == j ? 1 : 0);\n        printf("\\n");\n    }\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "1 0 0 \n0 1 0 \n0 0 1" }],
  },
  {
    id: "c_41",
    type: "code",
    category: "Chaînes avancées",
    title: "strcat",
    description: "Concaténer deux chaînes.",
    instruction: `Concaténez <code>"Hello, "</code> et <code>"World!"</code> dans un buffer <code>char buf[64]</code> avec <code>strcpy</code> + <code>strcat</code>, puis affichez.`,
    code_template: `#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n    char buf[64];\n    // strcpy + strcat\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n    char buf[64];\n    strcpy(buf, "Hello, ");\n    strcat(buf, "World!");\n    printf("%s\\n", buf);\n    return 0;\n}\n`,
    tests: [
      { type: "contains", expected: "strcat" },
      { type: "output", expected_output: "Hello, World!" },
    ],
  },
  {
    id: "c_42",
    type: "code",
    category: "Chaînes avancées",
    title: "Convertir en majuscules",
    description: "toupper sur chaque caractère.",
    instruction: `Convertissez <code>"lyoko"</code> en majuscules avec <code>toupper</code> et affichez le résultat.`,
    code_template: `#include <stdio.h>\n#include <ctype.h>\n#include <string.h>\n\nint main(void) {\n    char s[] = "lyoko";\n    // toupper\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <ctype.h>\n#include <string.h>\n\nint main(void) {\n    char s[] = "lyoko";\n    for (int i = 0; s[i]; i++) s[i] = toupper((unsigned char)s[i]);\n    printf("%s\\n", s);\n    return 0;\n}\n`,
    tests: [
      { type: "contains", expected: "toupper" },
      { type: "output", expected_output: "LYOKO" },
    ],
  },
  {
    id: "c_43",
    type: "code",
    category: "Chaînes avancées",
    title: "Compter une occurrence",
    description: "Combien de fois 'o' apparaît.",
    instruction: `Comptez les <code>'o'</code> dans <code>"Code Lyoko"</code> et affichez le total.`,
    code_template: `#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n    const char *s = "Code Lyoko";\n    int n = 0;\n    // compter\n    printf("%d\\n", n);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n    const char *s = "Code Lyoko";\n    int n = 0;\n    for (int i = 0; s[i]; i++) if (s[i] == 'o') n++;\n    printf("%d\\n", n);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "3" }],
  },
  {
    id: "c_44",
    type: "code",
    category: "Chaînes avancées",
    title: "Remplacer un caractère",
    description: "'.' devient ' ' (espace).",
    instruction: `Dans la chaîne <code>"a.b.c.d"</code>, remplacez tous les '.' par ' ' et affichez le résultat.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    char s[] = "a.b.c.d";\n    // remplacer\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    char s[] = "a.b.c.d";\n    for (int i = 0; s[i]; i++) if (s[i] == '.') s[i] = ' ';\n    printf("%s\\n", s);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "a b c d" }],
  },
  {
    id: "c_45",
    type: "code",
    category: "Chaînes avancées",
    title: "Inverser une chaîne",
    description: "In-place reversal.",
    instruction: `Inversez <code>"reverse"</code> en place et affichez.`,
    code_template: `#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n    char s[] = "reverse";\n    // inverser\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n    char s[] = "reverse";\n    int n = strlen(s);\n    for (int i = 0, j = n - 1; i < j; i++, j--) { char t = s[i]; s[i] = s[j]; s[j] = t; }\n    printf("%s\\n", s);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "esrever" }],
  },
  {
    id: "c_46",
    type: "code",
    category: "Chaînes avancées",
    title: "strstr",
    description: "Recherche de sous-chaîne.",
    instruction: `Cherchez <code>"oko"</code> dans <code>"Code Lyoko"</code> avec <code>strstr</code>. Affichez <code>oui</code> si trouvé, <code>non</code> sinon.`,
    code_template: `#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n    const char *s = "Code Lyoko";\n    // strstr\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n    const char *s = "Code Lyoko";\n    printf("%s\\n", strstr(s, "oko") ? "oui" : "non");\n    return 0;\n}\n`,
    tests: [
      { type: "contains", expected: "strstr" },
      { type: "output", expected_output: "oui" },
    ],
  },
  {
    id: "c_47",
    type: "code",
    category: "Chaînes avancées",
    title: "Compter les mots",
    description: "Mots séparés par espaces.",
    instruction: `Comptez les mots dans <code>"un deux trois quatre"</code> et affichez le total.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    const char *s = "un deux trois quatre";\n    int n = 0;\n    // compter\n    printf("%d\\n", n);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    const char *s = "un deux trois quatre";\n    int n = 0;\n    int in = 0;\n    for (int i = 0; s[i]; i++) {\n        if (s[i] != ' ' && !in) { n++; in = 1; }\n        else if (s[i] == ' ') in = 0;\n    }\n    printf("%d\\n", n);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "4" }],
  },
  {
    id: "c_48",
    type: "code",
    category: "Chaînes avancées",
    title: "atoi maison",
    description: "Convertir une chaîne en entier.",
    instruction: `Convertissez <code>"42"</code> en entier sans utiliser <code>atoi</code> (seulement arithmétique sur les caractères), puis affichez le résultat × 2.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    const char *s = "42";\n    int n = 0;\n    // conversion\n    printf("%d\\n", n * 2);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    const char *s = "42";\n    int n = 0;\n    for (int i = 0; s[i]; i++) n = n * 10 + (s[i] - '0');\n    printf("%d\\n", n * 2);\n    return 0;\n}\n`,
    tests: [
      { type: "not_contains", expected: "atoi" },
      { type: "output", expected_output: "84" },
    ],
  },
  {
    id: "c_49",
    type: "code",
    category: "Chaînes avancées",
    title: "isdigit",
    description: "Vérifier qu'une chaîne est numérique.",
    instruction: `Vérifiez si <code>"12345"</code> ne contient que des chiffres avec <code>isdigit</code>. Affichez <code>oui</code> ou <code>non</code>.`,
    code_template: `#include <stdio.h>\n#include <ctype.h>\n\nint main(void) {\n    const char *s = "12345";\n    int allDigits = 1;\n    // vérifier\n    printf("%s\\n", allDigits ? "oui" : "non");\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <ctype.h>\n\nint main(void) {\n    const char *s = "12345";\n    int allDigits = 1;\n    for (int i = 0; s[i]; i++) if (!isdigit((unsigned char)s[i])) { allDigits = 0; break; }\n    printf("%s\\n", allDigits ? "oui" : "non");\n    return 0;\n}\n`,
    tests: [
      { type: "contains", expected: "isdigit" },
      { type: "output", expected_output: "oui" },
    ],
  },
  {
    id: "c_50",
    type: "code",
    category: "Chaînes avancées",
    title: "Concaténer N copies",
    description: "Répéter une chaîne.",
    instruction: `Construisez la chaîne <code>"ab"</code> répétée 4 fois (résultat : <code>"abababab"</code>) dans un buffer de 32 chars, puis affichez.`,
    code_template: `#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n    char buf[32] = "";\n    // répéter\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n    char buf[32] = "";\n    for (int i = 0; i < 4; i++) strcat(buf, "ab");\n    printf("%s\\n", buf);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "abababab" }],
  },
  {
    id: "c_51",
    type: "code",
    category: "Conversion de types",
    title: "Cast float → int",
    description: "Tronquer un flottant.",
    instruction: `Castez <code>3.99</code> en <code>int</code> et affichez le résultat (sans arrondi, juste la troncature).`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    double x = 3.99;\n    // cast\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    double x = 3.99;\n    int n = (int)x;\n    printf("%d\\n", n);\n    return 0;\n}\n`,
    tests: [
      { type: "regex", expected: "\\(int\\)" },
      { type: "output", expected_output: "3" },
    ],
  },
  {
    id: "c_52",
    type: "code",
    category: "Conversion de types",
    title: "Division entière vs flottante",
    description: "Forcer la division flottante.",
    instruction: `Affichez le résultat de <code>7 / 2</code> en flottant (1 décimale) en castant le numérateur.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int a = 7, b = 2;\n    // forcer division flottante\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int a = 7, b = 2;\n    printf("%.1f\\n", (double)a / b);\n    return 0;\n}\n`,
    tests: [
      { type: "regex", expected: "\\(double\\)|\\(float\\)" },
      { type: "output", expected_output: "3.5" },
    ],
  },
  {
    id: "c_53",
    type: "code",
    category: "Conversion de types",
    title: "Caractère → int",
    description: "ASCII value.",
    instruction: `Affichez la valeur ASCII du caractère <code>'A'</code>.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    char c = 'A';\n    // afficher en %d\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    char c = 'A';\n    printf("%d\\n", (int)c);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "65" }],
  },
  {
    id: "c_54",
    type: "code",
    category: "Math",
    title: "Puissance",
    description: "pow() de math.h.",
    instruction: `Calculez <code>2^10</code> avec <code>pow</code> et affichez le résultat en entier.`,
    code_template: `#include <stdio.h>\n#include <math.h>\n\nint main(void) {\n    // 2^10\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <math.h>\n\nint main(void) {\n    int r = (int)pow(2, 10);\n    printf("%d\\n", r);\n    return 0;\n}\n`,
    tests: [
      { type: "contains", expected: "pow" },
      { type: "output", expected_output: "1024" },
    ],
    hint: "Compilez avec -lm si nécessaire (Piston le fait automatiquement).",
  },
  {
    id: "c_55",
    type: "code",
    category: "Math",
    title: "Racine carrée",
    description: "sqrt().",
    instruction: `Affichez <code>sqrt(144)</code> en entier.`,
    code_template: `#include <stdio.h>\n#include <math.h>\n\nint main(void) {\n    // sqrt(144)\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <math.h>\n\nint main(void) {\n    printf("%d\\n", (int)sqrt(144));\n    return 0;\n}\n`,
    tests: [
      { type: "contains", expected: "sqrt" },
      { type: "output", expected_output: "12" },
    ],
  },
  {
    id: "c_56",
    type: "code",
    category: "Math",
    title: "Valeur absolue",
    description: "abs() pour entiers.",
    instruction: `Affichez <code>abs(-42)</code>.`,
    code_template: `#include <stdio.h>\n#include <stdlib.h>\n\nint main(void) {\n    // abs(-42)\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <stdlib.h>\n\nint main(void) {\n    printf("%d\\n", abs(-42));\n    return 0;\n}\n`,
    tests: [
      { type: "contains", expected: "abs" },
      { type: "output", expected_output: "42" },
    ],
  },
  {
    id: "c_57",
    type: "code",
    category: "Math",
    title: "Min de 3 entiers",
    description: "Sans utiliser de bibliothèque.",
    instruction: `Pour <code>a=5, b=2, c=8</code>, calculez et affichez le minimum (sans fmin/min).`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int a = 5, b = 2, c = 8;\n    // calcul du min\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int a = 5, b = 2, c = 8;\n    int min = a;\n    if (b < min) min = b;\n    if (c < min) min = c;\n    printf("%d\\n", min);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "2" }],
  },
  {
    id: "c_58",
    type: "code",
    category: "Math",
    title: "Ackermann (petit)",
    description: "Fonction récursive classique (m=2, n=3).",
    instruction: `Implémentez <code>int ack(int m, int n)</code> et affichez <code>ack(2, 3)</code>. La fonction d'Ackermann : ack(0,n)=n+1 ; ack(m,0)=ack(m-1,1) ; ack(m,n)=ack(m-1, ack(m,n-1)).`,
    code_template: `#include <stdio.h>\n\nint ack(int m, int n) {\n    // récursion\n    return 0;\n}\n\nint main(void) {\n    printf("%d\\n", ack(2, 3));\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint ack(int m, int n) {\n    if (m == 0) return n + 1;\n    if (n == 0) return ack(m - 1, 1);\n    return ack(m - 1, ack(m, n - 1));\n}\n\nint main(void) {\n    printf("%d\\n", ack(2, 3));\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "9" }],
  },
  {
    id: "c_59",
    type: "code",
    category: "Math",
    title: "Nombre parfait",
    description: "Somme des diviseurs propres.",
    instruction: `Un nombre est parfait si la somme de ses diviseurs propres (autres que lui-même) vaut le nombre. Affichez <code>oui</code> si <code>28</code> est parfait, sinon <code>non</code>.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int n = 28;\n    int s = 0;\n    // calculer\n    printf("%s\\n", s == n ? "oui" : "non");\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int n = 28;\n    int s = 0;\n    for (int i = 1; i < n; i++) if (n % i == 0) s += i;\n    printf("%s\\n", s == n ? "oui" : "non");\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "oui" }],
  },
  {
    id: "c_60",
    type: "code",
    category: "Math",
    title: "Compter les chiffres",
    description: "Nombre de chiffres d'un entier.",
    instruction: `Comptez le nombre de chiffres de <code>1234567</code> (sans utiliser <code>printf</code> pour mesurer).`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int n = 1234567;\n    int count = 0;\n    // compter\n    printf("%d\\n", count);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int n = 1234567;\n    int count = 0;\n    while (n > 0) { n /= 10; count++; }\n    printf("%d\\n", count);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "7" }],
  },
];

addExercises("c", exercises);
