import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/** Module C — Part 12 : bits, préprocesseur, unions, projets divers. */
const exercises: Exercise[] = [
  { id: "c_226", type: "code", category: "Bits", title: "AND bit à bit", description: "Opérateur &.", instruction: "Affichez <code>12 &amp; 10</code> (résultat : 8).", code_template: "#include <stdio.h>\nint main(void) {\n    // \n    return 0;\n}\n", solution: "#include <stdio.h>\nint main(void) {\n    printf(\"%d\\n\", 12 & 10);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "8" }] },
  { id: "c_227", type: "code", category: "Bits", title: "OR bit à bit", description: "Opérateur |.", instruction: "Affichez <code>12 | 10</code> (résultat : 14).", code_template: "#include <stdio.h>\nint main(void) {\n    return 0;\n}\n", solution: "#include <stdio.h>\nint main(void) {\n    printf(\"%d\\n\", 12 | 10);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "14" }] },
  { id: "c_228", type: "code", category: "Bits", title: "XOR bit à bit", description: "Opérateur ^.", instruction: "Affichez <code>12 ^ 10</code> (résultat : 6).", code_template: "#include <stdio.h>\nint main(void) {\n    return 0;\n}\n", solution: "#include <stdio.h>\nint main(void) {\n    printf(\"%d\\n\", 12 ^ 10);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "6" }] },
  { id: "c_229", type: "code", category: "Bits", title: "NOT bit à bit", description: "Complément ~.", instruction: "Pour <code>unsigned char x = 0xF0</code>, affichez <code>~x</code> (=0x0F = 15).", code_template: "#include <stdio.h>\nint main(void) {\n    unsigned char x = 0xF0;\n    // \n    return 0;\n}\n", solution: "#include <stdio.h>\nint main(void) {\n    unsigned char x = 0xF0;\n    printf(\"%d\\n\", (unsigned char)~x);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "15" }] },
  { id: "c_230", type: "code", category: "Bits", title: "Décalage gauche", description: "Multiplication par 2^n.", instruction: "Affichez <code>1 &lt;&lt; 4</code> (résultat : 16).", code_template: "#include <stdio.h>\nint main(void) {\n    return 0;\n}\n", solution: "#include <stdio.h>\nint main(void) {\n    printf(\"%d\\n\", 1 << 4);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "16" }] },
  { id: "c_231", type: "code", category: "Bits", title: "Décalage droite", description: "Division par 2^n.", instruction: "Affichez <code>32 &gt;&gt; 2</code> (résultat : 8).", code_template: "#include <stdio.h>\nint main(void) {\n    return 0;\n}\n", solution: "#include <stdio.h>\nint main(void) {\n    printf(\"%d\\n\", 32 >> 2);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "8" }] },
  { id: "c_232", type: "code", category: "Bits", title: "Tester un bit", description: "Bit n d'un entier.", instruction: "Affichez le bit 2 de 13 (=0b1101) → 1.", code_template: "#include <stdio.h>\nint main(void) {\n    int x = 13;\n    // bit 2\n    return 0;\n}\n", solution: "#include <stdio.h>\nint main(void) {\n    int x = 13;\n    printf(\"%d\\n\", (x >> 2) & 1);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "1" }] },
  { id: "c_233", type: "code", category: "Bits", title: "Set un bit", description: "Activer un bit.", instruction: "Activez le bit 1 de 8 (=0b1000) → 10.", code_template: "#include <stdio.h>\nint main(void) {\n    int x = 8;\n    // x |= (1 << 1)\n    return 0;\n}\n", solution: "#include <stdio.h>\nint main(void) {\n    int x = 8;\n    x |= (1 << 1);\n    printf(\"%d\\n\", x);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "10" }] },
  { id: "c_234", type: "code", category: "Bits", title: "Clear un bit", description: "Désactiver un bit.", instruction: "Effacez le bit 0 de 7 (=0b111) → 6.", code_template: "#include <stdio.h>\nint main(void) {\n    int x = 7;\n    // \n    return 0;\n}\n", solution: "#include <stdio.h>\nint main(void) {\n    int x = 7;\n    x &= ~(1 << 0);\n    printf(\"%d\\n\", x);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "6" }] },
  { id: "c_235", type: "code", category: "Bits", title: "Toggle un bit", description: "Inverser un bit.", instruction: "Toggle le bit 1 de 6 (=0b110) → 4.", code_template: "#include <stdio.h>\nint main(void) {\n    int x = 6;\n    // \n    return 0;\n}\n", solution: "#include <stdio.h>\nint main(void) {\n    int x = 6;\n    x ^= (1 << 1);\n    printf(\"%d\\n\", x);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "4" }] },
  { id: "c_236", type: "code", category: "Bits", title: "Compter bits à 1", description: "Population count.", instruction: "Comptez les bits à 1 dans 13 (=0b1101) → 3.", code_template: "#include <stdio.h>\nint main(void) {\n    int x = 13, count = 0;\n    // \n    return 0;\n}\n", solution: "#include <stdio.h>\nint main(void) {\n    int x = 13, count = 0;\n    while (x) { count += x & 1; x >>= 1; }\n    printf(\"%d\\n\", count);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "3" }] },
  { id: "c_237", type: "code", category: "Bits", title: "Puissance de 2", description: "Vérifier x & (x-1) == 0.", instruction: "Vérifiez si 16 est une puissance de 2 (résultat : 1).", code_template: "#include <stdio.h>\nint main(void) {\n    int x = 16;\n    // \n    return 0;\n}\n", solution: "#include <stdio.h>\nint main(void) {\n    int x = 16;\n    printf(\"%d\\n\", (x > 0 && (x & (x - 1)) == 0) ? 1 : 0);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "1" }] },
  { id: "c_238", type: "code", category: "Préprocesseur", title: "#define constante", description: "Constante symbolique.", instruction: "Définissez <code>#define PI 3</code> et affichez PI.", code_template: "#include <stdio.h>\n// #define PI\nint main(void) {\n    // printf PI\n    return 0;\n}\n", solution: "#include <stdio.h>\n#define PI 3\nint main(void) {\n    printf(\"%d\\n\", PI);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "3" }] },
  { id: "c_239", type: "code", category: "Préprocesseur", title: "Macro avec argument", description: "Macro fonction.", instruction: "Définissez <code>#define SQ(x) ((x)*(x))</code> et affichez SQ(5) (=25).", code_template: "#include <stdio.h>\n// #define SQ\nint main(void) {\n    return 0;\n}\n", solution: "#include <stdio.h>\n#define SQ(x) ((x)*(x))\nint main(void) {\n    printf(\"%d\\n\", SQ(5));\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "25" }] },
  { id: "c_240", type: "code", category: "Préprocesseur", title: "Compilation conditionnelle", description: "#ifdef DEBUG.", instruction: "Avec <code>#define DEBUG</code> puis <code>#ifdef DEBUG</code>, affichez \"dbg\".", code_template: "#include <stdio.h>\n// \nint main(void) {\n    return 0;\n}\n", solution: "#include <stdio.h>\n#define DEBUG\nint main(void) {\n#ifdef DEBUG\n    printf(\"dbg\\n\");\n#endif\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "dbg" }] },
  { id: "c_241", type: "code", category: "Préprocesseur", title: "Stringify #", description: "Convertir token en string.", instruction: "Définissez <code>#define STR(x) #x</code> et affichez <code>STR(hello)</code>.", code_template: "#include <stdio.h>\n// \nint main(void) {\n    return 0;\n}\n", solution: "#include <stdio.h>\n#define STR(x) #x\nint main(void) {\n    printf(\"%s\\n\", STR(hello));\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "hello" }] },
  { id: "c_242", type: "code", category: "Préprocesseur", title: "Concaténation ##", description: "Token paste.", instruction: "Définissez <code>#define CAT(a,b) a##b</code> et affichez <code>CAT(va,r1)</code> avec <code>int var1=7</code>.", code_template: "#include <stdio.h>\n// \nint main(void) {\n    int var1 = 7;\n    return 0;\n}\n", solution: "#include <stdio.h>\n#define CAT(a,b) a##b\nint main(void) {\n    int var1 = 7;\n    printf(\"%d\\n\", CAT(va, r1));\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "7" }] },
  { id: "c_243", type: "code", category: "Union", title: "Union basique", description: "Mémoire partagée.", instruction: "Définissez <code>union U { int i; float f; }</code> et écrivez/lisez <code>u.i = 42</code>.", code_template: "#include <stdio.h>\nunion U { int i; float f; };\nint main(void) {\n    union U u;\n    // \n    return 0;\n}\n", solution: "#include <stdio.h>\nunion U { int i; float f; };\nint main(void) {\n    union U u;\n    u.i = 42;\n    printf(\"%d\\n\", u.i);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "42" }] },
  { id: "c_244", type: "code", category: "Union", title: "sizeof union", description: "Taille = max des membres.", instruction: "Affichez <code>sizeof(union U)</code> avec int + double (résultat : 8).", code_template: "#include <stdio.h>\nunion U { int i; double d; };\nint main(void) {\n    return 0;\n}\n", solution: "#include <stdio.h>\nunion U { int i; double d; };\nint main(void) {\n    printf(\"%zu\\n\", sizeof(union U));\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "8" }] },
  { id: "c_245", type: "code", category: "Bitfield", title: "Champs de bits dans struct", description: "Économiser la mémoire.", instruction: "Définissez <code>struct Flags { unsigned a:1; unsigned b:1; }</code>. Mettez a=1, b=0, affichez a+b.", code_template: "#include <stdio.h>\nstruct Flags { unsigned a:1; unsigned b:1; };\nint main(void) {\n    struct Flags f;\n    // \n    return 0;\n}\n", solution: "#include <stdio.h>\nstruct Flags { unsigned a:1; unsigned b:1; };\nint main(void) {\n    struct Flags f;\n    f.a = 1; f.b = 0;\n    printf(\"%d\\n\", f.a + f.b);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "1" }] },
  { id: "c_246", type: "code", category: "Enum", title: "Enum typique", description: "Constantes nommées.", instruction: "Définissez <code>enum Color { RED, GREEN, BLUE }</code> et affichez <code>GREEN</code> (=1).", code_template: "#include <stdio.h>\nenum Color { RED, GREEN, BLUE };\nint main(void) {\n    return 0;\n}\n", solution: "#include <stdio.h>\nenum Color { RED, GREEN, BLUE };\nint main(void) {\n    printf(\"%d\\n\", GREEN);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "1" }] },
  { id: "c_247", type: "code", category: "Type", title: "typedef struct", description: "Alias de type.", instruction: "Définissez <code>typedef struct { int x; } Point</code> et créez un Point avec x=5.", code_template: "#include <stdio.h>\ntypedef struct { int x; } Point;\nint main(void) {\n    // \n    return 0;\n}\n", solution: "#include <stdio.h>\ntypedef struct { int x; } Point;\nint main(void) {\n    Point p = {5};\n    printf(\"%d\\n\", p.x);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "5" }] },
  { id: "c_248", type: "code", category: "Génériques", title: "_Generic (C11)", description: "Dispatch par type.", instruction: "Avec <code>_Generic(x, int: \"int\", float: \"float\")</code>, affichez le type d'<code>int x = 1</code>.", code_template: "#include <stdio.h>\nint main(void) {\n    int x = 1;\n    // \n    return 0;\n}\n", solution: "#include <stdio.h>\nint main(void) {\n    int x = 1;\n    printf(\"%s\\n\", _Generic(x, int: \"int\", float: \"float\", default: \"?\"));\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "int" }] },
  { id: "c_249", type: "code", category: "Variadiques", title: "Fonction à arguments variables", description: "stdarg.h.", instruction: "Définissez <code>int sum(int n, ...)</code> avec <code>va_list</code>, somme de 3 args : 1+2+3.", code_template: "#include <stdio.h>\n#include <stdarg.h>\nint sum(int n, ...) {\n    // va_list, va_start, va_arg, va_end\n    return 0;\n}\nint main(void) {\n    printf(\"%d\\n\", sum(3, 1, 2, 3));\n    return 0;\n}\n", solution: "#include <stdio.h>\n#include <stdarg.h>\nint sum(int n, ...) {\n    va_list ap;\n    va_start(ap, n);\n    int s = 0;\n    for (int i = 0; i < n; i++) s += va_arg(ap, int);\n    va_end(ap);\n    return s;\n}\nint main(void) {\n    printf(\"%d\\n\", sum(3, 1, 2, 3));\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "6" }] },
  { id: "c_250", type: "code", category: "Projet final", title: "Mini calculatrice", description: "Operations + - * / par switch.", instruction: "Lisez non — appliquez l'op <code>'+'</code> à 7 et 3 dans un switch, affichez 10.", code_template: "#include <stdio.h>\nint main(void) {\n    char op = '+';\n    int a = 7, b = 3, r = 0;\n    // switch\n    return 0;\n}\n", solution: "#include <stdio.h>\nint main(void) {\n    char op = '+';\n    int a = 7, b = 3, r = 0;\n    switch (op) {\n        case '+': r = a + b; break;\n        case '-': r = a - b; break;\n        case '*': r = a * b; break;\n        case '/': r = b ? a / b : 0; break;\n    }\n    printf(\"%d\\n\", r);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "10" }] },
];

addExercises("c", exercises);
