import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/**
 * Module C — Part 8 : algorithmes avancés, dichotomie, DP, math, divers.
 */
const exercises: Exercise[] = [
  {
    id: "c_121",
    type: "code",
    category: "Algorithmes avancés",
    title: "Recherche dichotomique",
    description: "Binary search dans un tableau trié.",
    instruction: `Cherchez <code>23</code> dans <code>{1, 3, 5, 7, 11, 17, 23, 29, 31}</code> par dichotomie. Affichez l'indice (réponse : 6).`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {1, 3, 5, 7, 11, 17, 23, 29, 31};\n    int n = 9, target = 23;\n    int lo = 0, hi = n - 1;\n    int idx = -1;\n    // dichotomie\n    printf("%d\\n", idx);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {1, 3, 5, 7, 11, 17, 23, 29, 31};\n    int n = 9, target = 23;\n    int lo = 0, hi = n - 1;\n    int idx = -1;\n    while (lo <= hi) {\n        int mid = (lo + hi) / 2;\n        if (t[mid] == target) { idx = mid; break; }\n        if (t[mid] < target) lo = mid + 1;\n        else hi = mid - 1;\n    }\n    printf("%d\\n", idx);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "6" }],
  },
  {
    id: "c_122",
    type: "code",
    category: "Tri",
    title: "Tri par sélection",
    description: "Selection sort.",
    instruction: `Triez <code>{64, 25, 12, 22, 11}</code> avec selection sort. Affichez le résultat.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {64, 25, 12, 22, 11};\n    int n = 5;\n    // selection sort\n    for (int i = 0; i < n; i++) printf("%d ", t[i]);\n    printf("\\n");\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {64, 25, 12, 22, 11};\n    int n = 5;\n    for (int i = 0; i < n - 1; i++) {\n        int mi = i;\n        for (int j = i + 1; j < n; j++) if (t[j] < t[mi]) mi = j;\n        int tmp = t[i]; t[i] = t[mi]; t[mi] = tmp;\n    }\n    for (int i = 0; i < n; i++) printf("%d ", t[i]);\n    printf("\\n");\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "11 12 22 25 64" }],
  },
  {
    id: "c_123",
    type: "code",
    category: "Tri",
    title: "Tri par insertion",
    description: "Insertion sort.",
    instruction: `Triez <code>{12, 11, 13, 5, 6}</code> avec insertion sort. Affichez le résultat.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {12, 11, 13, 5, 6};\n    int n = 5;\n    // insertion sort\n    for (int i = 0; i < n; i++) printf("%d ", t[i]);\n    printf("\\n");\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {12, 11, 13, 5, 6};\n    int n = 5;\n    for (int i = 1; i < n; i++) {\n        int key = t[i];\n        int j = i - 1;\n        while (j >= 0 && t[j] > key) { t[j+1] = t[j]; j--; }\n        t[j+1] = key;\n    }\n    for (int i = 0; i < n; i++) printf("%d ", t[i]);\n    printf("\\n");\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "5 6 11 12 13" }],
  },
  {
    id: "c_124",
    type: "code",
    category: "Tri",
    title: "qsort de stdlib",
    description: "Utiliser la fonction de tri standard.",
    instruction: `Triez <code>{40, 10, 100, 90, 20, 25}</code> avec <code>qsort</code> + une fonction de comparaison <code>int cmp(const void *a, const void *b)</code>. Affichez le résultat.`,
    code_template: `#include <stdio.h>\n#include <stdlib.h>\n\nint cmp(const void *a, const void *b) {\n    // votre code\n    return 0;\n}\n\nint main(void) {\n    int t[] = {40, 10, 100, 90, 20, 25};\n    int n = 6;\n    qsort(t, n, sizeof(int), cmp);\n    for (int i = 0; i < n; i++) printf("%d ", t[i]);\n    printf("\\n");\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <stdlib.h>\n\nint cmp(const void *a, const void *b) {\n    int x = *(const int *)a, y = *(const int *)b;\n    return (x > y) - (x < y);\n}\n\nint main(void) {\n    int t[] = {40, 10, 100, 90, 20, 25};\n    int n = 6;\n    qsort(t, n, sizeof(int), cmp);\n    for (int i = 0; i < n; i++) printf("%d ", t[i]);\n    printf("\\n");\n    return 0;\n}\n`,
    tests: [
      { type: "contains", expected: "qsort" },
      { type: "output", expected_output: "10 20 25 40 90 100" },
    ],
  },
  {
    id: "c_125",
    type: "code",
    category: "Tri",
    title: "Tri à bulles optimisé",
    description: "Stop si pas de swap.",
    instruction: `Implémentez bubble sort avec un flag "swapped" : si aucune permutation à un passage, on arrête. Triez <code>{3, 1, 4, 1, 5, 9, 2, 6}</code>.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {3, 1, 4, 1, 5, 9, 2, 6};\n    int n = 8;\n    // bubble optimisé\n    for (int i = 0; i < n; i++) printf("%d ", t[i]);\n    printf("\\n");\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {3, 1, 4, 1, 5, 9, 2, 6};\n    int n = 8;\n    for (int i = 0; i < n - 1; i++) {\n        int swapped = 0;\n        for (int j = 0; j < n - i - 1; j++) {\n            if (t[j] > t[j+1]) { int tmp = t[j]; t[j] = t[j+1]; t[j+1] = tmp; swapped = 1; }\n        }\n        if (!swapped) break;\n    }\n    for (int i = 0; i < n; i++) printf("%d ", t[i]);\n    printf("\\n");\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "1 1 2 3 4 5 6 9" }],
  },
  {
    id: "c_126",
    type: "code",
    category: "Tri",
    title: "Merge de 2 tableaux triés",
    description: "Étape clef du merge sort.",
    instruction: `Fusionnez <code>{1, 3, 5, 7}</code> et <code>{2, 4, 6, 8}</code> en un tableau trié. Affichez le résultat.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int a[] = {1, 3, 5, 7};\n    int b[] = {2, 4, 6, 8};\n    int n = 4, m = 4;\n    int c[8];\n    int i = 0, j = 0, k = 0;\n    // merge\n    for (int x = 0; x < 8; x++) printf("%d ", c[x]);\n    printf("\\n");\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int a[] = {1, 3, 5, 7};\n    int b[] = {2, 4, 6, 8};\n    int n = 4, m = 4;\n    int c[8];\n    int i = 0, j = 0, k = 0;\n    while (i < n && j < m) c[k++] = a[i] < b[j] ? a[i++] : b[j++];\n    while (i < n) c[k++] = a[i++];\n    while (j < m) c[k++] = b[j++];\n    for (int x = 0; x < 8; x++) printf("%d ", c[x]);\n    printf("\\n");\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "1 2 3 4 5 6 7 8" }],
  },
  {
    id: "c_127",
    type: "code",
    category: "Number theory",
    title: "Test de primalité",
    description: "Vérifier qu'un nombre est premier.",
    instruction: `Vérifiez si <code>97</code> est premier (boucle jusqu'à √n). Affichez <code>oui</code> ou <code>non</code>.`,
    code_template: `#include <stdio.h>\n#include <math.h>\n\nint main(void) {\n    int n = 97;\n    int prime = 1;\n    // tester\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <math.h>\n\nint main(void) {\n    int n = 97;\n    int prime = 1;\n    if (n < 2) prime = 0;\n    else for (int i = 2; (long)i * i <= n; i++) if (n % i == 0) { prime = 0; break; }\n    printf("%s\\n", prime ? "oui" : "non");\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "oui" }],
  },
  {
    id: "c_128",
    type: "code",
    category: "Number theory",
    title: "Crible d'Ératosthène",
    description: "Tous les nombres premiers ≤ 30.",
    instruction: `Trouvez tous les nombres premiers jusqu'à 30 avec le crible d'Ératosthène. Affichez-les séparés par espaces.`,
    code_template: `#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n    int sieve[31];\n    // crible\n    // afficher\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n    int sieve[31];\n    for (int i = 0; i < 31; i++) sieve[i] = 1;\n    sieve[0] = sieve[1] = 0;\n    for (int i = 2; i * i <= 30; i++) if (sieve[i]) for (int j = i * i; j <= 30; j += i) sieve[j] = 0;\n    for (int i = 2; i <= 30; i++) if (sieve[i]) printf("%d ", i);\n    printf("\\n");\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "2 3 5 7 11 13 17 19 23 29" }],
  },
  {
    id: "c_129",
    type: "code",
    category: "Number theory",
    title: "PPCM",
    description: "Plus petit commun multiple.",
    instruction: `Calculez le PPCM (LCM) de 12 et 18 via PGCD : ppcm = (a*b) / pgcd(a,b). Réponse : 36.`,
    code_template: `#include <stdio.h>\n\nint pgcd(int a, int b) { return b == 0 ? a : pgcd(b, a % b); }\n\nint main(void) {\n    int a = 12, b = 18;\n    // ppcm\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint pgcd(int a, int b) { return b == 0 ? a : pgcd(b, a % b); }\n\nint main(void) {\n    int a = 12, b = 18;\n    printf("%d\\n", (a * b) / pgcd(a, b));\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "36" }],
  },
  {
    id: "c_130",
    type: "code",
    category: "Number theory",
    title: "Inverser un entier",
    description: "Sans le convertir en chaîne.",
    instruction: `Inversez les chiffres de <code>12345</code> arithmétiquement (résultat : 54321). Affichez le résultat.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int n = 12345;\n    int r = 0;\n    // boucle\n    printf("%d\\n", r);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int n = 12345;\n    int r = 0;\n    while (n > 0) { r = r * 10 + n % 10; n /= 10; }\n    printf("%d\\n", r);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "54321" }],
  },
  {
    id: "c_131",
    type: "code",
    category: "Number theory",
    title: "Somme des chiffres",
    description: "Somme arithmétique des digits.",
    instruction: `Somme des chiffres de <code>9876</code>. Réponse : 30.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int n = 9876;\n    int s = 0;\n    // boucle\n    printf("%d\\n", s);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int n = 9876;\n    int s = 0;\n    while (n > 0) { s += n % 10; n /= 10; }\n    printf("%d\\n", s);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "30" }],
  },
  {
    id: "c_132",
    type: "code",
    category: "Number theory",
    title: "Armstrong number",
    description: "Nombre = somme cubes de ses chiffres.",
    instruction: `Vérifiez si <code>153</code> est un nombre d'Armstrong (1³+5³+3³ = 153). Affichez <code>oui</code>.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int n = 153, original = n, sum = 0;\n    // calculer\n    printf("%s\\n", sum == original ? "oui" : "non");\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int n = 153, original = n, sum = 0;\n    while (n > 0) { int d = n % 10; sum += d*d*d; n /= 10; }\n    printf("%s\\n", sum == original ? "oui" : "non");\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "oui" }],
  },
  {
    id: "c_133",
    type: "code",
    category: "DP",
    title: "Fibonacci itératif",
    description: "Sans récursion exponentielle.",
    instruction: `Calculez fib(30) itérativement. Réponse : 832040.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int n = 30;\n    int a = 0, b = 1;\n    // itérer\n    printf("%d\\n", a);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int n = 30;\n    int a = 0, b = 1;\n    for (int i = 0; i < n; i++) { int t = a + b; a = b; b = t; }\n    printf("%d\\n", a);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "832040" }],
  },
  {
    id: "c_134",
    type: "code",
    category: "DP",
    title: "Coin change (compter)",
    description: "Combien de façons de faire 5 avec [1, 2, 5].",
    instruction: `Avec les pièces <code>{1, 2, 5}</code>, comptez combien de façons existent pour faire la somme 5 (réponse : 4 → 5, 2+2+1, 2+1+1+1, 1×5).`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int coins[] = {1, 2, 5};\n    int nc = 3, target = 5;\n    int dp[6] = {0};\n    dp[0] = 1;\n    // DP\n    printf("%d\\n", dp[target]);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int coins[] = {1, 2, 5};\n    int nc = 3, target = 5;\n    int dp[6] = {0};\n    dp[0] = 1;\n    for (int i = 0; i < nc; i++)\n        for (int j = coins[i]; j <= target; j++)\n            dp[j] += dp[j - coins[i]];\n    printf("%d\\n", dp[target]);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "4" }],
  },
  {
    id: "c_135",
    type: "code",
    category: "DP",
    title: "Escaliers (climbing stairs)",
    description: "Nombre de façons de monter n marches (1 ou 2 à la fois).",
    instruction: `Pour 10 marches avec des sauts de 1 ou 2, calculez le nombre de chemins. Réponse : 89.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int n = 10;\n    int dp[12] = {0};\n    dp[0] = 1; dp[1] = 1;\n    // DP\n    printf("%d\\n", dp[n]);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int n = 10;\n    int dp[12] = {0};\n    dp[0] = 1; dp[1] = 1;\n    for (int i = 2; i <= n; i++) dp[i] = dp[i-1] + dp[i-2];\n    printf("%d\\n", dp[n]);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "89" }],
  },
  {
    id: "c_136",
    type: "code",
    category: "DP",
    title: "Plus longue sous-séquence (LIS)",
    description: "Longest increasing subsequence.",
    instruction: `Trouvez la longueur de la LIS dans <code>{10, 9, 2, 5, 3, 7, 101, 18}</code>. Réponse : 4 (2,3,7,101).`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {10, 9, 2, 5, 3, 7, 101, 18};\n    int n = 8;\n    int dp[8];\n    int best = 0;\n    // DP O(n²)\n    printf("%d\\n", best);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {10, 9, 2, 5, 3, 7, 101, 18};\n    int n = 8;\n    int dp[8];\n    int best = 1;\n    for (int i = 0; i < n; i++) {\n        dp[i] = 1;\n        for (int j = 0; j < i; j++) if (t[j] < t[i] && dp[j] + 1 > dp[i]) dp[i] = dp[j] + 1;\n        if (dp[i] > best) best = dp[i];\n    }\n    printf("%d\\n", best);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "4" }],
  },
  {
    id: "c_137",
    type: "code",
    category: "DP",
    title: "Knapsack 0/1",
    description: "Sac à dos binaire.",
    instruction: `Capacité 7, objets (poids, valeur) : (2,3), (3,4), (4,5), (5,6). Maximisez la valeur totale. Réponse : 9 (objets 2 et 3, poids 3+4=7).`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int W = 7;\n    int w[] = {2, 3, 4, 5};\n    int v[] = {3, 4, 5, 6};\n    int n = 4;\n    int dp[5][8] = {{0}};\n    // DP\n    printf("%d\\n", dp[n][W]);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int W = 7;\n    int w[] = {2, 3, 4, 5};\n    int v[] = {3, 4, 5, 6};\n    int n = 4;\n    int dp[5][8] = {{0}};\n    for (int i = 1; i <= n; i++)\n        for (int j = 0; j <= W; j++) {\n            dp[i][j] = dp[i-1][j];\n            if (j >= w[i-1] && dp[i-1][j - w[i-1]] + v[i-1] > dp[i][j])\n                dp[i][j] = dp[i-1][j - w[i-1]] + v[i-1];\n        }\n    printf("%d\\n", dp[n][W]);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "9" }],
  },
  {
    id: "c_138",
    type: "code",
    category: "Algorithmes avancés",
    title: "Power set (toutes les parties)",
    description: "Subsets via bitmask.",
    instruction: `Pour <code>{1, 2, 3}</code>, comptez le nombre de sous-ensembles (incluant le vide). Réponse : 8.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {1, 2, 3};\n    int n = 3;\n    int count = 0;\n    // 2^n via bitmask\n    printf("%d\\n", count);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {1, 2, 3};\n    int n = 3;\n    int count = 0;\n    for (int mask = 0; mask < (1 << n); mask++) count++;\n    printf("%d\\n", count);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "8" }],
  },
  {
    id: "c_139",
    type: "code",
    category: "Algorithmes avancés",
    title: "Permutations",
    description: "Compter les permutations de n éléments.",
    instruction: `Calculez n! itérativement pour n=6 (= 720), c'est le nombre de permutations de 6 éléments distincts.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int n = 6;\n    int f = 1;\n    // itérer\n    printf("%d\\n", f);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int n = 6;\n    int f = 1;\n    for (int i = 2; i <= n; i++) f *= i;\n    printf("%d\\n", f);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "720" }],
  },
  {
    id: "c_140",
    type: "code",
    category: "Algorithmes avancés",
    title: "Combinaisons C(n,k)",
    description: "Coefficient binomial via Pascal.",
    instruction: `Calculez C(8, 3) (= 56) via Pascal : <code>C(n,k) = C(n-1,k-1) + C(n-1,k)</code>.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int n = 8, k = 3;\n    int t[9][9] = {{0}};\n    // Pascal\n    printf("%d\\n", t[n][k]);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int n = 8, k = 3;\n    int t[9][9] = {{0}};\n    for (int i = 0; i <= n; i++) {\n        t[i][0] = 1;\n        for (int j = 1; j <= i; j++) t[i][j] = t[i-1][j-1] + (j <= i-1 ? t[i-1][j] : 0);\n    }\n    printf("%d\\n", t[n][k]);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "56" }],
  },
  {
    id: "c_141",
    type: "code",
    category: "Hashing",
    title: "DJB2 simplifié",
    description: "Hash classique d'une chaîne.",
    instruction: `Calculez le hash DJB2 de <code>"abc"</code> et affichez son modulo 1000. Algo : hash=5381 ; pour chaque c, hash = hash*33 + c.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    const char *s = "abc";\n    unsigned long h = 5381;\n    // hash\n    printf("%lu\\n", h % 1000);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    const char *s = "abc";\n    unsigned long h = 5381;\n    for (int i = 0; s[i]; i++) h = h * 33 + (unsigned char)s[i];\n    printf("%lu\\n", h % 1000);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "186" }],
  },
  {
    id: "c_142",
    type: "code",
    category: "Récursion",
    title: "Tours de Hanoï",
    description: "Compter le nombre de mouvements.",
    instruction: `Calculez le nombre de coups nécessaires pour résoudre Hanoï avec 6 disques (2^n - 1 = 63).`,
    code_template: `#include <stdio.h>\n\nint hanoi(int n) {\n    // récursif\n    return 0;\n}\n\nint main(void) {\n    printf("%d\\n", hanoi(6));\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint hanoi(int n) {\n    if (n == 0) return 0;\n    return 2 * hanoi(n - 1) + 1;\n}\n\nint main(void) {\n    printf("%d\\n", hanoi(6));\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "63" }],
  },
  {
    id: "c_143",
    type: "code",
    category: "Récursion",
    title: "Power récursif",
    description: "Exponentiation rapide.",
    instruction: `Calculez 2^16 par exponentiation rapide récursive (binaire). Réponse : 65536.`,
    code_template: `#include <stdio.h>\n\nlong fastpow(long base, int exp) {\n    // récursif\n    return 0;\n}\n\nint main(void) {\n    printf("%ld\\n", fastpow(2, 16));\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nlong fastpow(long base, int exp) {\n    if (exp == 0) return 1;\n    long half = fastpow(base, exp / 2);\n    return (exp & 1) ? half * half * base : half * half;\n}\n\nint main(void) {\n    printf("%ld\\n", fastpow(2, 16));\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "65536" }],
  },
  {
    id: "c_144",
    type: "code",
    category: "Récursion",
    title: "Compter chemins en grille",
    description: "Grille m×n, mouvements droite/bas uniquement.",
    instruction: `Dans une grille 3×3, combien de chemins du coin haut-gauche au coin bas-droit (mouvements droite ou bas seulement) ? Réponse : 6.`,
    code_template: `#include <stdio.h>\n\nint paths(int m, int n) {\n    // récursif (DP-friendly)\n    return 0;\n}\n\nint main(void) {\n    printf("%d\\n", paths(3, 3));\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint paths(int m, int n) {\n    if (m == 1 || n == 1) return 1;\n    return paths(m - 1, n) + paths(m, n - 1);\n}\n\nint main(void) {\n    printf("%d\\n", paths(3, 3));\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "6" }],
  },
  {
    id: "c_145",
    type: "code",
    category: "Strings",
    title: "Vérifier palindrome (ignore case)",
    description: "Insensible à la casse.",
    instruction: `Vérifiez si <code>"RaceCar"</code> est un palindrome en ignorant la casse. Affichez <code>oui</code>.`,
    code_template: `#include <stdio.h>\n#include <ctype.h>\n#include <string.h>\n\nint main(void) {\n    const char *s = "RaceCar";\n    int n = strlen(s);\n    int ok = 1;\n    // comparer en lowercase\n    printf("%s\\n", ok ? "oui" : "non");\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <ctype.h>\n#include <string.h>\n\nint main(void) {\n    const char *s = "RaceCar";\n    int n = strlen(s);\n    int ok = 1;\n    for (int i = 0; i < n / 2; i++)\n        if (tolower((unsigned char)s[i]) != tolower((unsigned char)s[n - 1 - i])) { ok = 0; break; }\n    printf("%s\\n", ok ? "oui" : "non");\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "oui" }],
  },
  {
    id: "c_146",
    type: "code",
    category: "Strings",
    title: "Compression run-length",
    description: "RLE basique.",
    instruction: `Compressez <code>"aaabbc"</code> en <code>"a3b2c1"</code> (chaque caractère suivi de son compte).`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    const char *s = "aaabbc";\n    char out[64];\n    int k = 0;\n    // RLE\n    out[k] = 0;\n    printf("%s\\n", out);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    const char *s = "aaabbc";\n    char out[64];\n    int k = 0;\n    for (int i = 0; s[i]; ) {\n        char c = s[i];\n        int n = 0;\n        while (s[i] == c) { n++; i++; }\n        out[k++] = c;\n        k += sprintf(out + k, "%d", n);\n    }\n    out[k] = 0;\n    printf("%s\\n", out);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "a3b2c1" }],
  },
  {
    id: "c_147",
    type: "code",
    category: "Math",
    title: "Triangle de Pascal",
    description: "Afficher les 5 premières lignes.",
    instruction: `Affichez les 5 premières lignes du triangle de Pascal, une ligne par retour ligne, valeurs séparées par espace.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int t[5][5] = {{0}};\n    for (int i = 0; i < 5; i++) {\n        // remplir + afficher\n    }\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int t[5][5] = {{0}};\n    for (int i = 0; i < 5; i++) {\n        t[i][0] = 1;\n        for (int j = 1; j <= i; j++) t[i][j] = t[i-1][j-1] + (j <= i-1 ? t[i-1][j] : 0);\n        for (int j = 0; j <= i; j++) printf("%d ", t[i][j]);\n        printf("\\n");\n    }\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "1 \n1 1 \n1 2 1 \n1 3 3 1 \n1 4 6 4 1" }],
  },
  {
    id: "c_148",
    type: "code",
    category: "Misc",
    title: "Temps en hh:mm:ss",
    description: "Convertir des secondes.",
    instruction: `Convertissez 3725 secondes en format <code>hh:mm:ss</code> (réponse : <code>01:02:05</code>).`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int s = 3725;\n    // calculer h, m, s\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int s = 3725;\n    int h = s / 3600; s %= 3600;\n    int m = s / 60; s %= 60;\n    printf("%02d:%02d:%02d\\n", h, m, s);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "01:02:05" }],
  },
  {
    id: "c_149",
    type: "code",
    category: "Misc",
    title: "FizzBuzz",
    description: "Le classique.",
    instruction: `Affichez les nombres de 1 à 15. Pour les multiples de 3 affichez <code>Fizz</code>, de 5 <code>Buzz</code>, des deux <code>FizzBuzz</code>. Un nombre/mot par ligne.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    // FizzBuzz 1..15\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    for (int i = 1; i <= 15; i++) {\n        if (i % 15 == 0) printf("FizzBuzz\\n");\n        else if (i % 3 == 0) printf("Fizz\\n");\n        else if (i % 5 == 0) printf("Buzz\\n");\n        else printf("%d\\n", i);\n    }\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz" }],
  },
  {
    id: "c_150",
    type: "code",
    category: "Misc",
    title: "Mission accomplie",
    description: "Hommage à Code Lyoko.",
    instruction: `Affichez le message final : <code>Tour désactivée. Retour sur Terre.</code>`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    // message final\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    printf("Tour désactivée. Retour sur Terre.\\n");\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "Tour désactivée. Retour sur Terre." }],
    hint: "Tu viens de finir 150 exercices C. Bravo Lyoko-warrior !",
  },
];

addExercises("c", exercises);
