import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/**
 * Module C — Part 7 : structures de données (listes chaînées, piles, files).
 */
const exercises: Exercise[] = [
  {
    id: "c_91",
    type: "code",
    category: "Listes chaînées",
    title: "Premier nœud",
    description: "Définir et allouer une struct Noeud.",
    instruction: `Définissez <code>typedef struct Noeud { int v; struct Noeud *next; } Noeud;</code>. Allouez un nœud avec <code>v=10</code> et <code>next=NULL</code>, affichez <code>v</code>, puis libérez.`,
    code_template: `#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct Noeud { int v; struct Noeud *next; } Noeud;\n\nint main(void) {\n    // allouer\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct Noeud { int v; struct Noeud *next; } Noeud;\n\nint main(void) {\n    Noeud *n = malloc(sizeof(Noeud));\n    n->v = 10;\n    n->next = NULL;\n    printf("%d\\n", n->v);\n    free(n);\n    return 0;\n}\n`,
    tests: [
      { type: "contains", expected: "struct Noeud" },
      { type: "output", expected_output: "10" },
    ],
  },
  {
    id: "c_92",
    type: "code",
    category: "Listes chaînées",
    title: "Liste à 3 éléments",
    description: "Chaînage manuel.",
    instruction: `Créez une liste chaînée 1 → 2 → 3, parcourez-la et affichez les valeurs séparées par espaces. N'oubliez pas de free.`,
    code_template: `#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct N { int v; struct N *next; } N;\n\nint main(void) {\n    // 3 nœuds chaînés\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct N { int v; struct N *next; } N;\n\nint main(void) {\n    N *c = malloc(sizeof(N)); c->v = 3; c->next = NULL;\n    N *b = malloc(sizeof(N)); b->v = 2; b->next = c;\n    N *a = malloc(sizeof(N)); a->v = 1; a->next = b;\n    for (N *p = a; p; p = p->next) printf("%d ", p->v);\n    printf("\\n");\n    free(a); free(b); free(c);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "1 2 3" }],
  },
  {
    id: "c_93",
    type: "code",
    category: "Listes chaînées",
    title: "Insérer en tête",
    description: "Push front.",
    instruction: `Insérez 3, puis 2, puis 1 en tête d'une liste vide. Parcourez et affichez (devrait donner 1 2 3 — le dernier inséré est devant).`,
    code_template: `#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct N { int v; struct N *next; } N;\n\nN *prepend(N *head, int v) {\n    // votre code\n    return head;\n}\n\nint main(void) {\n    N *head = NULL;\n    head = prepend(head, 3);\n    head = prepend(head, 2);\n    head = prepend(head, 1);\n    for (N *p = head; p; p = p->next) printf("%d ", p->v);\n    printf("\\n");\n    // free omis pour simplifier\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct N { int v; struct N *next; } N;\n\nN *prepend(N *head, int v) {\n    N *n = malloc(sizeof(N));\n    n->v = v;\n    n->next = head;\n    return n;\n}\n\nint main(void) {\n    N *head = NULL;\n    head = prepend(head, 3);\n    head = prepend(head, 2);\n    head = prepend(head, 1);\n    for (N *p = head; p; p = p->next) printf("%d ", p->v);\n    printf("\\n");\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "1 2 3" }],
  },
  {
    id: "c_94",
    type: "code",
    category: "Listes chaînées",
    title: "Longueur d'une liste",
    description: "Compter les éléments.",
    instruction: `Écrivez <code>int len(N *head)</code> qui retourne la longueur d'une liste. Testez sur une liste de 5 éléments.`,
    code_template: `#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct N { int v; struct N *next; } N;\n\nint len(N *head) {\n    // votre code\n    return 0;\n}\n\nN *make(int v, N *next) { N *n = malloc(sizeof(N)); n->v = v; n->next = next; return n; }\n\nint main(void) {\n    N *l = make(1, make(2, make(3, make(4, make(5, NULL)))));\n    printf("%d\\n", len(l));\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct N { int v; struct N *next; } N;\n\nint len(N *head) {\n    int n = 0;\n    for (N *p = head; p; p = p->next) n++;\n    return n;\n}\n\nN *make(int v, N *next) { N *n = malloc(sizeof(N)); n->v = v; n->next = next; return n; }\n\nint main(void) {\n    N *l = make(1, make(2, make(3, make(4, make(5, NULL)))));\n    printf("%d\\n", len(l));\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "5" }],
  },
  {
    id: "c_95",
    type: "code",
    category: "Listes chaînées",
    title: "Inverser une liste",
    description: "Classique d'entretien.",
    instruction: `Inversez la liste 1→2→3→4 et affichez les valeurs.`,
    code_template: `#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct N { int v; struct N *next; } N;\n\nN *reverse(N *head) {\n    // votre code\n    return head;\n}\n\nN *make(int v, N *next) { N *n = malloc(sizeof(N)); n->v = v; n->next = next; return n; }\n\nint main(void) {\n    N *l = make(1, make(2, make(3, make(4, NULL))));\n    l = reverse(l);\n    for (N *p = l; p; p = p->next) printf("%d ", p->v);\n    printf("\\n");\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct N { int v; struct N *next; } N;\n\nN *reverse(N *head) {\n    N *prev = NULL, *cur = head;\n    while (cur) { N *next = cur->next; cur->next = prev; prev = cur; cur = next; }\n    return prev;\n}\n\nN *make(int v, N *next) { N *n = malloc(sizeof(N)); n->v = v; n->next = next; return n; }\n\nint main(void) {\n    N *l = make(1, make(2, make(3, make(4, NULL))));\n    l = reverse(l);\n    for (N *p = l; p; p = p->next) printf("%d ", p->v);\n    printf("\\n");\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "4 3 2 1" }],
  },
  {
    id: "c_96",
    type: "code",
    category: "Listes chaînées",
    title: "Chercher une valeur",
    description: "Linear search dans une liste.",
    instruction: `Implémentez <code>int contains(N *head, int v)</code> qui retourne 1 si v est dans la liste, 0 sinon. Cherchez 3 dans la liste 1→2→3→4.`,
    code_template: `#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct N { int v; struct N *next; } N;\n\nint contains(N *head, int v) {\n    // votre code\n    return 0;\n}\n\nN *make(int v, N *next) { N *n = malloc(sizeof(N)); n->v = v; n->next = next; return n; }\n\nint main(void) {\n    N *l = make(1, make(2, make(3, make(4, NULL))));\n    printf("%d\\n", contains(l, 3));\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct N { int v; struct N *next; } N;\n\nint contains(N *head, int v) {\n    for (N *p = head; p; p = p->next) if (p->v == v) return 1;\n    return 0;\n}\n\nN *make(int v, N *next) { N *n = malloc(sizeof(N)); n->v = v; n->next = next; return n; }\n\nint main(void) {\n    N *l = make(1, make(2, make(3, make(4, NULL))));\n    printf("%d\\n", contains(l, 3));\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "1" }],
  },
  {
    id: "c_97",
    type: "code",
    category: "Listes chaînées",
    title: "Somme d'une liste",
    description: "Parcours + accumulation.",
    instruction: `Affichez la somme des valeurs de la liste 10→20→30→40.`,
    code_template: `#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct N { int v; struct N *next; } N;\nN *make(int v, N *next) { N *n = malloc(sizeof(N)); n->v = v; n->next = next; return n; }\n\nint main(void) {\n    N *l = make(10, make(20, make(30, make(40, NULL))));\n    int s = 0;\n    // parcours\n    printf("%d\\n", s);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct N { int v; struct N *next; } N;\nN *make(int v, N *next) { N *n = malloc(sizeof(N)); n->v = v; n->next = next; return n; }\n\nint main(void) {\n    N *l = make(10, make(20, make(30, make(40, NULL))));\n    int s = 0;\n    for (N *p = l; p; p = p->next) s += p->v;\n    printf("%d\\n", s);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "100" }],
  },
  {
    id: "c_98",
    type: "code",
    category: "Piles",
    title: "Pile sur tableau",
    description: "push/pop avec un index sommet.",
    instruction: `Implémentez une pile avec <code>int stack[10]</code> et un <code>top</code>. Push 1, 2, 3, puis pop deux fois et affichez la valeur popée à chaque fois (séparées par espace).`,
    code_template: `#include <stdio.h>\n\nint stack[10];\nint top = -1;\n\nvoid push(int v) {\n    // votre code\n}\nint pop(void) {\n    // votre code\n    return 0;\n}\n\nint main(void) {\n    push(1); push(2); push(3);\n    printf("%d ", pop());\n    printf("%d ", pop());\n    printf("\\n");\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint stack[10];\nint top = -1;\n\nvoid push(int v) { stack[++top] = v; }\nint pop(void) { return stack[top--]; }\n\nint main(void) {\n    push(1); push(2); push(3);\n    printf("%d ", pop());\n    printf("%d ", pop());\n    printf("\\n");\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "3 2" }],
  },
  {
    id: "c_99",
    type: "code",
    category: "Piles",
    title: "Parenthèses équilibrées",
    description: "Application classique d'une pile.",
    instruction: `Vérifiez si <code>"((()))"</code> a ses parenthèses équilibrées. Affichez <code>oui</code> ou <code>non</code>. Utilisez une pile (ou un compteur car que des '(').`,
    code_template: `#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n    const char *s = "((()))";\n    int bal = 0;\n    // parcourir\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n    const char *s = "((()))";\n    int bal = 0;\n    int ok = 1;\n    for (int i = 0; s[i]; i++) {\n        if (s[i] == '(') bal++;\n        else if (s[i] == ')') { if (bal == 0) { ok = 0; break; } bal--; }\n    }\n    printf("%s\\n", (ok && bal == 0) ? "oui" : "non");\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "oui" }],
  },
  {
    id: "c_100",
    type: "code",
    category: "Piles",
    title: "Inverser un tableau avec une pile",
    description: "Push tous, pop tous.",
    instruction: `Inversez <code>{1, 2, 3, 4, 5}</code> en utilisant une pile (push tous, pop tous dans un nouveau tableau), affichez le résultat.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {1, 2, 3, 4, 5};\n    int n = 5;\n    int stack[10];\n    int top = -1;\n    int out[10];\n    // push tous\n    // pop tous dans out\n    for (int i = 0; i < n; i++) printf("%d ", out[i]);\n    printf("\\n");\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {1, 2, 3, 4, 5};\n    int n = 5;\n    int stack[10];\n    int top = -1;\n    int out[10];\n    for (int i = 0; i < n; i++) stack[++top] = t[i];\n    for (int i = 0; i < n; i++) out[i] = stack[top--];\n    for (int i = 0; i < n; i++) printf("%d ", out[i]);\n    printf("\\n");\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "5 4 3 2 1" }],
  },
  {
    id: "c_101",
    type: "code",
    category: "Files",
    title: "File FIFO sur tableau circulaire",
    description: "enqueue/dequeue.",
    instruction: `Implémentez une file FIFO avec un tableau de taille 5. Enqueue 10, 20, 30, dequeue deux fois et affichez les valeurs dequeue (séparées par espace).`,
    code_template: `#include <stdio.h>\n\nint q[5];\nint front = 0, rear = 0, count = 0;\n\nvoid enq(int v) {\n    // votre code\n}\nint deq(void) {\n    // votre code\n    return 0;\n}\n\nint main(void) {\n    enq(10); enq(20); enq(30);\n    printf("%d ", deq());\n    printf("%d ", deq());\n    printf("\\n");\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint q[5];\nint front = 0, rear = 0, count = 0;\n\nvoid enq(int v) { q[rear] = v; rear = (rear + 1) % 5; count++; }\nint deq(void) { int v = q[front]; front = (front + 1) % 5; count--; return v; }\n\nint main(void) {\n    enq(10); enq(20); enq(30);\n    printf("%d ", deq());\n    printf("%d ", deq());\n    printf("\\n");\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "10 20" }],
  },
  {
    id: "c_102",
    type: "code",
    category: "Tableaux dynamiques",
    title: "Vector double-au-besoin",
    description: "Simuler std::vector.",
    instruction: `Allouez 2 entiers, puis push 5 valeurs (1..5) en doublant la capacité quand pleine, affichez le total.`,
    code_template: `#include <stdio.h>\n#include <stdlib.h>\n\nint main(void) {\n    int cap = 2, size = 0;\n    int *t = malloc(cap * sizeof(int));\n    // push 1 à 5\n    int s = 0;\n    for (int i = 0; i < size; i++) s += t[i];\n    printf("%d\\n", s);\n    free(t);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <stdlib.h>\n\nint main(void) {\n    int cap = 2, size = 0;\n    int *t = malloc(cap * sizeof(int));\n    for (int v = 1; v <= 5; v++) {\n        if (size == cap) { cap *= 2; t = realloc(t, cap * sizeof(int)); }\n        t[size++] = v;\n    }\n    int s = 0;\n    for (int i = 0; i < size; i++) s += t[i];\n    printf("%d\\n", s);\n    free(t);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "15" }],
  },
  {
    id: "c_103",
    type: "code",
    category: "Hash maps",
    title: "Compter occurrences avec un tableau",
    description: "Hash trivial sur ASCII.",
    instruction: `Comptez l'apparition de chaque lettre minuscule dans <code>"banana"</code>. Affichez le total pour 'a', 'b', 'n' séparé par espaces.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    const char *s = "banana";\n    int count[26] = {0};\n    // compter\n    printf("%d %d %d\\n", count['a'-'a'], count['b'-'a'], count['n'-'a']);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    const char *s = "banana";\n    int count[26] = {0};\n    for (int i = 0; s[i]; i++) if (s[i] >= 'a' && s[i] <= 'z') count[s[i]-'a']++;\n    printf("%d %d %d\\n", count['a'-'a'], count['b'-'a'], count['n'-'a']);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "3 1 2" }],
  },
  {
    id: "c_104",
    type: "code",
    category: "Hash maps",
    title: "Premier caractère unique",
    description: "Indice du 1er caractère qui n'apparaît qu'une fois.",
    instruction: `Dans <code>"loveleetcode"</code>, trouvez l'indice du 1er caractère unique. Réponse attendue : 2 (le 'v').`,
    code_template: `#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n    const char *s = "loveleetcode";\n    int count[26] = {0};\n    // compter\n    // trouver premier index avec count==1\n    int n = strlen(s);\n    int idx = -1;\n    for (int i = 0; i < n; i++) {\n    }\n    printf("%d\\n", idx);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n    const char *s = "loveleetcode";\n    int count[26] = {0};\n    int n = strlen(s);\n    for (int i = 0; i < n; i++) count[s[i]-'a']++;\n    int idx = -1;\n    for (int i = 0; i < n; i++) if (count[s[i]-'a'] == 1) { idx = i; break; }\n    printf("%d\\n", idx);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "2" }],
  },
  {
    id: "c_105",
    type: "code",
    category: "Hash maps",
    title: "Anagrammes",
    description: "Deux chaînes sont-elles anagrammes ?",
    instruction: `Vérifiez si <code>"listen"</code> et <code>"silent"</code> sont des anagrammes. Affichez <code>oui</code> ou <code>non</code>.`,
    code_template: `#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n    const char *a = "listen";\n    const char *b = "silent";\n    if (strlen(a) != strlen(b)) { printf("non\\n"); return 0; }\n    int ca[26] = {0}, cb[26] = {0};\n    // remplir\n    // comparer\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n    const char *a = "listen";\n    const char *b = "silent";\n    if (strlen(a) != strlen(b)) { printf("non\\n"); return 0; }\n    int ca[26] = {0}, cb[26] = {0};\n    for (int i = 0; a[i]; i++) ca[a[i]-'a']++;\n    for (int i = 0; b[i]; i++) cb[b[i]-'a']++;\n    int eq = 1;\n    for (int i = 0; i < 26; i++) if (ca[i] != cb[i]) { eq = 0; break; }\n    printf("%s\\n", eq ? "oui" : "non");\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "oui" }],
  },
  {
    id: "c_106",
    type: "code",
    category: "Algos sur tableaux",
    title: "Doublon dans un tableau",
    description: "Détecter un duplicata.",
    instruction: `Vérifiez si <code>{1, 2, 3, 4, 5, 2}</code> contient un doublon. Affichez <code>oui</code> ou <code>non</code>.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {1, 2, 3, 4, 5, 2};\n    int n = 6;\n    // chercher\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {1, 2, 3, 4, 5, 2};\n    int n = 6;\n    int found = 0;\n    for (int i = 0; i < n && !found; i++)\n        for (int j = i+1; j < n && !found; j++)\n            if (t[i] == t[j]) found = 1;\n    printf("%s\\n", found ? "oui" : "non");\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "oui" }],
  },
  {
    id: "c_107",
    type: "code",
    category: "Algos sur tableaux",
    title: "Two sum",
    description: "Indices a+b == target.",
    instruction: `Dans <code>{2, 7, 11, 15}</code>, trouvez les indices de deux éléments dont la somme est 9. Affichez <code>i j</code>.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {2, 7, 11, 15};\n    int target = 9;\n    int n = 4;\n    // double boucle\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {2, 7, 11, 15};\n    int target = 9;\n    int n = 4;\n    for (int i = 0; i < n; i++)\n        for (int j = i+1; j < n; j++)\n            if (t[i] + t[j] == target) { printf("%d %d\\n", i, j); return 0; }\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "0 1" }],
  },
  {
    id: "c_108",
    type: "code",
    category: "Algos sur tableaux",
    title: "Décalage circulaire",
    description: "Rotate left by k.",
    instruction: `Décalez <code>{1, 2, 3, 4, 5}</code> de 2 positions vers la gauche (résultat : <code>3 4 5 1 2</code>), affichez le résultat.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int t[5] = {1, 2, 3, 4, 5};\n    int k = 2;\n    int tmp[5];\n    // décaler\n    for (int i = 0; i < 5; i++) printf("%d ", tmp[i]);\n    printf("\\n");\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int t[5] = {1, 2, 3, 4, 5};\n    int k = 2;\n    int tmp[5];\n    for (int i = 0; i < 5; i++) tmp[i] = t[(i + k) % 5];\n    for (int i = 0; i < 5; i++) printf("%d ", tmp[i]);\n    printf("\\n");\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "3 4 5 1 2" }],
  },
  {
    id: "c_109",
    type: "code",
    category: "Algos sur tableaux",
    title: "Maximum subarray (Kadane)",
    description: "Plus grande somme contiguë.",
    instruction: `Pour <code>{-2, 1, -3, 4, -1, 2, 1, -5, 4}</code>, trouvez la plus grande somme contiguë (réponse : 6, soit 4+(-1)+2+1). Affichez le résultat.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {-2, 1, -3, 4, -1, 2, 1, -5, 4};\n    int n = 9;\n    // Kadane\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {-2, 1, -3, 4, -1, 2, 1, -5, 4};\n    int n = 9;\n    int best = t[0], cur = t[0];\n    for (int i = 1; i < n; i++) {\n        cur = (cur + t[i] > t[i]) ? cur + t[i] : t[i];\n        if (cur > best) best = cur;\n    }\n    printf("%d\\n", best);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "6" }],
  },
  {
    id: "c_110",
    type: "code",
    category: "Algos sur tableaux",
    title: "Plus de la moitié (élément majoritaire)",
    description: "Boyer-Moore voting.",
    instruction: `Dans <code>{3, 2, 3, 4, 3, 3, 5}</code>, l'élément majoritaire (> n/2 occurrences) est 3. Trouvez-le et affichez-le. Utilisez l'algorithme de Boyer-Moore (compteur + candidat).`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {3, 2, 3, 4, 3, 3, 5};\n    int n = 7;\n    int cand = 0, count = 0;\n    // Boyer-Moore\n    printf("%d\\n", cand);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {3, 2, 3, 4, 3, 3, 5};\n    int n = 7;\n    int cand = 0, count = 0;\n    for (int i = 0; i < n; i++) {\n        if (count == 0) { cand = t[i]; count = 1; }\n        else if (t[i] == cand) count++;\n        else count--;\n    }\n    printf("%d\\n", cand);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "3" }],
  },
  {
    id: "c_111",
    type: "code",
    category: "Algos sur tableaux",
    title: "Premier négatif",
    description: "Linear search.",
    instruction: `Trouvez l'indice du premier nombre négatif dans <code>{4, 2, 7, -3, 8, -1}</code>. Affichez-le. (réponse : 3)`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {4, 2, 7, -3, 8, -1};\n    int n = 6;\n    int idx = -1;\n    // boucle\n    printf("%d\\n", idx);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {4, 2, 7, -3, 8, -1};\n    int n = 6;\n    int idx = -1;\n    for (int i = 0; i < n; i++) if (t[i] < 0) { idx = i; break; }\n    printf("%d\\n", idx);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "3" }],
  },
  {
    id: "c_112",
    type: "code",
    category: "Algos sur tableaux",
    title: "Triée ?",
    description: "Vérifier l'ordre croissant.",
    instruction: `Vérifiez si <code>{1, 3, 5, 7, 9}</code> est trié en ordre croissant. Affichez <code>oui</code> ou <code>non</code>.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {1, 3, 5, 7, 9};\n    int n = 5;\n    // vérification\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {1, 3, 5, 7, 9};\n    int n = 5;\n    int sorted = 1;\n    for (int i = 1; i < n; i++) if (t[i] < t[i-1]) { sorted = 0; break; }\n    printf("%s\\n", sorted ? "oui" : "non");\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "oui" }],
  },
  {
    id: "c_113",
    type: "code",
    category: "Algos sur tableaux",
    title: "Décaler les zéros à la fin",
    description: "Move zeroes.",
    instruction: `Déplacez les zéros à la fin de <code>{0, 1, 0, 3, 12}</code> (résultat : <code>1 3 12 0 0</code>), en préservant l'ordre des non-zéros. Affichez le tableau.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {0, 1, 0, 3, 12};\n    int n = 5;\n    int j = 0;\n    // déplacer non-zeros\n    // remplir reste avec 0\n    for (int i = 0; i < n; i++) printf("%d ", t[i]);\n    printf("\\n");\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {0, 1, 0, 3, 12};\n    int n = 5;\n    int j = 0;\n    for (int i = 0; i < n; i++) if (t[i] != 0) t[j++] = t[i];\n    while (j < n) t[j++] = 0;\n    for (int i = 0; i < n; i++) printf("%d ", t[i]);\n    printf("\\n");\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "1 3 12 0 0" }],
  },
  {
    id: "c_114",
    type: "code",
    category: "Algos sur tableaux",
    title: "Compter les paires",
    description: "Combien de (i, j) tels que t[i] + t[j] = k.",
    instruction: `Pour <code>{1, 5, 7, -1, 5}</code> et k = 6, comptez le nombre de paires (i &lt; j) telles que t[i] + t[j] = 6. Réponse attendue : 3.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {1, 5, 7, -1, 5};\n    int n = 5, k = 6;\n    int count = 0;\n    // double boucle\n    printf("%d\\n", count);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {1, 5, 7, -1, 5};\n    int n = 5, k = 6;\n    int count = 0;\n    for (int i = 0; i < n; i++)\n        for (int j = i+1; j < n; j++)\n            if (t[i] + t[j] == k) count++;\n    printf("%d\\n", count);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "3" }],
  },
  {
    id: "c_115",
    type: "code",
    category: "Listes chaînées",
    title: "Concaténer deux listes",
    description: "Lier la queue de A à la tête de B.",
    instruction: `Concaténez 1→2→3 et 4→5, affichez la liste résultante 1 2 3 4 5.`,
    code_template: `#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct N { int v; struct N *next; } N;\nN *make(int v, N *next) { N *n = malloc(sizeof(N)); n->v = v; n->next = next; return n; }\n\nN *concat(N *a, N *b) {\n    // votre code\n    return a;\n}\n\nint main(void) {\n    N *a = make(1, make(2, make(3, NULL)));\n    N *b = make(4, make(5, NULL));\n    N *c = concat(a, b);\n    for (N *p = c; p; p = p->next) printf("%d ", p->v);\n    printf("\\n");\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct N { int v; struct N *next; } N;\nN *make(int v, N *next) { N *n = malloc(sizeof(N)); n->v = v; n->next = next; return n; }\n\nN *concat(N *a, N *b) {\n    if (!a) return b;\n    N *p = a;\n    while (p->next) p = p->next;\n    p->next = b;\n    return a;\n}\n\nint main(void) {\n    N *a = make(1, make(2, make(3, NULL)));\n    N *b = make(4, make(5, NULL));\n    N *c = concat(a, b);\n    for (N *p = c; p; p = p->next) printf("%d ", p->v);\n    printf("\\n");\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "1 2 3 4 5" }],
  },
  {
    id: "c_116",
    type: "code",
    category: "Listes chaînées",
    title: "Détecter une boucle",
    description: "Floyd's tortoise and hare.",
    instruction: `Sur une liste avec ou sans boucle, utilisez l'algo lent/rapide. Construisez 1→2→3→4→2 (le dernier pointe vers le 2), détectez la boucle et affichez <code>oui</code>.`,
    code_template: `#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct N { int v; struct N *next; } N;\n\nint main(void) {\n    N *a = malloc(sizeof(N)); a->v = 1;\n    N *b = malloc(sizeof(N)); b->v = 2;\n    N *c = malloc(sizeof(N)); c->v = 3;\n    N *d = malloc(sizeof(N)); d->v = 4;\n    a->next = b; b->next = c; c->next = d; d->next = b; // boucle\n    // Floyd\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct N { int v; struct N *next; } N;\n\nint main(void) {\n    N *a = malloc(sizeof(N)); a->v = 1;\n    N *b = malloc(sizeof(N)); b->v = 2;\n    N *c = malloc(sizeof(N)); c->v = 3;\n    N *d = malloc(sizeof(N)); d->v = 4;\n    a->next = b; b->next = c; c->next = d; d->next = b;\n    N *slow = a, *fast = a;\n    int loop = 0;\n    while (fast && fast->next) {\n        slow = slow->next;\n        fast = fast->next->next;\n        if (slow == fast) { loop = 1; break; }\n    }\n    printf("%s\\n", loop ? "oui" : "non");\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "oui" }],
  },
  {
    id: "c_117",
    type: "code",
    category: "Listes chaînées",
    title: "Milieu d'une liste",
    description: "Slow + fast pointers.",
    instruction: `Trouvez l'élément du milieu de 1→2→3→4→5 (réponse : 3). Utilisez l'algo slow/fast.`,
    code_template: `#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct N { int v; struct N *next; } N;\nN *make(int v, N *next) { N *n = malloc(sizeof(N)); n->v = v; n->next = next; return n; }\n\nint main(void) {\n    N *l = make(1, make(2, make(3, make(4, make(5, NULL)))));\n    // slow + fast\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct N { int v; struct N *next; } N;\nN *make(int v, N *next) { N *n = malloc(sizeof(N)); n->v = v; n->next = next; return n; }\n\nint main(void) {\n    N *l = make(1, make(2, make(3, make(4, make(5, NULL)))));\n    N *slow = l, *fast = l;\n    while (fast && fast->next) { slow = slow->next; fast = fast->next->next; }\n    printf("%d\\n", slow->v);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "3" }],
  },
  {
    id: "c_118",
    type: "code",
    category: "Hash maps",
    title: "Premier doublon",
    description: "Indice du premier élément qui apparaît une 2e fois.",
    instruction: `Dans <code>{1, 2, 3, 2, 4, 3}</code>, trouvez la valeur du premier doublon rencontré (réponse : 2).`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {1, 2, 3, 2, 4, 3};\n    int n = 6;\n    int seen[10] = {0};\n    int dup = -1;\n    // chercher\n    printf("%d\\n", dup);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int t[] = {1, 2, 3, 2, 4, 3};\n    int n = 6;\n    int seen[10] = {0};\n    int dup = -1;\n    for (int i = 0; i < n; i++) {\n        if (seen[t[i]]) { dup = t[i]; break; }\n        seen[t[i]] = 1;\n    }\n    printf("%d\\n", dup);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "2" }],
  },
  {
    id: "c_119",
    type: "code",
    category: "Mémoire dynamique",
    title: "Tableau de chaînes",
    description: "char **.",
    instruction: `Allouez un tableau de 3 chaînes (<code>"Aelita"</code>, <code>"Yumi"</code>, <code>"Odd"</code>), affichez la concaténation séparée par <code>-</code>. Libérez tout.`,
    code_template: `#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n\nint main(void) {\n    const char *src[] = {"Aelita", "Yumi", "Odd"};\n    char **t = malloc(3 * sizeof(char *));\n    // allouer + copier\n    // afficher\n    // free\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n\nint main(void) {\n    const char *src[] = {"Aelita", "Yumi", "Odd"};\n    char **t = malloc(3 * sizeof(char *));\n    for (int i = 0; i < 3; i++) {\n        t[i] = malloc(strlen(src[i]) + 1);\n        strcpy(t[i], src[i]);\n    }\n    for (int i = 0; i < 3; i++) {\n        printf("%s%s", t[i], i < 2 ? "-" : "\\n");\n    }\n    for (int i = 0; i < 3; i++) free(t[i]);\n    free(t);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "Aelita-Yumi-Odd" }],
  },
  {
    id: "c_120",
    type: "code",
    category: "Hash maps",
    title: "Comptage de mots distincts",
    description: "Combien de mots différents dans un texte simple.",
    instruction: `Comptez les mots distincts dans la chaîne (séparée par espaces) "<code>code lyoko code carthage lyoko</code>". Utilisez un tableau de 16 buckets de chaînes, comparez avec <code>strcmp</code>. Réponse : 3 (code, lyoko, carthage).`,
    code_template: `#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n    const char *text = "code lyoko code carthage lyoko";\n    char words[16][32];\n    int n = 0;\n    // tokeniser à la main avec strtok ou scan caractère par caractère\n    // ajouter si pas déjà présent\n    char buf[256];\n    strcpy(buf, text);\n    char *tok = strtok(buf, " ");\n    while (tok) {\n        int found = 0;\n        for (int i = 0; i < n; i++) if (strcmp(words[i], tok) == 0) { found = 1; break; }\n        if (!found) strcpy(words[n++], tok);\n        tok = strtok(NULL, " ");\n    }\n    printf("%d\\n", n);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n    const char *text = "code lyoko code carthage lyoko";\n    char words[16][32];\n    int n = 0;\n    char buf[256];\n    strcpy(buf, text);\n    char *tok = strtok(buf, " ");\n    while (tok) {\n        int found = 0;\n        for (int i = 0; i < n; i++) if (strcmp(words[i], tok) == 0) { found = 1; break; }\n        if (!found) strcpy(words[n++], tok);\n        tok = strtok(NULL, " ");\n    }\n    printf("%d\\n", n);\n    return 0;\n}\n`,
    tests: [
      { type: "contains", expected: "strtok" },
      { type: "output", expected_output: "3" },
    ],
  },
];

addExercises("c", exercises);
