import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/**
 * Module C — Part 6 : structures avancées, enums, unions, bitwise, fichiers.
 */
const exercises: Exercise[] = [
  {
    id: "c_61",
    type: "code",
    category: "Structures",
    title: "typedef struct",
    description: "Éviter de répéter struct partout.",
    instruction: `Définissez <code>typedef struct { int x, y; } Point;</code>, créez <code>Point p = {1, 2}</code>, affichez <code>p.x + p.y</code>.`,
    code_template: `#include <stdio.h>\n\n// typedef ici\n\nint main(void) {\n    // utiliser Point\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\ntypedef struct { int x, y; } Point;\n\nint main(void) {\n    Point p = {1, 2};\n    printf("%d\\n", p.x + p.y);\n    return 0;\n}\n`,
    tests: [
      { type: "contains", expected: "typedef struct" },
      { type: "output", expected_output: "3" },
    ],
  },
  {
    id: "c_62",
    type: "code",
    category: "Structures",
    title: "Struct passée en argument",
    description: "Fonction qui reçoit une struct.",
    instruction: `Avec <code>typedef struct { int w, h; } Rect;</code>, écrivez <code>int aire(Rect r)</code> et affichez <code>aire({3, 4})</code>.`,
    code_template: `#include <stdio.h>\n\ntypedef struct { int w, h; } Rect;\n\nint aire(Rect r) {\n    // votre code\n    return 0;\n}\n\nint main(void) {\n    Rect r = {3, 4};\n    printf("%d\\n", aire(r));\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\ntypedef struct { int w, h; } Rect;\n\nint aire(Rect r) { return r.w * r.h; }\n\nint main(void) {\n    Rect r = {3, 4};\n    printf("%d\\n", aire(r));\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "12" }],
  },
  {
    id: "c_63",
    type: "code",
    category: "Structures",
    title: "Pointeur sur struct",
    description: "Modifier via pointeur, opérateur ->.",
    instruction: `Avec <code>typedef struct { int compteur; } Cell;</code>, écrivez <code>void inc(Cell *c)</code> qui fait <code>c-&gt;compteur++</code>, testez et affichez compteur final (départ 0, 3 inc).`,
    code_template: `#include <stdio.h>\n\ntypedef struct { int compteur; } Cell;\n\nvoid inc(Cell *c) {\n    // votre code\n}\n\nint main(void) {\n    Cell c = {0};\n    inc(&c); inc(&c); inc(&c);\n    printf("%d\\n", c.compteur);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\ntypedef struct { int compteur; } Cell;\n\nvoid inc(Cell *c) { c->compteur++; }\n\nint main(void) {\n    Cell c = {0};\n    inc(&c); inc(&c); inc(&c);\n    printf("%d\\n", c.compteur);\n    return 0;\n}\n`,
    tests: [
      { type: "regex", expected: "c\\s*->\\s*compteur" },
      { type: "output", expected_output: "3" },
    ],
  },
  {
    id: "c_64",
    type: "code",
    category: "Structures",
    title: "Tableau de structs",
    description: "Collection d'éléments structurés.",
    instruction: `Avec <code>typedef struct { char *nom; int age; } Personne;</code>, créez 3 personnes (Alice 20, Bob 30, Carol 25) et affichez la somme des âges.`,
    code_template: `#include <stdio.h>\n\ntypedef struct { char *nom; int age; } Personne;\n\nint main(void) {\n    Personne arr[3] = { {"Alice", 20}, {"Bob", 30}, {"Carol", 25} };\n    int s = 0;\n    // somme\n    printf("%d\\n", s);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\ntypedef struct { char *nom; int age; } Personne;\n\nint main(void) {\n    Personne arr[3] = { {"Alice", 20}, {"Bob", 30}, {"Carol", 25} };\n    int s = 0;\n    for (int i = 0; i < 3; i++) s += arr[i].age;\n    printf("%d\\n", s);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "75" }],
  },
  {
    id: "c_65",
    type: "code",
    category: "Structures",
    title: "Struct imbriquée",
    description: "Une struct dans une struct.",
    instruction: `Définissez <code>typedef struct { int x, y; } Point;</code> et <code>typedef struct { Point pos; int hp; } Joueur;</code>. Créez un joueur en (5, 10) avec 100 hp, affichez <code>pos.x + pos.y + hp</code>.`,
    code_template: `#include <stdio.h>\n\ntypedef struct { int x, y; } Point;\ntypedef struct { Point pos; int hp; } Joueur;\n\nint main(void) {\n    Joueur j = {{5, 10}, 100};\n    // afficher\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\ntypedef struct { int x, y; } Point;\ntypedef struct { Point pos; int hp; } Joueur;\n\nint main(void) {\n    Joueur j = {{5, 10}, 100};\n    printf("%d\\n", j.pos.x + j.pos.y + j.hp);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "115" }],
  },
  {
    id: "c_66",
    type: "quiz",
    category: "Enums",
    title: "Premier enum",
    content: `<p>Quelle est la valeur entière par défaut de <code>VERT</code> dans <code>enum Couleur { ROUGE, VERT, BLEU };</code> ?</p>`,
    options: ["0", "1", "2", "Indéfini"],
    correct: 1,
    explanation: "Par défaut, les enums démarrent à 0 et s'incrémentent. ROUGE=0, VERT=1, BLEU=2.",
  },
  {
    id: "c_67",
    type: "code",
    category: "Enums",
    title: "Enum dans un switch",
    description: "Switch sur les valeurs d'enum.",
    instruction: `Définissez <code>enum Saison { HIVER, PRINTEMPS, ETE, AUTOMNE };</code>, switchez sur <code>ETE</code> et affichez <code>chaud</code>.`,
    code_template: `#include <stdio.h>\n\nenum Saison { HIVER, PRINTEMPS, ETE, AUTOMNE };\n\nint main(void) {\n    enum Saison s = ETE;\n    // switch\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nenum Saison { HIVER, PRINTEMPS, ETE, AUTOMNE };\n\nint main(void) {\n    enum Saison s = ETE;\n    switch (s) {\n        case ETE: printf("chaud\\n"); break;\n        case HIVER: printf("froid\\n"); break;\n        default: printf("doux\\n"); break;\n    }\n    return 0;\n}\n`,
    tests: [
      { type: "contains", expected: "switch" },
      { type: "output", expected_output: "chaud" },
    ],
  },
  {
    id: "c_68",
    type: "code",
    category: "Enums",
    title: "Enum avec valeur explicite",
    description: "Assigner des valeurs custom.",
    instruction: `Définissez <code>enum Code { OK = 200, NOT_FOUND = 404, SERVER_ERR = 500 };</code> puis affichez <code>NOT_FOUND</code>.`,
    code_template: `#include <stdio.h>\n\n// enum ici\n\nint main(void) {\n    // afficher NOT_FOUND\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nenum Code { OK = 200, NOT_FOUND = 404, SERVER_ERR = 500 };\n\nint main(void) {\n    printf("%d\\n", NOT_FOUND);\n    return 0;\n}\n`,
    tests: [
      { type: "regex", expected: "NOT_FOUND\\s*=\\s*404" },
      { type: "output", expected_output: "404" },
    ],
  },
  {
    id: "c_69",
    type: "code",
    category: "Unions",
    title: "Première union",
    description: "Plusieurs membres au même endroit.",
    instruction: `Définissez <code>union Valeur { int i; float f; };</code>, assignez <code>i = 42</code> et affichez <code>i</code>.`,
    code_template: `#include <stdio.h>\n\nunion Valeur { int i; float f; };\n\nint main(void) {\n    union Valeur v;\n    v.i = 42;\n    // afficher\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nunion Valeur { int i; float f; };\n\nint main(void) {\n    union Valeur v;\n    v.i = 42;\n    printf("%d\\n", v.i);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "42" }],
  },
  {
    id: "c_70",
    type: "quiz",
    category: "Unions",
    title: "Taille d'une union",
    content: `<p>Quelle est <strong>sizeof(union)</strong> pour <code>union U { int i; double d; char c; };</code> (sur une machine 64-bit standard) ?</p>`,
    options: ["13 (somme)", "1 (le plus petit)", "8 (le plus grand)", "4 (le médian)"],
    correct: 2,
    explanation: "Une union occupe la place du plus grand de ses membres. <code>double</code> = 8 octets.",
  },
  {
    id: "c_71",
    type: "code",
    category: "Opérations bit à bit",
    title: "ET binaire",
    description: "Opérateur &.",
    instruction: `Affichez <code>12 & 10</code>. Indice : 12 = 1100, 10 = 1010, AND = 1000 = 8.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    // 12 & 10\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    printf("%d\\n", 12 & 10);\n    return 0;\n}\n`,
    tests: [
      { type: "contains", expected: "&" },
      { type: "output", expected_output: "8" },
    ],
  },
  {
    id: "c_72",
    type: "code",
    category: "Opérations bit à bit",
    title: "OU binaire",
    description: "Opérateur |.",
    instruction: `Affichez <code>12 | 10</code>.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    // 12 | 10\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    printf("%d\\n", 12 | 10);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "14" }],
  },
  {
    id: "c_73",
    type: "code",
    category: "Opérations bit à bit",
    title: "XOR binaire",
    description: "Opérateur ^.",
    instruction: `Affichez <code>12 ^ 10</code>.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    // 12 ^ 10\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    printf("%d\\n", 12 ^ 10);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "6" }],
  },
  {
    id: "c_74",
    type: "code",
    category: "Opérations bit à bit",
    title: "Décalage à gauche",
    description: "Multiplier par 2^n.",
    instruction: `Affichez <code>1 &lt;&lt; 5</code>.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    // 1 << 5\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    printf("%d\\n", 1 << 5);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "32" }],
  },
  {
    id: "c_75",
    type: "code",
    category: "Opérations bit à bit",
    title: "Vérifier qu'un nombre est pair",
    description: "Test du bit de poids faible.",
    instruction: `Affichez <code>pair</code> si <code>14</code> est pair, sinon <code>impair</code>, en utilisant uniquement <code>&amp;</code> (pas <code>%</code>).`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int n = 14;\n    // tester bit de poids faible\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int n = 14;\n    printf("%s\\n", (n & 1) == 0 ? "pair" : "impair");\n    return 0;\n}\n`,
    tests: [
      { type: "not_contains", expected: "%" },
      { type: "output", expected_output: "pair" },
    ],
  },
  {
    id: "c_76",
    type: "code",
    category: "Opérations bit à bit",
    title: "Compter les bits à 1",
    description: "Popcount naïf.",
    instruction: `Comptez le nombre de bits à 1 dans <code>0b10110110</code> (= 182) et affichez le résultat.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int n = 0b10110110;\n    int count = 0;\n    // boucle\n    printf("%d\\n", count);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int n = 0b10110110;\n    int count = 0;\n    while (n) { count += n & 1; n >>= 1; }\n    printf("%d\\n", count);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "5" }],
  },
  {
    id: "c_77",
    type: "code",
    category: "Opérations bit à bit",
    title: "Set, clear, toggle",
    description: "Manipulation de bits.",
    instruction: `Démarrez avec <code>x = 0</code>. Set bit 3 (<code>x |= (1 &lt;&lt; 3)</code>), set bit 0, clear bit 3. Affichez x final.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int x = 0;\n    // set, set, clear\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int x = 0;\n    x |= (1 << 3);\n    x |= (1 << 0);\n    x &= ~(1 << 3);\n    printf("%d\\n", x);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "1" }],
  },
  {
    id: "c_78",
    type: "code",
    category: "Opérations bit à bit",
    title: "Hex via printf",
    description: "Formatage hexadécimal.",
    instruction: `Affichez <code>255</code> en hexadécimal avec <code>%x</code>.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    // %x\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    printf("%x\\n", 255);\n    return 0;\n}\n`,
    tests: [
      { type: "contains", expected: "%x" },
      { type: "output", expected_output: "ff" },
    ],
  },
  {
    id: "c_79",
    type: "code",
    category: "Opérations bit à bit",
    title: "Échanger via XOR",
    description: "Swap sans variable temporaire.",
    instruction: `Échangez <code>a=3, b=5</code> en utilisant uniquement XOR (sans variable temporaire), puis affichez <code>a b</code>.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int a = 3, b = 5;\n    // swap via XOR\n    printf("%d %d\\n", a, b);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int a = 3, b = 5;\n    a ^= b; b ^= a; a ^= b;\n    printf("%d %d\\n", a, b);\n    return 0;\n}\n`,
    tests: [
      { type: "regex", expected: "\\^=" },
      { type: "output", expected_output: "5 3" },
    ],
  },
  {
    id: "c_80",
    type: "code",
    category: "Opérations bit à bit",
    title: "Puissance de 2 ?",
    description: "Détection rapide.",
    instruction: `Vérifiez si <code>64</code> est une puissance de 2 (utilisez <code>n &amp; (n-1)</code>), affichez <code>oui</code> ou <code>non</code>.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int n = 64;\n    // test\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int n = 64;\n    printf("%s\\n", (n > 0 && (n & (n - 1)) == 0) ? "oui" : "non");\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "oui" }],
  },
  {
    id: "c_81",
    type: "code",
    category: "Fichiers",
    title: "Écrire dans un fichier",
    description: "fopen, fprintf, fclose.",
    instruction: `Ouvrez <code>"out.txt"</code> en écriture, écrivez <code>"Hello!"</code> avec <code>fprintf</code>, fermez. Puis ouvrez en lecture et affichez le contenu.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    // écrire puis lire\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    FILE *f = fopen("out.txt", "w");\n    fprintf(f, "Hello!");\n    fclose(f);\n    f = fopen("out.txt", "r");\n    char buf[16];\n    fgets(buf, 16, f);\n    fclose(f);\n    printf("%s\\n", buf);\n    return 0;\n}\n`,
    tests: [
      { type: "contains", expected: "fopen" },
      { type: "contains", expected: "fclose" },
      { type: "output", expected_output: "Hello!" },
    ],
  },
  {
    id: "c_82",
    type: "code",
    category: "Fichiers",
    title: "Lire ligne par ligne",
    description: "fgets dans une boucle.",
    instruction: `Écrivez <code>"a\\nb\\nc"</code> dans <code>"in.txt"</code>, puis relisez ligne par ligne avec <code>fgets</code> et affichez le total de lignes lues.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    FILE *f = fopen("in.txt", "w");\n    fprintf(f, "a\\nb\\nc\\n");\n    fclose(f);\n    // relire\n    f = fopen("in.txt", "r");\n    char buf[16];\n    int n = 0;\n    // boucle fgets\n    fclose(f);\n    printf("%d\\n", n);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    FILE *f = fopen("in.txt", "w");\n    fprintf(f, "a\\nb\\nc\\n");\n    fclose(f);\n    f = fopen("in.txt", "r");\n    char buf[16];\n    int n = 0;\n    while (fgets(buf, sizeof buf, f)) n++;\n    fclose(f);\n    printf("%d\\n", n);\n    return 0;\n}\n`,
    tests: [
      { type: "contains", expected: "fgets" },
      { type: "output", expected_output: "3" },
    ],
  },
  {
    id: "c_83",
    type: "code",
    category: "Fichiers",
    title: "fwrite binaire",
    description: "Écriture brute.",
    instruction: `Écrivez un tableau <code>int t[3] = {10, 20, 30}</code> dans <code>"data.bin"</code> avec <code>fwrite</code>, puis relisez avec <code>fread</code> et affichez la somme.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    int t[3] = {10, 20, 30};\n    FILE *f = fopen("data.bin", "wb");\n    // fwrite\n    fclose(f);\n    int r[3];\n    f = fopen("data.bin", "rb");\n    // fread\n    fclose(f);\n    int s = 0;\n    for (int i = 0; i < 3; i++) s += r[i];\n    printf("%d\\n", s);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    int t[3] = {10, 20, 30};\n    FILE *f = fopen("data.bin", "wb");\n    fwrite(t, sizeof(int), 3, f);\n    fclose(f);\n    int r[3];\n    f = fopen("data.bin", "rb");\n    fread(r, sizeof(int), 3, f);\n    fclose(f);\n    int s = 0;\n    for (int i = 0; i < 3; i++) s += r[i];\n    printf("%d\\n", s);\n    return 0;\n}\n`,
    tests: [
      { type: "contains", expected: "fwrite" },
      { type: "contains", expected: "fread" },
      { type: "output", expected_output: "60" },
    ],
  },
  {
    id: "c_84",
    type: "code",
    category: "Fichiers",
    title: "ftell / fseek",
    description: "Positionnement dans un fichier.",
    instruction: `Écrivez <code>"ABCDEFG"</code> dans <code>"a.txt"</code>. Ouvrez en lecture, <code>fseek</code> à offset 3, lisez 1 caractère et affichez-le.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    FILE *f = fopen("a.txt", "w");\n    fprintf(f, "ABCDEFG");\n    fclose(f);\n    // fseek + lire\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    FILE *f = fopen("a.txt", "w");\n    fprintf(f, "ABCDEFG");\n    fclose(f);\n    f = fopen("a.txt", "r");\n    fseek(f, 3, SEEK_SET);\n    char c = fgetc(f);\n    fclose(f);\n    printf("%c\\n", c);\n    return 0;\n}\n`,
    tests: [
      { type: "contains", expected: "fseek" },
      { type: "output", expected_output: "D" },
    ],
  },
  {
    id: "c_85",
    type: "code",
    category: "Fichiers",
    title: "Compter octets",
    description: "Taille d'un fichier via fseek+ftell.",
    instruction: `Écrivez <code>"Hello, World!"</code> (13 caractères) dans <code>"size.txt"</code>. Ouvrez en lecture, allez à la fin avec <code>fseek(f, 0, SEEK_END)</code>, puis affichez <code>ftell(f)</code>.`,
    code_template: `#include <stdio.h>\n\nint main(void) {\n    FILE *f = fopen("size.txt", "w");\n    fprintf(f, "Hello, World!");\n    fclose(f);\n    // taille\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n\nint main(void) {\n    FILE *f = fopen("size.txt", "w");\n    fprintf(f, "Hello, World!");\n    fclose(f);\n    f = fopen("size.txt", "r");\n    fseek(f, 0, SEEK_END);\n    long n = ftell(f);\n    fclose(f);\n    printf("%ld\\n", n);\n    return 0;\n}\n`,
    tests: [
      { type: "contains", expected: "ftell" },
      { type: "output", expected_output: "13" },
    ],
  },
  {
    id: "c_86",
    type: "code",
    category: "Mémoire dynamique",
    title: "calloc",
    description: "Allouer + zero-initialiser.",
    instruction: `Allouez un tableau de 5 <code>int</code> avec <code>calloc</code>, affichez tous les éléments séparés par espaces (doivent être 0), puis <code>free</code>.`,
    code_template: `#include <stdio.h>\n#include <stdlib.h>\n\nint main(void) {\n    // calloc\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <stdlib.h>\n\nint main(void) {\n    int *t = calloc(5, sizeof(int));\n    for (int i = 0; i < 5; i++) printf("%d ", t[i]);\n    printf("\\n");\n    free(t);\n    return 0;\n}\n`,
    tests: [
      { type: "contains", expected: "calloc" },
      { type: "output", expected_output: "0 0 0 0 0" },
    ],
  },
  {
    id: "c_87",
    type: "code",
    category: "Mémoire dynamique",
    title: "realloc",
    description: "Redimensionner une allocation.",
    instruction: `Allouez 3 <code>int</code> avec <code>malloc</code>, remplissez avec {1, 2, 3}, puis <code>realloc</code> à 5 éléments et complétez avec {4, 5}. Affichez la somme totale.`,
    code_template: `#include <stdio.h>\n#include <stdlib.h>\n\nint main(void) {\n    int *t = malloc(3 * sizeof(int));\n    t[0] = 1; t[1] = 2; t[2] = 3;\n    // realloc à 5\n    int s = 0;\n    for (int i = 0; i < 5; i++) s += t[i];\n    printf("%d\\n", s);\n    free(t);\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <stdlib.h>\n\nint main(void) {\n    int *t = malloc(3 * sizeof(int));\n    t[0] = 1; t[1] = 2; t[2] = 3;\n    t = realloc(t, 5 * sizeof(int));\n    t[3] = 4; t[4] = 5;\n    int s = 0;\n    for (int i = 0; i < 5; i++) s += t[i];\n    printf("%d\\n", s);\n    free(t);\n    return 0;\n}\n`,
    tests: [
      { type: "contains", expected: "realloc" },
      { type: "output", expected_output: "15" },
    ],
  },
  {
    id: "c_88",
    type: "code",
    category: "Mémoire dynamique",
    title: "Allouer un tableau 2D",
    description: "Tableau de pointeurs.",
    instruction: `Allouez dynamiquement une matrice 3×3 d'entiers (tableau de pointeurs), remplissez avec <code>i*3 + j</code>, affichez la diagonale (m[0][0], m[1][1], m[2][2]) séparée par espaces, puis libérez.`,
    code_template: `#include <stdio.h>\n#include <stdlib.h>\n\nint main(void) {\n    // allouer + remplir + afficher + free\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <stdlib.h>\n\nint main(void) {\n    int **m = malloc(3 * sizeof(int *));\n    for (int i = 0; i < 3; i++) {\n        m[i] = malloc(3 * sizeof(int));\n        for (int j = 0; j < 3; j++) m[i][j] = i * 3 + j;\n    }\n    for (int i = 0; i < 3; i++) printf("%d ", m[i][i]);\n    printf("\\n");\n    for (int i = 0; i < 3; i++) free(m[i]);\n    free(m);\n    return 0;\n}\n`,
    tests: [{ type: "output", expected_output: "0 4 8" }],
  },
  {
    id: "c_89",
    type: "code",
    category: "Mémoire dynamique",
    title: "strdup à la main",
    description: "Allouer + copier une chaîne.",
    instruction: `Sans utiliser <code>strdup</code>, copiez <code>"Lyoko"</code> dans un buffer alloué par <code>malloc</code>, affichez-le, puis libérez.`,
    code_template: `#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n\nint main(void) {\n    const char *src = "Lyoko";\n    // malloc + strcpy\n    return 0;\n}\n`,
    solution: `#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n\nint main(void) {\n    const char *src = "Lyoko";\n    char *dup = malloc(strlen(src) + 1);\n    strcpy(dup, src);\n    printf("%s\\n", dup);\n    free(dup);\n    return 0;\n}\n`,
    tests: [
      { type: "contains", expected: "malloc" },
      { type: "not_contains", expected: "strdup" },
      { type: "output", expected_output: "Lyoko" },
    ],
  },
  {
    id: "c_90",
    type: "quiz",
    category: "Mémoire dynamique",
    title: "Que faire après free ?",
    content: `<p>Après avoir libéré un pointeur avec <code>free(p)</code>, quelle est la meilleure pratique ?</p>`,
    options: [
      "Réutiliser p tel quel",
      "Faire p = NULL pour éviter un dangling pointer",
      "Appeler free(p) une seconde fois",
      "Rien, le compilateur s'en occupe",
    ],
    correct: 1,
    explanation: "Après <code>free</code>, le pointeur devient invalide (dangling). L'assigner à <code>NULL</code> empêche toute utilisation accidentelle et rend les bugs visibles (segfault propre).",
  },
];

addExercises("c", exercises);
