import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/** Module C — Part 11 : POSIX (fork, exec, pipes, signals, threads). */
const exercises: Exercise[] = [
  { id: "c_201", type: "code", category: "POSIX", title: "fork()", description: "Créer un processus enfant.", instruction: "Utilisez <code>fork()</code>. Si pid==0, affichez \"child\", sinon attendez avec <code>wait(NULL)</code> puis affichez \"parent\".", code_template: "#include <stdio.h>\n#include <sys/wait.h>\n#include <unistd.h>\nint main(void) {\n    // fork\n    return 0;\n}\n", solution: "#include <stdio.h>\n#include <sys/wait.h>\n#include <unistd.h>\nint main(void) {\n    pid_t pid = fork();\n    if (pid == 0) {\n        printf(\"child\\n\");\n    } else {\n        wait(NULL);\n        printf(\"parent\\n\");\n    }\n    return 0;\n}\n", tests: [{ type: "contains", expected: "fork()" }, { type: "contains", expected: "wait(NULL)" }] },
  { id: "c_202", type: "code", category: "POSIX", title: "getpid / getppid", description: "PID du process.", instruction: "Affichez <code>getpid()</code> et <code>getppid()</code> séparés d'un espace.", code_template: "#include <stdio.h>\n#include <unistd.h>\nint main(void) {\n    // pid + ppid\n    return 0;\n}\n", solution: "#include <stdio.h>\n#include <unistd.h>\nint main(void) {\n    printf(\"%d %d\\n\", getpid(), getppid());\n    return 0;\n}\n", tests: [{ type: "contains", expected: "getpid()" }, { type: "contains", expected: "getppid()" }] },
  { id: "c_203", type: "code", category: "POSIX", title: "execlp", description: "Remplacer le process par une commande.", instruction: "Utilisez <code>execlp(\"ls\", \"ls\", NULL)</code> après un fork.", code_template: "#include <unistd.h>\n#include <sys/wait.h>\nint main(void) {\n    if (fork() == 0) {\n        // execlp\n    } else {\n        wait(NULL);\n    }\n    return 0;\n}\n", solution: "#include <unistd.h>\n#include <sys/wait.h>\nint main(void) {\n    if (fork() == 0) {\n        execlp(\"ls\", \"ls\", NULL);\n    } else {\n        wait(NULL);\n    }\n    return 0;\n}\n", tests: [{ type: "contains", expected: "execlp" }] },
  { id: "c_204", type: "code", category: "POSIX", title: "pipe()", description: "Communication entre process.", instruction: "Créez un pipe avec <code>int fd[2]; pipe(fd);</code> et affichez fd[0] et fd[1].", code_template: "#include <stdio.h>\n#include <unistd.h>\nint main(void) {\n    int fd[2];\n    // pipe\n    return 0;\n}\n", solution: "#include <stdio.h>\n#include <unistd.h>\nint main(void) {\n    int fd[2];\n    pipe(fd);\n    printf(\"%d %d\\n\", fd[0] >= 0, fd[1] >= 0);\n    close(fd[0]); close(fd[1]);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "1 1" }] },
  { id: "c_205", type: "code", category: "POSIX", title: "Signal SIGINT", description: "Capter Ctrl+C.", instruction: "Installez un handler avec <code>signal(SIGINT, handler)</code>.", code_template: "#include <stdio.h>\n#include <signal.h>\nvoid handler(int sig) { printf(\"caught\\n\"); }\nint main(void) {\n    // signal\n    return 0;\n}\n", solution: "#include <stdio.h>\n#include <signal.h>\nvoid handler(int sig) { printf(\"caught\\n\"); }\nint main(void) {\n    signal(SIGINT, handler);\n    printf(\"ok\\n\");\n    return 0;\n}\n", tests: [{ type: "contains", expected: "signal(SIGINT" }] },
  { id: "c_206", type: "code", category: "POSIX", title: "kill()", description: "Envoyer un signal.", instruction: "Utilisez <code>kill(getpid(), SIGUSR1)</code> avec un handler qui affiche \"sig\".", code_template: "#include <stdio.h>\n#include <signal.h>\n#include <unistd.h>\nvoid h(int s) { printf(\"sig\\n\"); }\nint main(void) {\n    signal(SIGUSR1, h);\n    // kill\n    return 0;\n}\n", solution: "#include <stdio.h>\n#include <signal.h>\n#include <unistd.h>\nvoid h(int s) { printf(\"sig\\n\"); }\nint main(void) {\n    signal(SIGUSR1, h);\n    kill(getpid(), SIGUSR1);\n    return 0;\n}\n", tests: [{ type: "contains", expected: "kill(getpid()" }] },
  { id: "c_207", type: "code", category: "Threads", title: "pthread_create", description: "Lancer un thread.", instruction: "Avec <code>pthread_create(&t, NULL, fn, NULL)</code>, lancez un thread qui affiche \"hi\". Joindre.", code_template: "#include <stdio.h>\n#include <pthread.h>\nvoid *fn(void *arg) { printf(\"hi\\n\"); return NULL; }\nint main(void) {\n    pthread_t t;\n    // create + join\n    return 0;\n}\n", solution: "#include <stdio.h>\n#include <pthread.h>\nvoid *fn(void *arg) { printf(\"hi\\n\"); return NULL; }\nint main(void) {\n    pthread_t t;\n    pthread_create(&t, NULL, fn, NULL);\n    pthread_join(t, NULL);\n    return 0;\n}\n", tests: [{ type: "contains", expected: "pthread_create" }, { type: "contains", expected: "pthread_join" }] },
  { id: "c_208", type: "code", category: "Threads", title: "Passer un argument", description: "Argument au thread.", instruction: "Passez un <code>int*</code> au thread qui affiche sa valeur (42).", code_template: "#include <stdio.h>\n#include <pthread.h>\nvoid *fn(void *arg) {\n    // \n    return NULL;\n}\nint main(void) {\n    pthread_t t;\n    int x = 42;\n    // create\n    return 0;\n}\n", solution: "#include <stdio.h>\n#include <pthread.h>\nvoid *fn(void *arg) {\n    int *p = (int*)arg;\n    printf(\"%d\\n\", *p);\n    return NULL;\n}\nint main(void) {\n    pthread_t t;\n    int x = 42;\n    pthread_create(&t, NULL, fn, &x);\n    pthread_join(t, NULL);\n    return 0;\n}\n", tests: [{ type: "contains", expected: "pthread_create(&t, NULL, fn, &x)" }] },
  { id: "c_209", type: "code", category: "Threads", title: "Mutex", description: "Section critique.", instruction: "Protégez l'incrément d'un compteur partagé avec <code>pthread_mutex_t</code>.", code_template: "#include <pthread.h>\npthread_mutex_t m = PTHREAD_MUTEX_INITIALIZER;\nint counter = 0;\nvoid *inc(void *arg) {\n    // lock/unlock\n    return NULL;\n}\nint main(void) {\n    return 0;\n}\n", solution: "#include <pthread.h>\npthread_mutex_t m = PTHREAD_MUTEX_INITIALIZER;\nint counter = 0;\nvoid *inc(void *arg) {\n    pthread_mutex_lock(&m);\n    counter++;\n    pthread_mutex_unlock(&m);\n    return NULL;\n}\nint main(void) {\n    return 0;\n}\n", tests: [{ type: "contains", expected: "pthread_mutex_lock" }, { type: "contains", expected: "pthread_mutex_unlock" }] },
  { id: "c_210", type: "code", category: "Threads", title: "pthread_self", description: "ID du thread courant.", instruction: "Affichez <code>pthread_self()</code> > 0 (résultat : 1).", code_template: "#include <stdio.h>\n#include <pthread.h>\nint main(void) {\n    // self\n    return 0;\n}\n", solution: "#include <stdio.h>\n#include <pthread.h>\nint main(void) {\n    pthread_t s = pthread_self();\n    printf(\"%d\\n\", s != 0 ? 1 : 0);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "1" }] },
  { id: "c_211", type: "code", category: "Réseaux", title: "socket() TCP", description: "Créer un socket.", instruction: "<code>socket(AF_INET, SOCK_STREAM, 0)</code>. Affichez 1 si fd ≥ 0.", code_template: "#include <stdio.h>\n#include <sys/socket.h>\nint main(void) {\n    // socket\n    return 0;\n}\n", solution: "#include <stdio.h>\n#include <sys/socket.h>\n#include <unistd.h>\nint main(void) {\n    int fd = socket(AF_INET, SOCK_STREAM, 0);\n    printf(\"%d\\n\", fd >= 0 ? 1 : 0);\n    if (fd >= 0) close(fd);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "1" }] },
  { id: "c_212", type: "code", category: "Réseaux", title: "sockaddr_in", description: "Adresse IPv4.", instruction: "Initialisez une <code>struct sockaddr_in</code> avec port 8080 et INADDR_ANY.", code_template: "#include <netinet/in.h>\n#include <arpa/inet.h>\nint main(void) {\n    struct sockaddr_in addr;\n    // \n    return 0;\n}\n", solution: "#include <netinet/in.h>\n#include <arpa/inet.h>\nint main(void) {\n    struct sockaddr_in addr;\n    addr.sin_family = AF_INET;\n    addr.sin_port = htons(8080);\n    addr.sin_addr.s_addr = htonl(INADDR_ANY);\n    return 0;\n}\n", tests: [{ type: "contains", expected: "sin_family = AF_INET" }, { type: "contains", expected: "htons(8080)" }] },
  { id: "c_213", type: "code", category: "Réseaux", title: "bind()", description: "Associer socket+adresse.", instruction: "Bindez un socket sur une <code>sockaddr_in</code>.", code_template: "#include <sys/socket.h>\n#include <netinet/in.h>\nint main(void) {\n    int fd = socket(AF_INET, SOCK_STREAM, 0);\n    struct sockaddr_in a = {0};\n    a.sin_family = AF_INET; a.sin_port = htons(0); a.sin_addr.s_addr = htonl(INADDR_ANY);\n    // bind\n    return 0;\n}\n", solution: "#include <sys/socket.h>\n#include <netinet/in.h>\n#include <unistd.h>\nint main(void) {\n    int fd = socket(AF_INET, SOCK_STREAM, 0);\n    struct sockaddr_in a = {0};\n    a.sin_family = AF_INET; a.sin_port = htons(0); a.sin_addr.s_addr = htonl(INADDR_ANY);\n    bind(fd, (struct sockaddr*)&a, sizeof(a));\n    close(fd);\n    return 0;\n}\n", tests: [{ type: "contains", expected: "bind(fd" }] },
  { id: "c_214", type: "code", category: "Réseaux", title: "listen() / accept()", description: "Serveur TCP basique.", instruction: "Appelez <code>listen(fd, 5)</code> et <code>accept(fd, NULL, NULL)</code>.", code_template: "#include <sys/socket.h>\nint main(void) {\n    int fd = socket(AF_INET, SOCK_STREAM, 0);\n    // listen + accept\n    return 0;\n}\n", solution: "#include <sys/socket.h>\n#include <unistd.h>\nint main(void) {\n    int fd = socket(AF_INET, SOCK_STREAM, 0);\n    listen(fd, 5);\n    // accept(fd, NULL, NULL); -- skipped en runtime\n    close(fd);\n    return 0;\n}\n", tests: [{ type: "contains", expected: "listen(fd, 5)" }, { type: "contains", expected: "accept(fd" }] },
  { id: "c_215", type: "code", category: "Réseaux", title: "htons / ntohs", description: "Big-endian réseau.", instruction: "Convertissez 8080 en big-endian avec <code>htons</code>, reconvertissez avec <code>ntohs</code>. Affichez 8080.", code_template: "#include <stdio.h>\n#include <arpa/inet.h>\nint main(void) {\n    // \n    return 0;\n}\n", solution: "#include <stdio.h>\n#include <arpa/inet.h>\nint main(void) {\n    unsigned short n = htons(8080);\n    printf(\"%d\\n\", ntohs(n));\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "8080" }] },
  { id: "c_216", type: "code", category: "POSIX", title: "open() / read() / close()", description: "I/O bas niveau.", instruction: "Ouvrez <code>/dev/null</code> en lecture et fermez. Affichez 1 si fd ≥ 0.", code_template: "#include <fcntl.h>\n#include <unistd.h>\n#include <stdio.h>\nint main(void) {\n    // \n    return 0;\n}\n", solution: "#include <fcntl.h>\n#include <unistd.h>\n#include <stdio.h>\nint main(void) {\n    int fd = open(\"/dev/null\", O_RDONLY);\n    printf(\"%d\\n\", fd >= 0 ? 1 : 0);\n    if (fd >= 0) close(fd);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "1" }] },
  { id: "c_217", type: "code", category: "POSIX", title: "write() stdout", description: "Écriture brute.", instruction: "Avec <code>write(1, \"hi\\n\", 3)</code>, écrivez sur stdout.", code_template: "#include <unistd.h>\nint main(void) {\n    // write\n    return 0;\n}\n", solution: "#include <unistd.h>\nint main(void) {\n    write(1, \"hi\\n\", 3);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "hi" }] },
  { id: "c_218", type: "code", category: "POSIX", title: "dup2 redirection", description: "Rediriger stdout.", instruction: "Avec <code>dup2(fd, 1)</code>, redirigez stdout vers un fd (concept).", code_template: "#include <unistd.h>\n#include <fcntl.h>\nint main(void) {\n    int fd = open(\"/dev/null\", O_WRONLY);\n    // dup2\n    return 0;\n}\n", solution: "#include <unistd.h>\n#include <fcntl.h>\nint main(void) {\n    int fd = open(\"/dev/null\", O_WRONLY);\n    dup2(fd, 1);\n    close(fd);\n    return 0;\n}\n", tests: [{ type: "contains", expected: "dup2(fd, 1)" }] },
  { id: "c_219", type: "code", category: "POSIX", title: "sleep()", description: "Pause non busy.", instruction: "Appelez <code>sleep(0)</code> et affichez \"ok\".", code_template: "#include <stdio.h>\n#include <unistd.h>\nint main(void) {\n    // sleep\n    return 0;\n}\n", solution: "#include <stdio.h>\n#include <unistd.h>\nint main(void) {\n    sleep(0);\n    printf(\"ok\\n\");\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "ok" }] },
  { id: "c_220", type: "code", category: "POSIX", title: "errno + perror", description: "Diagnostic d'erreur.", instruction: "Si <code>open(\"/nope/x\", O_RDONLY) == -1</code>, affichez \"err\" sinon \"ok\".", code_template: "#include <stdio.h>\n#include <fcntl.h>\nint main(void) {\n    // \n    return 0;\n}\n", solution: "#include <stdio.h>\n#include <fcntl.h>\nint main(void) {\n    int fd = open(\"/nope/x\", O_RDONLY);\n    if (fd == -1) printf(\"err\\n\");\n    else printf(\"ok\\n\");\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "err" }] },
  { id: "c_221", type: "code", category: "Threads", title: "pthread_cond_t", description: "Variable de condition.", instruction: "Déclarez <code>pthread_cond_t cond = PTHREAD_COND_INITIALIZER</code> et appelez <code>pthread_cond_signal(&cond)</code>.", code_template: "#include <pthread.h>\nint main(void) {\n    pthread_cond_t cond = PTHREAD_COND_INITIALIZER;\n    // signal\n    return 0;\n}\n", solution: "#include <pthread.h>\nint main(void) {\n    pthread_cond_t cond = PTHREAD_COND_INITIALIZER;\n    pthread_cond_signal(&cond);\n    return 0;\n}\n", tests: [{ type: "contains", expected: "pthread_cond_signal" }] },
  { id: "c_222", type: "code", category: "Threads", title: "Detach", description: "Thread auto-cleanup.", instruction: "Détachez un thread avec <code>pthread_detach(t)</code>.", code_template: "#include <pthread.h>\nvoid *fn(void *arg) { return NULL; }\nint main(void) {\n    pthread_t t;\n    pthread_create(&t, NULL, fn, NULL);\n    // detach\n    return 0;\n}\n", solution: "#include <pthread.h>\nvoid *fn(void *arg) { return NULL; }\nint main(void) {\n    pthread_t t;\n    pthread_create(&t, NULL, fn, NULL);\n    pthread_detach(t);\n    return 0;\n}\n", tests: [{ type: "contains", expected: "pthread_detach(t)" }] },
  { id: "c_223", type: "code", category: "POSIX", title: "getenv", description: "Lire une env var.", instruction: "Affichez <code>getenv(\"PATH\")</code> non-NULL (1).", code_template: "#include <stdio.h>\n#include <stdlib.h>\nint main(void) {\n    // \n    return 0;\n}\n", solution: "#include <stdio.h>\n#include <stdlib.h>\nint main(void) {\n    char *p = getenv(\"PATH\");\n    printf(\"%d\\n\", p != NULL ? 1 : 0);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "1" }] },
  { id: "c_224", type: "code", category: "POSIX", title: "system()", description: "Exécuter une commande shell.", instruction: "Avec <code>system(\"echo Lyoko\")</code>, exécutez echo.", code_template: "#include <stdlib.h>\nint main(void) {\n    // system\n    return 0;\n}\n", solution: "#include <stdlib.h>\nint main(void) {\n    system(\"echo Lyoko\");\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "Lyoko" }] },
  { id: "c_225", type: "code", category: "POSIX", title: "time() / ctime()", description: "Horodatage.", instruction: "Avec <code>time(NULL)</code>, vérifiez que le timestamp est > 0 (affichez 1).", code_template: "#include <stdio.h>\n#include <time.h>\nint main(void) {\n    // \n    return 0;\n}\n", solution: "#include <stdio.h>\n#include <time.h>\nint main(void) {\n    time_t t = time(NULL);\n    printf(\"%d\\n\", t > 0 ? 1 : 0);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "1" }] },
];

addExercises("c", exercises);
