import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/** Module C — Part 9 : pointeurs avancés & gestion mémoire. */
const exercises: Exercise[] = [
  { id: "c_151", type: "code", category: "Pointeurs avancés", title: "Double pointeur", description: "Pointeur sur pointeur.", instruction: "Déclarez <code>int x = 42</code>, <code>int *p = &x</code>, <code>int **pp = &p</code>. Affichez <code>**pp</code>.", code_template: "#include <stdio.h>\nint main(void) {\n    int x = 42;\n    // **pp\n    return 0;\n}\n", solution: "#include <stdio.h>\nint main(void) {\n    int x = 42;\n    int *p = &x;\n    int **pp = &p;\n    printf(\"%d\\n\", **pp);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "42" }] },
  { id: "c_152", type: "code", category: "Pointeurs avancés", title: "Arithmétique de pointeur", description: "Avancer dans un tableau.", instruction: "Avec <code>int t[]={10,20,30}; int *p=t;</code>, affichez <code>*(p+2)</code>.", code_template: "#include <stdio.h>\nint main(void) {\n    int t[] = {10, 20, 30};\n    int *p = t;\n    // *(p+2)\n    return 0;\n}\n", solution: "#include <stdio.h>\nint main(void) {\n    int t[] = {10, 20, 30};\n    int *p = t;\n    printf(\"%d\\n\", *(p + 2));\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "30" }] },
  { id: "c_153", type: "code", category: "Pointeurs avancés", title: "Pointeur de fonction", description: "Stocker une fonction.", instruction: "Définissez <code>int add(int,int)</code> et un pointeur <code>int (*fp)(int,int)=add</code>. Appelez <code>fp(2,3)</code>.", code_template: "#include <stdio.h>\nint add(int a, int b) { return a + b; }\nint main(void) {\n    // fp\n    return 0;\n}\n", solution: "#include <stdio.h>\nint add(int a, int b) { return a + b; }\nint main(void) {\n    int (*fp)(int, int) = add;\n    printf(\"%d\\n\", fp(2, 3));\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "5" }] },
  { id: "c_154", type: "code", category: "Pointeurs avancés", title: "Callback avec qsort", description: "Comparateur passé à qsort.", instruction: "Triez <code>{3,1,4,1,5}</code> avec <code>qsort</code> et un comparateur d'entiers croissants.", code_template: "#include <stdio.h>\n#include <stdlib.h>\nint cmp(const void *a, const void *b) {\n    // \n}\nint main(void) {\n    int t[] = {3, 1, 4, 1, 5};\n    qsort(t, 5, sizeof(int), cmp);\n    for (int i = 0; i < 5; i++) printf(\"%d \", t[i]);\n    printf(\"\\n\");\n    return 0;\n}\n", solution: "#include <stdio.h>\n#include <stdlib.h>\nint cmp(const void *a, const void *b) {\n    return (*(int*)a) - (*(int*)b);\n}\nint main(void) {\n    int t[] = {3, 1, 4, 1, 5};\n    qsort(t, 5, sizeof(int), cmp);\n    for (int i = 0; i < 5; i++) printf(\"%d \", t[i]);\n    printf(\"\\n\");\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "1 1 3 4 5" }] },
  { id: "c_155", type: "code", category: "Pointeurs avancés", title: "void* générique", description: "Pointeur typé dynamiquement.", instruction: "Stockez un <code>int</code> dans un <code>void *p</code>, puis cast et affichez.", code_template: "#include <stdio.h>\nint main(void) {\n    int x = 7;\n    void *p = &x;\n    // cast\n    return 0;\n}\n", solution: "#include <stdio.h>\nint main(void) {\n    int x = 7;\n    void *p = &x;\n    printf(\"%d\\n\", *(int*)p);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "7" }] },
  { id: "c_156", type: "code", category: "Mémoire", title: "malloc / free", description: "Allocation dynamique.", instruction: "Allouez un <code>int*</code> avec <code>malloc</code>, mettez 99, affichez, puis <code>free</code>.", code_template: "#include <stdio.h>\n#include <stdlib.h>\nint main(void) {\n    int *p = malloc(sizeof(int));\n    // \n    free(p);\n    return 0;\n}\n", solution: "#include <stdio.h>\n#include <stdlib.h>\nint main(void) {\n    int *p = malloc(sizeof(int));\n    *p = 99;\n    printf(\"%d\\n\", *p);\n    free(p);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "99" }] },
  { id: "c_157", type: "code", category: "Mémoire", title: "calloc", description: "Allocation zéro-initialisée.", instruction: "Allouez 5 entiers avec <code>calloc(5, sizeof(int))</code> et affichez la somme (0).", code_template: "#include <stdio.h>\n#include <stdlib.h>\nint main(void) {\n    // calloc\n    return 0;\n}\n", solution: "#include <stdio.h>\n#include <stdlib.h>\nint main(void) {\n    int *p = calloc(5, sizeof(int));\n    int s = 0;\n    for (int i = 0; i < 5; i++) s += p[i];\n    printf(\"%d\\n\", s);\n    free(p);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "0" }] },
  { id: "c_158", type: "code", category: "Mémoire", title: "realloc", description: "Redimensionner un buffer.", instruction: "Allouez 3 ints, écrivez 1,2,3, <code>realloc</code> à 5, affichez taille.", code_template: "#include <stdio.h>\n#include <stdlib.h>\nint main(void) {\n    int *p = malloc(3 * sizeof(int));\n    for (int i = 0; i < 3; i++) p[i] = i + 1;\n    // realloc\n    return 0;\n}\n", solution: "#include <stdio.h>\n#include <stdlib.h>\nint main(void) {\n    int *p = malloc(3 * sizeof(int));\n    for (int i = 0; i < 3; i++) p[i] = i + 1;\n    p = realloc(p, 5 * sizeof(int));\n    printf(\"%d\\n\", 5);\n    free(p);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "5" }] },
  { id: "c_159", type: "code", category: "Mémoire", title: "Tableau 2D dynamique", description: "Matrice via malloc.", instruction: "Allouez une matrice 2×3 d'<code>int**</code>, remplissez et affichez <code>m[1][2]</code> = 6.", code_template: "#include <stdio.h>\n#include <stdlib.h>\nint main(void) {\n    int **m = malloc(2 * sizeof(int*));\n    for (int i = 0; i < 2; i++) m[i] = malloc(3 * sizeof(int));\n    // remplir\n    return 0;\n}\n", solution: "#include <stdio.h>\n#include <stdlib.h>\nint main(void) {\n    int **m = malloc(2 * sizeof(int*));\n    for (int i = 0; i < 2; i++) m[i] = malloc(3 * sizeof(int));\n    int k = 1;\n    for (int i = 0; i < 2; i++) for (int j = 0; j < 3; j++) m[i][j] = k++;\n    printf(\"%d\\n\", m[1][2]);\n    for (int i = 0; i < 2; i++) free(m[i]);\n    free(m);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "6" }] },
  { id: "c_160", type: "code", category: "Mémoire", title: "memcpy", description: "Copie mémoire bas niveau.", instruction: "Copiez <code>\"Lyoko\"</code> vers un buffer avec <code>memcpy</code>.", code_template: "#include <stdio.h>\n#include <string.h>\nint main(void) {\n    char buf[16];\n    // memcpy\n    return 0;\n}\n", solution: "#include <stdio.h>\n#include <string.h>\nint main(void) {\n    char buf[16];\n    memcpy(buf, \"Lyoko\", 6);\n    printf(\"%s\\n\", buf);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "Lyoko" }] },
  { id: "c_161", type: "code", category: "Mémoire", title: "memset", description: "Initialisation mémoire.", instruction: "Avec <code>memset</code>, remplissez un buffer de 5 octets avec <code>'A'</code>.", code_template: "#include <stdio.h>\n#include <string.h>\nint main(void) {\n    char buf[6];\n    // memset\n    buf[5] = 0;\n    printf(\"%s\\n\", buf);\n    return 0;\n}\n", solution: "#include <stdio.h>\n#include <string.h>\nint main(void) {\n    char buf[6];\n    memset(buf, 'A', 5);\n    buf[5] = 0;\n    printf(\"%s\\n\", buf);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "AAAAA" }] },
  { id: "c_162", type: "code", category: "Mémoire", title: "memcmp", description: "Comparer des blocs mémoire.", instruction: "Comparez <code>\"abc\"</code> et <code>\"abd\"</code> avec <code>memcmp</code>. Affichez 1 si différent, 0 sinon.", code_template: "#include <stdio.h>\n#include <string.h>\nint main(void) {\n    // memcmp\n    return 0;\n}\n", solution: "#include <stdio.h>\n#include <string.h>\nint main(void) {\n    int r = memcmp(\"abc\", \"abd\", 3);\n    printf(\"%d\\n\", r != 0 ? 1 : 0);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "1" }] },
  { id: "c_163", type: "code", category: "Mémoire", title: "Fuite mémoire", description: "Détecter un leak.", instruction: "Corrigez le leak : allouez puis libérez correctement. Affichez \"ok\".", code_template: "#include <stdio.h>\n#include <stdlib.h>\nint main(void) {\n    int *p = malloc(sizeof(int) * 100);\n    // free ?\n    printf(\"ok\\n\");\n    return 0;\n}\n", solution: "#include <stdio.h>\n#include <stdlib.h>\nint main(void) {\n    int *p = malloc(sizeof(int) * 100);\n    free(p);\n    printf(\"ok\\n\");\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "ok" }] },
  { id: "c_164", type: "code", category: "Pointeurs avancés", title: "Pointeur const", description: "Pointeur sur const.", instruction: "Déclarez <code>const int *p</code> pointant sur <code>x=5</code>. Affichez <code>*p</code>.", code_template: "#include <stdio.h>\nint main(void) {\n    int x = 5;\n    // const int *p\n    return 0;\n}\n", solution: "#include <stdio.h>\nint main(void) {\n    int x = 5;\n    const int *p = &x;\n    printf(\"%d\\n\", *p);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "5" }] },
  { id: "c_165", type: "code", category: "Pointeurs avancés", title: "Pointer to const vs const pointer", description: "Distinguer les 2 const.", instruction: "Déclarez <code>int * const p = &x</code> (pointeur const sur int). Modifiez <code>*p</code> à 10.", code_template: "#include <stdio.h>\nint main(void) {\n    int x = 5;\n    // int * const p\n    return 0;\n}\n", solution: "#include <stdio.h>\nint main(void) {\n    int x = 5;\n    int * const p = &x;\n    *p = 10;\n    printf(\"%d\\n\", x);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "10" }] },
  { id: "c_166", type: "code", category: "Pointeurs avancés", title: "NULL check", description: "Sécuriser un déréférencement.", instruction: "Si <code>malloc</code> renvoie NULL, affichez \"fail\", sinon affichez \"ok\" et libérez.", code_template: "#include <stdio.h>\n#include <stdlib.h>\nint main(void) {\n    int *p = malloc(sizeof(int));\n    // check\n    return 0;\n}\n", solution: "#include <stdio.h>\n#include <stdlib.h>\nint main(void) {\n    int *p = malloc(sizeof(int));\n    if (p == NULL) { printf(\"fail\\n\"); return 1; }\n    printf(\"ok\\n\");\n    free(p);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "ok" }] },
  { id: "c_167", type: "code", category: "Pointeurs avancés", title: "Swap avec pointeurs", description: "Échanger 2 entiers.", instruction: "Définissez <code>void swap(int*, int*)</code> et échangez 1 et 2.", code_template: "#include <stdio.h>\nvoid swap(int *a, int *b) {\n    // \n}\nint main(void) {\n    int x = 1, y = 2;\n    swap(&x, &y);\n    printf(\"%d %d\\n\", x, y);\n    return 0;\n}\n", solution: "#include <stdio.h>\nvoid swap(int *a, int *b) {\n    int t = *a; *a = *b; *b = t;\n}\nint main(void) {\n    int x = 1, y = 2;\n    swap(&x, &y);\n    printf(\"%d %d\\n\", x, y);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "2 1" }] },
  { id: "c_168", type: "code", category: "Pointeurs avancés", title: "Retourner un pointeur", description: "Pointeur en valeur de retour.", instruction: "Définissez <code>int* alloc_int(int v)</code> qui malloc et retourne un pointeur initialisé à v.", code_template: "#include <stdio.h>\n#include <stdlib.h>\nint* alloc_int(int v) {\n    // \n}\nint main(void) {\n    int *p = alloc_int(42);\n    printf(\"%d\\n\", *p);\n    free(p);\n    return 0;\n}\n", solution: "#include <stdio.h>\n#include <stdlib.h>\nint* alloc_int(int v) {\n    int *p = malloc(sizeof(int));\n    *p = v;\n    return p;\n}\n int main(void) {\n    int *p = alloc_int(42);\n    printf(\"%d\\n\", *p);\n    free(p);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "42" }] },
  { id: "c_169", type: "code", category: "Pointeurs avancés", title: "Tableau de pointeurs de fonctions", description: "Dispatch table.", instruction: "Créez <code>int (*ops[2])(int,int) = {add, sub}</code>, appelez <code>ops[0](5,3)</code>.", code_template: "#include <stdio.h>\nint add(int a, int b) { return a + b; }\nint sub(int a, int b) { return a - b; }\nint main(void) {\n    // table\n    return 0;\n}\n", solution: "#include <stdio.h>\nint add(int a, int b) { return a + b; }\nint sub(int a, int b) { return a - b; }\nint main(void) {\n    int (*ops[2])(int, int) = {add, sub};\n    printf(\"%d\\n\", ops[0](5, 3));\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "8" }] },
  { id: "c_170", type: "code", category: "Pointeurs avancés", title: "Pointeur sur struct", description: "Accès via ->.", instruction: "Déclarez <code>struct Point{int x,y;}</code>, allouez et accédez via <code>p-&gt;x = 3</code>.", code_template: "#include <stdio.h>\n#include <stdlib.h>\nstruct Point { int x, y; };\nint main(void) {\n    struct Point *p = malloc(sizeof(struct Point));\n    // p->x, p->y\n    free(p);\n    return 0;\n}\n", solution: "#include <stdio.h>\n#include <stdlib.h>\nstruct Point { int x, y; };\nint main(void) {\n    struct Point *p = malloc(sizeof(struct Point));\n    p->x = 3; p->y = 4;\n    printf(\"%d %d\\n\", p->x, p->y);\n    free(p);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "3 4" }] },
  { id: "c_171", type: "code", category: "Mémoire", title: "Stack vs heap", description: "Différence d'allocation.", instruction: "Déclarez <code>int s = 1</code> (stack) et <code>int *h = malloc(...)</code> avec *h=2 (heap). Affichez s+*h.", code_template: "#include <stdio.h>\n#include <stdlib.h>\nint main(void) {\n    // stack + heap\n    return 0;\n}\n", solution: "#include <stdio.h>\n#include <stdlib.h>\nint main(void) {\n    int s = 1;\n    int *h = malloc(sizeof(int));\n    *h = 2;\n    printf(\"%d\\n\", s + *h);\n    free(h);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "3" }] },
  { id: "c_172", type: "code", category: "Pointeurs avancés", title: "sizeof pointeur vs tableau", description: "Subtilité C.", instruction: "Affichez <code>sizeof(t)/sizeof(t[0])</code> pour <code>int t[5]</code> (résultat : 5).", code_template: "#include <stdio.h>\nint main(void) {\n    int t[5];\n    // sizeof\n    return 0;\n}\n", solution: "#include <stdio.h>\nint main(void) {\n    int t[5];\n    printf(\"%zu\\n\", sizeof(t) / sizeof(t[0]));\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "5" }] },
  { id: "c_173", type: "code", category: "Mémoire", title: "Strdup manuel", description: "Dupliquer une chaîne.", instruction: "Avec malloc + strcpy, dupliquez <code>\"Aelita\"</code> et affichez la copie.", code_template: "#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\nint main(void) {\n    const char *src = \"Aelita\";\n    // dup\n    return 0;\n}\n", solution: "#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\nint main(void) {\n    const char *src = \"Aelita\";\n    char *dup = malloc(strlen(src) + 1);\n    strcpy(dup, src);\n    printf(\"%s\\n\", dup);\n    free(dup);\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "Aelita" }] },
  { id: "c_174", type: "code", category: "Pointeurs avancés", title: "Restrict keyword", description: "Optimisation alias.", instruction: "Définissez <code>void copy(int * restrict d, const int * restrict s, int n)</code>.", code_template: "#include <stdio.h>\nvoid copy(int * restrict d, const int * restrict s, int n) {\n    // \n}\nint main(void) {\n    int a[3], b[] = {1, 2, 3};\n    copy(a, b, 3);\n    for (int i = 0; i < 3; i++) printf(\"%d \", a[i]);\n    printf(\"\\n\");\n    return 0;\n}\n", solution: "#include <stdio.h>\nvoid copy(int * restrict d, const int * restrict s, int n) {\n    for (int i = 0; i < n; i++) d[i] = s[i];\n}\nint main(void) {\n    int a[3], b[] = {1, 2, 3};\n    copy(a, b, 3);\n    for (int i = 0; i < 3; i++) printf(\"%d \", a[i]);\n    printf(\"\\n\");\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "1 2 3" }] },
  { id: "c_175", type: "code", category: "Mémoire", title: "Alignement", description: "alignof / _Alignof.", instruction: "Affichez <code>_Alignof(double)</code> (typiquement 8).", code_template: "#include <stdio.h>\n#include <stdalign.h>\nint main(void) {\n    // _Alignof\n    return 0;\n}\n", solution: "#include <stdio.h>\n#include <stdalign.h>\nint main(void) {\n    printf(\"%zu\\n\", _Alignof(double));\n    return 0;\n}\n", tests: [{ type: "output", expected_output: "8" }] },
];

addExercises("c", exercises);
