import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/**
 * C++ — Part 9 : templates avancés + concepts (C++20).
 */
const exercises: Exercise[] = [
  {
    id: "cpp_176",
    type: "code",
    category: "Templates",
    title: "Function template",
    description: "T générique.",
    instruction: "Définissez <code>template&lt;typename T&gt; T identity(T x) { return x; }</code>. Testez avec int.",
    code_template: "template<typename T> T identity(T x) {\n  return x;\n}",
    solution: "#include <iostream>\ntemplate<typename T> T identity(T x) {\n  return x;\n}\nint main() {\n  std::cout << identity(42) << '\\n';\n}",
    tests: [{ expected: "template<typename T>", type: "contains" }],
  },
  {
    id: "cpp_177",
    type: "code",
    category: "Templates",
    title: "Class template",
    description: "Container générique.",
    instruction: "Définissez <code>template&lt;typename T&gt; class Box { T value; ... };</code>.",
    code_template: "template<typename T>\nclass Box {\n  // \n};",
    solution: "#include <iostream>\ntemplate<typename T>\nclass Box {\n public:\n  T value;\n  T get() const { return value; }\n};\nint main() {\n  Box<int> b{42};\n  std::cout << b.get() << '\\n';\n}",
    tests: [{ expected: "template<typename T>", type: "contains" }, { expected: "class Box", type: "contains" }],
  },
  {
    id: "cpp_178",
    type: "code",
    category: "Templates",
    title: "Variadic template",
    description: "Nombre variable d'arguments.",
    instruction: "Définissez <code>template&lt;typename... Args&gt; void print(Args... args)</code> qui utilise fold expression.",
    code_template: "template<typename... Args>\nvoid print(Args... args) {\n  // \n}",
    solution: "#include <iostream>\ntemplate<typename... Args>\nvoid print(Args... args) {\n  ((std::cout << args << ' '), ...);\n  std::cout << '\\n';\n}\nint main() {\n  print(1, 2.5, \"hello\");\n}",
    tests: [{ expected: "typename... Args", type: "contains" }, { expected: "...", type: "contains" }],
  },
  {
    id: "cpp_179",
    type: "code",
    category: "Templates",
    title: "Template specialization",
    description: "Cas spécifique pour un type.",
    instruction: "Définissez <code>template&lt;typename T&gt; struct Trait</code> et une spécialisation pour <code>int</code>.",
    code_template: "template<typename T> struct Trait {\n  static const bool isInt = false;\n};\n// spécialisation int\n",
    solution: "template<typename T> struct Trait {\n  static const bool isInt = false;\n};\ntemplate<> struct Trait<int> {\n  static const bool isInt = true;\n};",
    tests: [{ expected: "template<> struct Trait<int>", type: "contains" }],
  },
  {
    id: "cpp_180",
    type: "code",
    category: "Templates",
    title: "Non-type template parameter",
    description: "Template paramétré par valeur.",
    instruction: "Définissez <code>template&lt;int N&gt; struct Array { int data[N]; };</code> et instanciez avec N=10.",
    code_template: "template<int N>\nstruct Array {\n  int data[N];\n};",
    solution: "#include <iostream>\ntemplate<int N>\nstruct Array {\n  int data[N];\n};\nint main() {\n  Array<10> arr;\n  std::cout << sizeof(arr.data) / sizeof(int) << '\\n';\n}",
    tests: [{ expected: "template<int N>", type: "contains" }],
  },
  {
    id: "cpp_181",
    type: "code",
    category: "Concepts",
    title: "Concept basique (C++20)",
    description: "Contrainte sur un template.",
    instruction: "Définissez <code>template&lt;typename T&gt; concept Numeric = std::is_arithmetic_v&lt;T&gt;;</code>.",
    code_template: "#include <type_traits>\ntemplate<typename T>\nconcept Numeric = /* */;",
    solution: "#include <type_traits>\ntemplate<typename T>\nconcept Numeric = std::is_arithmetic_v<T>;",
    tests: [{ expected: "concept Numeric", type: "contains" }, { expected: "is_arithmetic_v", type: "contains" }],
  },
  {
    id: "cpp_182",
    type: "code",
    category: "Concepts",
    title: "requires clause",
    description: "Contrainte sur une fonction template.",
    instruction: "Définissez <code>template&lt;Numeric T&gt; T add(T a, T b) { return a + b; }</code>.",
    code_template: "template<typename T>\nconcept Numeric = std::is_arithmetic_v<T>;\n// add\n",
    solution: "#include <type_traits>\ntemplate<typename T>\nconcept Numeric = std::is_arithmetic_v<T>;\ntemplate<Numeric T>\nT add(T a, T b) { return a + b; }",
    tests: [{ expected: "<Numeric T>", type: "contains" }],
  },
  {
    id: "cpp_183",
    type: "code",
    category: "Concepts",
    title: "Concept std::integral",
    description: "Concept standard.",
    instruction: "Définissez <code>template&lt;std::integral T&gt; T square(T x)</code>.",
    code_template: "#include <concepts>\n// square\n",
    solution: "#include <concepts>\ntemplate<std::integral T>\nT square(T x) { return x * x; }",
    tests: [{ expected: "std::integral", type: "contains" }],
  },
  {
    id: "cpp_184",
    type: "code",
    category: "Templates",
    title: "auto return type",
    description: "Type retourné déduit.",
    instruction: "Définissez <code>auto sum(int a, int b)</code> qui retourne a+b. Le compilateur déduit int.",
    code_template: "auto sum(int a, int b) {\n  // \n}",
    solution: "auto sum(int a, int b) {\n  return a + b;\n}",
    tests: [{ expected: "auto sum", type: "contains" }],
  },
  {
    id: "cpp_185",
    type: "code",
    category: "Templates",
    title: "decltype",
    description: "Type d'une expression.",
    instruction: "Avec <code>decltype</code>, déclarez <code>int x = 5; decltype(x) y = 10;</code>.",
    code_template: "int main() {\n  int x = 5;\n  // decltype\n}",
    solution: "int main() {\n  int x = 5;\n  decltype(x) y = 10;\n  return 0;\n}",
    tests: [{ expected: "decltype", type: "contains" }],
  },
  {
    id: "cpp_186",
    type: "code",
    category: "Templates",
    title: "trailing return type",
    description: "auto + ->.",
    instruction: "Définissez <code>auto multiply(int a, int b) -&gt; int</code>.",
    code_template: "// trailing return\n",
    solution: "auto multiply(int a, int b) -> int {\n  return a * b;\n}",
    tests: [{ expected: "-> int", type: "contains" }],
  },
  {
    id: "cpp_187",
    type: "code",
    category: "Templates",
    title: "Template avec default",
    description: "Type par défaut.",
    instruction: "Définissez <code>template&lt;typename T = int&gt; class Container</code> qui peut être utilisé sans angle brackets.",
    code_template: "template<typename T = int>\nclass Container {\n  T value;\n};",
    solution: "#include <iostream>\ntemplate<typename T = int>\nclass Container {\npublic:\n  T value{42};\n};\nint main() {\n  Container c;\n  std::cout << c.value << '\\n';\n}",
    tests: [{ expected: "T = int", type: "contains" }],
  },
  {
    id: "cpp_188",
    type: "code",
    category: "Templates",
    title: "SFINAE (concept précurseur)",
    description: "Substitution Failure Is Not An Error.",
    instruction: "Définissez <code>template&lt;typename T&gt; std::enable_if_t&lt;std::is_integral_v&lt;T&gt;, T&gt; safeAdd(T a, T b)</code>.",
    code_template: "#include <type_traits>\n// enable_if\n",
    solution: "#include <type_traits>\ntemplate<typename T>\nstd::enable_if_t<std::is_integral_v<T>, T> safeAdd(T a, T b) {\n  return a + b;\n}",
    tests: [{ expected: "enable_if_t", type: "contains" }],
  },
  {
    id: "cpp_189",
    type: "code",
    category: "Templates",
    title: "Template template parameter",
    description: "Template prenant un template.",
    instruction: "Définissez <code>template&lt;template&lt;typename&gt; class C, typename T&gt; void print(C&lt;T&gt; c)</code>.",
    code_template: "template<template<typename> class C, typename T>\nvoid print(C<T> c) {\n  // \n}",
    solution: "#include <vector>\n#include <iostream>\ntemplate<template<typename, typename = std::allocator<int>> class C, typename T>\nvoid print(C<T> c) {\n  for (auto x : c) std::cout << x << ' ';\n}",
    tests: [{ expected: "template<typename", type: "contains" }],
  },
  {
    id: "cpp_190",
    type: "code",
    category: "Concepts",
    title: "Concept avec requires expression",
    description: "Conditions ad hoc.",
    instruction: "Définissez <code>concept Addable</code> qui requiert que <code>a + b</code> soit valide.",
    code_template: "#include <concepts>\ntemplate<typename T>\nconcept Addable = /* */;",
    solution: "#include <concepts>\ntemplate<typename T>\nconcept Addable = requires(T a, T b) {\n  { a + b } -> std::same_as<T>;\n};",
    tests: [{ expected: "requires(T", type: "contains" }, { expected: "a + b", type: "contains" }],
  },
  {
    id: "cpp_191",
    type: "code",
    category: "Templates",
    title: "Constexpr function",
    description: "Évaluable à la compilation.",
    instruction: "Définissez <code>constexpr int fact(int n)</code> récursif qui calcule la factorielle.",
    code_template: "constexpr int fact(int n) {\n  // \n}",
    solution: "constexpr int fact(int n) {\n  return n <= 1 ? 1 : n * fact(n - 1);\n}",
    tests: [{ expected: "constexpr", type: "contains" }],
  },
  {
    id: "cpp_192",
    type: "code",
    category: "Templates",
    title: "if constexpr",
    description: "Branche compile-time.",
    instruction: "Définissez <code>template&lt;typename T&gt; T process(T x)</code> qui retourne <code>x * 2</code> si T est entier, sinon <code>x</code>.",
    code_template: "#include <type_traits>\ntemplate<typename T>\nT process(T x) {\n  // if constexpr\n}",
    solution: "#include <type_traits>\ntemplate<typename T>\nT process(T x) {\n  if constexpr (std::is_integral_v<T>) {\n    return x * 2;\n  } else {\n    return x;\n  }\n}",
    tests: [{ expected: "if constexpr", type: "contains" }],
  },
  {
    id: "cpp_193",
    type: "code",
    category: "Templates",
    title: "Inline variable",
    description: "Variable inline (C++17).",
    instruction: "Définissez <code>inline constexpr int MAX_SIZE = 100;</code> dans un header.",
    code_template: "// inline constexpr\n",
    solution: "inline constexpr int MAX_SIZE = 100;",
    tests: [{ expected: "inline constexpr", type: "contains" }],
  },
  {
    id: "cpp_194",
    type: "code",
    category: "Templates",
    title: "static_assert",
    description: "Vérification à la compilation.",
    instruction: "Avec <code>static_assert(sizeof(int) &gt;= 4, \"int too small\")</code>, garantissez que int fait au moins 4 octets.",
    code_template: "// static_assert\n",
    solution: "static_assert(sizeof(int) >= 4, \"int too small\");",
    tests: [{ expected: "static_assert", type: "contains" }],
  },
  {
    id: "cpp_195",
    type: "code",
    category: "Concepts",
    title: "Concept avec sous-concepts",
    description: "Composition de concepts.",
    instruction: "Définissez <code>concept Sortable</code> qui demande <code>std::movable</code> ET <code>std::totally_ordered</code>.",
    code_template: "#include <concepts>\ntemplate<typename T>\nconcept Sortable = /* */;",
    solution: "#include <concepts>\ntemplate<typename T>\nconcept Sortable = std::movable<T> && std::totally_ordered<T>;",
    tests: [{ expected: "std::movable", type: "contains" }, { expected: "std::totally_ordered", type: "contains" }],
  },
  {
    id: "cpp_196",
    type: "code",
    category: "Templates",
    title: "Variadic via fold expression",
    description: "Somme générique.",
    instruction: "Définissez <code>template&lt;typename... Args&gt; auto sum(Args... args)</code> qui retourne la somme.",
    code_template: "template<typename... Args>\nauto sum(Args... args) {\n  // fold\n}",
    solution: "template<typename... Args>\nauto sum(Args... args) {\n  return (args + ...);\n}",
    tests: [{ expected: "(args + ...)", type: "contains" }],
  },
  {
    id: "cpp_197",
    type: "code",
    category: "Templates",
    title: "Tuple",
    description: "Tuple générique.",
    instruction: "Créez <code>std::tuple&lt;int, std::string, double&gt; t{42, \"hello\", 3.14}</code> et accédez via <code>std::get&lt;1&gt;(t)</code>.",
    code_template: "#include <iostream>\n#include <tuple>\n#include <string>\nint main() {\n  // tuple\n}",
    solution: "#include <iostream>\n#include <tuple>\n#include <string>\nint main() {\n  std::tuple<int, std::string, double> t{42, \"hello\", 3.14};\n  std::cout << std::get<1>(t) << '\\n';\n}",
    tests: [{ expected: "std::tuple", type: "contains" }, { expected: "std::get<", type: "contains" }],
  },
  {
    id: "cpp_198",
    type: "code",
    category: "Templates",
    title: "Structured bindings",
    description: "Destructurer un tuple/pair.",
    instruction: "Avec <code>auto [a, b] = std::make_pair(1, 2.5)</code>, déstructurez.",
    code_template: "#include <utility>\nint main() {\n  // structured bindings\n}",
    solution: "#include <utility>\n#include <iostream>\nint main() {\n  auto [a, b] = std::make_pair(1, 2.5);\n  std::cout << a << '/' << b << '\\n';\n}",
    tests: [{ expected: "auto [", type: "contains" }],
  },
  {
    id: "cpp_199",
    type: "code",
    category: "Templates",
    title: "std::optional",
    description: "Valeur potentiellement absente.",
    instruction: "Définissez <code>std::optional&lt;int&gt; maybeGet(bool ok)</code> qui retourne 42 si ok, sinon nullopt.",
    code_template: "#include <optional>\nstd::optional<int> maybeGet(bool ok) {\n  // \n}",
    solution: "#include <optional>\nstd::optional<int> maybeGet(bool ok) {\n  if (ok) return 42;\n  return std::nullopt;\n}",
    tests: [{ expected: "std::optional", type: "contains" }, { expected: "std::nullopt", type: "contains" }],
  },
  {
    id: "cpp_200",
    type: "code",
    category: "Templates",
    title: "std::variant",
    description: "Sum type type-safe.",
    instruction: "Créez <code>std::variant&lt;int, std::string&gt; v</code> et utilisez <code>std::holds_alternative</code> pour tester le type courant.",
    code_template: "#include <variant>\n#include <string>\nint main() {\n  // variant\n}",
    solution: "#include <variant>\n#include <string>\n#include <iostream>\nint main() {\n  std::variant<int, std::string> v = 42;\n  std::cout << std::holds_alternative<int>(v) << '\\n';\n}",
    tests: [{ expected: "std::variant", type: "contains" }, { expected: "holds_alternative", type: "contains" }],
  },
];

addExercises("cpp", exercises);
