import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/**
 * C++ — Part 10 : threading, lambdas avancées, modern C++ features.
 */
const exercises: Exercise[] = [
  {
    id: "cpp_201",
    type: "code",
    category: "Threading",
    title: "std::thread basique",
    description: "Lancer un thread.",
    instruction: "Lancez un <code>std::thread</code> qui affiche 'hello'. Joinez.",
    code_template: "#include <thread>\n#include <iostream>\nint main() {\n  // thread\n}",
    solution: "#include <thread>\n#include <iostream>\nint main() {\n  std::thread t([]() { std::cout << \"hello\\n\"; });\n  t.join();\n}",
    tests: [{ expected: "std::thread", type: "contains" }, { expected: ".join()", type: "contains" }],
  },
  {
    id: "cpp_202",
    type: "code",
    category: "Threading",
    title: "Mutex + lock",
    description: "Protéger une section critique.",
    instruction: "Utilisez <code>std::mutex</code> + <code>std::lock_guard</code> pour protéger un counter incrémenté par 2 threads.",
    code_template: "#include <thread>\n#include <mutex>\nstd::mutex m;\nint counter = 0;\nvoid inc() {\n  // \n}",
    solution: "#include <thread>\n#include <mutex>\nstd::mutex m;\nint counter = 0;\nvoid inc() {\n  std::lock_guard<std::mutex> lock(m);\n  counter++;\n}",
    tests: [{ expected: "lock_guard", type: "contains" }],
  },
  {
    id: "cpp_203",
    type: "code",
    category: "Threading",
    title: "std::atomic",
    description: "Opérations atomiques sans mutex.",
    instruction: "Utilisez <code>std::atomic&lt;int&gt; counter</code>, incrémentez avec <code>counter++</code>.",
    code_template: "#include <atomic>\nstd::atomic<int> counter{0};\nvoid inc() {\n  // \n}",
    solution: "#include <atomic>\nstd::atomic<int> counter{0};\nvoid inc() {\n  counter++;\n}",
    tests: [{ expected: "std::atomic", type: "contains" }],
  },
  {
    id: "cpp_204",
    type: "code",
    category: "Threading",
    title: "std::async + future",
    description: "Tâche asynchrone.",
    instruction: "Lancez <code>std::async</code> qui retourne 42, await avec <code>.get()</code>.",
    code_template: "#include <future>\n#include <iostream>\nint main() {\n  // async + get\n}",
    solution: "#include <future>\n#include <iostream>\nint main() {\n  auto f = std::async(std::launch::async, []() { return 42; });\n  std::cout << f.get() << '\\n';\n}",
    tests: [{ expected: "std::async", type: "contains" }, { expected: ".get()", type: "contains" }],
  },
  {
    id: "cpp_205",
    type: "code",
    category: "Threading",
    title: "std::condition_variable",
    description: "Synchronisation.",
    instruction: "Utilisez une <code>condition_variable</code> + mutex pour wait/notify.",
    code_template: "#include <condition_variable>\n#include <mutex>\nstd::mutex m;\nstd::condition_variable cv;\nbool ready = false;\nvoid wait_for_signal() {\n  // wait\n}",
    solution: "#include <condition_variable>\n#include <mutex>\nstd::mutex m;\nstd::condition_variable cv;\nbool ready = false;\nvoid wait_for_signal() {\n  std::unique_lock<std::mutex> lock(m);\n  cv.wait(lock, []{ return ready; });\n}",
    tests: [{ expected: "condition_variable", type: "contains" }, { expected: "cv.wait", type: "contains" }],
  },
  {
    id: "cpp_206",
    type: "code",
    category: "Threading",
    title: "std::jthread (C++20)",
    description: "Thread auto-joinant.",
    instruction: "Lancez <code>std::jthread</code> qui se join automatiquement à la fin du scope.",
    code_template: "#include <thread>\n#include <iostream>\nint main() {\n  // jthread\n}",
    solution: "#include <thread>\n#include <iostream>\nint main() {\n  std::jthread t([]() { std::cout << \"jthread\\n\"; });\n  // auto-join\n}",
    tests: [{ expected: "std::jthread", type: "contains" }],
  },
  {
    id: "cpp_207",
    type: "code",
    category: "Lambdas",
    title: "Lambda capture par valeur",
    description: "[x] capture par copie.",
    instruction: "Créez une lambda qui capture <code>x = 10</code> par valeur et retourne <code>x * 2</code>.",
    code_template: "int main() {\n  int x = 10;\n  auto f = /* */;\n}",
    solution: "#include <iostream>\nint main() {\n  int x = 10;\n  auto f = [x]() { return x * 2; };\n  std::cout << f() << '\\n';\n}",
    tests: [{ expected: "[x]", type: "contains" }],
  },
  {
    id: "cpp_208",
    type: "code",
    category: "Lambdas",
    title: "Lambda capture par référence",
    description: "[&x] capture by ref.",
    instruction: "Capturez <code>counter</code> par référence et incrémentez-le dans la lambda.",
    code_template: "int main() {\n  int counter = 0;\n  auto inc = /* */;\n}",
    solution: "#include <iostream>\nint main() {\n  int counter = 0;\n  auto inc = [&counter]() { counter++; };\n  inc(); inc(); inc();\n  std::cout << counter << '\\n';\n}",
    tests: [{ expected: "[&counter]", type: "contains" }],
  },
  {
    id: "cpp_209",
    type: "code",
    category: "Lambdas",
    title: "Lambda capture mixed",
    description: "[=, &y] tout par valeur sauf y.",
    instruction: "Créez une lambda <code>[=, &amp;y]</code> qui capture tout par valeur, sauf y par référence.",
    code_template: "int main() {\n  int x = 1;\n  int y = 2;\n  auto f = /* */;\n}",
    solution: "int main() {\n  int x = 1;\n  int y = 2;\n  auto f = [=, &y]() { y = x; };\n  f();\n}",
    tests: [{ expected: "[=, &y]", type: "contains" }],
  },
  {
    id: "cpp_210",
    type: "code",
    category: "Lambdas",
    title: "Lambda mutable",
    description: "Modifier les variables capturées par valeur.",
    instruction: "Avec une lambda <code>[count = 0]() mutable { count++; }</code>, démontrez un état interne.",
    code_template: "auto counter = /* */;\n",
    solution: "#include <iostream>\nint main() {\n  auto counter = [count = 0]() mutable { return ++count; };\n  std::cout << counter() << '\\n';\n  std::cout << counter() << '\\n';\n}",
    tests: [{ expected: "mutable", type: "contains" }, { expected: "count = 0", type: "contains" }],
  },
  {
    id: "cpp_211",
    type: "code",
    category: "Lambdas",
    title: "Generic lambda (C++14)",
    description: "auto en paramètre.",
    instruction: "Définissez <code>auto add = [](auto a, auto b) { return a + b; };</code>.",
    code_template: "// generic lambda\n",
    solution: "#include <iostream>\nint main() {\n  auto add = [](auto a, auto b) { return a + b; };\n  std::cout << add(1, 2) << '\\n';\n  std::cout << add(1.5, 2.5) << '\\n';\n}",
    tests: [{ expected: "(auto a, auto b)", type: "contains" }],
  },
  {
    id: "cpp_212",
    type: "code",
    category: "Lambdas",
    title: "Lambda avec init capture",
    description: "Init dans la capture (C++14).",
    instruction: "Créez une lambda qui capture <code>[ptr = std::make_unique&lt;int&gt;(42)]</code>.",
    code_template: "#include <memory>\n// lambda avec init capture\n",
    solution: "#include <memory>\n#include <iostream>\nint main() {\n  auto f = [ptr = std::make_unique<int>(42)]() { return *ptr; };\n  std::cout << f() << '\\n';\n}",
    tests: [{ expected: "[ptr = ", type: "contains" }],
  },
  {
    id: "cpp_213",
    type: "code",
    category: "Modern C++",
    title: "std::string_view",
    description: "Vue non-propriétaire sur une string.",
    instruction: "Utilisez <code>std::string_view</code> au lieu de <code>const string&amp;</code> pour passer une string en argument sans copie.",
    code_template: "#include <string_view>\nvoid print(std::string_view sv) {\n  // \n}",
    solution: "#include <string_view>\n#include <iostream>\nvoid print(std::string_view sv) {\n  std::cout << sv << '\\n';\n}",
    tests: [{ expected: "string_view", type: "contains" }],
  },
  {
    id: "cpp_214",
    type: "code",
    category: "Modern C++",
    title: "std::span (C++20)",
    description: "Vue non-propriétaire sur un range.",
    instruction: "Utilisez <code>std::span&lt;int&gt;</code> pour passer un range sans copie.",
    code_template: "#include <span>\nint sum(std::span<int> s) {\n  // \n}",
    solution: "#include <span>\nint sum(std::span<int> s) {\n  int total = 0;\n  for (int x : s) total += x;\n  return total;\n}",
    tests: [{ expected: "std::span", type: "contains" }],
  },
  {
    id: "cpp_215",
    type: "code",
    category: "Modern C++",
    title: "Designated initializers (C++20)",
    description: "Init par nom.",
    instruction: "Initialisez <code>struct P { int x, y; }</code> avec <code>P{.x = 5, .y = 10}</code>.",
    code_template: "struct P { int x, y; };\nint main() {\n  // designated\n}",
    solution: "struct P { int x, y; };\nint main() {\n  P p{.x = 5, .y = 10};\n  return 0;\n}",
    tests: [{ expected: ".x =", type: "contains" }, { expected: ".y =", type: "contains" }],
  },
  {
    id: "cpp_216",
    type: "code",
    category: "Modern C++",
    title: "std::ranges (C++20)",
    description: "Pipeline LINQ-like.",
    instruction: "Utilisez <code>std::ranges::sort</code> sur un vector.",
    code_template: "#include <vector>\n#include <ranges>\n#include <algorithm>\nint main() {\n  std::vector<int> v = {3, 1, 2};\n  // ranges::sort\n}",
    solution: "#include <vector>\n#include <algorithm>\nint main() {\n  std::vector<int> v = {3, 1, 2};\n  std::ranges::sort(v);\n}",
    tests: [{ expected: "ranges::sort", type: "contains" }],
  },
  {
    id: "cpp_217",
    type: "code",
    category: "Modern C++",
    title: "ranges views",
    description: "Lazy pipeline.",
    instruction: "Avec <code>std::views::filter + transform</code>, gardez les pairs et doublez-les.",
    code_template: "#include <vector>\n#include <ranges>\nint main() {\n  std::vector<int> v = {1, 2, 3, 4, 5};\n  // views\n}",
    solution: "#include <vector>\n#include <ranges>\n#include <iostream>\nint main() {\n  std::vector<int> v = {1, 2, 3, 4, 5};\n  auto r = v | std::views::filter([](int x) { return x % 2 == 0; })\n             | std::views::transform([](int x) { return x * 2; });\n  for (int x : r) std::cout << x << ' ';\n}",
    tests: [{ expected: "views::filter", type: "contains" }, { expected: "views::transform", type: "contains" }],
  },
  {
    id: "cpp_218",
    type: "code",
    category: "Modern C++",
    title: "std::format (C++20)",
    description: "fmt-like formatting.",
    instruction: "Avec <code>std::format(\"{} + {} = {}\", 1, 2, 3)</code>, formatez une chaîne.",
    code_template: "#include <format>\nint main() {\n  // \n}",
    solution: "#include <format>\n#include <iostream>\nint main() {\n  std::cout << std::format(\"{} + {} = {}\", 1, 2, 3) << '\\n';\n}",
    tests: [{ expected: "std::format", type: "contains" }],
  },
  {
    id: "cpp_219",
    type: "code",
    category: "Modern C++",
    title: "std::chrono",
    description: "Temps moderne.",
    instruction: "Mesurez la durée d'un calcul avec <code>std::chrono::high_resolution_clock</code>.",
    code_template: "#include <chrono>\nint main() {\n  // chrono\n}",
    solution: "#include <chrono>\n#include <iostream>\nint main() {\n  auto start = std::chrono::high_resolution_clock::now();\n  // calcul\n  auto end = std::chrono::high_resolution_clock::now();\n  auto dur = std::chrono::duration_cast<std::chrono::microseconds>(end - start);\n  std::cout << dur.count() << '\\n';\n}",
    tests: [{ expected: "high_resolution_clock", type: "contains" }],
  },
  {
    id: "cpp_220",
    type: "code",
    category: "Modern C++",
    title: "Strong typing avec enum class",
    description: "Pas de conversion implicite vers int.",
    instruction: "Définissez <code>enum class Color { Red, Green, Blue }</code> et utilisez-la.",
    code_template: "// enum class\n",
    solution: "enum class Color { Red, Green, Blue };\nint main() {\n  Color c = Color::Red;\n  return 0;\n}",
    tests: [{ expected: "enum class", type: "contains" }],
  },
  {
    id: "cpp_221",
    type: "code",
    category: "Modern C++",
    title: "nullptr vs NULL",
    description: "Pointeur null typé.",
    instruction: "Utilisez <code>nullptr</code> au lieu de <code>NULL</code> pour un pointeur null.",
    code_template: "void f(int* p) {}\nint main() {\n  // nullptr\n}",
    solution: "void f(int* p) {}\nint main() {\n  f(nullptr);\n}",
    tests: [{ expected: "nullptr", type: "contains" }],
  },
  {
    id: "cpp_222",
    type: "code",
    category: "Modern C++",
    title: "Range-based for + structured bindings",
    description: "Itérer sur une map.",
    instruction: "Avec <code>for (auto& [key, value] : m)</code>, itérez sur un map.",
    code_template: "#include <map>\n#include <iostream>\nint main() {\n  std::map<std::string, int> m = {{\"a\", 1}, {\"b\", 2}};\n  // structured bindings\n}",
    solution: "#include <map>\n#include <iostream>\n#include <string>\nint main() {\n  std::map<std::string, int> m = {{\"a\", 1}, {\"b\", 2}};\n  for (const auto& [key, value] : m) std::cout << key << '=' << value << '\\n';\n}",
    tests: [{ expected: "[key, value]", type: "contains" }],
  },
  {
    id: "cpp_223",
    type: "code",
    category: "Modern C++",
    title: "constexpr if",
    description: "Branche compile-time.",
    instruction: "Utilisez <code>if constexpr (std::is_integral_v&lt;T&gt;)</code> dans une fonction template.",
    code_template: "#include <type_traits>\ntemplate<typename T>\nT process(T x) {\n  // if constexpr\n}",
    solution: "#include <type_traits>\ntemplate<typename T>\nT process(T x) {\n  if constexpr (std::is_integral_v<T>) return x * 2;\n  else return x;\n}",
    tests: [{ expected: "if constexpr", type: "contains" }],
  },
  {
    id: "cpp_224",
    type: "code",
    category: "Modern C++",
    title: "spaceship operator (C++20)",
    description: "<=> pour comparison.",
    instruction: "Définissez <code>auto operator&lt;=&gt;(const P&amp;) const = default</code> dans une struct P.",
    code_template: "#include <compare>\nstruct P {\n  int x, y;\n  // <=>\n};",
    solution: "#include <compare>\nstruct P {\n  int x, y;\n  auto operator<=>(const P&) const = default;\n};",
    tests: [{ expected: "operator<=>", type: "contains" }, { expected: "= default", type: "contains" }],
  },
  {
    id: "cpp_225",
    type: "code",
    category: "Final",
    title: "Mission C++ moderne",
    description: "Combo final.",
    instruction: "Créez une <code>class Game</code> avec smart pointer, lambda, structured bindings, concept Numeric, et instanciez-la.",
    code_template: "// Mission\n",
    solution: "#include <iostream>\n#include <memory>\n#include <concepts>\ntemplate<typename T> concept Numeric = std::is_arithmetic_v<T>;\nclass Game {\n  std::unique_ptr<int> score = std::make_unique<int>(0);\npublic:\n  template<Numeric T>\n  void addScore(T pts) { *score += static_cast<int>(pts); }\n  int getScore() const { return *score; }\n};\nint main() {\n  Game g;\n  g.addScore(10);\n  std::cout << g.getScore() << '\\n';\n}",
    tests: [{ expected: "unique_ptr", type: "contains" }, { expected: "concept", type: "contains" }, { expected: "Numeric", type: "contains" }],
    hint: "Tu viens de finir 220+ exos C++. Bravo Lyoko-warrior !",
  },
];

addExercises("cpp", exercises);
