import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/**
 * C++ — Part 8 : smart pointers, RAII, move semantics.
 */
const exercises: Exercise[] = [
  {
    id: "cpp_151",
    type: "code",
    category: "Smart Pointers",
    title: "std::unique_ptr",
    description: "Pointeur unique.",
    instruction: "Créez un <code>std::unique_ptr&lt;int&gt;</code> avec <code>std::make_unique&lt;int&gt;(42)</code>, déréférencez et affichez.",
    code_template: "#include <iostream>\n#include <memory>\nint main() {\n  // unique_ptr\n}",
    solution: "#include <iostream>\n#include <memory>\nint main() {\n  auto p = std::make_unique<int>(42);\n  std::cout << *p << '\\n';\n  return 0;\n}",
    tests: [{ expected: "make_unique", type: "contains" }, { expected: "unique_ptr", type: "contains" }],
  },
  {
    id: "cpp_152",
    type: "code",
    category: "Smart Pointers",
    title: "std::shared_ptr",
    description: "Pointeur partagé (refcount).",
    instruction: "Créez <code>std::shared_ptr</code> avec make_shared, affichez <code>use_count()</code>.",
    code_template: "#include <iostream>\n#include <memory>\nint main() {\n  auto p = /* */;\n  // use_count\n}",
    solution: "#include <iostream>\n#include <memory>\nint main() {\n  auto p = std::make_shared<int>(100);\n  std::cout << p.use_count() << '\\n';\n}",
    tests: [{ expected: "make_shared", type: "contains" }, { expected: "use_count", type: "contains" }],
  },
  {
    id: "cpp_153",
    type: "code",
    category: "Smart Pointers",
    title: "std::weak_ptr",
    description: "Référence faible (sans incrémenter le refcount).",
    instruction: "Créez un <code>shared_ptr</code>, un <code>weak_ptr</code> sur lui, et appelez <code>.lock()</code>.",
    code_template: "#include <iostream>\n#include <memory>\nint main() {\n  // shared + weak\n}",
    solution: "#include <iostream>\n#include <memory>\nint main() {\n  auto sp = std::make_shared<int>(42);\n  std::weak_ptr<int> wp = sp;\n  if (auto locked = wp.lock()) std::cout << *locked << '\\n';\n}",
    tests: [{ expected: "weak_ptr", type: "contains" }, { expected: ".lock()", type: "contains" }],
  },
  {
    id: "cpp_154",
    type: "code",
    category: "RAII",
    title: "RAII pour fichier",
    description: "Encapsuler une ressource.",
    instruction: "Définissez <code>class File</code> qui open dans le constructor et close dans le destructor.",
    code_template: "#include <cstdio>\nclass File {\n  // \n};",
    solution: "#include <cstdio>\nclass File {\n  FILE* f;\npublic:\n  File(const char* path) { f = fopen(path, \"r\"); }\n  ~File() { if (f) fclose(f); }\n};",
    tests: [{ expected: "~File()", type: "contains" }, { expected: "fclose", type: "contains" }],
  },
  {
    id: "cpp_155",
    type: "code",
    category: "Move Semantics",
    title: "std::move",
    description: "Transférer la propriété.",
    instruction: "Avec <code>std::move</code>, transférez un <code>std::string s1 = \"hello\"</code> dans s2. Affichez la taille de s1 après (typiquement 0).",
    code_template: "#include <iostream>\n#include <string>\nint main() {\n  std::string s1 = \"hello\";\n  // move\n}",
    solution: "#include <iostream>\n#include <string>\n#include <utility>\nint main() {\n  std::string s1 = \"hello\";\n  std::string s2 = std::move(s1);\n  std::cout << s1.size() << '\\n';\n  std::cout << s2 << '\\n';\n}",
    tests: [{ expected: "std::move", type: "contains" }],
  },
  {
    id: "cpp_156",
    type: "code",
    category: "Move Semantics",
    title: "Move constructor",
    description: "Constructor par move.",
    instruction: "Définissez <code>class Wrapper</code> avec un move constructor qui transfère un buffer <code>char*</code>.",
    code_template: "#include <utility>\nclass Wrapper {\n  char* data;\npublic:\n  Wrapper(char* d) : data(d) {}\n  // move constructor\n};",
    solution: "#include <utility>\nclass Wrapper {\n  char* data;\npublic:\n  Wrapper(char* d) : data(d) {}\n  Wrapper(Wrapper&& other) noexcept : data(other.data) {\n    other.data = nullptr;\n  }\n};",
    tests: [{ expected: "Wrapper&& other", type: "contains" }, { expected: "noexcept", type: "contains" }],
  },
  {
    id: "cpp_157",
    type: "code",
    category: "Move Semantics",
    title: "Rule of Five",
    description: "5 special members à définir ensemble.",
    instruction: "Listez les 5 special members par commentaire dans <code>class R5</code> : destructor, copy constructor, copy assign, move constructor, move assign.",
    code_template: "class R5 {\n  // 5 special members\n};",
    solution: "class R5 {\npublic:\n  ~R5() {} // destructor\n  R5(const R5&) {} // copy constructor\n  R5& operator=(const R5&) { return *this; } // copy assign\n  R5(R5&&) noexcept {} // move constructor\n  R5& operator=(R5&&) noexcept { return *this; } // move assign\n};",
    tests: [{ expected: "~R5", type: "contains" }, { expected: "R5(const R5&)", type: "contains" }, { expected: "R5(R5&&)", type: "contains" }],
  },
  {
    id: "cpp_158",
    type: "code",
    category: "Smart Pointers",
    title: "Custom deleter",
    description: "Smart pointer avec finaliseur custom.",
    instruction: "Créez un <code>unique_ptr&lt;FILE, decltype(&amp;fclose)&gt;</code> qui ferme automatiquement le fichier.",
    code_template: "#include <cstdio>\n#include <memory>\nint main() {\n  // unique_ptr custom deleter\n}",
    solution: "#include <cstdio>\n#include <memory>\nint main() {\n  std::unique_ptr<FILE, decltype(&fclose)> fp(fopen(\"test.txt\", \"w\"), &fclose);\n}",
    tests: [{ expected: "decltype(&fclose)", type: "contains" }],
  },
  {
    id: "cpp_159",
    type: "code",
    category: "Smart Pointers",
    title: "shared_ptr cycle problem",
    description: "Démonstration cycle de référence.",
    instruction: "Définissez <code>struct Node</code> avec <code>weak_ptr&lt;Node&gt; parent</code> et <code>shared_ptr&lt;Node&gt; child</code> — bonne approche évitant le cycle.",
    code_template: "#include <memory>\nstruct Node {\n  // \n};",
    solution: "#include <memory>\nstruct Node {\n  std::weak_ptr<Node> parent;\n  std::shared_ptr<Node> child;\n};",
    tests: [{ expected: "weak_ptr<Node> parent", type: "contains" }, { expected: "shared_ptr<Node> child", type: "contains" }],
  },
  {
    id: "cpp_160",
    type: "code",
    category: "RAII",
    title: "Lock guard",
    description: "RAII pour mutex.",
    instruction: "Utilisez <code>std::lock_guard&lt;std::mutex&gt;</code> pour verrouiller un mutex.",
    code_template: "#include <mutex>\nstd::mutex m;\nvoid f() {\n  // lock_guard\n}",
    solution: "#include <mutex>\nstd::mutex m;\nvoid f() {\n  std::lock_guard<std::mutex> lock(m);\n  // section critique\n}",
    tests: [{ expected: "lock_guard", type: "contains" }],
  },
  {
    id: "cpp_161",
    type: "code",
    category: "Move Semantics",
    title: "Perfect forwarding",
    description: "Template universal reference.",
    instruction: "Définissez <code>template&lt;typename T&gt; void wrapper(T&amp;&amp; arg) { real(std::forward&lt;T&gt;(arg)); }</code>.",
    code_template: "#include <utility>\ntemplate<typename T>\nvoid wrapper(T&& arg) {\n  // forward\n}",
    solution: "#include <utility>\ntemplate<typename T>\nvoid real(T&& arg) {}\ntemplate<typename T>\nvoid wrapper(T&& arg) {\n  real(std::forward<T>(arg));\n}",
    tests: [{ expected: "std::forward", type: "contains" }, { expected: "T&&", type: "contains" }],
  },
  {
    id: "cpp_162",
    type: "code",
    category: "RAII",
    title: "Scoped resource",
    description: "Custom RAII guard.",
    instruction: "Définissez <code>class ScopedTimer</code> qui log au constructor 'start' et au destructor 'stop'.",
    code_template: "#include <iostream>\nclass ScopedTimer {\n  // \n};",
    solution: "#include <iostream>\nclass ScopedTimer {\npublic:\n  ScopedTimer() { std::cout << \"start\\n\"; }\n  ~ScopedTimer() { std::cout << \"stop\\n\"; }\n};",
    tests: [{ expected: "ScopedTimer()", type: "contains" }, { expected: "~ScopedTimer()", type: "contains" }],
  },
  {
    id: "cpp_163",
    type: "code",
    category: "Smart Pointers",
    title: "unique_ptr release",
    description: "Récupérer la propriété brute.",
    instruction: "Avec <code>p.release()</code>, récupérez le pointeur brut pour transmission à une API C.",
    code_template: "#include <memory>\nint main() {\n  auto p = std::make_unique<int>(42);\n  // release\n  int* raw = nullptr;\n  delete raw;\n}",
    solution: "#include <memory>\nint main() {\n  auto p = std::make_unique<int>(42);\n  int* raw = p.release();\n  delete raw;\n}",
    tests: [{ expected: "p.release()", type: "contains" }],
  },
  {
    id: "cpp_164",
    type: "code",
    category: "Smart Pointers",
    title: "unique_ptr reset",
    description: "Remplacer le contenu.",
    instruction: "Reset un <code>unique_ptr</code> avec une nouvelle valeur via <code>p.reset(new int(99))</code>.",
    code_template: "#include <memory>\nint main() {\n  auto p = std::make_unique<int>(1);\n  // reset\n}",
    solution: "#include <memory>\n#include <iostream>\nint main() {\n  auto p = std::make_unique<int>(1);\n  p.reset(new int(99));\n  std::cout << *p << '\\n';\n}",
    tests: [{ expected: ".reset(", type: "contains" }],
  },
  {
    id: "cpp_165",
    type: "code",
    category: "Move Semantics",
    title: "Move-only type",
    description: "Empêcher la copie.",
    instruction: "Définissez <code>class FileHandle</code> non copiable (= delete) mais movable.",
    code_template: "class FileHandle {\n  // \n};",
    solution: "class FileHandle {\npublic:\n  FileHandle() = default;\n  FileHandle(const FileHandle&) = delete;\n  FileHandle& operator=(const FileHandle&) = delete;\n  FileHandle(FileHandle&&) = default;\n  FileHandle& operator=(FileHandle&&) = default;\n};",
    tests: [{ expected: "= delete", type: "contains" }, { expected: "= default", type: "contains" }],
  },
  {
    id: "cpp_166",
    type: "code",
    category: "RAII",
    title: "Stream RAII",
    description: "fstream RAII.",
    instruction: "Avec <code>std::ofstream f(\"out.txt\")</code>, écrivez 'hello' — la fermeture se fait au destructeur.",
    code_template: "#include <fstream>\nint main() {\n  // fstream\n}",
    solution: "#include <fstream>\nint main() {\n  std::ofstream f(\"out.txt\");\n  f << \"hello\\n\";\n  // fermeture auto au destructor\n}",
    tests: [{ expected: "std::ofstream", type: "contains" }],
  },
  {
    id: "cpp_167",
    type: "code",
    category: "Smart Pointers",
    title: "make_shared vs make_unique",
    description: "Quand utiliser quoi.",
    instruction: "Créez 2 ressources : une exclusive avec <code>make_unique</code>, une partagée avec <code>make_shared</code>.",
    code_template: "#include <memory>\nint main() {\n  // unique + shared\n}",
    solution: "#include <memory>\nint main() {\n  auto unique = std::make_unique<int>(1);\n  auto shared = std::make_shared<int>(2);\n}",
    tests: [{ expected: "make_unique", type: "contains" }, { expected: "make_shared", type: "contains" }],
  },
  {
    id: "cpp_168",
    type: "code",
    category: "Move Semantics",
    title: "noexcept",
    description: "Garantie pas d'exception.",
    instruction: "Marquez le move constructor de <code>class S</code> avec <code>noexcept</code> pour permettre l'optimisation par vector.",
    code_template: "class S {\n  // move ctor noexcept\n};",
    solution: "class S {\npublic:\n  S(S&&) noexcept = default;\n};",
    tests: [{ expected: "noexcept", type: "contains" }],
  },
  {
    id: "cpp_169",
    type: "code",
    category: "Smart Pointers",
    title: "Polymorphism + unique_ptr",
    description: "Pointeur vers base.",
    instruction: "Définissez <code>struct Animal</code> avec méthode virtuelle, <code>struct Dog : Animal</code>, et un <code>unique_ptr&lt;Animal&gt;</code> qui pointe sur un Dog.",
    code_template: "#include <memory>\n#include <iostream>\nstruct Animal { virtual ~Animal() = default; virtual void speak() = 0; };\nstruct Dog : Animal { void speak() override { std::cout << \"wouf\\n\"; } };\nint main() {\n  // unique_ptr<Animal>\n}",
    solution: "#include <memory>\n#include <iostream>\nstruct Animal { virtual ~Animal() = default; virtual void speak() = 0; };\nstruct Dog : Animal { void speak() override { std::cout << \"wouf\\n\"; } };\nint main() {\n  std::unique_ptr<Animal> a = std::make_unique<Dog>();\n  a->speak();\n}",
    tests: [{ expected: "unique_ptr<Animal>", type: "contains" }, { expected: "make_unique<Dog>", type: "contains" }],
  },
  {
    id: "cpp_170",
    type: "code",
    category: "RAII",
    title: "Initializer list",
    description: "Initialiser dans le constructor.",
    instruction: "Définissez <code>class P</code> avec un membre <code>const int x</code> initialisé via member initializer list.",
    code_template: "class P {\n  const int x;\npublic:\n  P(int v) /* */;\n};",
    solution: "class P {\n  const int x;\npublic:\n  P(int v) : x(v) {}\n};",
    tests: [{ expected: ": x(v)", type: "contains" }],
  },
  {
    id: "cpp_171",
    type: "code",
    category: "Move Semantics",
    title: "Return by value (NRVO/copy elision)",
    description: "Le compilateur peut éliser la copie.",
    instruction: "Une fonction qui retourne <code>std::vector&lt;int&gt;</code> par valeur — pas besoin de move.",
    code_template: "#include <vector>\nstd::vector<int> make() {\n  // \n}",
    solution: "#include <vector>\nstd::vector<int> make() {\n  std::vector<int> v = {1, 2, 3};\n  return v;\n}",
    tests: [{ expected: "return v", type: "contains" }],
  },
  {
    id: "cpp_172",
    type: "code",
    category: "Smart Pointers",
    title: "shared_ptr enable_shared_from_this",
    description: "Obtenir shared_ptr depuis this.",
    instruction: "Définissez <code>class C : public std::enable_shared_from_this&lt;C&gt;</code> avec méthode <code>get_shared()</code> qui retourne <code>shared_from_this()</code>.",
    code_template: "#include <memory>\nclass C : public std::enable_shared_from_this<C> {\n  // get_shared\n};",
    solution: "#include <memory>\nclass C : public std::enable_shared_from_this<C> {\npublic:\n  std::shared_ptr<C> get_shared() { return shared_from_this(); }\n};",
    tests: [{ expected: "enable_shared_from_this", type: "contains" }, { expected: "shared_from_this", type: "contains" }],
  },
  {
    id: "cpp_173",
    type: "code",
    category: "RAII",
    title: "std::scoped_lock (multi-mutex)",
    description: "Lock atomique de plusieurs mutex.",
    instruction: "Avec <code>std::scoped_lock</code>, verrouillez 2 mutex en une seule ligne (évite deadlock).",
    code_template: "#include <mutex>\nstd::mutex a, b;\nvoid f() {\n  // scoped_lock\n}",
    solution: "#include <mutex>\nstd::mutex a, b;\nvoid f() {\n  std::scoped_lock lock(a, b);\n}",
    tests: [{ expected: "scoped_lock", type: "contains" }],
  },
  {
    id: "cpp_174",
    type: "code",
    category: "Move Semantics",
    title: "vector emplace_back",
    description: "Construire en place.",
    instruction: "Avec <code>v.emplace_back(args)</code>, construisez un objet directement dans le vector (sans copier).",
    code_template: "#include <vector>\n#include <string>\nint main() {\n  std::vector<std::string> v;\n  // emplace_back\n}",
    solution: "#include <vector>\n#include <string>\nint main() {\n  std::vector<std::string> v;\n  v.emplace_back(\"hello\");\n}",
    tests: [{ expected: "emplace_back", type: "contains" }],
  },
  {
    id: "cpp_175",
    type: "code",
    category: "Smart Pointers",
    title: "Smart pointer + container",
    description: "Vector de unique_ptr.",
    instruction: "Créez un <code>std::vector&lt;std::unique_ptr&lt;int&gt;&gt;</code>, push 3 valeurs, affichez la taille.",
    code_template: "#include <vector>\n#include <memory>\n#include <iostream>\nint main() {\n  // \n}",
    solution: "#include <vector>\n#include <memory>\n#include <iostream>\nint main() {\n  std::vector<std::unique_ptr<int>> v;\n  v.push_back(std::make_unique<int>(1));\n  v.push_back(std::make_unique<int>(2));\n  v.push_back(std::make_unique<int>(3));\n  std::cout << v.size() << '\\n';\n}",
    tests: [{ expected: "vector<std::unique_ptr", type: "contains" }],
  },
];

addExercises("cpp", exercises);
