import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/**
 * C++ — Part 7 : STL containers + algorithms + iterators.
 */
const exercises: Exercise[] = [
  {
    id: "cpp_126",
    type: "code",
    category: "STL Containers",
    title: "std::vector pushback",
    description: "Vector dynamique.",
    instruction: "Créez un <code>std::vector&lt;int&gt;</code>, push_back 1, 2, 3, et affichez le contenu séparé par espace.",
    code_template: "#include <iostream>\n#include <vector>\nint main() {\n  // vector\n  return 0;\n}",
    solution: "#include <iostream>\n#include <vector>\nint main() {\n  std::vector<int> v;\n  v.push_back(1); v.push_back(2); v.push_back(3);\n  for (int x : v) std::cout << x << ' ';\n  std::cout << '\\n';\n  return 0;\n}",
    tests: [{ expected: "std::vector", type: "contains" }, { expected: "push_back", type: "contains" }],
  },
  {
    id: "cpp_127",
    type: "code",
    category: "STL Containers",
    title: "vector init list",
    description: "Initializer list.",
    instruction: "Initialisez <code>std::vector&lt;int&gt;</code> avec <code>{10, 20, 30}</code> et affichez sa taille.",
    code_template: "#include <iostream>\n#include <vector>\nint main() {\n  // \n}",
    solution: "#include <iostream>\n#include <vector>\nint main() {\n  std::vector<int> v = {10, 20, 30};\n  std::cout << v.size() << '\\n';\n  return 0;\n}",
    tests: [{ expected: "{10, 20, 30}", type: "contains" }, { expected: ".size()", type: "contains" }],
  },
  {
    id: "cpp_128",
    type: "code",
    category: "STL Containers",
    title: "std::map",
    description: "Dictionnaire trié.",
    instruction: "Créez <code>std::map&lt;std::string, int&gt;</code>, insérez (\"a\",1), (\"b\",2), affichez la valeur de 'a'.",
    code_template: "#include <iostream>\n#include <map>\n#include <string>\nint main() {\n  // \n}",
    solution: "#include <iostream>\n#include <map>\n#include <string>\nint main() {\n  std::map<std::string, int> m = {{\"a\",1}, {\"b\",2}};\n  std::cout << m[\"a\"] << '\\n';\n  return 0;\n}",
    tests: [{ expected: "std::map", type: "contains" }],
  },
  {
    id: "cpp_129",
    type: "code",
    category: "STL Containers",
    title: "std::unordered_map",
    description: "Hash map (O(1)).",
    instruction: "Créez un <code>unordered_map&lt;int, std::string&gt;</code>, insérez (1, \"un\"), affichez.",
    code_template: "#include <iostream>\n#include <unordered_map>\n#include <string>\nint main() {\n  // \n}",
    solution: "#include <iostream>\n#include <unordered_map>\n#include <string>\nint main() {\n  std::unordered_map<int, std::string> m;\n  m[1] = \"un\";\n  std::cout << m[1] << '\\n';\n  return 0;\n}",
    tests: [{ expected: "unordered_map", type: "contains" }],
  },
  {
    id: "cpp_130",
    type: "code",
    category: "STL Containers",
    title: "std::set",
    description: "Ensemble unique trié.",
    instruction: "Insérez 3, 1, 4, 1, 5 dans un <code>std::set&lt;int&gt;</code>, affichez la taille.",
    code_template: "#include <iostream>\n#include <set>\nint main() {\n  // \n}",
    solution: "#include <iostream>\n#include <set>\nint main() {\n  std::set<int> s = {3, 1, 4, 1, 5};\n  std::cout << s.size() << '\\n';\n  return 0;\n}",
    tests: [{ expected: "std::set", type: "contains" }],
  },
  {
    id: "cpp_131",
    type: "code",
    category: "STL Containers",
    title: "std::list (doublement chaînée)",
    description: "Insertion en tête O(1).",
    instruction: "Créez un <code>std::list&lt;int&gt;</code>, push_front 1, 2, 3, affichez sa taille.",
    code_template: "#include <iostream>\n#include <list>\nint main() {\n  // \n}",
    solution: "#include <iostream>\n#include <list>\nint main() {\n  std::list<int> l;\n  l.push_front(1); l.push_front(2); l.push_front(3);\n  std::cout << l.size() << '\\n';\n  return 0;\n}",
    tests: [{ expected: "std::list", type: "contains" }, { expected: "push_front", type: "contains" }],
  },
  {
    id: "cpp_132",
    type: "code",
    category: "STL Containers",
    title: "std::deque",
    description: "Double-ended queue.",
    instruction: "Créez un <code>std::deque&lt;int&gt;</code>, push_back 1, push_front 0, affichez le premier élément.",
    code_template: "#include <iostream>\n#include <deque>\nint main() {\n  // \n}",
    solution: "#include <iostream>\n#include <deque>\nint main() {\n  std::deque<int> d;\n  d.push_back(1);\n  d.push_front(0);\n  std::cout << d.front() << '\\n';\n  return 0;\n}",
    tests: [{ expected: "std::deque", type: "contains" }],
  },
  {
    id: "cpp_133",
    type: "code",
    category: "STL Containers",
    title: "std::stack",
    description: "LIFO.",
    instruction: "Push 1, 2, 3 dans un stack puis pop deux fois. Affichez le top final.",
    code_template: "#include <iostream>\n#include <stack>\nint main() {\n  // \n}",
    solution: "#include <iostream>\n#include <stack>\nint main() {\n  std::stack<int> s;\n  s.push(1); s.push(2); s.push(3);\n  s.pop(); s.pop();\n  std::cout << s.top() << '\\n';\n  return 0;\n}",
    tests: [{ expected: "std::stack", type: "contains" }, { expected: ".top()", type: "contains" }],
  },
  {
    id: "cpp_134",
    type: "code",
    category: "STL Containers",
    title: "std::queue",
    description: "FIFO.",
    instruction: "Push 10, 20, 30 dans une queue puis pop. Affichez le front.",
    code_template: "#include <iostream>\n#include <queue>\nint main() {\n  // \n}",
    solution: "#include <iostream>\n#include <queue>\nint main() {\n  std::queue<int> q;\n  q.push(10); q.push(20); q.push(30);\n  q.pop();\n  std::cout << q.front() << '\\n';\n  return 0;\n}",
    tests: [{ expected: "std::queue", type: "contains" }, { expected: ".front()", type: "contains" }],
  },
  {
    id: "cpp_135",
    type: "code",
    category: "STL Containers",
    title: "std::priority_queue",
    description: "Heap max.",
    instruction: "Push 3, 1, 4, 1, 5 dans une <code>priority_queue</code>, top doit être 5.",
    code_template: "#include <iostream>\n#include <queue>\nint main() {\n  // \n}",
    solution: "#include <iostream>\n#include <queue>\nint main() {\n  std::priority_queue<int> pq;\n  for (int x : {3, 1, 4, 1, 5}) pq.push(x);\n  std::cout << pq.top() << '\\n';\n  return 0;\n}",
    tests: [{ expected: "priority_queue", type: "contains" }],
  },
  {
    id: "cpp_136",
    type: "code",
    category: "STL Algorithms",
    title: "std::sort",
    description: "Tri.",
    instruction: "Triez <code>{5, 2, 8, 1, 4}</code> avec <code>std::sort</code> et affichez le résultat.",
    code_template: "#include <iostream>\n#include <vector>\n#include <algorithm>\nint main() {\n  std::vector<int> v = {5, 2, 8, 1, 4};\n  // sort\n  for (int x : v) std::cout << x << ' ';\n  std::cout << '\\n';\n}",
    solution: "#include <iostream>\n#include <vector>\n#include <algorithm>\nint main() {\n  std::vector<int> v = {5, 2, 8, 1, 4};\n  std::sort(v.begin(), v.end());\n  for (int x : v) std::cout << x << ' ';\n  std::cout << '\\n';\n}",
    tests: [{ expected: "std::sort", type: "contains" }, { expected: ".begin()", type: "contains" }],
  },
  {
    id: "cpp_137",
    type: "code",
    category: "STL Algorithms",
    title: "std::find",
    description: "Recherche linéaire.",
    instruction: "Trouvez 42 dans <code>{10, 20, 42, 30}</code>. Affichez l'indice (via distance avec begin()).",
    code_template: "#include <iostream>\n#include <vector>\n#include <algorithm>\nint main() {\n  std::vector<int> v = {10, 20, 42, 30};\n  // find\n}",
    solution: "#include <iostream>\n#include <vector>\n#include <algorithm>\nint main() {\n  std::vector<int> v = {10, 20, 42, 30};\n  auto it = std::find(v.begin(), v.end(), 42);\n  std::cout << std::distance(v.begin(), it) << '\\n';\n}",
    tests: [{ expected: "std::find", type: "contains" }],
  },
  {
    id: "cpp_138",
    type: "code",
    category: "STL Algorithms",
    title: "std::count",
    description: "Compter les occurrences.",
    instruction: "Comptez les 3 dans <code>{1, 3, 2, 3, 3, 4}</code> avec <code>std::count</code>. Affichez le total.",
    code_template: "#include <iostream>\n#include <vector>\n#include <algorithm>\nint main() {\n  std::vector<int> v = {1, 3, 2, 3, 3, 4};\n  // count\n}",
    solution: "#include <iostream>\n#include <vector>\n#include <algorithm>\nint main() {\n  std::vector<int> v = {1, 3, 2, 3, 3, 4};\n  std::cout << std::count(v.begin(), v.end(), 3) << '\\n';\n}",
    tests: [{ expected: "std::count", type: "contains" }],
  },
  {
    id: "cpp_139",
    type: "code",
    category: "STL Algorithms",
    title: "std::accumulate",
    description: "Somme via numeric.",
    instruction: "Sommez <code>{1, 2, 3, 4, 5}</code> avec <code>std::accumulate</code>.",
    code_template: "#include <iostream>\n#include <vector>\n#include <numeric>\nint main() {\n  std::vector<int> v = {1, 2, 3, 4, 5};\n  // accumulate\n}",
    solution: "#include <iostream>\n#include <vector>\n#include <numeric>\nint main() {\n  std::vector<int> v = {1, 2, 3, 4, 5};\n  std::cout << std::accumulate(v.begin(), v.end(), 0) << '\\n';\n}",
    tests: [{ expected: "std::accumulate", type: "contains" }],
  },
  {
    id: "cpp_140",
    type: "code",
    category: "STL Algorithms",
    title: "std::transform",
    description: "Map des éléments.",
    instruction: "Doublez chaque élément de <code>{1, 2, 3}</code> avec <code>std::transform</code> + lambda.",
    code_template: "#include <iostream>\n#include <vector>\n#include <algorithm>\nint main() {\n  std::vector<int> v = {1, 2, 3};\n  std::vector<int> out(3);\n  // transform\n}",
    solution: "#include <iostream>\n#include <vector>\n#include <algorithm>\nint main() {\n  std::vector<int> v = {1, 2, 3};\n  std::vector<int> out(3);\n  std::transform(v.begin(), v.end(), out.begin(), [](int x) { return x * 2; });\n  for (int x : out) std::cout << x << ' ';\n  std::cout << '\\n';\n}",
    tests: [{ expected: "std::transform", type: "contains" }],
  },
  {
    id: "cpp_141",
    type: "code",
    category: "STL Algorithms",
    title: "std::all_of / any_of",
    description: "Tests booléens.",
    instruction: "Pour <code>{2, 4, 6}</code>, testez <code>all_of(pair?)</code> et <code>any_of(&gt; 5)</code>. Affichez les 2 résultats.",
    code_template: "#include <iostream>\n#include <vector>\n#include <algorithm>\nint main() {\n  std::vector<int> v = {2, 4, 6};\n  // all_of + any_of\n}",
    solution: "#include <iostream>\n#include <vector>\n#include <algorithm>\nint main() {\n  std::vector<int> v = {2, 4, 6};\n  std::cout << std::all_of(v.begin(), v.end(), [](int x){ return x % 2 == 0; }) << '\\n';\n  std::cout << std::any_of(v.begin(), v.end(), [](int x){ return x > 5; }) << '\\n';\n}",
    tests: [{ expected: "std::all_of", type: "contains" }, { expected: "std::any_of", type: "contains" }],
  },
  {
    id: "cpp_142",
    type: "code",
    category: "STL Algorithms",
    title: "std::reverse",
    description: "Inverser un range.",
    instruction: "Inversez <code>{1, 2, 3, 4, 5}</code> en place et affichez.",
    code_template: "#include <iostream>\n#include <vector>\n#include <algorithm>\nint main() {\n  std::vector<int> v = {1, 2, 3, 4, 5};\n  // reverse\n}",
    solution: "#include <iostream>\n#include <vector>\n#include <algorithm>\nint main() {\n  std::vector<int> v = {1, 2, 3, 4, 5};\n  std::reverse(v.begin(), v.end());\n  for (int x : v) std::cout << x << ' ';\n  std::cout << '\\n';\n}",
    tests: [{ expected: "std::reverse", type: "contains" }],
  },
  {
    id: "cpp_143",
    type: "code",
    category: "STL Algorithms",
    title: "std::unique",
    description: "Retirer doublons consécutifs.",
    instruction: "Triez puis appliquez <code>std::unique + .erase</code> pour ne garder qu'un exemplaire de chaque valeur.",
    code_template: "#include <iostream>\n#include <vector>\n#include <algorithm>\nint main() {\n  std::vector<int> v = {1, 2, 2, 3, 3, 3, 4};\n  // sort + unique + erase\n}",
    solution: "#include <iostream>\n#include <vector>\n#include <algorithm>\nint main() {\n  std::vector<int> v = {1, 2, 2, 3, 3, 3, 4};\n  std::sort(v.begin(), v.end());\n  v.erase(std::unique(v.begin(), v.end()), v.end());\n  for (int x : v) std::cout << x << ' ';\n  std::cout << '\\n';\n}",
    tests: [{ expected: "std::unique", type: "contains" }],
  },
  {
    id: "cpp_144",
    type: "code",
    category: "STL Algorithms",
    title: "std::min_element / max_element",
    description: "Extrêmes.",
    instruction: "Pour <code>{7, 2, 9, 1, 5}</code>, affichez <code>*min_element</code> puis <code>*max_element</code>.",
    code_template: "#include <iostream>\n#include <vector>\n#include <algorithm>\nint main() {\n  std::vector<int> v = {7, 2, 9, 1, 5};\n  // min/max element\n}",
    solution: "#include <iostream>\n#include <vector>\n#include <algorithm>\nint main() {\n  std::vector<int> v = {7, 2, 9, 1, 5};\n  std::cout << *std::min_element(v.begin(), v.end()) << '\\n';\n  std::cout << *std::max_element(v.begin(), v.end()) << '\\n';\n}",
    tests: [{ expected: "min_element", type: "contains" }, { expected: "max_element", type: "contains" }],
  },
  {
    id: "cpp_145",
    type: "code",
    category: "STL Algorithms",
    title: "std::for_each",
    description: "Itération fonctionnelle.",
    instruction: "Pour <code>{1, 2, 3}</code>, utilisez <code>std::for_each</code> + lambda qui affiche chaque élément.",
    code_template: "#include <iostream>\n#include <vector>\n#include <algorithm>\nint main() {\n  std::vector<int> v = {1, 2, 3};\n  // for_each\n}",
    solution: "#include <iostream>\n#include <vector>\n#include <algorithm>\nint main() {\n  std::vector<int> v = {1, 2, 3};\n  std::for_each(v.begin(), v.end(), [](int x) { std::cout << x << '\\n'; });\n}",
    tests: [{ expected: "std::for_each", type: "contains" }],
  },
  {
    id: "cpp_146",
    type: "code",
    category: "STL Algorithms",
    title: "std::copy",
    description: "Copier un range.",
    instruction: "Copiez <code>{1, 2, 3}</code> dans <code>std::vector&lt;int&gt; out</code> (initialisé à taille 3) avec <code>std::copy</code>.",
    code_template: "#include <iostream>\n#include <vector>\n#include <algorithm>\nint main() {\n  std::vector<int> v = {1, 2, 3};\n  std::vector<int> out(3);\n  // copy\n}",
    solution: "#include <iostream>\n#include <vector>\n#include <algorithm>\nint main() {\n  std::vector<int> v = {1, 2, 3};\n  std::vector<int> out(3);\n  std::copy(v.begin(), v.end(), out.begin());\n  for (int x : out) std::cout << x << ' ';\n  std::cout << '\\n';\n}",
    tests: [{ expected: "std::copy", type: "contains" }],
  },
  {
    id: "cpp_147",
    type: "code",
    category: "STL Iterators",
    title: "auto + iterator",
    description: "Type déduit.",
    instruction: "Itérez sur un vector avec <code>auto it = v.begin()</code> et affichez via <code>*it</code>.",
    code_template: "#include <iostream>\n#include <vector>\nint main() {\n  std::vector<int> v = {10, 20, 30};\n  // auto iterator\n}",
    solution: "#include <iostream>\n#include <vector>\nint main() {\n  std::vector<int> v = {10, 20, 30};\n  for (auto it = v.begin(); it != v.end(); ++it) std::cout << *it << ' ';\n  std::cout << '\\n';\n}",
    tests: [{ expected: "auto it", type: "contains" }],
  },
  {
    id: "cpp_148",
    type: "code",
    category: "STL Iterators",
    title: "Range-based for",
    description: "for (auto&amp; x : v).",
    instruction: "Itérez sur <code>{1, 2, 3, 4, 5}</code> avec <code>for (int x : v)</code> et sommez.",
    code_template: "#include <iostream>\n#include <vector>\nint main() {\n  std::vector<int> v = {1, 2, 3, 4, 5};\n  int s = 0;\n  // range-based for\n}",
    solution: "#include <iostream>\n#include <vector>\nint main() {\n  std::vector<int> v = {1, 2, 3, 4, 5};\n  int s = 0;\n  for (int x : v) s += x;\n  std::cout << s << '\\n';\n}",
    tests: [{ expected: "for (int x : v)", type: "contains" }],
  },
  {
    id: "cpp_149",
    type: "code",
    category: "STL Iterators",
    title: "std::back_inserter",
    description: "Insérer en fin via iterator.",
    instruction: "Avec <code>std::copy + std::back_inserter</code>, copiez <code>{1, 2, 3}</code> vers un nouveau vector vide.",
    code_template: "#include <iostream>\n#include <vector>\n#include <iterator>\n#include <algorithm>\nint main() {\n  std::vector<int> v = {1, 2, 3};\n  std::vector<int> out;\n  // back_inserter\n}",
    solution: "#include <iostream>\n#include <vector>\n#include <iterator>\n#include <algorithm>\nint main() {\n  std::vector<int> v = {1, 2, 3};\n  std::vector<int> out;\n  std::copy(v.begin(), v.end(), std::back_inserter(out));\n  std::cout << out.size() << '\\n';\n}",
    tests: [{ expected: "back_inserter", type: "contains" }],
  },
  {
    id: "cpp_150",
    type: "code",
    category: "STL Algorithms",
    title: "std::lower_bound",
    description: "Binary search.",
    instruction: "Avec <code>std::lower_bound</code> sur <code>{1, 3, 5, 7, 9}</code>, trouvez la position d'insertion de 6.",
    code_template: "#include <iostream>\n#include <vector>\n#include <algorithm>\nint main() {\n  std::vector<int> v = {1, 3, 5, 7, 9};\n  // lower_bound\n}",
    solution: "#include <iostream>\n#include <vector>\n#include <algorithm>\nint main() {\n  std::vector<int> v = {1, 3, 5, 7, 9};\n  auto it = std::lower_bound(v.begin(), v.end(), 6);\n  std::cout << std::distance(v.begin(), it) << '\\n';\n}",
    tests: [{ expected: "lower_bound", type: "contains" }],
  },
];

addExercises("cpp", exercises);
