import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/**
 * C# — Part 7 : LINQ avancé (GroupBy, Aggregate, Joins, SelectMany).
 */
const exercises: Exercise[] = [
  {
    id: "cs_156",
    type: "code",
    category: "LINQ avancé",
    title: "Where + Select",
    description: "Filtrer puis projeter.",
    instruction: "Pour <code>var nums = new[] {1,2,3,4,5}</code>, gardez les pairs et doublez-les. Affichez-les joints par virgule.",
    code_template: "using System;\nusing System.Linq;\nclass P {\n  static void Main() {\n    var nums = new[] {1,2,3,4,5};\n    // Where + Select\n  }\n}",
    solution: "using System;\nusing System.Linq;\nclass P {\n  static void Main() {\n    var nums = new[] {1,2,3,4,5};\n    var r = nums.Where(x => x % 2 == 0).Select(x => x * 2);\n    Console.WriteLine(string.Join(\",\", r));\n  }\n}",
    tests: [{ expected: ".Where(", type: "contains" }, { expected: ".Select(", type: "contains" }],
  },
  {
    id: "cs_157",
    type: "code",
    category: "LINQ avancé",
    title: "GroupBy",
    description: "Grouper par clé.",
    instruction: "Pour <code>new[] {\"apple\",\"banana\",\"avocado\",\"blueberry\"}</code>, groupez par première lettre. Loggez chaque <code>clé:count</code>.",
    code_template: "using System;\nusing System.Linq;\nclass P {\n  static void Main() {\n    var words = new[] {\"apple\",\"banana\",\"avocado\",\"blueberry\"};\n    // GroupBy\n  }\n}",
    solution: "using System;\nusing System.Linq;\nclass P {\n  static void Main() {\n    var words = new[] {\"apple\",\"banana\",\"avocado\",\"blueberry\"};\n    foreach (var g in words.GroupBy(w => w[0]))\n      Console.WriteLine($\"{g.Key}:{g.Count()}\");\n  }\n}",
    tests: [{ expected: "GroupBy", type: "contains" }, { expected: ".Count()", type: "contains" }],
  },
  {
    id: "cs_158",
    type: "code",
    category: "LINQ avancé",
    title: "Aggregate (somme custom)",
    description: "Reduce du C#.",
    instruction: "Avec <code>Aggregate</code>, calculez le produit de <code>{1,2,3,4,5}</code> (= 120).",
    code_template: "using System.Linq;\nvar nums = new[] {1,2,3,4,5};\n// Aggregate\n",
    solution: "using System;\nusing System.Linq;\nvar nums = new[] {1,2,3,4,5};\nint prod = nums.Aggregate(1, (acc, x) => acc * x);\nConsole.WriteLine(prod);",
    tests: [{ expected: "Aggregate", type: "contains" }],
  },
  {
    id: "cs_159",
    type: "code",
    category: "LINQ avancé",
    title: "Sum / Min / Max / Average",
    description: "Agrégats standards.",
    instruction: "Pour <code>{10, 20, 30, 40, 50}</code>, loggez sum, min, max, average chacun sur sa ligne.",
    code_template: "using System;\nusing System.Linq;\nvar nums = new[] {10, 20, 30, 40, 50};\n// sum, min, max, avg\n",
    solution: "using System;\nusing System.Linq;\nvar nums = new[] {10, 20, 30, 40, 50};\nConsole.WriteLine(nums.Sum());\nConsole.WriteLine(nums.Min());\nConsole.WriteLine(nums.Max());\nConsole.WriteLine(nums.Average());",
    tests: [{ expected: ".Sum()", type: "contains" }, { expected: ".Average()", type: "contains" }],
  },
  {
    id: "cs_160",
    type: "code",
    category: "LINQ avancé",
    title: "OrderBy + ThenBy",
    description: "Tri multi-niveaux.",
    instruction: "Triez une liste de personnes par <code>Nom</code> ascendant puis <code>Age</code> descendant.",
    code_template: "using System;\nusing System.Linq;\nvar people = new[] {(Nom:\"B\", Age:30), (Nom:\"A\", Age:20), (Nom:\"A\", Age:30)};\n// OrderBy + ThenByDescending\n",
    solution: "using System;\nusing System.Linq;\nvar people = new[] {(Nom:\"B\", Age:30), (Nom:\"A\", Age:20), (Nom:\"A\", Age:30)};\nforeach (var p in people.OrderBy(p => p.Nom).ThenByDescending(p => p.Age))\n  Console.WriteLine($\"{p.Nom}/{p.Age}\");",
    tests: [{ expected: "OrderBy", type: "contains" }, { expected: "ThenBy", type: "contains" }],
  },
  {
    id: "cs_161",
    type: "code",
    category: "LINQ avancé",
    title: "Take / Skip",
    description: "Pagination.",
    instruction: "Pour <code>Enumerable.Range(1, 100)</code>, sautez 10 et prenez 5. Affichez joint par virgule.",
    code_template: "using System;\nusing System.Linq;\nvar all = Enumerable.Range(1, 100);\n// Skip 10 Take 5\n",
    solution: "using System;\nusing System.Linq;\nvar all = Enumerable.Range(1, 100);\nConsole.WriteLine(string.Join(\",\", all.Skip(10).Take(5)));",
    tests: [{ expected: ".Skip(", type: "contains" }, { expected: ".Take(", type: "contains" }],
  },
  {
    id: "cs_162",
    type: "code",
    category: "LINQ avancé",
    title: "First / FirstOrDefault",
    description: "Premier élément.",
    instruction: "Trouvez le premier nombre > 50 dans <code>{10, 30, 70, 90}</code>. Si absent, retournez -1 via <code>FirstOrDefault</code>.",
    code_template: "using System;\nusing System.Linq;\nvar nums = new[] {10, 30, 70, 90};\n// FirstOrDefault\n",
    solution: "using System;\nusing System.Linq;\nvar nums = new[] {10, 30, 70, 90};\nConsole.WriteLine(nums.FirstOrDefault(x => x > 50));",
    tests: [{ expected: "FirstOrDefault", type: "contains" }],
  },
  {
    id: "cs_163",
    type: "code",
    category: "LINQ avancé",
    title: "Single",
    description: "Exactement un élément.",
    instruction: "Avec <code>Single</code>, trouvez le nombre = 5 dans <code>{1, 3, 5, 7}</code>. Lance si 0 ou >1 match.",
    code_template: "using System.Linq;\nvar nums = new[] {1, 3, 5, 7};\n// Single\n",
    solution: "using System;\nusing System.Linq;\nvar nums = new[] {1, 3, 5, 7};\nConsole.WriteLine(nums.Single(x => x == 5));",
    tests: [{ expected: ".Single(", type: "contains" }],
  },
  {
    id: "cs_164",
    type: "code",
    category: "LINQ avancé",
    title: "Any / All",
    description: "Tests booléens.",
    instruction: "Pour <code>{2, 4, 6, 8}</code>, loggez <code>All(x => x % 2 == 0)</code> puis <code>Any(x => x > 100)</code>.",
    code_template: "using System;\nusing System.Linq;\nvar nums = new[] {2, 4, 6, 8};\n// All + Any\n",
    solution: "using System;\nusing System.Linq;\nvar nums = new[] {2, 4, 6, 8};\nConsole.WriteLine(nums.All(x => x % 2 == 0));\nConsole.WriteLine(nums.Any(x => x > 100));",
    tests: [{ expected: ".All(", type: "contains" }, { expected: ".Any(", type: "contains" }],
  },
  {
    id: "cs_165",
    type: "code",
    category: "LINQ avancé",
    title: "Distinct",
    description: "Éléments uniques.",
    instruction: "Pour <code>{1, 2, 2, 3, 3, 3, 4}</code>, gardez les uniques. Affichez joints par virgule.",
    code_template: "using System.Linq;\nvar nums = new[] {1, 2, 2, 3, 3, 3, 4};\n// Distinct\n",
    solution: "using System;\nusing System.Linq;\nvar nums = new[] {1, 2, 2, 3, 3, 3, 4};\nConsole.WriteLine(string.Join(\",\", nums.Distinct()));",
    tests: [{ expected: ".Distinct(", type: "contains" }],
  },
  {
    id: "cs_166",
    type: "code",
    category: "LINQ avancé",
    title: "Union / Intersect / Except",
    description: "Opérations ensemblistes.",
    instruction: "Pour <code>a={1,2,3}, b={2,3,4}</code>, calculez Union, Intersect, Except et loggez chacun sur une ligne joints par virgule.",
    code_template: "using System;\nusing System.Linq;\nvar a = new[] {1,2,3}; var b = new[] {2,3,4};\n// Union, Intersect, Except\n",
    solution: "using System;\nusing System.Linq;\nvar a = new[] {1,2,3}; var b = new[] {2,3,4};\nConsole.WriteLine(string.Join(\",\", a.Union(b)));\nConsole.WriteLine(string.Join(\",\", a.Intersect(b)));\nConsole.WriteLine(string.Join(\",\", a.Except(b)));",
    tests: [{ expected: ".Union(", type: "contains" }, { expected: ".Intersect(", type: "contains" }, { expected: ".Except(", type: "contains" }],
  },
  {
    id: "cs_167",
    type: "code",
    category: "LINQ avancé",
    title: "SelectMany",
    description: "Aplatir des collections.",
    instruction: "Pour <code>{new[]{1,2}, new[]{3,4}, new[]{5,6}}</code>, aplatissez avec SelectMany. Affichez joints par virgule.",
    code_template: "using System;\nusing System.Linq;\nvar matrix = new[] {new[]{1,2}, new[]{3,4}, new[]{5,6}};\n// SelectMany\n",
    solution: "using System;\nusing System.Linq;\nvar matrix = new[] {new[]{1,2}, new[]{3,4}, new[]{5,6}};\nConsole.WriteLine(string.Join(\",\", matrix.SelectMany(row => row)));",
    tests: [{ expected: "SelectMany", type: "contains" }],
  },
  {
    id: "cs_168",
    type: "code",
    category: "LINQ avancé",
    title: "Zip",
    description: "Combiner deux séquences.",
    instruction: "Avec <code>names={\"Alice\",\"Bob\",\"Carol\"}</code> et <code>ages={20,30,40}</code>, Zip pour afficher <code>nom:age</code> par ligne.",
    code_template: "using System;\nusing System.Linq;\nvar names = new[] {\"Alice\",\"Bob\",\"Carol\"};\nvar ages = new[] {20,30,40};\n// Zip\n",
    solution: "using System;\nusing System.Linq;\nvar names = new[] {\"Alice\",\"Bob\",\"Carol\"};\nvar ages = new[] {20,30,40};\nforeach (var pair in names.Zip(ages, (n, a) => $\"{n}:{a}\"))\n  Console.WriteLine(pair);",
    tests: [{ expected: ".Zip(", type: "contains" }],
  },
  {
    id: "cs_169",
    type: "code",
    category: "LINQ avancé",
    title: "Join",
    description: "Jointure SQL-like.",
    instruction: "Joignez <code>orders</code> (UserId) et <code>users</code> (Id) sur la clé pour afficher <code>userName/orderId</code>.",
    code_template: "using System;\nusing System.Linq;\nvar users = new[] {(Id:1, Name:\"A\"), (Id:2, Name:\"B\")};\nvar orders = new[] {(OrderId:10, UserId:1), (OrderId:11, UserId:2)};\n// Join\n",
    solution: "using System;\nusing System.Linq;\nvar users = new[] {(Id:1, Name:\"A\"), (Id:2, Name:\"B\")};\nvar orders = new[] {(OrderId:10, UserId:1), (OrderId:11, UserId:2)};\nvar joined = orders.Join(users, o => o.UserId, u => u.Id, (o, u) => $\"{u.Name}/{o.OrderId}\");\nforeach (var x in joined) Console.WriteLine(x);",
    tests: [{ expected: ".Join(", type: "contains" }],
  },
  {
    id: "cs_170",
    type: "code",
    category: "LINQ avancé",
    title: "GroupJoin",
    description: "Left outer join groupé.",
    instruction: "Avec GroupJoin, listez chaque user avec ses orders (potentiellement vide).",
    code_template: "using System;\nusing System.Linq;\nvar users = new[] {(Id:1, Name:\"A\"), (Id:2, Name:\"B\"), (Id:3, Name:\"C\")};\nvar orders = new[] {(Oid:10, Uid:1), (Oid:11, Uid:1), (Oid:12, Uid:2)};\n// GroupJoin\n",
    solution: "using System;\nusing System.Linq;\nvar users = new[] {(Id:1, Name:\"A\"), (Id:2, Name:\"B\"), (Id:3, Name:\"C\")};\nvar orders = new[] {(Oid:10, Uid:1), (Oid:11, Uid:1), (Oid:12, Uid:2)};\nvar joined = users.GroupJoin(orders, u => u.Id, o => o.Uid, (u, os) => $\"{u.Name}:{os.Count()}\");\nforeach (var x in joined) Console.WriteLine(x);",
    tests: [{ expected: "GroupJoin", type: "contains" }],
  },
  {
    id: "cs_171",
    type: "code",
    category: "LINQ avancé",
    title: "ToDictionary",
    description: "Construire un dict à partir d'une séquence.",
    instruction: "Pour <code>{(\"A\",1), (\"B\",2), (\"C\",3)}</code>, créez un Dictionary clé→valeur.",
    code_template: "using System.Linq;\nvar pairs = new[] {(\"A\",1), (\"B\",2), (\"C\",3)};\n// ToDictionary\n",
    solution: "using System;\nusing System.Linq;\nvar pairs = new[] {(\"A\",1), (\"B\",2), (\"C\",3)};\nvar dict = pairs.ToDictionary(p => p.Item1, p => p.Item2);\nConsole.WriteLine(dict[\"B\"]);",
    tests: [{ expected: "ToDictionary", type: "contains" }],
  },
  {
    id: "cs_172",
    type: "code",
    category: "LINQ avancé",
    title: "ToList vs ToArray",
    description: "Matérialisation.",
    instruction: "Convertissez <code>Enumerable.Range(1, 5)</code> en List puis en Array. Loggez Count et Length.",
    code_template: "using System;\nusing System.Linq;\nvar range = Enumerable.Range(1, 5);\n// ToList + ToArray\n",
    solution: "using System;\nusing System.Linq;\nvar range = Enumerable.Range(1, 5);\nConsole.WriteLine(range.ToList().Count);\nConsole.WriteLine(range.ToArray().Length);",
    tests: [{ expected: ".ToList()", type: "contains" }, { expected: ".ToArray()", type: "contains" }],
  },
  {
    id: "cs_173",
    type: "code",
    category: "LINQ avancé",
    title: "Reverse",
    description: "Inverser l'ordre.",
    instruction: "Inversez <code>{1,2,3,4,5}</code> et affichez joints par virgule.",
    code_template: "using System;\nusing System.Linq;\nvar nums = new[] {1,2,3,4,5};\n",
    solution: "using System;\nusing System.Linq;\nvar nums = new[] {1,2,3,4,5};\nConsole.WriteLine(string.Join(\",\", nums.Reverse()));",
    tests: [{ expected: ".Reverse()", type: "contains" }],
  },
  {
    id: "cs_174",
    type: "code",
    category: "LINQ avancé",
    title: "Concat",
    description: "Concaténer deux séquences.",
    instruction: "Concaténez <code>{1,2,3}</code> et <code>{4,5}</code>. Affichez joints par virgule.",
    code_template: "using System;\nusing System.Linq;\nvar a = new[] {1,2,3}; var b = new[] {4,5};\n",
    solution: "using System;\nusing System.Linq;\nvar a = new[] {1,2,3}; var b = new[] {4,5};\nConsole.WriteLine(string.Join(\",\", a.Concat(b)));",
    tests: [{ expected: ".Concat(", type: "contains" }],
  },
  {
    id: "cs_175",
    type: "code",
    category: "LINQ avancé",
    title: "Range / Repeat",
    description: "Générateurs.",
    instruction: "Affichez <code>Enumerable.Range(0, 5)</code> joint par virgule puis <code>Enumerable.Repeat(\"X\", 3)</code> joint par virgule.",
    code_template: "using System;\nusing System.Linq;\n// Range + Repeat\n",
    solution: "using System;\nusing System.Linq;\nConsole.WriteLine(string.Join(\",\", Enumerable.Range(0, 5)));\nConsole.WriteLine(string.Join(\",\", Enumerable.Repeat(\"X\", 3)));",
    tests: [{ expected: "Enumerable.Range", type: "contains" }, { expected: "Enumerable.Repeat", type: "contains" }],
  },
  {
    id: "cs_176",
    type: "code",
    category: "LINQ avancé",
    title: "Query syntax (from-where-select)",
    description: "Syntaxe SQL-like.",
    instruction: "Avec la query syntax LINQ, sélectionnez les nombres > 5 de <code>{1,3,5,7,9}</code>. Affichez joints par virgule.",
    code_template: "using System;\nusing System.Linq;\nvar nums = new[] {1,3,5,7,9};\n// query syntax\n",
    solution: "using System;\nusing System.Linq;\nvar nums = new[] {1,3,5,7,9};\nvar r = from n in nums where n > 5 select n;\nConsole.WriteLine(string.Join(\",\", r));",
    tests: [{ expected: "from", type: "contains" }, { expected: "where", type: "contains" }, { expected: "select", type: "contains" }],
  },
  {
    id: "cs_177",
    type: "code",
    category: "LINQ avancé",
    title: "let dans la query",
    description: "Variable temporaire LINQ.",
    instruction: "Avec query syntax + <code>let</code>, calculez le carré de chaque élément de {1,2,3,4} et gardez ceux > 5.",
    code_template: "using System;\nusing System.Linq;\nvar nums = new[] {1,2,3,4};\n// from + let\n",
    solution: "using System;\nusing System.Linq;\nvar nums = new[] {1,2,3,4};\nvar r = from n in nums let sq = n * n where sq > 5 select sq;\nConsole.WriteLine(string.Join(\",\", r));",
    tests: [{ expected: "let", type: "contains" }],
  },
  {
    id: "cs_178",
    type: "code",
    category: "LINQ avancé",
    title: "Lazy evaluation",
    description: "Deferred execution.",
    instruction: "Démontrez la deferred execution : <code>var q = nums.Where(...)</code> ne s'exécute qu'au .ToList(). Modifiez nums entre la définition et l'enum, puis loggez.",
    code_template: "using System;\nusing System.Collections.Generic;\nusing System.Linq;\nvar nums = new List<int> {1,2,3};\nvar q = nums.Where(x => x > 1);\nnums.Add(4);\n// .ToList et log\n",
    solution: "using System;\nusing System.Collections.Generic;\nusing System.Linq;\nvar nums = new List<int> {1,2,3};\nvar q = nums.Where(x => x > 1);\nnums.Add(4);\nConsole.WriteLine(string.Join(\",\", q.ToList()));",
    tests: [{ expected: ".ToList()", type: "contains" }],
  },
  {
    id: "cs_179",
    type: "code",
    category: "LINQ avancé",
    title: "OrderBy custom comparer",
    description: "IComparer<T> custom.",
    instruction: "Triez <code>{\"AA\", \"B\", \"CCC\"}</code> par longueur de chaîne croissante via OrderBy.",
    code_template: "using System;\nusing System.Linq;\nvar words = new[] {\"AA\",\"B\",\"CCC\"};\n// OrderBy(Length)\n",
    solution: "using System;\nusing System.Linq;\nvar words = new[] {\"AA\",\"B\",\"CCC\"};\nforeach (var w in words.OrderBy(s => s.Length)) Console.WriteLine(w);",
    tests: [{ expected: ".OrderBy(", type: "contains" }, { expected: ".Length", type: "contains" }],
  },
  {
    id: "cs_180",
    type: "code",
    category: "LINQ avancé",
    title: "GroupBy avec aggrégat",
    description: "Stats par groupe.",
    instruction: "Pour <code>{(\"A\", 10), (\"B\", 20), (\"A\", 30), (\"B\", 5)}</code>, calculez la somme par première lettre.",
    code_template: "using System;\nusing System.Linq;\nvar data = new[] {(\"A\", 10), (\"B\", 20), (\"A\", 30), (\"B\", 5)};\n// GroupBy + Sum\n",
    solution: "using System;\nusing System.Linq;\nvar data = new[] {(\"A\", 10), (\"B\", 20), (\"A\", 30), (\"B\", 5)};\nforeach (var g in data.GroupBy(x => x.Item1))\n  Console.WriteLine($\"{g.Key}:{g.Sum(x => x.Item2)}\");",
    tests: [{ expected: ".GroupBy(", type: "contains" }, { expected: ".Sum(", type: "contains" }],
  },
];

addExercises("csharp", exercises);
