import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/**
 * C# — Part 10 : ASP.NET Core, EF Core, DI, middleware, Minimal API.
 */
const exercises: Exercise[] = [
  {
    id: "cs_231",
    type: "code",
    category: "ASP.NET Core",
    title: "Minimal API GET",
    description: "Endpoint le plus simple.",
    instruction: "Avec <code>WebApplication.CreateBuilder</code>, créez une app, une route GET '/' qui retourne 'Hello, World!'.",
    code_template: "// Minimal API\n",
    solution: "var builder = WebApplication.CreateBuilder(args);\nvar app = builder.Build();\napp.MapGet(\"/\", () => \"Hello, World!\");\napp.Run();",
    tests: [{ expected: "MapGet", type: "contains" }, { expected: "app.Run()", type: "contains" }],
  },
  {
    id: "cs_232",
    type: "code",
    category: "ASP.NET Core",
    title: "Minimal API JSON",
    description: "Retourner objet JSON.",
    instruction: "Route GET '/api/user' qui retourne <code>new {Name = \"Aelita\", Level = 100}</code>.",
    code_template: "// MapGet JSON\n",
    solution: "var app = WebApplication.CreateBuilder(args).Build();\napp.MapGet(\"/api/user\", () => new { Name = \"Aelita\", Level = 100 });\napp.Run();",
    tests: [{ expected: "/api/user", type: "contains" }, { expected: "Name =", type: "contains" }],
  },
  {
    id: "cs_233",
    type: "code",
    category: "ASP.NET Core",
    title: "Route param",
    description: "Capter un segment dynamique.",
    instruction: "Route <code>GET /users/{id:int}</code> qui retourne l'id depuis le param.",
    code_template: "app.MapGet(\"/users/{id:int}\", /* */);",
    solution: "app.MapGet(\"/users/{id:int}\", (int id) => $\"User {id}\");",
    tests: [{ expected: "{id:int}", type: "contains" }],
  },
  {
    id: "cs_234",
    type: "code",
    category: "ASP.NET Core",
    title: "Query parameter",
    description: "?q=...",
    instruction: "Route <code>GET /search</code> qui prend <code>[FromQuery] string q</code> et retourne la query.",
    code_template: "using Microsoft.AspNetCore.Mvc;\napp.MapGet(\"/search\", /* */);",
    solution: "using Microsoft.AspNetCore.Mvc;\napp.MapGet(\"/search\", ([FromQuery] string q) => new { query = q });",
    tests: [{ expected: "[FromQuery]", type: "contains" }],
  },
  {
    id: "cs_235",
    type: "code",
    category: "ASP.NET Core",
    title: "POST body",
    description: "Recevoir JSON.",
    instruction: "Route <code>POST /users</code> qui reçoit un body <code>record User(string Name)</code> et le retourne avec status 201.",
    code_template: "// POST\n",
    solution: "public record User(string Name);\nvar app = WebApplication.CreateBuilder(args).Build();\napp.MapPost(\"/users\", (User u) => Results.Created($\"/users/{u.Name}\", u));\napp.Run();",
    tests: [{ expected: "MapPost", type: "contains" }, { expected: "Results.Created", type: "contains" }],
  },
  {
    id: "cs_236",
    type: "code",
    category: "ASP.NET Core",
    title: "Results.NotFound",
    description: "Status 404.",
    instruction: "Route GET /users/{id} qui retourne 404 si id != 1, sinon le user.",
    code_template: "// 404 ou user\n",
    solution: "app.MapGet(\"/users/{id:int}\", (int id) => id != 1 ? Results.NotFound() : Results.Ok(new { id, name = \"X\" }));",
    tests: [{ expected: "Results.NotFound", type: "contains" }],
  },
  {
    id: "cs_237",
    type: "code",
    category: "ASP.NET Core",
    title: "Middleware",
    description: "Pipeline custom.",
    instruction: "Ajoutez un middleware qui log chaque requête (URL) puis appelle <code>await next()</code>.",
    code_template: "var app = WebApplication.CreateBuilder(args).Build();\n// middleware\napp.Run();",
    solution: "using System;\nvar app = WebApplication.CreateBuilder(args).Build();\napp.Use(async (ctx, next) => {\n  Console.WriteLine(ctx.Request.Path);\n  await next();\n});\napp.Run();",
    tests: [{ expected: "app.Use(async", type: "contains" }, { expected: "await next", type: "contains" }],
  },
  {
    id: "cs_238",
    type: "code",
    category: "ASP.NET Core",
    title: "DI : enregistrer un service",
    description: "AddSingleton.",
    instruction: "Enregistrez <code>builder.Services.AddSingleton&lt;IMyService, MyService&gt;()</code>. Injectez dans une route.",
    code_template: "var builder = WebApplication.CreateBuilder(args);\n// AddSingleton\nvar app = builder.Build();\napp.MapGet(\"/\", (IMyService s) => s.Greet());\n",
    solution: "public interface IMyService { string Greet(); }\npublic class MyService : IMyService { public string Greet() => \"Hello!\"; }\nvar builder = WebApplication.CreateBuilder(args);\nbuilder.Services.AddSingleton<IMyService, MyService>();\nvar app = builder.Build();\napp.MapGet(\"/\", (IMyService s) => s.Greet());\napp.Run();",
    tests: [{ expected: "AddSingleton", type: "contains" }, { expected: "IMyService", type: "contains" }],
  },
  {
    id: "cs_239",
    type: "code",
    category: "ASP.NET Core",
    title: "DI : scoped",
    description: "Service par requête.",
    instruction: "Enregistrez avec <code>AddScoped</code> au lieu de Singleton.",
    code_template: "// AddScoped\n",
    solution: "builder.Services.AddScoped<IMyService, MyService>();",
    tests: [{ expected: "AddScoped", type: "contains" }],
  },
  {
    id: "cs_240",
    type: "code",
    category: "ASP.NET Core",
    title: "Controller traditionnel",
    description: "MVC Controller.",
    instruction: "Définissez un <code>UsersController : ControllerBase</code> avec <code>[ApiController][Route(\"api/users\")]</code> et une action GET qui retourne 'OK'.",
    code_template: "using Microsoft.AspNetCore.Mvc;\n// Controller\n",
    solution: "using Microsoft.AspNetCore.Mvc;\n[ApiController]\n[Route(\"api/users\")]\npublic class UsersController : ControllerBase {\n  [HttpGet]\n  public IActionResult Get() => Ok(\"OK\");\n}",
    tests: [{ expected: "[ApiController]", type: "contains" }, { expected: "ControllerBase", type: "contains" }, { expected: "[HttpGet]", type: "contains" }],
  },
  {
    id: "cs_241",
    type: "code",
    category: "EF Core",
    title: "DbContext",
    description: "Le contexte EF.",
    instruction: "Définissez <code>class AppContext : DbContext</code> avec une <code>DbSet&lt;User&gt; Users</code>.",
    code_template: "using Microsoft.EntityFrameworkCore;\npublic record User(int Id, string Name);\npublic class AppContext : DbContext {\n  // DbSet\n}",
    solution: "using Microsoft.EntityFrameworkCore;\npublic class User { public int Id { get; set; } public string Name { get; set; } = \"\"; }\npublic class AppContext : DbContext {\n  public DbSet<User> Users => Set<User>();\n  protected override void OnConfiguring(DbContextOptionsBuilder b) => b.UseSqlite(\"Data Source=app.db\");\n}",
    tests: [{ expected: "DbContext", type: "contains" }, { expected: "DbSet<User>", type: "contains" }],
  },
  {
    id: "cs_242",
    type: "code",
    category: "EF Core",
    title: "Migration",
    description: "Créer la DB.",
    instruction: "Avec <code>db.Database.EnsureCreated()</code>, créez la DB au démarrage.",
    code_template: "using var db = new AppContext();\n// EnsureCreated\n",
    solution: "using var db = new AppContext();\ndb.Database.EnsureCreated();",
    tests: [{ expected: "EnsureCreated", type: "contains" }],
  },
  {
    id: "cs_243",
    type: "code",
    category: "EF Core",
    title: "Ajouter une entité",
    description: "Add + SaveChanges.",
    instruction: "Ajoutez un User avec name='Aelita' au DbContext et persistez.",
    code_template: "using var db = new AppContext();\n// Add\n",
    solution: "using var db = new AppContext();\ndb.Users.Add(new User { Name = \"Aelita\" });\ndb.SaveChanges();",
    tests: [{ expected: ".Add(", type: "contains" }, { expected: "SaveChanges", type: "contains" }],
  },
  {
    id: "cs_244",
    type: "code",
    category: "EF Core",
    title: "Query avec LINQ",
    description: "Trouver une entité.",
    instruction: "Avec <code>db.Users.FirstOrDefault(u =&gt; u.Id == 1)</code>, récupérez le user.",
    code_template: "using var db = new AppContext();\n// query\n",
    solution: "using var db = new AppContext();\nvar u = db.Users.FirstOrDefault(u => u.Id == 1);",
    tests: [{ expected: ".FirstOrDefault", type: "contains" }],
  },
  {
    id: "cs_245",
    type: "code",
    category: "EF Core",
    title: "Update",
    description: "Modifier + SaveChanges.",
    instruction: "Récupérez un user, modifiez son Name, persistez.",
    code_template: "using var db = new AppContext();\n// update\n",
    solution: "using var db = new AppContext();\nvar u = db.Users.First();\nu.Name = \"NewName\";\ndb.SaveChanges();",
    tests: [{ expected: "SaveChanges", type: "contains" }, { expected: ".Name =", type: "contains" }],
  },
  {
    id: "cs_246",
    type: "code",
    category: "EF Core",
    title: "Delete",
    description: "Remove + SaveChanges.",
    instruction: "Supprimez un user puis persistez.",
    code_template: "using var db = new AppContext();\n// remove\n",
    solution: "using var db = new AppContext();\nvar u = db.Users.First();\ndb.Users.Remove(u);\ndb.SaveChanges();",
    tests: [{ expected: ".Remove(", type: "contains" }, { expected: "SaveChanges", type: "contains" }],
  },
  {
    id: "cs_247",
    type: "code",
    category: "EF Core",
    title: "Include (eager loading)",
    description: "Charger relations.",
    instruction: "Avec <code>.Include(u =&gt; u.Posts)</code>, chargez les posts liés.",
    code_template: "using Microsoft.EntityFrameworkCore;\n// Include\n",
    solution: "using Microsoft.EntityFrameworkCore;\nvar users = db.Users.Include(u => u.Posts).ToList();",
    tests: [{ expected: ".Include(", type: "contains" }],
  },
  {
    id: "cs_248",
    type: "code",
    category: "EF Core",
    title: "Async query",
    description: "ToListAsync.",
    instruction: "Avec <code>await db.Users.ToListAsync()</code>, récupérez tous les users en async.",
    code_template: "using Microsoft.EntityFrameworkCore;\nasync Task Main() {\n  // \n}",
    solution: "using Microsoft.EntityFrameworkCore;\nusing System.Threading.Tasks;\nasync Task Main() {\n  var users = await db.Users.ToListAsync();\n}",
    tests: [{ expected: "ToListAsync", type: "contains" }],
  },
  {
    id: "cs_249",
    type: "code",
    category: "ASP.NET Core",
    title: "Configuration (appsettings)",
    description: "Lire config.",
    instruction: "Lisez <code>builder.Configuration[\"DatabaseUrl\"]</code> et utilisez-la.",
    code_template: "var builder = WebApplication.CreateBuilder(args);\n// Configuration\n",
    solution: "using System;\nvar builder = WebApplication.CreateBuilder(args);\nvar dbUrl = builder.Configuration[\"DatabaseUrl\"];\nConsole.WriteLine(dbUrl);",
    tests: [{ expected: "Configuration[", type: "contains" }],
  },
  {
    id: "cs_250",
    type: "code",
    category: "ASP.NET Core",
    title: "Environment",
    description: "Dev vs Prod.",
    instruction: "Avec <code>app.Environment.IsDevelopment()</code>, activez le DeveloperExceptionPage en dev.",
    code_template: "if (/* */) app.UseDeveloperExceptionPage();\n",
    solution: "if (app.Environment.IsDevelopment()) app.UseDeveloperExceptionPage();",
    tests: [{ expected: "IsDevelopment", type: "contains" }],
  },
  {
    id: "cs_251",
    type: "code",
    category: "ASP.NET Core",
    title: "CORS",
    description: "AddCors + UseCors.",
    instruction: "Activez CORS avec <code>AddCors</code> + une policy AllowAll et <code>app.UseCors</code>.",
    code_template: "// CORS\n",
    solution: "builder.Services.AddCors(o => o.AddPolicy(\"All\", b => b.AllowAnyOrigin().AllowAnyMethod()));\napp.UseCors(\"All\");",
    tests: [{ expected: "AddCors", type: "contains" }, { expected: "UseCors", type: "contains" }],
  },
  {
    id: "cs_252",
    type: "code",
    category: "ASP.NET Core",
    title: "Authentication JWT (concept)",
    description: "AddAuthentication.",
    instruction: "Enregistrez l'authentification JWT Bearer.",
    code_template: "// AddAuthentication\n",
    solution: "using Microsoft.AspNetCore.Authentication.JwtBearer;\nbuilder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer();",
    tests: [{ expected: "AddAuthentication", type: "contains" }, { expected: "AddJwtBearer", type: "contains" }],
  },
  {
    id: "cs_253",
    type: "code",
    category: "ASP.NET Core",
    title: "Authorization",
    description: "Require auth sur une route.",
    instruction: "Ajoutez <code>.RequireAuthorization()</code> sur une route GET /protected.",
    code_template: "app.MapGet(\"/protected\", () => \"secret\")/* */;\n",
    solution: "app.MapGet(\"/protected\", () => \"secret\").RequireAuthorization();",
    tests: [{ expected: ".RequireAuthorization", type: "contains" }],
  },
  {
    id: "cs_254",
    type: "code",
    category: "ASP.NET Core",
    title: "Swagger / OpenAPI",
    description: "Documentation auto.",
    instruction: "Ajoutez Swagger avec <code>AddEndpointsApiExplorer</code> + <code>AddSwaggerGen</code> + <code>UseSwagger</code> + <code>UseSwaggerUI</code>.",
    code_template: "// Swagger\n",
    solution: "builder.Services.AddEndpointsApiExplorer();\nbuilder.Services.AddSwaggerGen();\nvar app = builder.Build();\napp.UseSwagger();\napp.UseSwaggerUI();",
    tests: [{ expected: "AddSwaggerGen", type: "contains" }, { expected: "UseSwagger", type: "contains" }],
  },
  {
    id: "cs_255",
    type: "code",
    category: "Final",
    title: "Mini-API C# complète",
    description: "Combo final.",
    instruction: "Minimal API avec CORS + Auth + Routes CRUD GET/POST /users + DI d'un repository.",
    code_template: "// Mini-API\n",
    solution: "public record User(int Id, string Name);\npublic interface IUserRepo {\n  IEnumerable<User> GetAll();\n  void Add(User u);\n}\npublic class InMemoryRepo : IUserRepo {\n  private readonly List<User> _all = new();\n  public IEnumerable<User> GetAll() => _all;\n  public void Add(User u) => _all.Add(u);\n}\nvar builder = WebApplication.CreateBuilder(args);\nbuilder.Services.AddSingleton<IUserRepo, InMemoryRepo>();\nbuilder.Services.AddCors();\nvar app = builder.Build();\napp.UseCors(b => b.AllowAnyOrigin());\napp.MapGet(\"/users\", (IUserRepo r) => r.GetAll());\napp.MapPost(\"/users\", (User u, IUserRepo r) => { r.Add(u); return Results.Created($\"/users/{u.Id}\", u); });\napp.Run();",
    tests: [{ expected: "MapGet", type: "contains" }, { expected: "MapPost", type: "contains" }, { expected: "AddSingleton", type: "contains" }, { expected: "AddCors", type: "contains" }],
    hint: "Tu viens de finir 220+ exos C#. Bravo Lyoko-warrior !",
  },
];

addExercises("csharp", exercises);
