import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/**
 * C# — Part 8 : async/await avancé, Task, parallel, cancellation.
 */
const exercises: Exercise[] = [
  {
    id: "cs_181",
    type: "code",
    category: "Async avancé",
    title: "Task.Run",
    description: "Exécuter en background.",
    instruction: "Lancez un calcul en background avec <code>Task.Run(() => ...)</code> et attendez le résultat.",
    code_template: "using System;\nusing System.Threading.Tasks;\nclass P {\n  static async Task Main() {\n    // Task.Run\n  }\n}",
    solution: "using System;\nusing System.Threading.Tasks;\nclass P {\n  static async Task Main() {\n    int r = await Task.Run(() => 42);\n    Console.WriteLine(r);\n  }\n}",
    tests: [{ expected: "Task.Run", type: "contains" }, { expected: "await", type: "contains" }],
  },
  {
    id: "cs_182",
    type: "code",
    category: "Async avancé",
    title: "Task.WhenAll",
    description: "Plusieurs tâches en parallèle.",
    instruction: "Lancez 3 tâches <code>Task.FromResult(1/2/3)</code> en parallèle avec <code>Task.WhenAll</code>, somme et affichez.",
    code_template: "using System;\nusing System.Threading.Tasks;\nclass P {\n  static async Task Main() {\n    // Task.WhenAll\n  }\n}",
    solution: "using System;\nusing System.Threading.Tasks;\nclass P {\n  static async Task Main() {\n    int[] results = await Task.WhenAll(Task.FromResult(1), Task.FromResult(2), Task.FromResult(3));\n    Console.WriteLine(results.Sum());\n  }\n}",
    tests: [{ expected: "Task.WhenAll", type: "contains" }],
  },
  {
    id: "cs_183",
    type: "code",
    category: "Async avancé",
    title: "Task.WhenAny",
    description: "La 1re qui finit.",
    instruction: "Avec <code>Task.WhenAny</code>, attendez la 1re terminée parmi 3 tâches. Affichez son résultat.",
    code_template: "using System;\nusing System.Threading.Tasks;\nclass P {\n  static async Task Main() {\n    // WhenAny\n  }\n}",
    solution: "using System;\nusing System.Threading.Tasks;\nclass P {\n  static async Task Main() {\n    var t = await Task.WhenAny(Task.FromResult(\"A\"), Task.FromResult(\"B\"));\n    Console.WriteLine(t.Result);\n  }\n}",
    tests: [{ expected: "Task.WhenAny", type: "contains" }],
  },
  {
    id: "cs_184",
    type: "code",
    category: "Async avancé",
    title: "CancellationToken",
    description: "Annuler une opération.",
    instruction: "Créez un <code>CancellationTokenSource</code>, passez son Token à une tâche, cancellez après 100ms.",
    code_template: "using System;\nusing System.Threading;\nusing System.Threading.Tasks;\nclass P {\n  static async Task Main() {\n    // CTS\n  }\n}",
    solution: "using System;\nusing System.Threading;\nusing System.Threading.Tasks;\nclass P {\n  static async Task Main() {\n    var cts = new CancellationTokenSource();\n    cts.CancelAfter(100);\n    try {\n      await Task.Delay(1000, cts.Token);\n    } catch (OperationCanceledException) {\n      Console.WriteLine(\"annulé\");\n    }\n  }\n}",
    tests: [{ expected: "CancellationTokenSource", type: "contains" }, { expected: "CancelAfter", type: "contains" }],
  },
  {
    id: "cs_185",
    type: "code",
    category: "Async avancé",
    title: "ConfigureAwait(false)",
    description: "Ne pas re-capturer le contexte.",
    instruction: "Sur une bibliothèque, awaitez <code>Task.Delay(100).ConfigureAwait(false)</code> pour éviter de re-capturer le SynchronizationContext.",
    code_template: "using System.Threading.Tasks;\nasync Task Lib() {\n  // ConfigureAwait\n}",
    solution: "using System.Threading.Tasks;\nasync Task Lib() {\n  await Task.Delay(100).ConfigureAwait(false);\n}",
    tests: [{ expected: "ConfigureAwait(false)", type: "contains" }],
  },
  {
    id: "cs_186",
    type: "code",
    category: "Async avancé",
    title: "ValueTask",
    description: "Alternative légère à Task.",
    instruction: "Définissez une méthode async <code>ValueTask&lt;int&gt; GetCachedAsync</code> qui retourne immédiatement la valeur 42 sans allouer.",
    code_template: "using System.Threading.Tasks;\nasync ValueTask<int> GetCachedAsync() {\n  // \n}",
    solution: "using System.Threading.Tasks;\nasync ValueTask<int> GetCachedAsync() {\n  return 42;\n}",
    tests: [{ expected: "ValueTask", type: "contains" }],
  },
  {
    id: "cs_187",
    type: "code",
    category: "Async avancé",
    title: "IAsyncEnumerable",
    description: "Stream async.",
    instruction: "Définissez une méthode <code>async IAsyncEnumerable&lt;int&gt; Stream()</code> qui yield return 1, 2, 3. Itérez avec <code>await foreach</code>.",
    code_template: "using System;\nusing System.Collections.Generic;\nusing System.Threading.Tasks;\nasync IAsyncEnumerable<int> Stream() {\n  // yield return\n}",
    solution: "using System;\nusing System.Collections.Generic;\nusing System.Threading.Tasks;\nasync IAsyncEnumerable<int> Stream() {\n  yield return 1;\n  await Task.Yield();\n  yield return 2;\n  yield return 3;\n}\nasync Task Main() {\n  await foreach (var x in Stream()) Console.WriteLine(x);\n}",
    tests: [{ expected: "IAsyncEnumerable", type: "contains" }, { expected: "yield return", type: "contains" }, { expected: "await foreach", type: "contains" }],
  },
  {
    id: "cs_188",
    type: "code",
    category: "Async avancé",
    title: "Parallel.For",
    description: "Boucle parallèle CPU-bound.",
    instruction: "Utilisez <code>Parallel.For(0, 10, i => ...)</code> pour faire un calcul léger en parallèle.",
    code_template: "using System.Threading.Tasks;\n// Parallel.For\n",
    solution: "using System;\nusing System.Threading.Tasks;\nParallel.For(0, 10, i => {\n  Console.WriteLine($\"i={i}\");\n});",
    tests: [{ expected: "Parallel.For", type: "contains" }],
  },
  {
    id: "cs_189",
    type: "code",
    category: "Async avancé",
    title: "Parallel.ForEach",
    description: "ForEach parallèle.",
    instruction: "Avec <code>Parallel.ForEach</code> sur <code>{1,2,3,4,5}</code>, loggez chaque valeur.",
    code_template: "using System.Threading.Tasks;\nvar nums = new[] {1,2,3,4,5};\n// Parallel.ForEach\n",
    solution: "using System;\nusing System.Threading.Tasks;\nvar nums = new[] {1,2,3,4,5};\nParallel.ForEach(nums, n => Console.WriteLine(n));",
    tests: [{ expected: "Parallel.ForEach", type: "contains" }],
  },
  {
    id: "cs_190",
    type: "code",
    category: "Async avancé",
    title: "AsParallel (PLINQ)",
    description: "LINQ parallèle.",
    instruction: "Avec <code>.AsParallel()</code>, doublez les nombres de 1 à 1000.",
    code_template: "using System.Linq;\nvar nums = Enumerable.Range(1, 1000);\n// AsParallel\n",
    solution: "using System;\nusing System.Linq;\nvar nums = Enumerable.Range(1, 1000);\nvar doubled = nums.AsParallel().Select(x => x * 2).ToArray();\nConsole.WriteLine(doubled.Length);",
    tests: [{ expected: "AsParallel", type: "contains" }],
  },
  {
    id: "cs_191",
    type: "code",
    category: "Async avancé",
    title: "lock",
    description: "Mutex simple.",
    instruction: "Protégez un accès partagé avec <code>lock(_lock)</code> et un objet <code>_lock</code>.",
    code_template: "object _lock = new object();\nint counter = 0;\nvoid Inc() {\n  // lock\n}",
    solution: "object _lock = new object();\nint counter = 0;\nvoid Inc() {\n  lock (_lock) {\n    counter++;\n  }\n}",
    tests: [{ expected: "lock (", type: "contains" }],
  },
  {
    id: "cs_192",
    type: "code",
    category: "Async avancé",
    title: "SemaphoreSlim",
    description: "Limiter la concurrence.",
    instruction: "Créez un <code>SemaphoreSlim(3)</code> pour limiter à 3 opérations simultanées.",
    code_template: "using System.Threading;\nvar sem = /* */;\nasync Task Work() {\n  await sem.WaitAsync();\n  try { /* */ }\n  finally { sem.Release(); }\n}",
    solution: "using System.Threading;\nusing System.Threading.Tasks;\nvar sem = new SemaphoreSlim(3);\nasync Task Work() {\n  await sem.WaitAsync();\n  try {\n    await Task.Delay(100);\n  }\n  finally { sem.Release(); }\n}",
    tests: [{ expected: "SemaphoreSlim", type: "contains" }, { expected: "WaitAsync", type: "contains" }],
  },
  {
    id: "cs_193",
    type: "code",
    category: "Async avancé",
    title: "Interlocked.Increment",
    description: "Incrément atomique.",
    instruction: "Utilisez <code>Interlocked.Increment(ref counter)</code> pour un compteur thread-safe sans lock.",
    code_template: "using System.Threading;\nint counter = 0;\nvoid Inc() {\n  // Interlocked\n}",
    solution: "using System.Threading;\nint counter = 0;\nvoid Inc() {\n  Interlocked.Increment(ref counter);\n}",
    tests: [{ expected: "Interlocked.Increment", type: "contains" }],
  },
  {
    id: "cs_194",
    type: "code",
    category: "Async avancé",
    title: "ConcurrentDictionary",
    description: "Dict thread-safe.",
    instruction: "Créez un <code>ConcurrentDictionary&lt;string, int&gt;</code>, ajoutez puis affichez la valeur 'x'.",
    code_template: "using System.Collections.Concurrent;\n",
    solution: "using System;\nusing System.Collections.Concurrent;\nvar d = new ConcurrentDictionary<string, int>();\nd[\"x\"] = 42;\nConsole.WriteLine(d[\"x\"]);",
    tests: [{ expected: "ConcurrentDictionary", type: "contains" }],
  },
  {
    id: "cs_195",
    type: "code",
    category: "Async avancé",
    title: "Channel",
    description: "Producer/consumer.",
    instruction: "Créez un <code>Channel&lt;int&gt;</code>. Producteur écrit 1,2,3, consommateur lit avec <code>WaitToReadAsync</code>.",
    code_template: "using System.Threading.Channels;\nusing System.Threading.Tasks;\nvar ch = /* */;\n// producer + consumer\n",
    solution: "using System;\nusing System.Threading.Channels;\nusing System.Threading.Tasks;\nvar ch = Channel.CreateUnbounded<int>();\nawait ch.Writer.WriteAsync(1);\nawait ch.Writer.WriteAsync(2);\nawait ch.Writer.WriteAsync(3);\nch.Writer.Complete();\nawait foreach (var v in ch.Reader.ReadAllAsync()) Console.WriteLine(v);",
    tests: [{ expected: "Channel.CreateUnbounded", type: "contains" }, { expected: "ReadAllAsync", type: "contains" }],
  },
  {
    id: "cs_196",
    type: "code",
    category: "Async avancé",
    title: "Exception async",
    description: "try/catch dans async.",
    instruction: "Une méthode async qui throw, captée par try/catch dans l'appelant.",
    code_template: "using System;\nusing System.Threading.Tasks;\nasync Task Fail() { throw new Exception(\"KO\"); }\nasync Task Main() {\n  try { /* */ } catch (Exception e) { /* */ }\n}",
    solution: "using System;\nusing System.Threading.Tasks;\nasync Task Fail() { throw new Exception(\"KO\"); }\nasync Task Main() {\n  try {\n    await Fail();\n  } catch (Exception e) {\n    Console.WriteLine(e.Message);\n  }\n}",
    tests: [{ expected: "try {", type: "contains" }, { expected: "catch (Exception", type: "contains" }],
  },
  {
    id: "cs_197",
    type: "code",
    category: "Async avancé",
    title: "AggregateException",
    description: "WhenAll groupe les exceptions.",
    instruction: "Avec <code>Task.WhenAll</code> sur 2 tâches qui throw, captez <code>AggregateException</code>.",
    code_template: "using System;\nusing System.Threading.Tasks;\nasync Task Main() {\n  var t1 = Task.Run(() => { throw new Exception(\"A\"); });\n  var t2 = Task.Run(() => { throw new Exception(\"B\"); });\n  try { /* */ } catch (Exception e) { /* */ }\n}",
    solution: "using System;\nusing System.Threading.Tasks;\nasync Task Main() {\n  var t1 = Task.Run(() => { throw new Exception(\"A\"); });\n  var t2 = Task.Run(() => { throw new Exception(\"B\"); });\n  try { await Task.WhenAll(t1, t2); }\n  catch (Exception) {\n    foreach (var e in new[] {t1.Exception, t2.Exception}) Console.WriteLine(e?.InnerException?.Message);\n  }\n}",
    tests: [{ expected: "Task.WhenAll", type: "contains" }, { expected: "Exception", type: "contains" }],
  },
  {
    id: "cs_198",
    type: "code",
    category: "Async avancé",
    title: "async void — anti-pattern",
    description: "À éviter sauf event handlers.",
    instruction: "Convertissez <code>async void Handler()</code> en <code>async Task Handler()</code> (le bon pattern).",
    code_template: "async void Handler() {\n  // \n}",
    solution: "using System.Threading.Tasks;\nasync Task Handler() {\n  await Task.Delay(100);\n}",
    tests: [{ expected: "async Task", type: "contains" }],
  },
  {
    id: "cs_199",
    type: "code",
    category: "Async avancé",
    title: "Task.Delay",
    description: "Attente non-bloquante.",
    instruction: "Attendez 500ms avec <code>await Task.Delay(500)</code> puis loggez 'fin'.",
    code_template: "using System;\nusing System.Threading.Tasks;\nasync Task Main() {\n  // Delay\n}",
    solution: "using System;\nusing System.Threading.Tasks;\nasync Task Main() {\n  await Task.Delay(500);\n  Console.WriteLine(\"fin\");\n}",
    tests: [{ expected: "Task.Delay", type: "contains" }],
  },
  {
    id: "cs_200",
    type: "code",
    category: "Async avancé",
    title: "Task.FromResult",
    description: "Tâche déjà résolue.",
    instruction: "Retournez <code>Task.FromResult(42)</code> depuis une méthode <code>Task&lt;int&gt;</code>.",
    code_template: "using System.Threading.Tasks;\nTask<int> Get42() {\n  // \n}",
    solution: "using System.Threading.Tasks;\nTask<int> Get42() => Task.FromResult(42);",
    tests: [{ expected: "Task.FromResult", type: "contains" }],
  },
  {
    id: "cs_201",
    type: "code",
    category: "Async avancé",
    title: "HttpClient async",
    description: "Requête HTTP.",
    instruction: "Avec <code>HttpClient</code>, faites GET sur <code>https://example.com</code> et loggez le status.",
    code_template: "using System;\nusing System.Net.Http;\nusing System.Threading.Tasks;\nstatic readonly HttpClient http = new HttpClient();\nasync Task Main() {\n  // GET\n}",
    solution: "using System;\nusing System.Net.Http;\nusing System.Threading.Tasks;\nstatic readonly HttpClient http = new HttpClient();\nasync Task Main() {\n  var res = await http.GetAsync(\"https://example.com\");\n  Console.WriteLine(res.StatusCode);\n}",
    tests: [{ expected: "HttpClient", type: "contains" }, { expected: "GetAsync", type: "contains" }],
  },
  {
    id: "cs_202",
    type: "code",
    category: "Async avancé",
    title: "TaskCompletionSource",
    description: "Promesse manuelle.",
    instruction: "Créez un <code>TaskCompletionSource&lt;int&gt;</code>, settez son result à 42 plus tard et await.",
    code_template: "using System.Threading.Tasks;\nasync Task Main() {\n  var tcs = /* */;\n  // SetResult\n  // await\n}",
    solution: "using System;\nusing System.Threading.Tasks;\nasync Task Main() {\n  var tcs = new TaskCompletionSource<int>();\n  tcs.SetResult(42);\n  Console.WriteLine(await tcs.Task);\n}",
    tests: [{ expected: "TaskCompletionSource", type: "contains" }, { expected: "SetResult", type: "contains" }],
  },
  {
    id: "cs_203",
    type: "code",
    category: "Async avancé",
    title: "Threading.Thread",
    description: "Thread bas niveau.",
    instruction: "Créez un <code>new Thread(() => ...)</code> qui log 'hello', démarrez-le et joinez.",
    code_template: "using System.Threading;\n// Thread\n",
    solution: "using System;\nusing System.Threading;\nvar t = new Thread(() => Console.WriteLine(\"hello\"));\nt.Start();\nt.Join();",
    tests: [{ expected: "new Thread", type: "contains" }, { expected: ".Start()", type: "contains" }],
  },
  {
    id: "cs_204",
    type: "code",
    category: "Async avancé",
    title: "ThreadLocal",
    description: "Storage par thread.",
    instruction: "Définissez un <code>ThreadLocal&lt;int&gt;</code> avec valeur initiale par thread = thread ID.",
    code_template: "using System.Threading;\n// ThreadLocal\n",
    solution: "using System;\nusing System.Threading;\nvar tl = new ThreadLocal<int>(() => Thread.CurrentThread.ManagedThreadId);\nConsole.WriteLine(tl.Value);",
    tests: [{ expected: "ThreadLocal", type: "contains" }],
  },
  {
    id: "cs_205",
    type: "code",
    category: "Async avancé",
    title: "BlockingCollection",
    description: "Producer/consumer thread-safe.",
    instruction: "Créez un <code>BlockingCollection&lt;int&gt;</code>, ajoutez 1,2,3, complétez puis itérez avec <code>GetConsumingEnumerable</code>.",
    code_template: "using System.Collections.Concurrent;\n// BlockingCollection\n",
    solution: "using System;\nusing System.Collections.Concurrent;\nvar bc = new BlockingCollection<int>();\nbc.Add(1); bc.Add(2); bc.Add(3);\nbc.CompleteAdding();\nforeach (var v in bc.GetConsumingEnumerable()) Console.WriteLine(v);",
    tests: [{ expected: "BlockingCollection", type: "contains" }, { expected: "CompleteAdding", type: "contains" }],
  },
];

addExercises("csharp", exercises);
