import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/**
 * C# — Part 9 : patterns avancés (records, pattern matching, génériques, DI).
 */
const exercises: Exercise[] = [
  {
    id: "cs_206",
    type: "code",
    category: "Records",
    title: "Record class",
    description: "Type immuable avec valeur par défaut.",
    instruction: "Définissez <code>record Person(string Name, int Age)</code> et créez une instance.",
    code_template: "// record\n",
    solution: "using System;\npublic record Person(string Name, int Age);\nvar p = new Person(\"Aelita\", 13);\nConsole.WriteLine(p);",
    tests: [{ expected: "record Person", type: "contains" }],
  },
  {
    id: "cs_207",
    type: "code",
    category: "Records",
    title: "Record with",
    description: "Cloner avec modifs.",
    instruction: "À partir d'un <code>Person</code>, créez une copie avec un nouveau Name via <code>with</code>.",
    code_template: "using System;\npublic record Person(string Name, int Age);\nvar p1 = new Person(\"Aelita\", 13);\n// with\n",
    solution: "using System;\npublic record Person(string Name, int Age);\nvar p1 = new Person(\"Aelita\", 13);\nvar p2 = p1 with { Name = \"Yumi\" };\nConsole.WriteLine(p2);",
    tests: [{ expected: "with", type: "contains" }],
  },
  {
    id: "cs_208",
    type: "code",
    category: "Pattern Matching",
    title: "switch expression",
    description: "Pattern matching moderne.",
    instruction: "Avec un switch expression sur un <code>int</code>, retournez 'petit'/'moyen'/'grand' selon &lt; 10, &lt; 100, sinon.",
    code_template: "string Size(int n) {\n  // switch expr\n}",
    solution: "string Size(int n) => n switch {\n  < 10 => \"petit\",\n  < 100 => \"moyen\",\n  _ => \"grand\"\n};",
    tests: [{ expected: "switch {", type: "contains" }, { expected: "=>", type: "contains" }],
  },
  {
    id: "cs_209",
    type: "code",
    category: "Pattern Matching",
    title: "Type pattern",
    description: "Switch sur type.",
    instruction: "Avec switch expression, retournez la description selon le type (int → 'entier', string → 'chaîne', _ → 'autre').",
    code_template: "string Describe(object o) {\n  // switch on type\n}",
    solution: "string Describe(object o) => o switch {\n  int => \"entier\",\n  string => \"chaîne\",\n  _ => \"autre\"\n};",
    tests: [{ expected: "switch", type: "contains" }, { expected: "int =>", type: "contains" }],
  },
  {
    id: "cs_210",
    type: "code",
    category: "Pattern Matching",
    title: "Property pattern",
    description: "Matcher sur propriétés.",
    instruction: "Définissez <code>IsAdult(Person p)</code> qui retourne true si <code>p is {Age: &gt;= 18}</code>.",
    code_template: "public record Person(string Name, int Age);\nbool IsAdult(Person p) {\n  // \n}",
    solution: "public record Person(string Name, int Age);\nbool IsAdult(Person p) => p is { Age: >= 18 };",
    tests: [{ expected: "{ Age:", type: "contains" }],
  },
  {
    id: "cs_211",
    type: "code",
    category: "Pattern Matching",
    title: "Tuple pattern",
    description: "Switch sur tuple.",
    instruction: "Selon (x, y), retournez 'origin' si (0,0), 'x-axis' si y=0, 'y-axis' si x=0, sinon 'free'.",
    code_template: "string Where(int x, int y) {\n  // switch (x, y)\n}",
    solution: "string Where(int x, int y) => (x, y) switch {\n  (0, 0) => \"origin\",\n  (_, 0) => \"x-axis\",\n  (0, _) => \"y-axis\",\n  _ => \"free\"\n};",
    tests: [{ expected: "switch", type: "contains" }, { expected: "(0, 0)", type: "contains" }],
  },
  {
    id: "cs_212",
    type: "code",
    category: "Génériques",
    title: "Méthode générique",
    description: "T générique.",
    instruction: "Définissez <code>T Identity&lt;T&gt;(T x)</code> qui retourne x. Testez avec int et string.",
    code_template: "T Identity<T>(T x) {\n  // \n}",
    solution: "using System;\nT Identity<T>(T x) => x;\nConsole.WriteLine(Identity(42));\nConsole.WriteLine(Identity(\"hello\"));",
    tests: [{ expected: "<T>(T x)", type: "contains" }],
  },
  {
    id: "cs_213",
    type: "code",
    category: "Génériques",
    title: "Generic constraint",
    description: "where T : ...",
    instruction: "Définissez <code>T Max&lt;T&gt;(T a, T b) where T : IComparable&lt;T&gt;</code>.",
    code_template: "using System;\nT Max<T>(T a, T b) where T : IComparable<T> {\n  // \n}",
    solution: "using System;\nT Max<T>(T a, T b) where T : IComparable<T> => a.CompareTo(b) >= 0 ? a : b;\nConsole.WriteLine(Max(3, 7));",
    tests: [{ expected: "where T : IComparable", type: "contains" }],
  },
  {
    id: "cs_214",
    type: "code",
    category: "Génériques",
    title: "Classe générique",
    description: "Conteneur générique.",
    instruction: "Définissez <code>class Box&lt;T&gt;</code> avec un attribut Value et une méthode Get.",
    code_template: "class Box<T> {\n  // \n}",
    solution: "using System;\nclass Box<T> {\n  public T Value;\n  public T Get() => Value;\n}\nvar b = new Box<int> { Value = 42 };\nConsole.WriteLine(b.Get());",
    tests: [{ expected: "class Box<T>", type: "contains" }],
  },
  {
    id: "cs_215",
    type: "code",
    category: "Génériques",
    title: "Covariance",
    description: "out T (covariant).",
    instruction: "Définissez <code>interface IReader&lt;out T&gt;</code> avec une méthode <code>T Read()</code>.",
    code_template: "interface IReader<out T> {\n  // \n}",
    solution: "interface IReader<out T> {\n  T Read();\n}",
    tests: [{ expected: "<out T>", type: "contains" }],
  },
  {
    id: "cs_216",
    type: "code",
    category: "Génériques",
    title: "Contravariance",
    description: "in T (contravariant).",
    instruction: "Définissez <code>interface IWriter&lt;in T&gt;</code> avec une méthode <code>void Write(T x)</code>.",
    code_template: "interface IWriter<in T> {\n  // \n}",
    solution: "interface IWriter<in T> {\n  void Write(T x);\n}",
    tests: [{ expected: "<in T>", type: "contains" }],
  },
  {
    id: "cs_217",
    type: "code",
    category: "Design Patterns",
    title: "Singleton thread-safe",
    description: "Lazy<T> en Singleton.",
    instruction: "Créez <code>class Singleton</code> avec <code>private static readonly Lazy&lt;Singleton&gt; _instance</code>.",
    code_template: "using System;\npublic sealed class Singleton {\n  // _instance + Instance property\n}",
    solution: "using System;\npublic sealed class Singleton {\n  private static readonly Lazy<Singleton> _instance = new(() => new Singleton());\n  public static Singleton Instance => _instance.Value;\n  private Singleton() {}\n}",
    tests: [{ expected: "Lazy<Singleton>", type: "contains" }, { expected: "static Singleton Instance", type: "contains" }],
  },
  {
    id: "cs_218",
    type: "code",
    category: "Design Patterns",
    title: "Factory",
    description: "Création centralisée.",
    instruction: "Définissez interface <code>IAnimal</code> et <code>AnimalFactory.Create(string type)</code> qui retourne Chien ou Chat.",
    code_template: "// IAnimal + factory\n",
    solution: "public interface IAnimal { string Speak(); }\npublic class Chien : IAnimal { public string Speak() => \"wouf\"; }\npublic class Chat : IAnimal { public string Speak() => \"miaou\"; }\npublic static class AnimalFactory {\n  public static IAnimal Create(string type) => type switch {\n    \"chien\" => new Chien(),\n    \"chat\" => new Chat(),\n    _ => throw new ArgumentException()\n  };\n}",
    tests: [{ expected: "IAnimal", type: "contains" }, { expected: "AnimalFactory", type: "contains" }],
  },
  {
    id: "cs_219",
    type: "code",
    category: "Design Patterns",
    title: "Strategy",
    description: "Algo interchangeable.",
    instruction: "Interface <code>ISortStrategy</code>, classes <code>BubbleSort</code> et <code>QuickSort</code>, <code>Context</code> qui prend une stratégie.",
    code_template: "// strategy\n",
    solution: "public interface ISortStrategy { void Sort(int[] arr); }\npublic class BubbleSort : ISortStrategy { public void Sort(int[] arr) {} }\npublic class QuickSort : ISortStrategy { public void Sort(int[] arr) {} }\npublic class Context {\n  private readonly ISortStrategy _strategy;\n  public Context(ISortStrategy s) => _strategy = s;\n  public void Run(int[] arr) => _strategy.Sort(arr);\n}",
    tests: [{ expected: "ISortStrategy", type: "contains" }, { expected: "Context", type: "contains" }],
  },
  {
    id: "cs_220",
    type: "code",
    category: "Design Patterns",
    title: "Repository pattern",
    description: "Abstraction d'accès aux données.",
    instruction: "Interface <code>IUserRepository</code> avec <code>GetById</code>, <code>Add</code>. Classe <code>InMemoryUserRepository</code> implémentant.",
    code_template: "// IUserRepository\n",
    solution: "using System.Collections.Generic;\npublic record User(int Id, string Name);\npublic interface IUserRepository {\n  User? GetById(int id);\n  void Add(User u);\n}\npublic class InMemoryUserRepository : IUserRepository {\n  private readonly Dictionary<int, User> _store = new();\n  public User? GetById(int id) => _store.TryGetValue(id, out var u) ? u : null;\n  public void Add(User u) => _store[u.Id] = u;\n}",
    tests: [{ expected: "IUserRepository", type: "contains" }, { expected: "GetById", type: "contains" }],
  },
  {
    id: "cs_221",
    type: "code",
    category: "Design Patterns",
    title: "Observer",
    description: "Pub/sub via events.",
    instruction: "Class <code>Publisher</code> avec event <code>OnEvent</code>. Abonnez-vous puis raise.",
    code_template: "using System;\npublic class Publisher {\n  // event OnEvent\n  public void Raise() {\n    // \n  }\n}",
    solution: "using System;\npublic class Publisher {\n  public event Action<string>? OnEvent;\n  public void Raise() {\n    OnEvent?.Invoke(\"hello\");\n  }\n}\nvar p = new Publisher();\np.OnEvent += msg => Console.WriteLine(msg);\np.Raise();",
    tests: [{ expected: "event Action", type: "contains" }, { expected: "OnEvent?", type: "contains" }],
  },
  {
    id: "cs_222",
    type: "code",
    category: "Design Patterns",
    title: "Builder fluide",
    description: "Chaîner les setters.",
    instruction: "Class <code>UrlBuilder</code> avec <code>SetHost</code>, <code>SetPort</code>, <code>Build</code>, retournant l'objet pour chainage.",
    code_template: "public class UrlBuilder {\n  // \n}",
    solution: "public class UrlBuilder {\n  private string _host = \"\", _port = \"\";\n  public UrlBuilder SetHost(string h) { _host = h; return this; }\n  public UrlBuilder SetPort(string p) { _port = p; return this; }\n  public string Build() => $\"http://{_host}:{_port}\";\n}",
    tests: [{ expected: "return this", type: "contains" }, { expected: "Build()", type: "contains" }],
  },
  {
    id: "cs_223",
    type: "code",
    category: "Records",
    title: "Record struct",
    description: "Record stack-allocated.",
    instruction: "Définissez <code>record struct Point(int X, int Y)</code> et créez une instance.",
    code_template: "// record struct\n",
    solution: "using System;\npublic record struct Point(int X, int Y);\nvar p = new Point(3, 4);\nConsole.WriteLine(p);",
    tests: [{ expected: "record struct Point", type: "contains" }],
  },
  {
    id: "cs_224",
    type: "code",
    category: "Records",
    title: "Record inheritance",
    description: "Hierarchie de records.",
    instruction: "Définissez <code>record Animal(string Name)</code> et <code>record Dog(string Name, string Breed) : Animal(Name)</code>.",
    code_template: "// records\n",
    solution: "public record Animal(string Name);\npublic record Dog(string Name, string Breed) : Animal(Name);",
    tests: [{ expected: "Dog(string Name", type: "contains" }, { expected: ") : Animal", type: "contains" }],
  },
  {
    id: "cs_225",
    type: "code",
    category: "Extensions",
    title: "Méthode d'extension",
    description: "Étendre une classe existante.",
    instruction: "Définissez une extension <code>IsPalindrome(this string s)</code> et testez sur 'level'.",
    code_template: "using System;\npublic static class StringExt {\n  // \n}",
    solution: "using System;\nusing System.Linq;\npublic static class StringExt {\n  public static bool IsPalindrome(this string s) {\n    return s.SequenceEqual(s.Reverse());\n  }\n}\nConsole.WriteLine(\"level\".IsPalindrome());",
    tests: [{ expected: "this string s", type: "contains" }, { expected: "static", type: "contains" }],
  },
  {
    id: "cs_226",
    type: "code",
    category: "Nullable",
    title: "Nullable reference types",
    description: "#nullable enable.",
    instruction: "Avec <code>#nullable enable</code>, déclarez <code>string? maybeName = null</code> et utilisez <code>?.</code> pour appeler ToUpper.",
    code_template: "#nullable enable\nstring? maybeName = null;\n// .ToUpper sûr\n",
    solution: "#nullable enable\nusing System;\nstring? maybeName = null;\nConsole.WriteLine(maybeName?.ToUpper() ?? \"vide\");",
    tests: [{ expected: "string?", type: "contains" }, { expected: "?.", type: "contains" }],
  },
  {
    id: "cs_227",
    type: "code",
    category: "Pattern Matching",
    title: "Relational pattern",
    description: ">, <, >=, <= dans switch.",
    instruction: "Avec switch expr sur un int, retournez 'négatif' (&lt; 0), 'zéro' (== 0), 'positif' (&gt; 0).",
    code_template: "string Sign(int n) {\n  // switch\n}",
    solution: "string Sign(int n) => n switch {\n  < 0 => \"négatif\",\n  0 => \"zéro\",\n  > 0 => \"positif\"\n};",
    tests: [{ expected: "< 0", type: "contains" }, { expected: "> 0", type: "contains" }],
  },
  {
    id: "cs_228",
    type: "code",
    category: "Pattern Matching",
    title: "List pattern (C# 11+)",
    description: "Matcher un tableau.",
    instruction: "Avec switch expr, retournez 'empty' pour <code>[]</code>, 'single' pour <code>[_]</code>, 'multi' pour <code>[_, .., _]</code>.",
    code_template: "string Describe(int[] arr) {\n  // \n}",
    solution: "string Describe(int[] arr) => arr switch {\n  [] => \"empty\",\n  [_] => \"single\",\n  [_, .., _] => \"multi\",\n  _ => \"?\"\n};",
    tests: [{ expected: "[]", type: "contains" }, { expected: "[_]", type: "contains" }],
  },
  {
    id: "cs_229",
    type: "code",
    category: "Génériques",
    title: "Default constraint",
    description: "where T : new()",
    instruction: "Définissez <code>T Create&lt;T&gt;() where T : new()</code> qui retourne <code>new T()</code>.",
    code_template: "T Create<T>() where T : new() {\n  // \n}",
    solution: "T Create<T>() where T : new() => new T();",
    tests: [{ expected: "where T : new()", type: "contains" }],
  },
  {
    id: "cs_230",
    type: "code",
    category: "Génériques",
    title: "Generic method overload",
    description: "Sélection de surcharge.",
    instruction: "Surchargez <code>Print&lt;T&gt;(T x)</code> avec deux versions : générique et <code>Print(int x)</code> spécialisée.",
    code_template: "using System;\nvoid Print<T>(T x) { Console.WriteLine(\"générique:\" + x); }\n// surcharge int\n",
    solution: "using System;\nvoid Print<T>(T x) { Console.WriteLine(\"générique:\" + x); }\nvoid Print(int x) { Console.WriteLine(\"int:\" + x); }\nPrint(42);\nPrint(\"hello\");",
    tests: [{ expected: "Print<T>", type: "contains" }, { expected: "Print(int", type: "contains" }],
  },
];

addExercises("csharp", exercises);
