import { addExercises } from "./registry";
import type { Exercise } from "./registry";

const exercises: Exercise[] = [
  { id: "dart_201", type: "code", category: "Async", title: "async/await", description: "Attendre un Future.", instruction: "Écrivez une fonction async qui await <code>Future.value(42)</code> et l'affiche.", code_template: "Future<void> main() async {\n  // \n}", solution: "Future<void> main() async {\n  final v = await Future.value(42);\n  print(v);\n}", tests: [{ expected: "async", type: "contains" }, { expected: "await", type: "contains" }] },
  { id: "dart_202", type: "code", category: "Async", title: "Future.delayed", description: "Délai async.", instruction: "Avec <code>Future.delayed(Duration(seconds: 1))</code>, attendez 1 seconde.", code_template: "Future<void> main() async {\n  // \n}", solution: "Future<void> main() async {\n  await Future.delayed(Duration(seconds: 1));\n  print('fait');\n}", tests: [{ expected: "Future.delayed", type: "contains" }] },
  { id: "dart_203", type: "code", category: "Async", title: "Future.wait (parallèle)", description: "Plusieurs Futures en parallèle.", instruction: "Avec <code>Future.wait([f1, f2])</code>, attendez 2 futures simultanément.", code_template: "Future<void> main() async {\n  final f1 = Future.value(1);\n  final f2 = Future.value(2);\n  // wait\n}", solution: "Future<void> main() async {\n  final f1 = Future.value(1);\n  final f2 = Future.value(2);\n  final results = await Future.wait([f1, f2]);\n  print(results);\n}", tests: [{ expected: "Future.wait", type: "contains" }] },
  { id: "dart_204", type: "code", category: "Async", title: "try/catch async", description: "Exception async.", instruction: "Captez l'erreur d'un <code>Future.error</code> avec try/catch.", code_template: "Future<void> main() async {\n  try {\n    // \n  } catch (e) {\n    // \n  }\n}", solution: "Future<void> main() async {\n  try {\n    await Future.error('boom');\n  } catch (e) {\n    print('caught: $e');\n  }\n}", tests: [{ expected: "Future.error", type: "contains" }, { expected: "catch (e)", type: "contains" }] },
  { id: "dart_205", type: "code", category: "Streams", title: "Stream basique", description: "Souscrire à un stream.", instruction: "Avec <code>Stream.fromIterable([1,2,3])</code>, listen et affichez chaque valeur.", code_template: "void main() {\n  // stream\n}", solution: "void main() {\n  Stream.fromIterable([1, 2, 3]).listen((v) => print(v));\n}", tests: [{ expected: "Stream.fromIterable", type: "contains" }, { expected: ".listen", type: "contains" }] },
  { id: "dart_206", type: "code", category: "Streams", title: "Stream.periodic", description: "Stream à intervalle.", instruction: "<code>Stream.periodic(Duration(seconds: 1), (i) =&gt; i)</code> qui émet un compteur.", code_template: "// periodic\n", solution: "void main() {\n  Stream.periodic(Duration(seconds: 1), (i) => i).take(3).listen(print);\n}", tests: [{ expected: "Stream.periodic", type: "contains" }] },
  { id: "dart_207", type: "code", category: "Streams", title: "await for", description: "Consommer un stream avec for.", instruction: "Avec <code>await for (var v in stream)</code>, itérez.", code_template: "Future<void> main() async {\n  final s = Stream.fromIterable([1, 2, 3]);\n  // await for\n}", solution: "Future<void> main() async {\n  final s = Stream.fromIterable([1, 2, 3]);\n  await for (var v in s) print(v);\n}", tests: [{ expected: "await for", type: "contains" }] },
  { id: "dart_208", type: "code", category: "Streams", title: "StreamController", description: "Stream custom.", instruction: "Créez un <code>StreamController&lt;int&gt;</code>, add 1,2,3 puis close.", code_template: "import 'dart:async';\nvoid main() {\n  // \n}", solution: "import 'dart:async';\nvoid main() {\n  final controller = StreamController<int>();\n  controller.stream.listen(print);\n  controller.add(1); controller.add(2); controller.add(3);\n  controller.close();\n}", tests: [{ expected: "StreamController<int>", type: "contains" }, { expected: ".add(", type: "contains" }] },
  { id: "dart_209", type: "code", category: "Streams", title: "Stream.map", description: "Transformer un stream.", instruction: "Doublez chaque élément d'un stream avec <code>.map((v) =&gt; v * 2)</code>.", code_template: "void main() {\n  // \n}", solution: "void main() {\n  Stream.fromIterable([1, 2, 3]).map((v) => v * 2).listen(print);\n}", tests: [{ expected: ".map(", type: "contains" }] },
  { id: "dart_210", type: "code", category: "Streams", title: "Stream.where", description: "Filtrer un stream.", instruction: "Gardez les pairs d'un stream avec <code>.where((v) =&gt; v % 2 == 0)</code>.", code_template: "void main() {\n  // \n}", solution: "void main() {\n  Stream.fromIterable([1, 2, 3, 4, 5]).where((v) => v % 2 == 0).listen(print);\n}", tests: [{ expected: ".where(", type: "contains" }] },
  { id: "dart_211", type: "code", category: "Streams", title: "Broadcast stream", description: "Plusieurs listeners.", instruction: "Avec <code>StreamController.broadcast()</code>, autorisez plusieurs subscribers.", code_template: "import 'dart:async';\nvoid main() {\n  final c = /* */;\n}", solution: "import 'dart:async';\nvoid main() {\n  final c = StreamController<int>.broadcast();\n  c.stream.listen((v) => print('A: $v'));\n  c.stream.listen((v) => print('B: $v'));\n  c.add(1);\n}", tests: [{ expected: "StreamController<int>.broadcast", type: "contains" }] },
  { id: "dart_212", type: "code", category: "Streams", title: "yield (async*)", description: "Générer un stream.", instruction: "Définissez <code>Stream&lt;int&gt; gen() async* { yield 1; yield 2; }</code>.", code_template: "Stream<int> gen() async* {\n  // \n}", solution: "Stream<int> gen() async* {\n  yield 1;\n  yield 2;\n  yield 3;\n}", tests: [{ expected: "async*", type: "contains" }, { expected: "yield", type: "contains" }] },
  { id: "dart_213", type: "code", category: "Streams", title: "yield* (delegate)", description: "Déléguer à un autre stream.", instruction: "Avec <code>yield*</code>, déléguez à <code>otherStream</code>.", code_template: "Stream<int> wrapper() async* {\n  // yield*\n}", solution: "Stream<int> wrapper() async* {\n  yield* Stream.fromIterable([1, 2, 3]);\n}", tests: [{ expected: "yield*", type: "contains" }] },
  { id: "dart_214", type: "code", category: "Async", title: "Completer", description: "Créer un Future manuel.", instruction: "Créez un <code>Completer&lt;int&gt;</code> et completez-le avec 42.", code_template: "import 'dart:async';\nFuture<void> main() async {\n  final c = /* */;\n  // \n}", solution: "import 'dart:async';\nFuture<void> main() async {\n  final c = Completer<int>();\n  c.complete(42);\n  print(await c.future);\n}", tests: [{ expected: "Completer<int>", type: "contains" }, { expected: ".complete(", type: "contains" }] },
  { id: "dart_215", type: "code", category: "Async", title: "Future.then chain", description: "Chaîner sans await.", instruction: "Avec <code>.then</code>, chaînez 2 callbacks sur un Future.", code_template: "void main() {\n  // \n}", solution: "void main() {\n  Future.value(10).then((v) => v * 2).then(print);\n}", tests: [{ expected: ".then(", type: "contains" }] },
  { id: "dart_216", type: "code", category: "Isolates", title: "Isolate.spawn", description: "Vrai parallélisme.", instruction: "Lancez un Isolate avec <code>Isolate.spawn</code> qui exécute une fonction.", code_template: "import 'dart:isolate';\nvoid worker(SendPort sp) {\n  sp.send(42);\n}\nFuture<void> main() async {\n  // spawn\n}", solution: "import 'dart:isolate';\nvoid worker(SendPort sp) {\n  sp.send(42);\n}\nFuture<void> main() async {\n  final receivePort = ReceivePort();\n  await Isolate.spawn(worker, receivePort.sendPort);\n  print(await receivePort.first);\n}", tests: [{ expected: "Isolate.spawn", type: "contains" }] },
  { id: "dart_217", type: "code", category: "Isolates", title: "compute (Flutter helper)", description: "Isolate simplifié.", instruction: "Avec <code>compute(fn, arg)</code> de flutter/foundation, exécutez une fonction dans un isolate.", code_template: "import 'package:flutter/foundation.dart';\nint heavy(int x) => x * x;\nFuture<void> main() async {\n  // compute\n}", solution: "import 'package:flutter/foundation.dart';\nint heavy(int x) => x * x;\nFuture<void> main() async {\n  final r = await compute(heavy, 7);\n  print(r);\n}", tests: [{ expected: "compute(", type: "contains" }] },
  { id: "dart_218", type: "code", category: "HTTP", title: "http package GET", description: "Requête réseau.", instruction: "Avec <code>http.get(Uri.parse(...))</code>, faites un GET et parsez statusCode.", code_template: "import 'package:http/http.dart' as http;\nFuture<void> main() async {\n  // \n}", solution: "import 'package:http/http.dart' as http;\nFuture<void> main() async {\n  final res = await http.get(Uri.parse('https://example.com'));\n  print(res.statusCode);\n}", tests: [{ expected: "http.get", type: "contains" }, { expected: "Uri.parse", type: "contains" }] },
  { id: "dart_219", type: "code", category: "HTTP", title: "POST JSON", description: "Envoyer un body JSON.", instruction: "POST avec headers <code>'Content-Type': 'application/json'</code> et body <code>jsonEncode({'x': 1})</code>.", code_template: "import 'dart:convert';\nimport 'package:http/http.dart' as http;\nFuture<void> main() async {\n  // POST\n}", solution: "import 'dart:convert';\nimport 'package:http/http.dart' as http;\nFuture<void> main() async {\n  final res = await http.post(\n    Uri.parse('https://api.example.com'),\n    headers: {'Content-Type': 'application/json'},\n    body: jsonEncode({'x': 1}),\n  );\n  print(res.statusCode);\n}", tests: [{ expected: "http.post", type: "contains" }, { expected: "jsonEncode", type: "contains" }] },
  { id: "dart_220", type: "code", category: "JSON", title: "jsonDecode", description: "Parser une string JSON.", instruction: "Avec <code>jsonDecode</code>, parsez <code>'{\"name\":\"Aelita\"}'</code> et affichez le name.", code_template: "import 'dart:convert';\nvoid main() {\n  // \n}", solution: "import 'dart:convert';\nvoid main() {\n  final obj = jsonDecode('{\"name\":\"Aelita\"}');\n  print(obj['name']);\n}", tests: [{ expected: "jsonDecode", type: "contains" }] },
  { id: "dart_221", type: "code", category: "JSON", title: "fromJson / toJson", description: "Sérialisation objet.", instruction: "Définissez <code>class User</code> avec <code>fromJson</code> + <code>toJson</code>.", code_template: "class User {\n  final String name;\n  User(this.name);\n  // factory fromJson + toJson\n}", solution: "class User {\n  final String name;\n  User(this.name);\n  factory User.fromJson(Map<String, dynamic> j) => User(j['name']);\n  Map<String, dynamic> toJson() => {'name': name};\n}", tests: [{ expected: "fromJson", type: "contains" }, { expected: "toJson", type: "contains" }] },
  { id: "dart_222", type: "code", category: "Persistence", title: "shared_preferences", description: "Stockage clé-valeur local.", instruction: "Avec <code>SharedPreferences</code>, sauvez une string puis relisez-la.", code_template: "import 'package:shared_preferences/shared_preferences.dart';\nFuture<void> main() async {\n  // \n}", solution: "import 'package:shared_preferences/shared_preferences.dart';\nFuture<void> main() async {\n  final prefs = await SharedPreferences.getInstance();\n  await prefs.setString('name', 'Aelita');\n  print(prefs.getString('name'));\n}", tests: [{ expected: "SharedPreferences", type: "contains" }, { expected: "setString", type: "contains" }] },
  { id: "dart_223", type: "code", category: "Async", title: "Timer", description: "Tâche unique différée.", instruction: "Avec <code>Timer(Duration(seconds: 2), () =&gt; print('fired'))</code>, planifiez un callback.", code_template: "import 'dart:async';\nvoid main() {\n  // Timer\n}", solution: "import 'dart:async';\nvoid main() {\n  Timer(Duration(seconds: 2), () => print('fired'));\n}", tests: [{ expected: "Timer(", type: "contains" }] },
  { id: "dart_224", type: "code", category: "Async", title: "Timer.periodic", description: "Tâche récurrente.", instruction: "<code>Timer.periodic(Duration(seconds: 1), (t) =&gt; ...)</code>.", code_template: "import 'dart:async';\nvoid main() {\n  // \n}", solution: "import 'dart:async';\nvoid main() {\n  Timer.periodic(Duration(seconds: 1), (t) {\n    print('tick');\n    if (t.tick >= 3) t.cancel();\n  });\n}", tests: [{ expected: "Timer.periodic", type: "contains" }, { expected: ".cancel()", type: "contains" }] },
  { id: "dart_225", type: "code", category: "Streams", title: "Subscription cancel", description: "Désabonnement.", instruction: "Souscrivez à un stream et annulez après réception du 1er event.", code_template: "import 'dart:async';\nvoid main() {\n  // \n}", solution: "import 'dart:async';\nvoid main() {\n  late StreamSubscription sub;\n  sub = Stream.periodic(Duration(milliseconds: 100), (i) => i).listen((v) {\n    print(v);\n    sub.cancel();\n  });\n}", tests: [{ expected: "StreamSubscription", type: "contains" }, { expected: ".cancel()", type: "contains" }] },
];

addExercises("dart", exercises);
