import { addExercises } from "./registry";
import type { Exercise } from "./registry";

const exercises: Exercise[] = [
  { id: "dart_226", type: "code", category: "Animations", title: "AnimationController", description: "Contrôleur d'animation.", instruction: "Créez un <code>AnimationController</code> avec <code>vsync: this</code> et <code>duration: Duration(seconds: 1)</code>.", code_template: "import 'package:flutter/material.dart';\nclass MyState extends State<StatefulWidget> with SingleTickerProviderStateMixin {\n  late AnimationController controller;\n  @override\n  void initState() {\n    super.initState();\n    // controller\n  }\n  @override Widget build(BuildContext c) => Container();\n}", solution: "import 'package:flutter/material.dart';\nclass MyState extends State<StatefulWidget> with SingleTickerProviderStateMixin {\n  late AnimationController controller;\n  @override\n  void initState() {\n    super.initState();\n    controller = AnimationController(vsync: this, duration: Duration(seconds: 1));\n  }\n  @override Widget build(BuildContext c) => Container();\n}", tests: [{ expected: "AnimationController", type: "contains" }, { expected: "vsync: this", type: "contains" }] },
  { id: "dart_227", type: "code", category: "Animations", title: "Tween", description: "Interpoler une valeur.", instruction: "Avec <code>Tween&lt;double&gt;(begin: 0, end: 100)</code>, créez une animation pilotée par un controller.", code_template: "// Tween\n", solution: "final animation = Tween<double>(begin: 0, end: 100).animate(controller);", tests: [{ expected: "Tween<double>", type: "contains" }, { expected: ".animate(", type: "contains" }] },
  { id: "dart_228", type: "code", category: "Animations", title: "CurvedAnimation", description: "Courbe d'animation.", instruction: "Avec <code>CurvedAnimation(parent: controller, curve: Curves.easeInOut)</code>.", code_template: "// curve\n", solution: "final curved = CurvedAnimation(parent: controller, curve: Curves.easeInOut);", tests: [{ expected: "CurvedAnimation", type: "contains" }, { expected: "Curves.easeInOut", type: "contains" }] },
  { id: "dart_229", type: "code", category: "Animations", title: "AnimatedBuilder", description: "Reconstruire à chaque tick.", instruction: "Utilisez <code>AnimatedBuilder(animation: controller, builder: ...)</code>.", code_template: "// AnimatedBuilder\n", solution: "AnimatedBuilder(\n  animation: controller,\n  builder: (ctx, child) => Opacity(opacity: controller.value, child: child),\n  child: Text('hello'),\n);", tests: [{ expected: "AnimatedBuilder", type: "contains" }] },
  { id: "dart_230", type: "code", category: "Animations", title: "AnimatedContainer", description: "Animation implicite.", instruction: "Avec <code>AnimatedContainer(duration: ..., color: ...)</code>, animez la couleur.", code_template: "// AnimatedContainer\n", solution: "AnimatedContainer(\n  duration: Duration(milliseconds: 300),\n  color: expanded ? Colors.blue : Colors.red,\n);", tests: [{ expected: "AnimatedContainer", type: "contains" }] },
  { id: "dart_231", type: "code", category: "Animations", title: "AnimatedOpacity", description: "Fade implicite.", instruction: "Avec <code>AnimatedOpacity(opacity: 0.5, duration: ...)</code>.", code_template: "// AnimatedOpacity\n", solution: "AnimatedOpacity(\n  opacity: visible ? 1.0 : 0.0,\n  duration: Duration(milliseconds: 500),\n  child: Text('hello'),\n);", tests: [{ expected: "AnimatedOpacity", type: "contains" }] },
  { id: "dart_232", type: "code", category: "Animations", title: "Hero animation", description: "Transition partagée.", instruction: "Enveloppez un widget avec <code>Hero(tag: 'avatar', child: ...)</code> sur les 2 écrans.", code_template: "// Hero\n", solution: "Hero(tag: 'avatar', child: Image.network('url'));", tests: [{ expected: "Hero(tag:", type: "contains" }] },
  { id: "dart_233", type: "code", category: "Animations", title: "TweenAnimationBuilder", description: "Tween sans controller.", instruction: "Utilisez <code>TweenAnimationBuilder&lt;double&gt;</code> avec begin/end/duration.", code_template: "// TweenAnimationBuilder\n", solution: "TweenAnimationBuilder<double>(\n  tween: Tween(begin: 0, end: 1),\n  duration: Duration(seconds: 1),\n  builder: (ctx, value, child) => Opacity(opacity: value, child: child),\n  child: Text('hi'),\n);", tests: [{ expected: "TweenAnimationBuilder<double>", type: "contains" }] },
  { id: "dart_234", type: "code", category: "Animations", title: "SlideTransition", description: "Animation de translation.", instruction: "Utilisez <code>SlideTransition(position: animation, child: ...)</code>.", code_template: "// SlideTransition\n", solution: "SlideTransition(\n  position: Tween<Offset>(begin: Offset(-1, 0), end: Offset.zero).animate(controller),\n  child: Text('slide'),\n);", tests: [{ expected: "SlideTransition", type: "contains" }] },
  { id: "dart_235", type: "code", category: "Animations", title: "FadeTransition", description: "Fondu animé.", instruction: "Utilisez <code>FadeTransition(opacity: animation, child: ...)</code>.", code_template: "// FadeTransition\n", solution: "FadeTransition(\n  opacity: controller,\n  child: Text('fade'),\n);", tests: [{ expected: "FadeTransition", type: "contains" }] },
  { id: "dart_236", type: "code", category: "Animations", title: "RotationTransition", description: "Rotation animée.", instruction: "Utilisez <code>RotationTransition(turns: animation, child: ...)</code>.", code_template: "// RotationTransition\n", solution: "RotationTransition(\n  turns: controller,\n  child: Icon(Icons.refresh),\n);", tests: [{ expected: "RotationTransition", type: "contains" }] },
  { id: "dart_237", type: "code", category: "Animations", title: "ScaleTransition", description: "Mise à l'échelle.", instruction: "Utilisez <code>ScaleTransition(scale: animation, child: ...)</code>.", code_template: "// ScaleTransition\n", solution: "ScaleTransition(\n  scale: controller,\n  child: Text('scale'),\n);", tests: [{ expected: "ScaleTransition", type: "contains" }] },
  { id: "dart_238", type: "code", category: "Animations", title: "AnimatedList", description: "Liste avec insertions animées.", instruction: "Utilisez <code>AnimatedList</code> avec un <code>GlobalKey&lt;AnimatedListState&gt;</code>.", code_template: "// AnimatedList\n", solution: "final listKey = GlobalKey<AnimatedListState>();\nAnimatedList(\n  key: listKey,\n  initialItemCount: items.length,\n  itemBuilder: (ctx, i, anim) => SizeTransition(sizeFactor: anim, child: Text(items[i])),\n);", tests: [{ expected: "AnimatedList", type: "contains" }, { expected: "GlobalKey<AnimatedListState>", type: "contains" }] },
  { id: "dart_239", type: "code", category: "Animations", title: "PageRouteBuilder", description: "Transition de route custom.", instruction: "Avec <code>PageRouteBuilder</code>, créez une transition fade.", code_template: "// PageRouteBuilder\n", solution: "PageRouteBuilder(\n  pageBuilder: (ctx, anim, secAnim) => SecondPage(),\n  transitionsBuilder: (ctx, anim, sec, child) => FadeTransition(opacity: anim, child: child),\n);", tests: [{ expected: "PageRouteBuilder", type: "contains" }, { expected: "transitionsBuilder", type: "contains" }] },
  { id: "dart_240", type: "code", category: "Perf", title: "const constructor", description: "Widgets compilés à la const.", instruction: "Préfixez un widget stateless de <code>const</code> pour réutiliser l'instance.", code_template: "Widget build(BuildContext c) {\n  return Text('hi'); // const ?\n}", solution: "Widget build(BuildContext c) {\n  return const Text('hi');\n}", tests: [{ expected: "const Text(", type: "contains" }] },
  { id: "dart_241", type: "code", category: "Perf", title: "ListView.builder", description: "Liste lazy.", instruction: "Pour une longue liste, utilisez <code>ListView.builder(itemCount, itemBuilder)</code>.", code_template: "// builder\n", solution: "ListView.builder(\n  itemCount: items.length,\n  itemBuilder: (ctx, i) => ListTile(title: Text(items[i])),\n);", tests: [{ expected: "ListView.builder", type: "contains" }, { expected: "itemBuilder", type: "contains" }] },
  { id: "dart_242", type: "code", category: "Perf", title: "RepaintBoundary", description: "Isoler le repaint.", instruction: "Enveloppez un widget coûteux dans <code>RepaintBoundary</code>.", code_template: "// RepaintBoundary\n", solution: "RepaintBoundary(\n  child: CustomPaint(painter: HeavyPainter()),\n);", tests: [{ expected: "RepaintBoundary", type: "contains" }] },
  { id: "dart_243", type: "code", category: "Perf", title: "Keys (ValueKey)", description: "Identité des widgets.", instruction: "Donnez un <code>ValueKey(id)</code> à chaque item d'une liste réordonnable.", code_template: "// ValueKey\n", solution: "items.map((item) => ListTile(key: ValueKey(item.id), title: Text(item.name))).toList();", tests: [{ expected: "ValueKey(", type: "contains" }] },
  { id: "dart_244", type: "code", category: "Perf", title: "dispose() controller", description: "Libérer ressources.", instruction: "Dans <code>dispose()</code>, appelez <code>controller.dispose()</code>.", code_template: "@override\nvoid dispose() {\n  // \n  super.dispose();\n}", solution: "@override\nvoid dispose() {\n  controller.dispose();\n  super.dispose();\n}", tests: [{ expected: "controller.dispose()", type: "contains" }, { expected: "super.dispose()", type: "contains" }] },
  { id: "dart_245", type: "code", category: "Perf", title: "Selector (Provider)", description: "Rebuild ciblé.", instruction: "Avec <code>Selector&lt;Cart, int&gt;</code>, ne reconstruisez que sur change du count.", code_template: "// Selector\n", solution: "Selector<Cart, int>(\n  selector: (ctx, cart) => cart.itemCount,\n  builder: (ctx, count, child) => Text('$count'),\n);", tests: [{ expected: "Selector<", type: "contains" }, { expected: "selector:", type: "contains" }] },
  { id: "dart_246", type: "code", category: "Tests", title: "Test widget", description: "Tester un widget.", instruction: "Avec <code>testWidgets</code> et <code>tester.pumpWidget</code>, testez l'affichage d'un Text.", code_template: "import 'package:flutter_test/flutter_test.dart';\nimport 'package:flutter/material.dart';\nvoid main() {\n  // testWidgets\n}", solution: "import 'package:flutter_test/flutter_test.dart';\nimport 'package:flutter/material.dart';\nvoid main() {\n  testWidgets('shows hello', (tester) async {\n    await tester.pumpWidget(MaterialApp(home: Text('hello')));\n    expect(find.text('hello'), findsOneWidget);\n  });\n}", tests: [{ expected: "testWidgets(", type: "contains" }, { expected: "pumpWidget", type: "contains" }] },
  { id: "dart_247", type: "code", category: "Tests", title: "find.byType", description: "Localiser un widget.", instruction: "Utilisez <code>find.byType(ElevatedButton)</code> pour trouver un bouton.", code_template: "// find\n", solution: "expect(find.byType(ElevatedButton), findsOneWidget);", tests: [{ expected: "find.byType", type: "contains" }] },
  { id: "dart_248", type: "code", category: "Tests", title: "tester.tap", description: "Simuler un clic.", instruction: "Avec <code>await tester.tap(find.byKey(Key('btn')))</code>, simulez un appui.", code_template: "// tap\n", solution: "await tester.tap(find.byKey(Key('btn')));\nawait tester.pump();", tests: [{ expected: "tester.tap", type: "contains" }, { expected: "tester.pump", type: "contains" }] },
  { id: "dart_249", type: "code", category: "Build", title: "kReleaseMode", description: "Détecter le mode release.", instruction: "Avec <code>kReleaseMode</code> de foundation, branchez du code spécifique.", code_template: "import 'package:flutter/foundation.dart';\nvoid main() {\n  // \n}", solution: "import 'package:flutter/foundation.dart';\nvoid main() {\n  if (kReleaseMode) {\n    print('release build');\n  } else {\n    print('debug build');\n  }\n}", tests: [{ expected: "kReleaseMode", type: "contains" }] },
  { id: "dart_250", type: "code", category: "Build", title: "Platform.isIOS / isAndroid", description: "Code par plateforme.", instruction: "Avec <code>Platform.isIOS</code> de dart:io, branchez selon la plateforme.", code_template: "import 'dart:io';\nvoid main() {\n  // \n}", solution: "import 'dart:io';\nvoid main() {\n  if (Platform.isIOS) {\n    print('iOS');\n  } else if (Platform.isAndroid) {\n    print('Android');\n  }\n}", tests: [{ expected: "Platform.isIOS", type: "contains" }, { expected: "Platform.isAndroid", type: "contains" }] },
];

addExercises("dart", exercises);
