import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/**
 * JavaScript — Part 8 : classes ES6+, generators, Symbol, JSON, regex, divers.
 */
const exercises: Exercise[] = [
  {
    id: "js_s8_e1",
    title: "Classe simple",
    description: "Premier class.",
    instruction: "Définissez <code>class Animal { constructor(nom) { this.nom = nom; } parler() { return this.nom + ' fait du bruit'; } }</code>. Créez un <code>chat</code> nommé 'Whiskers' et affichez son parler.",
    code_template: "// classe ici\n",
    solution: "class Animal { constructor(nom) { this.nom = nom; } parler() { return this.nom + ' fait du bruit'; } }\nconst chat = new Animal('Whiskers');\nconsole.log(chat.parler());",
    tests: [
      { type: "contains", expected: "class Animal" },
      { type: "output", expected: "Whiskers fait du bruit" },
    ],
    category: "Classes",
  },
  {
    id: "js_s8_e2",
    title: "Héritage",
    description: "extends + super.",
    instruction: "Définissez <code>class Chien extends Animal</code> avec une méthode <code>parler()</code> qui retourne <code>this.nom + ' aboie'</code>. Créez <code>new Chien('Rex')</code> et appelez parler().",
    code_template: "class Animal { constructor(nom) { this.nom = nom; } }\n// class Chien extends Animal\n",
    solution: "class Animal { constructor(nom) { this.nom = nom; } }\nclass Chien extends Animal { parler() { return this.nom + ' aboie'; } }\nconsole.log(new Chien('Rex').parler());",
    tests: [
      { type: "contains", expected: "extends Animal" },
      { type: "output", expected: "Rex aboie" },
    ],
    category: "Classes",
  },
  {
    id: "js_s8_e3",
    title: "super dans constructor",
    description: "Initialiser le parent.",
    instruction: "Définissez <code>class Chat extends Animal</code> dont le constructor prend (nom, race), appelle super(nom), et stocke race. Affichez <code>nom + '/' + race</code> via une méthode <code>info()</code> pour <code>new Chat('Felix', 'Siamois')</code>.",
    code_template: "class Animal { constructor(nom) { this.nom = nom; } }\n// Chat ici\n",
    solution: "class Animal { constructor(nom) { this.nom = nom; } }\nclass Chat extends Animal {\n  constructor(nom, race) { super(nom); this.race = race; }\n  info() { return this.nom + '/' + this.race; }\n}\nconsole.log(new Chat('Felix', 'Siamois').info());",
    tests: [
      { type: "contains", expected: "super(nom)" },
      { type: "output", expected: "Felix/Siamois" },
    ],
    category: "Classes",
  },
  {
    id: "js_s8_e4",
    title: "Méthode statique",
    description: "Pas besoin d'instance.",
    instruction: "Définissez <code>class Calc</code> avec une méthode statique <code>somme(a, b)</code> qui retourne a+b. Affichez <code>Calc.somme(7, 8)</code>.",
    code_template: "// classe avec static\n",
    solution: "class Calc { static somme(a, b) { return a + b; } }\nconsole.log(Calc.somme(7, 8));",
    tests: [
      { type: "contains", expected: "static somme" },
      { type: "output", expected: "15" },
    ],
    category: "Classes",
  },
  {
    id: "js_s8_e5",
    title: "Champs privés #",
    description: "Encapsulation avec #.",
    instruction: "Définissez <code>class CompteBancaire</code> avec un champ privé <code>#solde</code> initialisé via constructor, une méthode <code>depot(n)</code> qui ajoute, et un getter <code>solde</code>. Testez : dépôt 100, dépôt 50, affichez solde.",
    code_template: "// CompteBancaire\n",
    solution: "class CompteBancaire {\n  #solde = 0;\n  depot(n) { this.#solde += n; }\n  get solde() { return this.#solde; }\n}\nconst c = new CompteBancaire();\nc.depot(100); c.depot(50);\nconsole.log(c.solde);",
    tests: [
      { type: "regex", expected: "#solde" },
      { type: "output", expected: "150" },
    ],
    category: "Classes",
  },
  {
    id: "js_s8_e6",
    title: "Generator basique",
    description: "function* yield.",
    instruction: "Définissez <code>function* compter()</code> qui yield 1, 2, 3. Récupérez le générateur, appelez .next() trois fois et affichez chaque .value sur une ligne.",
    code_template: "function* compter() {\n  // yield 1, 2, 3\n}\nconst g = compter();\n// 3 .next()\n",
    solution: "function* compter() {\n  yield 1; yield 2; yield 3;\n}\nconst g = compter();\nconsole.log(g.next().value);\nconsole.log(g.next().value);\nconsole.log(g.next().value);",
    tests: [
      { type: "contains", expected: "function*" },
      { type: "output", expected: "1\n2\n3" },
    ],
    category: "Generators",
  },
  {
    id: "js_s8_e7",
    title: "Generator avec boucle",
    description: "yield dans for.",
    instruction: "Définissez <code>function* range(n)</code> qui yield 0..n-1. Itérez avec <code>for...of</code> sur <code>range(4)</code> et affichez chaque valeur joint par virgule.",
    code_template: "function* range(n) {\n  // yield i\n}\nconst arr = [...range(4)];\nconsole.log(arr.join(','));",
    solution: "function* range(n) {\n  for (let i = 0; i < n; i++) yield i;\n}\nconsole.log([...range(4)].join(','));",
    tests: [{ type: "output", expected: "0,1,2,3" }],
    category: "Generators",
  },
  {
    id: "js_s8_e8",
    title: "Generator infini (avec limit)",
    description: "Lazy evaluation.",
    instruction: "Définissez un generator infini <code>naturels()</code> qui yield 1, 2, 3, ... Récupérez les 5 premiers via une boucle qui break à 5, et affichez la somme.",
    code_template: "function* naturels() {\n  // infinite\n}\n// prendre les 5 premiers\n",
    solution: "function* naturels() {\n  let n = 1;\n  while (true) { yield n++; }\n}\nconst g = naturels();\nlet s = 0;\nfor (let i = 0; i < 5; i++) s += g.next().value;\nconsole.log(s);",
    tests: [{ type: "output", expected: "15" }],
    category: "Generators",
  },
  {
    id: "js_s8_e9",
    title: "Symbol unique",
    description: "Chaque Symbol est unique.",
    instruction: "Créez 2 symbols avec la même description <code>'id'</code>. Comparez-les avec === et affichez le résultat (devrait être false).",
    code_template: "// 2 Symbol('id')\n",
    solution: "const a = Symbol('id');\nconst b = Symbol('id');\nconsole.log(a === b);",
    tests: [
      { type: "contains", expected: "Symbol" },
      { type: "output", expected: "false" },
    ],
    category: "Symbols",
  },
  {
    id: "js_s8_e10",
    title: "Symbol comme clé",
    description: "Propriétés non énumerables par défaut.",
    instruction: "Utilisez un Symbol comme clé d'un objet : <code>const ID = Symbol('id');</code>, <code>obj = { [ID]: 42 }</code>. Affichez <code>obj[ID]</code>.",
    code_template: "// Symbol + clé objet\n",
    solution: "const ID = Symbol('id');\nconst obj = { [ID]: 42 };\nconsole.log(obj[ID]);",
    tests: [{ type: "output", expected: "42" }],
    category: "Symbols",
  },
  {
    id: "js_s8_e11",
    title: "JSON.stringify",
    description: "Sérialiser un objet.",
    instruction: "Sérialisez <code>{nom: 'Aelita', niveau: 100}</code> en JSON et affichez le résultat.",
    code_template: "const p = {nom: 'Aelita', niveau: 100};\n// stringify\n",
    solution: "const p = {nom: 'Aelita', niveau: 100};\nconsole.log(JSON.stringify(p));",
    tests: [
      { type: "contains", expected: "JSON.stringify" },
      { type: "output", expected: '{"nom":"Aelita","niveau":100}' },
    ],
    category: "JSON",
  },
  {
    id: "js_s8_e12",
    title: "JSON.parse",
    description: "Désérialiser une string.",
    instruction: "Parsez <code>'{\"x\":10,\"y\":20}'</code> avec JSON.parse et affichez x+y.",
    code_template: "const s = '{\"x\":10,\"y\":20}';\n// parse\n",
    solution: "const s = '{\"x\":10,\"y\":20}';\nconst o = JSON.parse(s);\nconsole.log(o.x + o.y);",
    tests: [
      { type: "contains", expected: "JSON.parse" },
      { type: "output", expected: "30" },
    ],
    category: "JSON",
  },
  {
    id: "js_s8_e13",
    title: "JSON.stringify indenté",
    description: "Pretty print.",
    instruction: "Sérialisez <code>{a:1}</code> avec une indentation de 2 espaces. Affichez le résultat (qui sera multi-ligne).",
    code_template: "// JSON.stringify avec 3e argument\n",
    solution: "console.log(JSON.stringify({a:1}, null, 2));",
    tests: [{ type: "output", expected: '{\n  "a": 1\n}' }],
    category: "JSON",
  },
  {
    id: "js_s8_e14",
    title: "Regex test",
    description: "Vérifier un format.",
    instruction: "Vérifiez si <code>'aelita@lyoko.fr'</code> correspond au pattern email basique <code>/^[^@]+@[^@]+\\.[^@]+$/</code>. Affichez true ou false.",
    code_template: "const email = 'aelita@lyoko.fr';\n// regex\n",
    solution: "const email = 'aelita@lyoko.fr';\nconsole.log(/^[^@]+@[^@]+\\.[^@]+$/.test(email));",
    tests: [{ type: "output", expected: "true" }],
    category: "Regex",
  },
  {
    id: "js_s8_e15",
    title: "Regex match",
    description: "Extraire un groupe.",
    instruction: "Extrayez la partie nom du fichier <code>'/path/to/file.txt'</code> avec une regex (groupe capturant). Affichez 'file.txt'.",
    code_template: "const path = '/path/to/file.txt';\n// regex avec groupe\n",
    solution: "const path = '/path/to/file.txt';\nconst m = path.match(/([^/]+)$/);\nconsole.log(m[1]);",
    tests: [{ type: "output", expected: "file.txt" }],
    category: "Regex",
  },
  {
    id: "js_s8_e16",
    title: "Regex replace",
    description: "Remplacer toutes les occurrences.",
    instruction: "Dans <code>'hello world hello you'</code>, remplacez chaque 'hello' par 'bye' avec une regex /g. Affichez le résultat.",
    code_template: "const s = 'hello world hello you';\n// replace\n",
    solution: "const s = 'hello world hello you';\nconsole.log(s.replace(/hello/g, 'bye'));",
    tests: [{ type: "output", expected: "bye world bye you" }],
    category: "Regex",
  },
  {
    id: "js_s8_e17",
    title: "Regex split",
    description: "Split sur plusieurs caractères.",
    instruction: "Splittez <code>'a,b;c,d;e'</code> sur ',' OU ';' avec une regex. Affichez joint par '|'.",
    code_template: "const s = 'a,b;c,d;e';\n// split\n",
    solution: "const s = 'a,b;c,d;e';\nconsole.log(s.split(/[,;]/).join('|'));",
    tests: [{ type: "output", expected: "a|b|c|d|e" }],
    category: "Regex",
  },
  {
    id: "js_s8_e18",
    title: "Template literals",
    description: "Interpolation avancée.",
    instruction: "Avec <code>nom='Yumi'</code> et <code>niveau=42</code>, affichez <code>'Yumi est au niveau 42'</code> via template literal.",
    code_template: "const nom = 'Yumi';\nconst niveau = 42;\n// template\n",
    solution: "const nom = 'Yumi';\nconst niveau = 42;\nconsole.log(`${nom} est au niveau ${niveau}`);",
    tests: [
      { type: "regex", expected: "\\`\\$\\{" },
      { type: "output", expected: "Yumi est au niveau 42" },
    ],
    category: "Templates",
  },
  {
    id: "js_s8_e19",
    title: "Tagged template",
    description: "Fonction tag sur template.",
    instruction: "Définissez <code>function tag(strings, ...vals)</code> qui joint les vals avec '|' et affiche. Testez avec <code>tag\\`a${1}b${2}c\\`</code>. Devrait afficher '1|2'.",
    code_template: "function tag(strings, ...vals) {\n  // joindre vals\n}\ntag`a${1}b${2}c`;",
    solution: "function tag(strings, ...vals) {\n  console.log(vals.join('|'));\n}\ntag`a${1}b${2}c`;",
    tests: [{ type: "output", expected: "1|2" }],
    category: "Templates",
  },
  {
    id: "js_s8_e20",
    title: "Optional chaining",
    description: "?. évite les erreurs sur null/undefined.",
    instruction: "Avec <code>user = { profil: { nom: 'Aelita' } }</code>, affichez <code>user.profil?.nom</code>, puis avec <code>user2 = {}</code>, <code>user2.profil?.nom</code>. Devrait afficher 'Aelita' puis 'undefined'.",
    code_template: "const user = { profil: { nom: 'Aelita' } };\nconst user2 = {};\n// ?.\n",
    solution: "const user = { profil: { nom: 'Aelita' } };\nconst user2 = {};\nconsole.log(user.profil?.nom);\nconsole.log(user2.profil?.nom);",
    tests: [
      { type: "contains", expected: "?." },
      { type: "output", expected: "Aelita\nundefined" },
    ],
    category: "ES2020+",
  },
  {
    id: "js_s8_e21",
    title: "Nullish coalescing",
    description: "?? remplace || pour les valeurs falsy non-null.",
    instruction: "Affichez <code>null ?? 'défaut'</code>, puis <code>0 ?? 'défaut'</code>, puis <code>'' ?? 'défaut'</code>. Devrait afficher 'défaut', 0, ''.",
    code_template: "// 3 ?? logs\n",
    solution: "console.log(null ?? 'défaut');\nconsole.log(0 ?? 'défaut');\nconsole.log('' ?? 'défaut');",
    tests: [
      { type: "contains", expected: "??" },
      { type: "output", expected: "défaut\n0\n" },
    ],
    category: "ES2020+",
  },
  {
    id: "js_s8_e22",
    title: "Iterator manuel",
    description: "Implémenter le protocole iterable.",
    instruction: "Créez un objet <code>compteur</code> avec une méthode <code>[Symbol.iterator]()</code> qui retourne un itérateur émettant 10, 20, 30. Affichez chaque valeur via for...of.",
    code_template: "const compteur = {\n  // [Symbol.iterator]() { ... }\n};\nfor (const v of compteur) console.log(v);",
    solution: "const compteur = {\n  [Symbol.iterator]() {\n    let i = 0;\n    const vals = [10, 20, 30];\n    return { next: () => i < vals.length ? { value: vals[i++], done: false } : { value: undefined, done: true } };\n  }\n};\nfor (const v of compteur) console.log(v);",
    tests: [{ type: "output", expected: "10\n20\n30" }],
    category: "Iterators",
  },
  {
    id: "js_s8_e23",
    title: "Number.isInteger",
    description: "Distinguer entiers et flottants.",
    instruction: "Testez <code>Number.isInteger(7)</code>, <code>Number.isInteger(7.5)</code>, <code>Number.isInteger('7')</code>. Affichez les 3 résultats.",
    code_template: "// 3 tests\n",
    solution: "console.log(Number.isInteger(7));\nconsole.log(Number.isInteger(7.5));\nconsole.log(Number.isInteger('7'));",
    tests: [{ type: "output", expected: "true\nfalse\nfalse" }],
    category: "Number",
  },
  {
    id: "js_s8_e24",
    title: "BigInt",
    description: "Grands entiers exacts.",
    instruction: "Calculez <code>2n ** 64n</code> et affichez la valeur en string (préfixe 'n' à enlever).",
    code_template: "// 2n ** 64n\n",
    solution: "const r = 2n ** 64n;\nconsole.log(r.toString());",
    tests: [
      { type: "contains", expected: "BigInt" },
      { type: "output", expected: "18446744073709551616" },
    ],
    category: "Number",
    hint: "BigInt s'écrit avec un suffixe n. Utilisez ** 64n et .toString().",
  },
  {
    id: "js_s8_e25",
    title: "Mission JavaScript",
    description: "Final boss.",
    instruction: "Implémentez en une ligne (chaîne map/filter/reduce) : à partir de <code>[1,2,3,4,5,6,7,8,9,10]</code>, gardez les pairs, multipliez chacun par 3, sommez. Affichez le résultat.",
    code_template: "const t = [1,2,3,4,5,6,7,8,9,10];\n// filter + map + reduce\n",
    solution: "const t = [1,2,3,4,5,6,7,8,9,10];\nconsole.log(t.filter(x => x % 2 === 0).map(x => x * 3).reduce((s, v) => s + v, 0));",
    tests: [{ type: "output", expected: "90" }],
    category: "Final",
    hint: "Tu viens de finir 200 exos JS. Bravo Lyoko-warrior !",
  },
];

addExercises("javascript", exercises);
