import { addExercises } from ".";
import type { Exercise } from "@/app/exercises/[module]/exercise-client";

// @ts-nocheck — Auto-converted from exercises-js-part2.js
const exercises: Exercise[] = [
    // === FONCTIONS (26-33) ===
    {
      id: "js_s1_e26",
      title: "Première fonction",
      description: "Créez et appelez une fonction simple.",
      instruction: "Créez une fonction <code>saluer()</code> qui affiche <strong>\"Bonjour !\"</strong>, puis appelez-la.",
      code_template: "// Créez la fonction saluer\n\n// Appelez-la\n",
      solution: 'function saluer() {\n  console.log("Bonjour !");\n}\nsaluer();',
      tests: [{ type: "output", expected: "Bonjour !" }],
      hint: "function nomFonction() { ... } puis nomFonction();",
      help_steps: [
        '1. <code>function saluer() {</code>',
        '2. <code>  console.log("Bonjour !");</code>',
        "3. <code>}</code>",
        "4. <code>saluer();</code>",
      ],
    },
    {
      id: "js_s1_e27",
      title: "Fonction avec paramètre",
      description: "Passez un argument à une fonction.",
      instruction: "Créez <code>saluerPersonne(nom)</code> qui affiche <strong>\"Bonjour Alice\"</strong>. Appelez-la avec <strong>\"Alice\"</strong>.",
      code_template: "// Créez la fonction avec un paramètre\n\n// Appelez-la\n",
      solution: 'function saluerPersonne(nom) {\n  console.log("Bonjour " + nom);\n}\nsaluerPersonne("Alice");',
      tests: [{ type: "output", expected: "Bonjour Alice" }],
      hint: "Le paramètre est une variable locale à la fonction.",
      help_steps: [
        "1. <code>function saluerPersonne(nom) {</code>",
        '2. <code>  console.log("Bonjour " + nom);</code>',
        '3. Appelez : <code>saluerPersonne("Alice");</code>',
      ],
    },
    {
      id: "js_s1_e28",
      title: "Fonction avec return",
      description: "Retournez une valeur depuis une fonction.",
      instruction: "Créez <code>doubler(n)</code> qui retourne <code>n * 2</code>. Affichez le résultat de <code>doubler(7)</code>.",
      code_template: "// Créez la fonction doubler\n\n// Affichez doubler(7)\n",
      solution: "function doubler(n) {\n  return n * 2;\n}\nconsole.log(doubler(7));",
      tests: [{ type: "output", expected: "14" }],
      hint: "return renvoie une valeur que vous pouvez utiliser avec console.log().",
      help_steps: [
        "1. <code>function doubler(n) { return n * 2; }</code>",
        "2. <code>console.log(doubler(7));</code>",
      ],
    },
    {
      id: "js_s1_e29",
      title: "Fonction fléchée",
      description: "Syntaxe moderne avec les arrow functions.",
      instruction: "Créez une fonction fléchée <code>carre</code> qui retourne le carré d'un nombre. Affichez <code>carre(5)</code>.",
      code_template: "// Créez la fonction fléchée carre\n\n// Affichez carre(5)\n",
      solution: "const carre = (n) => n * n;\nconsole.log(carre(5));",
      tests: [{ type: "output", expected: "25" }],
      hint: "Syntaxe : const fn = (param) => expression;",
      help_steps: [
        "1. <code>const carre = (n) => n * n;</code>",
        "2. <code>console.log(carre(5));</code>",
      ],
    },
    {
      id: "js_s1_e30",
      title: "Paramètres par défaut",
      description: "Donnez une valeur par défaut à un paramètre.",
      instruction: 'Créez <code>salut(nom = "Monde")</code> qui affiche <strong>"Bonjour Monde"</strong>. Appelez-la sans argument.',
      code_template: "// Fonction avec paramètre par défaut\n\n// Appelez sans argument\n",
      solution: 'function salut(nom = "Monde") {\n  console.log("Bonjour " + nom);\n}\nsalut();',
      tests: [{ type: "output", expected: "Bonjour Monde" }],
      hint: 'Syntaxe : function fn(param = "valeur") { ... }',
      help_steps: [
        '1. <code>function salut(nom = "Monde") {</code>',
        '2. <code>  console.log("Bonjour " + nom);</code>',
        "3. <code>salut();</code> — sans argument, utilise la valeur par défaut",
      ],
    },
    {
      id: "js_s1_e31",
      title: "Fonction récursive",
      description: "Une fonction qui s'appelle elle-même.",
      instruction: "Créez <code>factorielle(n)</code> qui calcule la factorielle. Affichez <code>factorielle(5)</code> (résultat : <strong>120</strong>).",
      code_template: "// Créez la fonction factorielle\n\n// Affichez factorielle(5)\n",
      solution: "function factorielle(n) {\n  if (n <= 1) return 1;\n  return n * factorielle(n - 1);\n}\nconsole.log(factorielle(5));",
      tests: [{ type: "output", expected: "120" }],
      hint: "Cas de base : si n <= 1, retourner 1. Sinon : n * factorielle(n-1).",
      help_steps: [
        "1. Cas de base : <code>if (n <= 1) return 1;</code>",
        "2. Récursion : <code>return n * factorielle(n - 1);</code>",
      ],
    },
    {
      id: "js_s1_e32",
      title: "Fonction max",
      description: "Trouvez le maximum de deux nombres.",
      instruction: "Créez <code>max(a, b)</code> qui retourne le plus grand. Affichez <code>max(8, 15)</code>.",
      code_template: "// Créez la fonction max\n\n// Affichez max(8, 15)\n",
      solution: "function max(a, b) {\n  return a > b ? a : b;\n}\nconsole.log(max(8, 15));",
      tests: [{ type: "output", expected: "15" }],
      hint: "Utilisez l'opérateur ternaire ou if/else.",
      help_steps: [
        "1. <code>function max(a, b) {</code>",
        "2. <code>  return a > b ? a : b;</code>",
        "3. <code>console.log(max(8, 15));</code>",
      ],
    },
    {
      id: "js_s1_e33",
      title: "Callback simple",
      description: "Passez une fonction en argument.",
      instruction: "Créez <code>appliquer(fn, valeur)</code> qui appelle <code>fn(valeur)</code>. Utilisez-la avec une fonction qui triple un nombre. Affichez le résultat pour <strong>4</strong>.",
      code_template: "// Créez appliquer(fn, valeur)\n\n// Créez une fonction tripler\n\n// Utilisez appliquer\n",
      solution: "function appliquer(fn, valeur) {\n  return fn(valeur);\n}\nconst tripler = (n) => n * 3;\nconsole.log(appliquer(tripler, 4));",
      tests: [{ type: "output", expected: "12" }],
      hint: "Une fonction peut recevoir une autre fonction en paramètre.",
      help_steps: [
        "1. <code>function appliquer(fn, valeur) { return fn(valeur); }</code>",
        "2. <code>const tripler = (n) => n * 3;</code>",
        "3. <code>console.log(appliquer(tripler, 4));</code>",
      ],
    },

    // === TABLEAUX (34-41) ===
    {
      id: "js_s1_e34",
      title: "Créer un tableau",
      description: "Déclarez et affichez un tableau.",
      instruction: 'Créez un tableau <code>fruits</code> contenant <strong>"pomme"</strong>, <strong>"banane"</strong>, <strong>"orange"</strong>. Affichez sa longueur.',
      code_template: "// Créez le tableau fruits\n\n// Affichez sa longueur\n",
      solution: 'let fruits = ["pomme", "banane", "orange"];\nconsole.log(fruits.length);',
      tests: [{ type: "output", expected: "3" }],
      hint: "Syntaxe : let tableau = [\"a\", \"b\", \"c\"]; et .length pour la taille.",
      help_steps: [
        '1. <code>let fruits = ["pomme", "banane", "orange"];</code>',
        "2. <code>console.log(fruits.length);</code>",
      ],
    },
    {
      id: "js_s1_e35",
      title: "Accéder aux éléments",
      description: "Accédez aux éléments par leur index.",
      instruction: 'Créez <code>couleurs</code> = <strong>["rouge", "vert", "bleu"]</strong>. Affichez le <strong>deuxième</strong> élément.',
      code_template: "// Créez le tableau\n\n// Affichez le 2ème élément (index 1)\n",
      solution: 'let couleurs = ["rouge", "vert", "bleu"];\nconsole.log(couleurs[1]);',
      tests: [{ type: "output", expected: "vert" }],
      hint: "Les index commencent à 0 : le 2ème élément est à l'index 1.",
      help_steps: [
        "1. Les index commencent à 0",
        "2. <code>couleurs[1]</code> donne le 2ème élément",
      ],
    },
    {
      id: "js_s1_e36",
      title: "push et pop",
      description: "Ajoutez et retirez des éléments.",
      instruction: 'Créez <code>pile</code> = <strong>[1, 2, 3]</strong>. Ajoutez <strong>4</strong> avec <code>push()</code>, retirez le dernier avec <code>pop()</code>, puis affichez le tableau avec <code>console.log(pile.join(", "))</code>.',
      code_template: "let pile = [1, 2, 3];\n\n// Ajoutez 4\n\n// Retirez le dernier\n\n// Affichez\n",
      solution: 'let pile = [1, 2, 3];\npile.push(4);\npile.pop();\nconsole.log(pile.join(", "));',
      tests: [{ type: "output", expected: "1, 2, 3" }],
      hint: "push() ajoute à la fin, pop() retire le dernier élément.",
      help_steps: [
        "1. <code>pile.push(4);</code> → [1,2,3,4]",
        "2. <code>pile.pop();</code> → [1,2,3]",
        '3. <code>console.log(pile.join(", "));</code>',
      ],
    },
    {
      id: "js_s1_e37",
      title: "forEach",
      description: "Parcourez un tableau avec forEach.",
      instruction: 'Créez <code>noms</code> = <strong>["Alice", "Bob", "Charlie"]</strong>. Utilisez <code>forEach</code> pour afficher chaque nom.',
      code_template: "// Créez le tableau\n\n// Parcourez avec forEach\n",
      solution: 'let noms = ["Alice", "Bob", "Charlie"];\nnoms.forEach((nom) => {\n  console.log(nom);\n});',
      tests: [
        { type: "output", expected: "Alice" },
        { type: "output", expected: "Bob" },
        { type: "output", expected: "Charlie" },
      ],
      hint: "tableau.forEach((element) => { ... });",
      help_steps: [
        "1. <code>noms.forEach((nom) => {</code>",
        "2. <code>  console.log(nom);</code>",
        "3. <code>});</code>",
      ],
    },
    {
      id: "js_s1_e38",
      title: "map - Transformer",
      description: "Transformez chaque élément d'un tableau.",
      instruction: "Créez <code>nombres</code> = <strong>[1, 2, 3, 4, 5]</strong>. Utilisez <code>map()</code> pour créer <code>doubles</code> (chaque nombre × 2). Affichez doubles.",
      code_template: "let nombres = [1, 2, 3, 4, 5];\n\n// Créez doubles avec map\n\n// Affichez\n",
      solution: 'let nombres = [1, 2, 3, 4, 5];\nlet doubles = nombres.map((n) => n * 2);\nconsole.log(doubles.join(", "));',
      tests: [{ type: "output", expected: "2, 4, 6, 8, 10" }],
      hint: "map() retourne un nouveau tableau transformé.",
      help_steps: [
        "1. <code>let doubles = nombres.map((n) => n * 2);</code>",
        '2. <code>console.log(doubles.join(", "));</code>',
      ],
    },
    {
      id: "js_s1_e39",
      title: "filter - Filtrer",
      description: "Filtrez les éléments d'un tableau.",
      instruction: "Créez <code>ages</code> = <strong>[12, 18, 25, 8, 30, 15]</strong>. Filtrez les majeurs (>= 18) dans <code>majeurs</code>. Affichez.",
      code_template: "let ages = [12, 18, 25, 8, 30, 15];\n\n// Filtrez les majeurs\n\n// Affichez\n",
      solution: 'let ages = [12, 18, 25, 8, 30, 15];\nlet majeurs = ages.filter((a) => a >= 18);\nconsole.log(majeurs.join(", "));',
      tests: [{ type: "output", expected: "18, 25, 30" }],
      hint: "filter() garde les éléments qui passent le test.",
      help_steps: [
        "1. <code>let majeurs = ages.filter((a) => a >= 18);</code>",
        '2. <code>console.log(majeurs.join(", "));</code>',
      ],
    },
    {
      id: "js_s1_e40",
      title: "reduce - Réduire",
      description: "Réduisez un tableau à une seule valeur.",
      instruction: "Créez <code>prix</code> = <strong>[10, 20, 30, 40]</strong>. Calculez le total avec <code>reduce()</code>. Affichez.",
      code_template: "let prix = [10, 20, 30, 40];\n\n// Calculez le total avec reduce\n\n// Affichez\n",
      solution: "let prix = [10, 20, 30, 40];\nlet total = prix.reduce((acc, p) => acc + p, 0);\nconsole.log(total);",
      tests: [{ type: "output", expected: "100" }],
      hint: "reduce((accumulateur, element) => ..., valeurInitiale)",
      help_steps: [
        "1. <code>let total = prix.reduce((acc, p) => acc + p, 0);</code>",
        "2. acc commence à 0, puis accumule chaque prix",
      ],
    },
    {
      id: "js_s1_e41",
      title: "find et includes",
      description: "Recherchez dans un tableau.",
      instruction: 'Créez <code>scores</code> = <strong>[45, 78, 92, 56, 88]</strong>. Trouvez le premier score > 80 avec <code>find()</code>. Affichez-le.',
      code_template: "let scores = [45, 78, 92, 56, 88];\n\n// Trouvez le premier > 80\n\n// Affichez\n",
      solution: "let scores = [45, 78, 92, 56, 88];\nlet bon = scores.find((s) => s > 80);\nconsole.log(bon);",
      tests: [{ type: "output", expected: "92" }],
      hint: "find() retourne le premier élément qui satisfait la condition.",
      help_steps: [
        "1. <code>let bon = scores.find((s) => s > 80);</code>",
        "2. <code>console.log(bon);</code> → 92",
      ],
    },

    // === OBJETS (42-50) ===
    {
      id: "js_s1_e42",
      title: "Créer un objet",
      description: "Déclarez un objet avec des propriétés.",
      instruction: 'Créez un objet <code>joueur</code> avec <code>nom: "Mario"</code>, <code>vies: 3</code>, <code>score: 0</code>. Affichez son nom.',
      code_template: "// Créez l'objet joueur\n\n// Affichez joueur.nom\n",
      solution: 'let joueur = {\n  nom: "Mario",\n  vies: 3,\n  score: 0\n};\nconsole.log(joueur.nom);',
      tests: [{ type: "output", expected: "Mario" }],
      hint: "Syntaxe : let obj = { cle: valeur, ... };",
      help_steps: [
        '1. <code>let joueur = { nom: "Mario", vies: 3, score: 0 };</code>',
        "2. <code>console.log(joueur.nom);</code>",
      ],
    },
    {
      id: "js_s1_e43",
      title: "Modifier un objet",
      description: "Modifiez les propriétés d'un objet.",
      instruction: 'Créez <code>joueur</code> avec <code>score: 0</code>. Ajoutez <strong>100</strong> au score, ajoutez une propriété <code>niveau: 2</code>. Affichez <code>"Score: 100, Niveau: 2"</code>.',
      code_template: 'let joueur = { nom: "Hero", score: 0 };\n\n// Modifiez le score\n\n// Ajoutez niveau\n\n// Affichez\n',
      solution: 'let joueur = { nom: "Hero", score: 0 };\njoueur.score += 100;\njoueur.niveau = 2;\nconsole.log(`Score: ${joueur.score}, Niveau: ${joueur.niveau}`);',
      tests: [{ type: "output", expected: "Score: 100, Niveau: 2" }],
      hint: "objet.propriete = valeur; pour modifier ou ajouter.",
      help_steps: [
        "1. <code>joueur.score += 100;</code>",
        "2. <code>joueur.niveau = 2;</code>",
        "3. Affichez avec un template literal",
      ],
    },
    {
      id: "js_s1_e44",
      title: "Méthode d'objet",
      description: "Ajoutez une fonction à un objet.",
      instruction: 'Créez <code>personnage</code> avec <code>nom: "Link"</code> et une méthode <code>presenter()</code> qui affiche <strong>"Je suis Link"</strong>. Appelez-la.',
      code_template: "// Créez l'objet avec une méthode\n\n// Appelez la méthode\n",
      solution: 'let personnage = {\n  nom: "Link",\n  presenter() {\n    console.log("Je suis " + this.nom);\n  }\n};\npersonnage.presenter();',
      tests: [{ type: "output", expected: "Je suis Link" }],
      hint: "this fait référence à l'objet lui-même dans une méthode.",
      help_steps: [
        "1. <code>presenter() { console.log(\"Je suis \" + this.nom); }</code>",
        "2. <code>personnage.presenter();</code>",
      ],
    },
    {
      id: "js_s1_e45",
      title: "Destructuring",
      description: "Extrayez des propriétés d'un objet.",
      instruction: 'Créez <code>config</code> = <code>{ largeur: 800, hauteur: 600, titre: "Mon Jeu" }</code>. Utilisez le destructuring pour extraire <code>largeur</code> et <code>hauteur</code>. Affichez <strong>"800x600"</strong>.',
      code_template: 'let config = { largeur: 800, hauteur: 600, titre: "Mon Jeu" };\n\n// Destructuring\n\n// Affichez\n',
      solution: 'let config = { largeur: 800, hauteur: 600, titre: "Mon Jeu" };\nconst { largeur, hauteur } = config;\nconsole.log(`${largeur}x${hauteur}`);',
      tests: [{ type: "output", expected: "800x600" }],
      hint: "const { prop1, prop2 } = objet;",
      help_steps: [
        "1. <code>const { largeur, hauteur } = config;</code>",
        "2. <code>console.log(`${largeur}x${hauteur}`);</code>",
      ],
    },
    {
      id: "js_s1_e46",
      title: "Spread operator",
      description: "Copiez et fusionnez des objets.",
      instruction: 'Créez <code>base</code> = <code>{ vies: 3, score: 0 }</code> et <code>bonus</code> = <code>{ score: 500, bouclier: true }</code>. Fusionnez avec le spread <code>...</code> dans <code>resultat</code>. Affichez <code>resultat.score</code>.',
      code_template: "let base = { vies: 3, score: 0 };\nlet bonus = { score: 500, bouclier: true };\n\n// Fusionnez\n\n// Affichez le score\n",
      solution: "let base = { vies: 3, score: 0 };\nlet bonus = { score: 500, bouclier: true };\nlet resultat = { ...base, ...bonus };\nconsole.log(resultat.score);",
      tests: [{ type: "output", expected: "500" }],
      hint: "{ ...obj1, ...obj2 } — les propriétés du 2ème écrasent celles du 1er.",
      help_steps: [
        "1. <code>let resultat = { ...base, ...bonus };</code>",
        "2. score de bonus (500) écrase score de base (0)",
      ],
    },
    {
      id: "js_s1_e47",
      title: "Tableau d'objets",
      description: "Manipulez un tableau d'objets.",
      instruction: 'Créez un tableau <code>ennemis</code> avec 3 objets ayant <code>nom</code> et <code>pv</code>. Filtrez ceux avec <code>pv > 50</code>. Affichez le nombre de survivants.',
      code_template: "// Créez le tableau d'ennemis\n\n// Filtrez pv > 50\n\n// Affichez le nombre\n",
      solution: 'let ennemis = [\n  { nom: "Goomba", pv: 30 },\n  { nom: "Koopa", pv: 80 },\n  { nom: "Bowser", pv: 200 }\n];\nlet survivants = ennemis.filter((e) => e.pv > 50);\nconsole.log(survivants.length);',
      tests: [{ type: "output", expected: "2" }],
      hint: "filter() fonctionne aussi sur des tableaux d'objets.",
      help_steps: [
        "1. Créez le tableau avec des objets { nom, pv }",
        "2. <code>ennemis.filter((e) => e.pv > 50)</code>",
      ],
    },
    {
      id: "js_s1_e48",
      title: "Classes",
      description: "Créez une classe JavaScript.",
      instruction: 'Créez une classe <code>Personnage</code> avec un constructeur <code>(nom, pv)</code> et une méthode <code>status()</code> qui affiche <strong>"Mario: 100 PV"</strong>. Créez une instance et appelez status().',
      code_template: "// Créez la classe Personnage\n\n// Créez une instance et appelez status()\n",
      solution: 'class Personnage {\n  constructor(nom, pv) {\n    this.nom = nom;\n    this.pv = pv;\n  }\n  status() {\n    console.log(`${this.nom}: ${this.pv} PV`);\n  }\n}\nlet mario = new Personnage("Mario", 100);\nmario.status();',
      tests: [{ type: "output", expected: "Mario: 100 PV" }],
      hint: "class NomClasse { constructor() { ... } methode() { ... } }",
      help_steps: [
        "1. <code>class Personnage { constructor(nom, pv) { this.nom = nom; this.pv = pv; } }</code>",
        "2. Ajoutez <code>status() { console.log(...); }</code>",
        '3. <code>new Personnage("Mario", 100)</code>',
      ],
    },
    {
      id: "js_s1_e49",
      title: "Héritage",
      description: "Étendez une classe avec extends.",
      instruction: 'Créez <code>Ennemi</code> qui étend <code>Personnage</code> (exo précédent) avec une méthode <code>attaquer()</code> affichant <strong>"Bowser attaque !"</strong>. Créez Bowser avec 500 PV.',
      code_template: 'class Personnage {\n  constructor(nom, pv) {\n    this.nom = nom;\n    this.pv = pv;\n  }\n}\n\n// Créez la classe Ennemi\n\n// Créez Bowser et appelez attaquer()\n',
      solution: 'class Personnage {\n  constructor(nom, pv) {\n    this.nom = nom;\n    this.pv = pv;\n  }\n}\nclass Ennemi extends Personnage {\n  attaquer() {\n    console.log(`${this.nom} attaque !`);\n  }\n}\nlet bowser = new Ennemi("Bowser", 500);\nbowser.attaquer();',
      tests: [{ type: "output", expected: "Bowser attaque !" }],
      hint: "class Enfant extends Parent { ... }",
      help_steps: [
        "1. <code>class Ennemi extends Personnage {</code>",
        "2. <code>  attaquer() { console.log(`${this.nom} attaque !`); }</code>",
        '3. <code>new Ennemi("Bowser", 500)</code>',
      ],
    },
    {
      id: "js_s1_e50",
      title: "Système de combat",
      description: "Mini-système de combat orienté objet.",
      instruction: 'Créez <code>Combattant</code> avec <code>nom</code>, <code>pv</code>, <code>attaque</code> et une méthode <code>frapper(cible)</code> qui réduit les PV de la cible. Faites Mario (100pv, 20atk) frapper Bowser (200pv, 30atk). Affichez les PV de Bowser.',
      code_template: "// Créez la classe Combattant\n\n// Créez Mario et Bowser\n\n// Mario frappe Bowser\n\n// Affichez les PV de Bowser\n",
      solution: 'class Combattant {\n  constructor(nom, pv, attaque) {\n    this.nom = nom;\n    this.pv = pv;\n    this.attaque = attaque;\n  }\n  frapper(cible) {\n    cible.pv -= this.attaque;\n  }\n}\nlet mario = new Combattant("Mario", 100, 20);\nlet bowser = new Combattant("Bowser", 200, 30);\nmario.frapper(bowser);\nconsole.log(bowser.pv);',
      tests: [{ type: "output", expected: "180" }],
      hint: "frapper(cible) { cible.pv -= this.attaque; }",
      help_steps: [
        "1. Classe avec constructor(nom, pv, attaque)",
        "2. <code>frapper(cible) { cible.pv -= this.attaque; }</code>",
        "3. Bowser: 200 - 20 = 180 PV",
      ],
    },
  ];

addExercises("javascript", exercises);
