import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/**
 * JavaScript — Part 5 : closures, portée, hoisting, this, currying.
 */
const exercises: Exercise[] = [
  {
    id: "js_s5_e1",
    title: "Premier closure",
    description: "Une fonction qui garde l'accès à ses variables locales.",
    instruction: "Créez une fonction <code>creerCompteur</code> qui retourne une fonction. À chaque appel de cette fonction retournée, elle incrémente et retourne un compteur (départ à 0). Affichez 3 appels successifs.",
    code_template: "function creerCompteur() {\n  // votre code\n}\n\nconst c = creerCompteur();\nconsole.log(c());\nconsole.log(c());\nconsole.log(c());",
    solution: "function creerCompteur() {\n  let n = 0;\n  return function() { return ++n; };\n}\n\nconst c = creerCompteur();\nconsole.log(c());\nconsole.log(c());\nconsole.log(c());",
    tests: [{ type: "output", expected: "1\n2\n3" }],
    category: "Closures",
    hint: "Variable capturée dans la closure : let n = 0 dans la fonction parente.",
  },
  {
    id: "js_s5_e2",
    title: "Compteur isolé",
    description: "Chaque appel à creerCompteur produit un compteur indépendant.",
    instruction: "Utilisez la même fonction <code>creerCompteur</code> deux fois pour créer deux compteurs indépendants. Incrémentez A trois fois et B une fois, puis affichez les valeurs respectives sur deux lignes.",
    code_template: "function creerCompteur() {\n  let n = 0;\n  return function() { return ++n; };\n}\n\nconst a = creerCompteur();\nconst b = creerCompteur();\n// trois appels à a, un appel à b\n// puis console.log les valeurs courantes",
    solution: "function creerCompteur() {\n  let n = 0;\n  return function() { return ++n; };\n}\n\nconst a = creerCompteur();\nconst b = creerCompteur();\nlet va; va = a(); va = a(); va = a();\nconst vb = b();\nconsole.log(va);\nconsole.log(vb);",
    tests: [{ type: "output", expected: "3\n1" }],
    category: "Closures",
  },
  {
    id: "js_s5_e3",
    title: "let vs var",
    description: "Différence de portée dans une boucle.",
    instruction: "Une boucle <code>for (var i = 0; i < 3; i++)</code> stocke 3 fonctions dans un tableau. Chaque fonction retourne <code>i</code>. Affichez le résultat des 3 fonctions. Ensuite refaites avec <code>let i</code>. Affichez d'abord les 3 retours de var, puis les 3 retours de let, soit 6 lignes.",
    code_template: "const fnVar = [];\nfor (var i = 0; i < 3; i++) fnVar.push(() => i);\nconst fnLet = [];\nfor (let i = 0; i < 3; i++) fnLet.push(() => i);\n// afficher fnVar[0..2]() puis fnLet[0..2]()",
    solution: "const fnVar = [];\nfor (var i = 0; i < 3; i++) fnVar.push(() => i);\nconst fnLet = [];\nfor (let i = 0; i < 3; i++) fnLet.push(() => i);\nfor (let k = 0; k < 3; k++) console.log(fnVar[k]());\nfor (let k = 0; k < 3; k++) console.log(fnLet[k]());",
    tests: [{ type: "output", expected: "3\n3\n3\n0\n1\n2" }],
    category: "Closures",
    hint: "var partage la même variable, let crée une nouvelle portée à chaque tour.",
  },
  {
    id: "js_s5_e4",
    title: "Hoisting de var",
    description: "Une variable var déclarée plus bas est utilisable avant.",
    instruction: "Affichez <code>x</code> AVANT sa déclaration <code>var x = 5;</code>. Le résultat doit être <code>undefined</code>.",
    code_template: "console.log(x);\nvar x = 5;",
    solution: "console.log(x);\nvar x = 5;",
    tests: [{ type: "output", expected: "undefined" }],
    category: "Hoisting",
    hint: "var est hoisted mais initialisée à undefined.",
  },
  {
    id: "js_s5_e5",
    title: "IIFE",
    description: "Immediately Invoked Function Expression.",
    instruction: "Écrivez une IIFE <code>(function() { ... })();</code> qui affiche <code>secret</code> sans laisser de fonction nommée dans le scope global.",
    code_template: "// votre IIFE ici",
    solution: "(function() { console.log('secret'); })();",
    tests: [
      { type: "regex", expected: "\\(\\s*function\\s*\\(\\s*\\)\\s*\\{[\\s\\S]*\\}\\s*\\)\\s*\\(" },
      { type: "output", expected: "secret" },
    ],
    category: "IIFE",
  },
  {
    id: "js_s5_e6",
    title: "Module pattern",
    description: "Un objet avec des données privées.",
    instruction: "Créez via IIFE un objet <code>compteur</code> avec deux méthodes : <code>incr()</code> (incrémente le compteur interne) et <code>valeur()</code> (retourne sa valeur). Le compteur démarre à 0 et n'est pas accessible directement. Appelez incr 3 fois puis affichez valeur().",
    code_template: "const compteur = (function() {\n  // votre code\n})();\n\ncompteur.incr();\ncompteur.incr();\ncompteur.incr();\nconsole.log(compteur.valeur());",
    solution: "const compteur = (function() {\n  let n = 0;\n  return {\n    incr() { n++; },\n    valeur() { return n; }\n  };\n})();\n\ncompteur.incr();\ncompteur.incr();\ncompteur.incr();\nconsole.log(compteur.valeur());",
    tests: [{ type: "output", expected: "3" }],
    category: "Module Pattern",
  },
  {
    id: "js_s5_e7",
    title: "this en mode strict",
    description: "Sans contexte, this est undefined.",
    instruction: "Définissez <code>function f() { return this === undefined; }</code> en mode strict et affichez le résultat de <code>f()</code>.",
    code_template: "'use strict';\nfunction f() { return this === undefined; }\nconsole.log(f());",
    solution: "'use strict';\nfunction f() { return this === undefined; }\nconsole.log(f());",
    tests: [{ type: "output", expected: "true" }],
    category: "this",
  },
  {
    id: "js_s5_e8",
    title: "this dans une méthode",
    description: "this fait référence à l'objet appelant.",
    instruction: "Définissez <code>obj = { nom: 'Aelita', salut() { return 'Bonjour ' + this.nom; } }</code> et affichez le retour de <code>obj.salut()</code>.",
    code_template: "// objet ici\n",
    solution: "const obj = { nom: 'Aelita', salut() { return 'Bonjour ' + this.nom; } };\nconsole.log(obj.salut());",
    tests: [{ type: "output", expected: "Bonjour Aelita" }],
    category: "this",
  },
  {
    id: "js_s5_e9",
    title: "Arrow function et this",
    description: "Les arrow functions n'ont pas leur propre this.",
    instruction: "Créez un objet <code>compteur = { n: 5, getN: () => this.n }</code>. Affichez <code>compteur.getN()</code>. Le résultat doit être <code>undefined</code> car l'arrow capture le this du scope englobant.",
    code_template: "const compteur = { n: 5, getN: () => this.n };\nconsole.log(compteur.getN());",
    solution: "const compteur = { n: 5, getN: () => this.n };\nconsole.log(compteur.getN());",
    tests: [{ type: "output", expected: "undefined" }],
    category: "this",
  },
  {
    id: "js_s5_e10",
    title: "bind",
    description: "Lier this à une valeur spécifique.",
    instruction: "Définissez <code>function presenter() { return 'Salut, je suis ' + this.nom; }</code>. Bindez-la à <code>{nom: 'Yumi'}</code> et affichez le résultat de l'appel.",
    code_template: "function presenter() { return 'Salut, je suis ' + this.nom; }\n// bind\n",
    solution: "function presenter() { return 'Salut, je suis ' + this.nom; }\nconst yumi = presenter.bind({ nom: 'Yumi' });\nconsole.log(yumi());",
    tests: [
      { type: "contains", expected: ".bind" },
      { type: "output", expected: "Salut, je suis Yumi" },
    ],
    category: "this",
  },
  {
    id: "js_s5_e11",
    title: "call",
    description: "Invoquer avec un this immédiat.",
    instruction: "Définissez <code>function info() { return this.nom + '/' + this.age; }</code>. Appelez avec <code>call</code> en passant <code>{nom: 'Odd', age: 14}</code>.",
    code_template: "function info() { return this.nom + '/' + this.age; }\n// call\n",
    solution: "function info() { return this.nom + '/' + this.age; }\nconsole.log(info.call({ nom: 'Odd', age: 14 }));",
    tests: [
      { type: "contains", expected: ".call" },
      { type: "output", expected: "Odd/14" },
    ],
    category: "this",
  },
  {
    id: "js_s5_e12",
    title: "apply",
    description: "Comme call mais avec un tableau d'arguments.",
    instruction: "Définissez <code>function additionner(a, b, c) { return a + b + c; }</code>. Appelez-la avec <code>apply</code> et le tableau <code>[1, 2, 3]</code>.",
    code_template: "function additionner(a, b, c) { return a + b + c; }\n// apply\n",
    solution: "function additionner(a, b, c) { return a + b + c; }\nconsole.log(additionner.apply(null, [1, 2, 3]));",
    tests: [
      { type: "contains", expected: ".apply" },
      { type: "output", expected: "6" },
    ],
    category: "this",
  },
  {
    id: "js_s5_e13",
    title: "Currying simple",
    description: "Une fonction qui retourne une fonction.",
    instruction: "Écrivez <code>multiplier(a)(b)</code> qui retourne a × b. Affichez <code>multiplier(3)(4)</code>.",
    code_template: "function multiplier(a) {\n  // retourne une fonction\n}\nconsole.log(multiplier(3)(4));",
    solution: "function multiplier(a) {\n  return function(b) { return a * b; };\n}\nconsole.log(multiplier(3)(4));",
    tests: [{ type: "output", expected: "12" }],
    category: "Currying",
  },
  {
    id: "js_s5_e14",
    title: "Currying à 3 niveaux",
    description: "additionner(a)(b)(c).",
    instruction: "Écrivez <code>additionner(a)(b)(c)</code> qui retourne a+b+c. Affichez le résultat de <code>additionner(10)(20)(30)</code>.",
    code_template: "function additionner(a) {\n  // \n}\nconsole.log(additionner(10)(20)(30));",
    solution: "function additionner(a) {\n  return b => c => a + b + c;\n}\nconsole.log(additionner(10)(20)(30));",
    tests: [{ type: "output", expected: "60" }],
    category: "Currying",
  },
  {
    id: "js_s5_e15",
    title: "Partial application",
    description: "Bind seulement le premier argument.",
    instruction: "Définissez <code>function f(a, b, c) { return a + b + c; }</code>. Avec <code>bind</code>, fixez a=100 et affichez f(2, 3) avec le partial.",
    code_template: "function f(a, b, c) { return a + b + c; }\n// partial avec bind\n",
    solution: "function f(a, b, c) { return a + b + c; }\nconst g = f.bind(null, 100);\nconsole.log(g(2, 3));",
    tests: [
      { type: "contains", expected: ".bind" },
      { type: "output", expected: "105" },
    ],
    category: "Partial Application",
  },
  {
    id: "js_s5_e16",
    title: "Composition de fonctions",
    description: "compose(f, g)(x) = f(g(x)).",
    instruction: "Écrivez <code>compose(f, g)</code> qui retourne une fonction qui applique d'abord g puis f. Testez avec <code>compose(x => x*2, x => x+1)(5)</code> (résultat : (5+1)*2 = 12).",
    code_template: "function compose(f, g) {\n  // \n}\nconsole.log(compose(x => x*2, x => x+1)(5));",
    solution: "function compose(f, g) {\n  return x => f(g(x));\n}\nconsole.log(compose(x => x*2, x => x+1)(5));",
    tests: [{ type: "output", expected: "12" }],
    category: "Composition",
  },
  {
    id: "js_s5_e17",
    title: "Pipe",
    description: "L'inverse de compose : applique de gauche à droite.",
    instruction: "Écrivez <code>pipe(...fns)</code> qui retourne une fonction appliquant chaque fn dans l'ordre. Testez avec <code>pipe(x => x+1, x => x*2, x => x-3)(5)</code> (résultat : ((5+1)*2)-3 = 9).",
    code_template: "function pipe(...fns) {\n  // \n}\nconsole.log(pipe(x => x+1, x => x*2, x => x-3)(5));",
    solution: "function pipe(...fns) {\n  return x => fns.reduce((acc, f) => f(acc), x);\n}\nconsole.log(pipe(x => x+1, x => x*2, x => x-3)(5));",
    tests: [
      { type: "contains", expected: "reduce" },
      { type: "output", expected: "9" },
    ],
    category: "Composition",
  },
  {
    id: "js_s5_e18",
    title: "Mémoïsation",
    description: "Cacher les résultats d'une fonction pure.",
    instruction: "Écrivez <code>memoize(fn)</code> qui retourne une version cachée de fn. Testez avec une fonction qui calcule lentement le carré (utilisez juste x*x ici), appelez 3 fois avec 5 et vérifiez que la sortie est toujours 25. Affichez les 3 résultats.",
    code_template: "function memoize(fn) {\n  // \n}\nconst sq = memoize(x => x * x);\nconsole.log(sq(5));\nconsole.log(sq(5));\nconsole.log(sq(5));",
    solution: "function memoize(fn) {\n  const cache = new Map();\n  return arg => {\n    if (cache.has(arg)) return cache.get(arg);\n    const r = fn(arg);\n    cache.set(arg, r);\n    return r;\n  };\n}\nconst sq = memoize(x => x * x);\nconsole.log(sq(5));\nconsole.log(sq(5));\nconsole.log(sq(5));",
    tests: [{ type: "output", expected: "25\n25\n25" }],
    category: "Closures",
  },
  {
    id: "js_s5_e19",
    title: "Fibonacci mémoïsé",
    description: "Closure + cache pour récursion rapide.",
    instruction: "Implémentez <code>fib(n)</code> avec memoization (via objet cache externe). Affichez <code>fib(30)</code>.",
    code_template: "const memo = {};\nfunction fib(n) {\n  // \n}\nconsole.log(fib(30));",
    solution: "const memo = {};\nfunction fib(n) {\n  if (n < 2) return n;\n  if (memo[n] !== undefined) return memo[n];\n  return memo[n] = fib(n-1) + fib(n-2);\n}\nconsole.log(fib(30));",
    tests: [{ type: "output", expected: "832040" }],
    category: "Closures",
  },
  {
    id: "js_s5_e20",
    title: "Throttle conceptuel",
    description: "Tracer combien de fois fn est appelée vs autorisée.",
    instruction: "Écrivez <code>limiter(fn, max)</code> qui empêche fn d'être appelée plus de <code>max</code> fois. Au-delà, retourne <code>'bloqué'</code>. Testez avec max=2 et 4 appels, affichez les 4 retours.",
    code_template: "function limiter(fn, max) {\n  // \n}\nconst dire = limiter(x => 'ok ' + x, 2);\nconsole.log(dire(1));\nconsole.log(dire(2));\nconsole.log(dire(3));\nconsole.log(dire(4));",
    solution: "function limiter(fn, max) {\n  let n = 0;\n  return (...args) => (++n <= max ? fn(...args) : 'bloqué');\n}\nconst dire = limiter(x => 'ok ' + x, 2);\nconsole.log(dire(1));\nconsole.log(dire(2));\nconsole.log(dire(3));\nconsole.log(dire(4));",
    tests: [{ type: "output", expected: "ok 1\nok 2\nbloqué\nbloqué" }],
    category: "Closures",
  },
  {
    id: "js_s5_e21",
    title: "Once",
    description: "fn ne s'exécute qu'une seule fois.",
    instruction: "Écrivez <code>once(fn)</code> qui n'appelle fn qu'une seule fois et retourne ensuite toujours le premier résultat. Testez avec une fonction qui retourne <code>'init'</code> et affichez 3 appels.",
    code_template: "function once(fn) {\n  // \n}\nconst init = once(() => 'init');\nconsole.log(init());\nconsole.log(init());\nconsole.log(init());",
    solution: "function once(fn) {\n  let done = false, result;\n  return (...args) => {\n    if (!done) { result = fn(...args); done = true; }\n    return result;\n  };\n}\nconst init = once(() => 'init');\nconsole.log(init());\nconsole.log(init());\nconsole.log(init());",
    tests: [{ type: "output", expected: "init\ninit\ninit" }],
    category: "Closures",
  },
  {
    id: "js_s5_e22",
    title: "Block scope",
    description: "let limite la portée à un bloc.",
    instruction: "Déclarez <code>let x = 1</code> dans le scope global, puis <code>{ let x = 2; console.log(x); }</code>, puis <code>console.log(x)</code> hors bloc. Devrait afficher 2 puis 1.",
    code_template: "let x = 1;\n{ /* bloc */ }\n",
    solution: "let x = 1;\n{ let x = 2; console.log(x); }\nconsole.log(x);",
    tests: [{ type: "output", expected: "2\n1" }],
    category: "Scope",
  },
  {
    id: "js_s5_e23",
    title: "Temporal Dead Zone",
    description: "let n'est pas accessible avant sa déclaration.",
    instruction: "Lisez la doc : essayer d'utiliser une variable <code>let</code> avant sa déclaration lance une <code>ReferenceError</code>. Utilisez try/catch pour capturer l'erreur, affichez <code>'caught'</code>.",
    code_template: "try {\n  console.log(x);\n  let x = 1;\n} catch (e) {\n  // \n}",
    solution: "try {\n  console.log(x);\n  let x = 1;\n} catch (e) {\n  console.log('caught');\n}",
    tests: [{ type: "output", expected: "caught" }],
    category: "Scope",
  },
  {
    id: "js_s5_e24",
    title: "Closure dans setTimeout",
    description: "L'arrow capture le bon scope.",
    instruction: "Lancez une boucle de 0 à 2 avec <code>let i</code> qui pousse dans un tableau <code>resultats</code> la valeur de i à chaque tour (synchrone, simulez le timing via push). Affichez le tableau joint par virgule.",
    code_template: "const resultats = [];\nfor (let i = 0; i < 3; i++) {\n  // push i\n}\nconsole.log(resultats.join(','));",
    solution: "const resultats = [];\nfor (let i = 0; i < 3; i++) {\n  resultats.push(i);\n}\nconsole.log(resultats.join(','));",
    tests: [{ type: "output", expected: "0,1,2" }],
    category: "Scope",
  },
  {
    id: "js_s5_e25",
    title: "Récursion + closure : Counter avec reset",
    description: "Compteur avec reset, valeur, set.",
    instruction: "Créez une fabrique <code>creerCompteurAvance()</code> qui retourne un objet avec <code>inc()</code>, <code>reset()</code>, et <code>valeur()</code>. Testez : inc×3, log valeur, reset, log valeur, inc, log valeur. Sorties attendues : 3, 0, 1.",
    code_template: "function creerCompteurAvance() {\n  // \n}\nconst c = creerCompteurAvance();\nc.inc(); c.inc(); c.inc();\nconsole.log(c.valeur());\nc.reset();\nconsole.log(c.valeur());\nc.inc();\nconsole.log(c.valeur());",
    solution: "function creerCompteurAvance() {\n  let n = 0;\n  return {\n    inc() { n++; },\n    reset() { n = 0; },\n    valeur() { return n; }\n  };\n}\nconst c = creerCompteurAvance();\nc.inc(); c.inc(); c.inc();\nconsole.log(c.valeur());\nc.reset();\nconsole.log(c.valeur());\nc.inc();\nconsole.log(c.valeur());",
    tests: [{ type: "output", expected: "3\n0\n1" }],
    category: "Closures",
  },
];

addExercises("javascript", exercises);
