import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/**
 * JavaScript — Part 6 : tableaux & objets avancés, ES6+ patterns.
 */
const exercises: Exercise[] = [
  {
    id: "js_s6_e1",
    title: "map basique",
    description: "Transformer chaque élément.",
    instruction: "Doublez tous les éléments de <code>[1, 2, 3, 4]</code> avec <code>map</code> et affichez le résultat séparé par virgule.",
    code_template: "const t = [1, 2, 3, 4];\n// map\n",
    solution: "const t = [1, 2, 3, 4];\nconsole.log(t.map(x => x * 2).join(','));",
    tests: [
      { type: "contains", expected: ".map" },
      { type: "output", expected: "2,4,6,8" },
    ],
    category: "Tableaux",
  },
  {
    id: "js_s6_e2",
    title: "filter basique",
    description: "Garder seulement les éléments qui passent un test.",
    instruction: "Filtrez les nombres pairs de <code>[1,2,3,4,5,6]</code> et affichez le résultat séparé par virgule.",
    code_template: "const t = [1, 2, 3, 4, 5, 6];\n// filter\n",
    solution: "const t = [1, 2, 3, 4, 5, 6];\nconsole.log(t.filter(x => x % 2 === 0).join(','));",
    tests: [
      { type: "contains", expected: ".filter" },
      { type: "output", expected: "2,4,6" },
    ],
    category: "Tableaux",
  },
  {
    id: "js_s6_e3",
    title: "reduce somme",
    description: "Accumulation classique.",
    instruction: "Sommez <code>[10, 20, 30, 40]</code> avec <code>reduce</code> et affichez le total.",
    code_template: "const t = [10, 20, 30, 40];\n// reduce\n",
    solution: "const t = [10, 20, 30, 40];\nconsole.log(t.reduce((s, x) => s + x, 0));",
    tests: [
      { type: "contains", expected: ".reduce" },
      { type: "output", expected: "100" },
    ],
    category: "Tableaux",
  },
  {
    id: "js_s6_e4",
    title: "Chaînage map + filter + reduce",
    description: "Pipeline fonctionnel.",
    instruction: "À partir de <code>[1, 2, 3, 4, 5]</code> : doublez, gardez les > 5, sommez. Affichez le résultat.",
    code_template: "const t = [1, 2, 3, 4, 5];\n// chainer\n",
    solution: "const t = [1, 2, 3, 4, 5];\nconsole.log(t.map(x => x * 2).filter(x => x > 5).reduce((s, x) => s + x, 0));",
    tests: [{ type: "output", expected: "24" }],
    category: "Tableaux",
  },
  {
    id: "js_s6_e5",
    title: "some / every",
    description: "Tester si au moins un / tous les éléments passent un test.",
    instruction: "Pour <code>[2, 4, 6, 8]</code>, affichez d'abord si TOUS sont pairs (every), puis si AU MOINS un est > 10 (some). Format : 'true' ou 'false' sur 2 lignes.",
    code_template: "const t = [2, 4, 6, 8];\n// every / some\n",
    solution: "const t = [2, 4, 6, 8];\nconsole.log(t.every(x => x % 2 === 0));\nconsole.log(t.some(x => x > 10));",
    tests: [{ type: "output", expected: "true\nfalse" }],
    category: "Tableaux",
  },
  {
    id: "js_s6_e6",
    title: "find / findIndex",
    description: "Premier élément qui matche.",
    instruction: "Dans <code>[5, 12, 8, 130, 44]</code>, trouvez la première valeur >= 10 (find) et son indice (findIndex). Affichez les 2 sur 2 lignes.",
    code_template: "const t = [5, 12, 8, 130, 44];\n// find / findIndex\n",
    solution: "const t = [5, 12, 8, 130, 44];\nconsole.log(t.find(x => x >= 10));\nconsole.log(t.findIndex(x => x >= 10));",
    tests: [{ type: "output", expected: "12\n1" }],
    category: "Tableaux",
  },
  {
    id: "js_s6_e7",
    title: "includes",
    description: "Vérifier la présence d'un élément.",
    instruction: "Affichez deux fois (true/false) : <code>[1,2,3].includes(2)</code> puis <code>['a','b'].includes('z')</code>.",
    code_template: "// 2 console.log avec includes\n",
    solution: "console.log([1,2,3].includes(2));\nconsole.log(['a','b'].includes('z'));",
    tests: [
      { type: "contains", expected: ".includes" },
      { type: "output", expected: "true\nfalse" },
    ],
    category: "Tableaux",
  },
  {
    id: "js_s6_e8",
    title: "flat",
    description: "Aplatir un tableau imbriqué d'1 niveau.",
    instruction: "Aplatissez <code>[1, [2, 3], [4, [5, 6]]]</code> et affichez le résultat (joint par virgule). Attendu : <code>1,2,3,4,5,6</code> — utilisez <code>flat(Infinity)</code>.",
    code_template: "const t = [1, [2, 3], [4, [5, 6]]];\n// flat\n",
    solution: "const t = [1, [2, 3], [4, [5, 6]]];\nconsole.log(t.flat(Infinity).join(','));",
    tests: [
      { type: "contains", expected: ".flat" },
      { type: "output", expected: "1,2,3,4,5,6" },
    ],
    category: "Tableaux",
  },
  {
    id: "js_s6_e9",
    title: "flatMap",
    description: "map + flat en une seule passe.",
    instruction: "À partir de <code>[1, 2, 3]</code>, retournez <code>[1, 1, 2, 2, 3, 3]</code> avec <code>flatMap(x => [x, x])</code>. Joignez par virgule.",
    code_template: "const t = [1, 2, 3];\n// flatMap\n",
    solution: "const t = [1, 2, 3];\nconsole.log(t.flatMap(x => [x, x]).join(','));",
    tests: [
      { type: "contains", expected: "flatMap" },
      { type: "output", expected: "1,1,2,2,3,3" },
    ],
    category: "Tableaux",
  },
  {
    id: "js_s6_e10",
    title: "sort numérique",
    description: "Attention au tri par défaut (lexicographique).",
    instruction: "Triez <code>[10, 1, 5, 2]</code> en ordre croissant numérique et affichez joint par virgule (résultat attendu : 1,2,5,10).",
    code_template: "const t = [10, 1, 5, 2];\n// sort\n",
    solution: "const t = [10, 1, 5, 2];\nconsole.log(t.sort((a, b) => a - b).join(','));",
    tests: [
      { type: "regex", expected: "sort\\(\\s*\\(?[a-z]+\\)?\\s*[=,]" },
      { type: "output", expected: "1,2,5,10" },
    ],
    category: "Tableaux",
  },
  {
    id: "js_s6_e11",
    title: "Destructuring tableau",
    description: "Extraire les premiers éléments.",
    instruction: "À partir de <code>[10, 20, 30, 40, 50]</code>, extrayez les 2 premiers et le reste avec destructuring : <code>[a, b, ...reste]</code>. Affichez <code>a b</code> puis <code>reste joint par virgule</code> sur 2 lignes.",
    code_template: "const t = [10, 20, 30, 40, 50];\n// destructuring\n",
    solution: "const t = [10, 20, 30, 40, 50];\nconst [a, b, ...reste] = t;\nconsole.log(a + ' ' + b);\nconsole.log(reste.join(','));",
    tests: [{ type: "output", expected: "10 20\n30,40,50" }],
    category: "Destructuring",
  },
  {
    id: "js_s6_e12",
    title: "Destructuring objet",
    description: "Extraire des propriétés.",
    instruction: "Avec <code>{nom: 'Aelita', age: 13, pays: 'Lyoko'}</code>, destructurez <code>nom</code> et <code>pays</code>, et affichez-les séparés par espace.",
    code_template: "const p = { nom: 'Aelita', age: 13, pays: 'Lyoko' };\n// destructuring\n",
    solution: "const p = { nom: 'Aelita', age: 13, pays: 'Lyoko' };\nconst { nom, pays } = p;\nconsole.log(nom + ' ' + pays);",
    tests: [{ type: "output", expected: "Aelita Lyoko" }],
    category: "Destructuring",
  },
  {
    id: "js_s6_e13",
    title: "Renommage en destructuring",
    description: "Utiliser un alias.",
    instruction: "Destructurez <code>{x: 5, y: 10}</code> en renommant <code>x</code> en <code>a</code> et <code>y</code> en <code>b</code>. Affichez <code>a+b</code>.",
    code_template: "const p = { x: 5, y: 10 };\n// const { x: a, y: b } = p;\n",
    solution: "const p = { x: 5, y: 10 };\nconst { x: a, y: b } = p;\nconsole.log(a + b);",
    tests: [
      { type: "regex", expected: "\\{\\s*x\\s*:\\s*a\\s*," },
      { type: "output", expected: "15" },
    ],
    category: "Destructuring",
  },
  {
    id: "js_s6_e14",
    title: "Spread tableau",
    description: "Concaténer avec spread.",
    instruction: "Concaténez <code>[1,2,3]</code> et <code>[4,5,6]</code> avec spread et affichez joint par virgule.",
    code_template: "const a = [1,2,3];\nconst b = [4,5,6];\n// spread\n",
    solution: "const a = [1,2,3];\nconst b = [4,5,6];\nconsole.log([...a, ...b].join(','));",
    tests: [
      { type: "contains", expected: "..." },
      { type: "output", expected: "1,2,3,4,5,6" },
    ],
    category: "Spread",
  },
  {
    id: "js_s6_e15",
    title: "Spread objet",
    description: "Fusionner deux objets.",
    instruction: "Fusionnez <code>{a:1, b:2}</code> et <code>{b:3, c:4}</code> avec spread. Affichez <code>JSON.stringify(resultat)</code>. Avec spread, la dernière clé écrase la première.",
    code_template: "const o1 = {a:1, b:2};\nconst o2 = {b:3, c:4};\n// fusion\n",
    solution: "const o1 = {a:1, b:2};\nconst o2 = {b:3, c:4};\nconsole.log(JSON.stringify({...o1, ...o2}));",
    tests: [{ type: "output", expected: '{"a":1,"b":3,"c":4}' }],
    category: "Spread",
  },
  {
    id: "js_s6_e16",
    title: "Object.keys / values / entries",
    description: "Itérer sur un objet.",
    instruction: "Pour <code>{x:10, y:20, z:30}</code>, affichez la somme des valeurs avec <code>Object.values</code>.",
    code_template: "const o = {x:10, y:20, z:30};\n// somme via Object.values\n",
    solution: "const o = {x:10, y:20, z:30};\nconsole.log(Object.values(o).reduce((s, v) => s + v, 0));",
    tests: [
      { type: "contains", expected: "Object.values" },
      { type: "output", expected: "60" },
    ],
    category: "Objets",
  },
  {
    id: "js_s6_e17",
    title: "Object.entries → Map",
    description: "Convertir un objet en Map.",
    instruction: "Convertissez <code>{a:1, b:2}</code> en Map et affichez la valeur de la clé 'b'.",
    code_template: "const o = {a:1, b:2};\n// new Map(Object.entries(o))\n",
    solution: "const o = {a:1, b:2};\nconst m = new Map(Object.entries(o));\nconsole.log(m.get('b'));",
    tests: [
      { type: "contains", expected: "new Map" },
      { type: "output", expected: "2" },
    ],
    category: "Objets",
  },
  {
    id: "js_s6_e18",
    title: "Object.assign",
    description: "Copier des propriétés.",
    instruction: "Avec <code>Object.assign</code>, créez un objet qui est la fusion de <code>{a:1}</code>, <code>{b:2}</code>, <code>{a:99}</code>. Affichez JSON.stringify.",
    code_template: "// Object.assign\n",
    solution: "const o = Object.assign({}, {a:1}, {b:2}, {a:99});\nconsole.log(JSON.stringify(o));",
    tests: [
      { type: "contains", expected: "Object.assign" },
      { type: "output", expected: '{"a":99,"b":2}' },
    ],
    category: "Objets",
  },
  {
    id: "js_s6_e19",
    title: "Object.freeze",
    description: "Immuabilité (shallow).",
    instruction: "Créez <code>{x:1}</code>, freezez-le, puis essayez de modifier <code>x</code> à 100. Affichez la valeur actuelle de <code>x</code> (devrait rester à 1).",
    code_template: "const o = {x:1};\nObject.freeze(o);\no.x = 100;\nconsole.log(o.x);",
    solution: "const o = {x:1};\nObject.freeze(o);\no.x = 100;\nconsole.log(o.x);",
    tests: [{ type: "output", expected: "1" }],
    category: "Objets",
    hint: "En mode non-strict la modif est silencieusement ignorée.",
  },
  {
    id: "js_s6_e20",
    title: "Getter / setter",
    description: "Propriété calculée.",
    instruction: "Créez un objet <code>cercle</code> avec un getter <code>aire</code> qui calcule πr² (où <code>r</code> est une propriété de l'objet, valeur 5). Affichez l'aire arrondie à 2 décimales.",
    code_template: "const cercle = {\n  r: 5,\n  // get aire()\n};\nconsole.log(cercle.aire.toFixed(2));",
    solution: "const cercle = {\n  r: 5,\n  get aire() { return Math.PI * this.r * this.r; }\n};\nconsole.log(cercle.aire.toFixed(2));",
    tests: [
      { type: "contains", expected: "get aire" },
      { type: "output", expected: "78.54" },
    ],
    category: "Objets",
  },
  {
    id: "js_s6_e21",
    title: "Map basique",
    description: "Clés non-string.",
    instruction: "Créez une Map, ajoutez les paires (1, 'un'), (2, 'deux'), (3, 'trois'). Affichez la valeur pour la clé 2.",
    code_template: "const m = new Map();\n// 3 sets\nconsole.log(m.get(2));",
    solution: "const m = new Map();\nm.set(1, 'un'); m.set(2, 'deux'); m.set(3, 'trois');\nconsole.log(m.get(2));",
    tests: [{ type: "output", expected: "deux" }],
    category: "Map/Set",
  },
  {
    id: "js_s6_e22",
    title: "Set unique",
    description: "Déduplication.",
    instruction: "À partir de <code>[1,2,2,3,3,3,4]</code>, retournez un tableau unique en utilisant un <code>Set</code>. Affichez joint par virgule.",
    code_template: "const t = [1,2,2,3,3,3,4];\n// new Set + spread\n",
    solution: "const t = [1,2,2,3,3,3,4];\nconsole.log([...new Set(t)].join(','));",
    tests: [
      { type: "contains", expected: "new Set" },
      { type: "output", expected: "1,2,3,4" },
    ],
    category: "Map/Set",
  },
  {
    id: "js_s6_e23",
    title: "Set intersection",
    description: "Éléments communs à 2 sets.",
    instruction: "Pour A = {1,2,3,4} et B = {3,4,5,6}, calculez l'intersection (avec set + filter). Affichez joint par virgule en ordre croissant.",
    code_template: "const A = new Set([1,2,3,4]);\nconst B = new Set([3,4,5,6]);\n// intersection\n",
    solution: "const A = new Set([1,2,3,4]);\nconst B = new Set([3,4,5,6]);\nconst inter = [...A].filter(x => B.has(x));\nconsole.log(inter.sort((a,b)=>a-b).join(','));",
    tests: [{ type: "output", expected: "3,4" }],
    category: "Map/Set",
  },
  {
    id: "js_s6_e24",
    title: "Clone superficiel",
    description: "Différence avec assignation.",
    instruction: "Créez <code>a = {x:1}</code>, clonez-le avec spread dans <code>b</code>, modifiez <code>b.x = 99</code>. Affichez <code>a.x</code> puis <code>b.x</code> sur 2 lignes (a.x devrait rester à 1).",
    code_template: "const a = {x:1};\n// clone + modif\n",
    solution: "const a = {x:1};\nconst b = {...a};\nb.x = 99;\nconsole.log(a.x);\nconsole.log(b.x);",
    tests: [{ type: "output", expected: "1\n99" }],
    category: "Objets",
  },
  {
    id: "js_s6_e25",
    title: "Deep clone via JSON",
    description: "Clone profond pour données sérialisables.",
    instruction: "Avec <code>a = {x: {y: 1}}</code>, deep-clonez via <code>JSON.parse(JSON.stringify(a))</code>, modifiez la copie, et vérifiez que l'original n'a pas changé. Affichez <code>a.x.y</code> puis la copie modifiée.",
    code_template: "const a = {x: {y: 1}};\nconst b = JSON.parse(JSON.stringify(a));\nb.x.y = 99;\nconsole.log(a.x.y);\nconsole.log(b.x.y);",
    solution: "const a = {x: {y: 1}};\nconst b = JSON.parse(JSON.stringify(a));\nb.x.y = 99;\nconsole.log(a.x.y);\nconsole.log(b.x.y);",
    tests: [{ type: "output", expected: "1\n99" }],
    category: "Objets",
  },
];

addExercises("javascript", exercises);
