import { addExercises } from ".";
import type { Exercise } from "@/app/exercises/[module]/exercise-client";

// @ts-nocheck — Auto-converted from exercises-js-part1.js
const exercises: Exercise[] = [
    // === PREMIERS PAS (1-5) ===
    {
      id: "js_s1_e1",
      title: "Hello World",
      description: "Votre premier programme JavaScript - affichez 'Hello, World!'",
      instruction: "Utilisez <code>console.log()</code> pour afficher le message <strong>Hello, World!</strong> dans la console.",
      code_template: '// Écrivez votre code ici\n',
      solution: 'console.log("Hello, World!");',
      tests: [{ type: "output", expected: "Hello, World!" }],
      hint: "Utilisez console.log() avec des guillemets autour du texte.",
      help_steps: [
        "1. Tapez <code>console.log(</code> pour commencer",
        '2. Ajoutez des guillemets doubles <code>""</code>',
        "3. Écrivez le message entre les guillemets",
        "4. Fermez avec la parenthèse <code>)</code> et un point-virgule <code>;</code>",
      ],
    },
    {
      id: "js_s1_e2",
      title: "Afficher un nombre",
      description: "Affichez le nombre 42 dans la console.",
      instruction: "Utilisez <code>console.log()</code> pour afficher le nombre <strong>42</strong>. Les nombres n'ont pas besoin de guillemets.",
      code_template: "// Affichez le nombre 42\n",
      solution: "console.log(42);",
      tests: [{ type: "output", expected: "42" }],
      hint: "Les nombres s'écrivent sans guillemets : console.log(42);",
      help_steps: [
        "1. Tapez <code>console.log(</code>",
        "2. Écrivez le nombre <code>42</code> sans guillemets",
        "3. Fermez avec <code>);</code>",
      ],
    },
    {
      id: "js_s1_e3",
      title: "Commentaires",
      description: "Apprenez à écrire des commentaires en JavaScript.",
      instruction: "Écrivez un commentaire sur une ligne avec <code>//</code> puis affichez <strong>JS est génial</strong> avec console.log().",
      code_template: "// Écrivez un commentaire ici\n// Puis affichez le message\n",
      solution: '// Mon commentaire\nconsole.log("JS est génial");',
      tests: [
        { type: "output", expected: "JS est génial" },
        { type: "code_match", expected: "^\\/\\/" },
      ],
      hint: "Un commentaire commence par // et console.log() affiche du texte.",
      help_steps: [
        "1. Les commentaires commencent par <code>//</code>",
        '2. Ensuite écrivez <code>console.log("JS est génial");</code>',
      ],
    },
    {
      id: "js_s1_e4",
      title: "Plusieurs messages",
      description: "Affichez plusieurs messages dans la console.",
      instruction: "Affichez <strong>Bonjour</strong> puis <strong>JavaScript</strong> sur deux lignes séparées avec deux console.log().",
      code_template: "// Affichez deux messages\n",
      solution: 'console.log("Bonjour");\nconsole.log("JavaScript");',
      tests: [
        { type: "output", expected: "Bonjour" },
        { type: "output", expected: "JavaScript" },
      ],
      hint: "Utilisez deux instructions console.log() séparées.",
      help_steps: [
        '1. Écrivez <code>console.log("Bonjour");</code>',
        '2. Sur la ligne suivante : <code>console.log("JavaScript");</code>',
      ],
    },
    {
      id: "js_s1_e5",
      title: "Opérations mathématiques",
      description: "Affichez le résultat d'un calcul.",
      instruction: "Affichez le résultat de <strong>15 + 27</strong> avec console.log(). JavaScript calcule automatiquement.",
      code_template: "// Affichez le résultat de 15 + 27\n",
      solution: "console.log(15 + 27);",
      tests: [{ type: "output", expected: "42" }],
      hint: "Écrivez l'opération directement dans console.log() sans guillemets.",
      help_steps: [
        "1. Tapez <code>console.log(</code>",
        "2. Écrivez <code>15 + 27</code> sans guillemets",
        "3. Fermez avec <code>);</code>",
      ],
    },

    // === VARIABLES (6-10) ===
    {
      id: "js_s1_e6",
      title: "Déclarer une variable let",
      description: "Créez une variable avec let et affichez-la.",
      instruction: "Déclarez une variable <code>prenom</code> avec <code>let</code> contenant <strong>\"Alice\"</strong>, puis affichez-la.",
      code_template: "// Déclarez la variable prenom\n\n// Affichez-la\n",
      solution: 'let prenom = "Alice";\nconsole.log(prenom);',
      tests: [{ type: "output", expected: "Alice" }],
      hint: "Syntaxe : let nomVariable = \"valeur\";",
      help_steps: [
        '1. Déclarez : <code>let prenom = "Alice";</code>',
        "2. Affichez : <code>console.log(prenom);</code>",
      ],
    },
    {
      id: "js_s1_e7",
      title: "Déclarer une constante",
      description: "Créez une constante avec const.",
      instruction: "Déclarez une constante <code>PI</code> avec la valeur <strong>3.14</strong> puis affichez-la.",
      code_template: "// Déclarez la constante PI\n\n// Affichez-la\n",
      solution: "const PI = 3.14;\nconsole.log(PI);",
      tests: [{ type: "output", expected: "3.14" }],
      hint: "Utilisez const au lieu de let pour une valeur qui ne change pas.",
      help_steps: [
        "1. Déclarez : <code>const PI = 3.14;</code>",
        "2. Affichez : <code>console.log(PI);</code>",
      ],
    },
    {
      id: "js_s1_e8",
      title: "Modifier une variable",
      description: "Modifiez la valeur d'une variable.",
      instruction: "Déclarez <code>score</code> à <strong>0</strong>, changez-le à <strong>100</strong>, puis affichez-le.",
      code_template: "// Déclarez score à 0\n\n// Changez-le à 100\n\n// Affichez-le\n",
      solution: "let score = 0;\nscore = 100;\nconsole.log(score);",
      tests: [{ type: "output", expected: "100" }],
      hint: "Utilisez let pour déclarer, puis réassignez sans let.",
      help_steps: [
        "1. <code>let score = 0;</code>",
        "2. <code>score = 100;</code> (sans let !)",
        "3. <code>console.log(score);</code>",
      ],
    },
    {
      id: "js_s1_e9",
      title: "Concaténation de strings",
      description: "Combinez des chaînes de caractères.",
      instruction: "Déclarez <code>nom</code> = <strong>\"Carthage\"</strong> et affichez <strong>\"Projet Carthage\"</strong> en concaténant <code>\"Projet \" + nom</code>.",
      code_template: '// Déclarez nom\n\n// Affichez "Projet " + nom\n',
      solution: 'let nom = "Carthage";\nconsole.log("Projet " + nom);',
      tests: [{ type: "output", expected: "Projet Carthage" }],
      hint: "L'opérateur + combine les chaînes de caractères.",
      help_steps: [
        '1. <code>let nom = "Carthage";</code>',
        '2. <code>console.log("Projet " + nom);</code>',
      ],
    },
    {
      id: "js_s1_e10",
      title: "Template literals",
      description: "Utilisez les backticks pour les template literals.",
      instruction: "Déclarez <code>age</code> = <strong>25</strong> et affichez <strong>\"J'ai 25 ans\"</strong> en utilisant un template literal avec <code>${}</code>.",
      code_template: "// Déclarez age\n\n// Affichez avec un template literal\n",
      solution: "let age = 25;\nconsole.log(`J'ai ${age} ans`);",
      tests: [{ type: "output", expected: "J'ai 25 ans" }],
      hint: "Les template literals utilisent des backticks ` et ${variable} pour insérer des valeurs.",
      help_steps: [
        "1. <code>let age = 25;</code>",
        "2. <code>console.log(`J'ai ${age} ans`);</code>",
        "3. Utilisez les backticks ` (AltGr + 7) et non des guillemets",
      ],
    },

    // === TYPES DE DONNÉES (11-15) ===
    {
      id: "js_s1_e11",
      title: "typeof - Vérifier le type",
      description: "Découvrez les types de données JavaScript.",
      instruction: "Affichez le type de <strong>\"Bonjour\"</strong> avec <code>typeof</code>.",
      code_template: '// Affichez le type de "Bonjour"\n',
      solution: 'console.log(typeof "Bonjour");',
      tests: [{ type: "output", expected: "string" }],
      hint: "typeof renvoie le type d'une valeur sous forme de chaîne.",
      help_steps: [
        '1. <code>console.log(typeof "Bonjour");</code>',
        "2. typeof renvoie \"string\" pour les chaînes de caractères",
      ],
    },
    {
      id: "js_s1_e12",
      title: "Booléens",
      description: "Découvrez les valeurs true et false.",
      instruction: "Déclarez <code>estMajeur</code> à <strong>true</strong> et affichez-le.",
      code_template: "// Déclarez estMajeur\n\n// Affichez-le\n",
      solution: "let estMajeur = true;\nconsole.log(estMajeur);",
      tests: [{ type: "output", expected: "true" }],
      hint: "true et false sont des booléens, sans guillemets.",
      help_steps: [
        "1. <code>let estMajeur = true;</code> (sans guillemets !)",
        "2. <code>console.log(estMajeur);</code>",
      ],
    },
    {
      id: "js_s1_e13",
      title: "Conversion en nombre",
      description: "Convertissez une chaîne en nombre.",
      instruction: "Déclarez <code>texte</code> = <strong>\"42\"</strong>, convertissez-le en nombre avec <code>Number()</code> et affichez le résultat de <code>nombre + 8</code>.",
      code_template: '// Déclarez texte = "42"\n\n// Convertissez et calculez\n',
      solution: 'let texte = "42";\nlet nombre = Number(texte);\nconsole.log(nombre + 8);',
      tests: [{ type: "output", expected: "50" }],
      hint: "Number() convertit une chaîne en nombre.",
      help_steps: [
        '1. <code>let texte = "42";</code>',
        "2. <code>let nombre = Number(texte);</code>",
        "3. <code>console.log(nombre + 8);</code>",
      ],
    },
    {
      id: "js_s1_e14",
      title: "null et undefined",
      description: "Comprenez la différence entre null et undefined.",
      instruction: "Déclarez <code>a</code> sans valeur (undefined) et <code>b</code> = <strong>null</strong>. Affichez les deux.",
      code_template: "// Déclarez a sans valeur\n\n// Déclarez b = null\n\n// Affichez les deux\n",
      solution: "let a;\nlet b = null;\nconsole.log(a);\nconsole.log(b);",
      tests: [
        { type: "output", expected: "undefined" },
        { type: "output", expected: "null" },
      ],
      hint: "Une variable déclarée sans valeur est undefined. null est une valeur explicite.",
      help_steps: [
        "1. <code>let a;</code> (pas de valeur = undefined)",
        "2. <code>let b = null;</code>",
        "3. Affichez les deux avec console.log()",
      ],
    },
    {
      id: "js_s1_e15",
      title: "Opérateurs arithmétiques",
      description: "Utilisez les opérateurs +, -, *, /, %.",
      instruction: "Calculez et affichez le <strong>reste</strong> de la division de <strong>17</strong> par <strong>5</strong> (opérateur modulo <code>%</code>).",
      code_template: "// Affichez le reste de 17 / 5\n",
      solution: "console.log(17 % 5);",
      tests: [{ type: "output", expected: "2" }],
      hint: "L'opérateur % (modulo) donne le reste d'une division.",
      help_steps: [
        "1. L'opérateur modulo est <code>%</code>",
        "2. <code>console.log(17 % 5);</code> affiche 2",
      ],
    },

    // === CONDITIONS (16-20) ===
    {
      id: "js_s1_e16",
      title: "If / else simple",
      description: "Votre première condition.",
      instruction: "Déclarez <code>temperature</code> = <strong>35</strong>. Si elle est supérieure à 30, affichez <strong>\"Il fait chaud\"</strong>, sinon <strong>\"Il fait bon\"</strong>.",
      code_template: "let temperature = 35;\n\n// Écrivez la condition if/else\n",
      solution: 'let temperature = 35;\nif (temperature > 30) {\n  console.log("Il fait chaud");\n} else {\n  console.log("Il fait bon");\n}',
      tests: [{ type: "output", expected: "Il fait chaud" }],
      hint: "Syntaxe : if (condition) { ... } else { ... }",
      help_steps: [
        "1. <code>if (temperature > 30) {</code>",
        '2. <code>  console.log("Il fait chaud");</code>',
        "3. <code>} else {</code>",
        '4. <code>  console.log("Il fait bon");</code>',
        "5. <code>}</code>",
      ],
    },
    {
      id: "js_s1_e17",
      title: "Comparaison stricte",
      description: "Différence entre == et ===.",
      instruction: "Affichez le résultat de <code>5 === \"5\"</code> (comparaison stricte).",
      code_template: '// Affichez le résultat de 5 === "5"\n',
      solution: 'console.log(5 === "5");',
      tests: [{ type: "output", expected: "false" }],
      hint: "=== compare la valeur ET le type. 5 (number) !== \"5\" (string).",
      help_steps: [
        '1. <code>console.log(5 === "5");</code>',
        "2. === vérifie le type aussi, donc number !== string → false",
      ],
    },
    {
      id: "js_s1_e18",
      title: "If / else if / else",
      description: "Conditions multiples.",
      instruction: "Déclarez <code>note</code> = <strong>15</strong>. Affichez <strong>\"Excellent\"</strong> si >= 16, <strong>\"Bien\"</strong> si >= 12, <strong>\"Passable\"</strong> si >= 10, sinon <strong>\"Insuffisant\"</strong>.",
      code_template: "let note = 15;\n\n// Écrivez les conditions\n",
      solution: 'let note = 15;\nif (note >= 16) {\n  console.log("Excellent");\n} else if (note >= 12) {\n  console.log("Bien");\n} else if (note >= 10) {\n  console.log("Passable");\n} else {\n  console.log("Insuffisant");\n}',
      tests: [{ type: "output", expected: "Bien" }],
      hint: "Utilisez else if pour enchaîner les conditions.",
      help_steps: [
        "1. <code>if (note >= 16) { ... }</code>",
        "2. <code>else if (note >= 12) { ... }</code>",
        "3. <code>else if (note >= 10) { ... }</code>",
        "4. <code>else { ... }</code>",
      ],
    },
    {
      id: "js_s1_e19",
      title: "Opérateur ternaire",
      description: "Raccourci pour if/else.",
      instruction: "Déclarez <code>age</code> = <strong>20</strong>. Utilisez l'opérateur ternaire pour stocker <strong>\"majeur\"</strong> ou <strong>\"mineur\"</strong> dans <code>statut</code>, puis affichez-le.",
      code_template: "let age = 20;\n\n// Utilisez l'opérateur ternaire\n\n// Affichez statut\n",
      solution: 'let age = 20;\nlet statut = age >= 18 ? "majeur" : "mineur";\nconsole.log(statut);',
      tests: [{ type: "output", expected: "majeur" }],
      hint: "Syntaxe : condition ? valeurSiVrai : valeurSiFaux",
      help_steps: [
        '1. <code>let statut = age >= 18 ? "majeur" : "mineur";</code>',
        "2. <code>console.log(statut);</code>",
      ],
    },
    {
      id: "js_s1_e20",
      title: "Opérateurs logiques",
      description: "Combinez des conditions avec && et ||.",
      instruction: "Déclarez <code>age</code> = <strong>25</strong> et <code>permis</code> = <strong>true</strong>. Affichez <strong>\"Peut conduire\"</strong> si age >= 18 ET permis est true.",
      code_template: "let age = 25;\nlet permis = true;\n\n// Vérifiez les deux conditions\n",
      solution: 'let age = 25;\nlet permis = true;\nif (age >= 18 && permis) {\n  console.log("Peut conduire");\n}',
      tests: [{ type: "output", expected: "Peut conduire" }],
      hint: "&& signifie ET : les deux conditions doivent être vraies.",
      help_steps: [
        "1. <code>if (age >= 18 && permis) {</code>",
        '2. <code>  console.log("Peut conduire");</code>',
        "3. <code>}</code>",
      ],
    },

    // === BOUCLES (21-25) ===
    {
      id: "js_s1_e21",
      title: "Boucle for",
      description: "Votre première boucle.",
      instruction: "Affichez les nombres de <strong>1 à 5</strong> avec une boucle <code>for</code>.",
      code_template: "// Boucle for de 1 à 5\n",
      solution: "for (let i = 1; i <= 5; i++) {\n  console.log(i);\n}",
      tests: [
        { type: "output", expected: "1" },
        { type: "output", expected: "3" },
        { type: "output", expected: "5" },
      ],
      hint: "Syntaxe : for (let i = 1; i <= 5; i++) { ... }",
      help_steps: [
        "1. <code>for (let i = 1; i <= 5; i++) {</code>",
        "2. <code>  console.log(i);</code>",
        "3. <code>}</code>",
      ],
    },
    {
      id: "js_s1_e22",
      title: "Boucle while",
      description: "Boucle avec condition.",
      instruction: "Utilisez une boucle <code>while</code> pour afficher les nombres de <strong>1 à 3</strong>.",
      code_template: "let i = 1;\n\n// Boucle while\n",
      solution: "let i = 1;\nwhile (i <= 3) {\n  console.log(i);\n  i++;\n}",
      tests: [
        { type: "output", expected: "1" },
        { type: "output", expected: "2" },
        { type: "output", expected: "3" },
      ],
      hint: "while (condition) { ... } — n'oubliez pas d'incrémenter i !",
      help_steps: [
        "1. <code>while (i <= 3) {</code>",
        "2. <code>  console.log(i);</code>",
        "3. <code>  i++;</code>",
        "4. <code>}</code>",
      ],
    },
    {
      id: "js_s1_e23",
      title: "Somme avec boucle",
      description: "Calculez une somme avec une boucle.",
      instruction: "Calculez la somme des nombres de <strong>1 à 10</strong> et affichez le résultat (<strong>55</strong>).",
      code_template: "let somme = 0;\n\n// Boucle pour additionner 1 à 10\n\n// Affichez la somme\n",
      solution: "let somme = 0;\nfor (let i = 1; i <= 10; i++) {\n  somme += i;\n}\nconsole.log(somme);",
      tests: [{ type: "output", expected: "55" }],
      hint: "Utilisez somme += i dans la boucle pour accumuler.",
      help_steps: [
        "1. <code>for (let i = 1; i <= 10; i++) {</code>",
        "2. <code>  somme += i;</code> (équivalent à somme = somme + i)",
        "3. <code>}</code>",
        "4. <code>console.log(somme);</code>",
      ],
    },
    {
      id: "js_s1_e24",
      title: "Boucle avec condition",
      description: "Combinez boucle et condition.",
      instruction: "Affichez uniquement les nombres <strong>pairs</strong> de 1 à 10.",
      code_template: "// Affichez les nombres pairs de 1 à 10\n",
      solution: "for (let i = 1; i <= 10; i++) {\n  if (i % 2 === 0) {\n    console.log(i);\n  }\n}",
      tests: [
        { type: "output", expected: "2" },
        { type: "output", expected: "6" },
        { type: "output", expected: "10" },
      ],
      hint: "Un nombre est pair si nombre % 2 === 0.",
      help_steps: [
        "1. <code>for (let i = 1; i <= 10; i++) {</code>",
        "2. <code>  if (i % 2 === 0) {</code>",
        "3. <code>    console.log(i);</code>",
        "4. <code>  }</code>",
        "5. <code>}</code>",
      ],
    },
    {
      id: "js_s1_e25",
      title: "FizzBuzz simplifié",
      description: "Le classique FizzBuzz !",
      instruction: "Pour les nombres de 1 à 15 : affichez <strong>\"Fizz\"</strong> si divisible par 3, <strong>\"Buzz\"</strong> si divisible par 5, <strong>\"FizzBuzz\"</strong> si divisible par les deux, sinon le nombre.",
      code_template: "// FizzBuzz de 1 à 15\n",
      solution: 'for (let i = 1; i <= 15; i++) {\n  if (i % 3 === 0 && i % 5 === 0) {\n    console.log("FizzBuzz");\n  } else if (i % 3 === 0) {\n    console.log("Fizz");\n  } else if (i % 5 === 0) {\n    console.log("Buzz");\n  } else {\n    console.log(i);\n  }\n}',
      tests: [
        { type: "output", expected: "FizzBuzz" },
        { type: "output", expected: "Fizz" },
        { type: "output", expected: "Buzz" },
        { type: "output", expected: "1" },
      ],
      hint: "Testez d'abord la condition combinée (% 3 && % 5) avant les conditions individuelles.",
      help_steps: [
        "1. Boucle <code>for (let i = 1; i <= 15; i++)</code>",
        "2. D'abord tester <code>i % 3 === 0 && i % 5 === 0</code> → FizzBuzz",
        "3. Puis <code>i % 3 === 0</code> → Fizz",
        "4. Puis <code>i % 5 === 0</code> → Buzz",
        "5. Sinon afficher <code>i</code>",
      ],
    },
  ];

addExercises("javascript", exercises);
