import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/**
 * JavaScript — Part 7 : Promises, async/await, error handling, timing patterns.
 *
 * Note : la sandbox JS du validateur exécute le code synchronement et capture
 * console.log. Pour rester déterministe, on utilise des promesses déjà résolues
 * (Promise.resolve, Promise.then) plutôt que setTimeout. async/await est OK.
 */
const exercises: Exercise[] = [
  {
    id: "js_s7_e1",
    title: "Promise résolue",
    description: "Premier .then().",
    instruction: "Créez <code>Promise.resolve(42)</code> et affichez la valeur via <code>.then</code>.",
    code_template: "// Promise.resolve(42).then(...)\n",
    solution: "Promise.resolve(42).then(v => console.log(v));",
    tests: [
      { type: "contains", expected: "Promise.resolve" },
      { type: "output", expected: "42" },
    ],
    category: "Promises",
  },
  {
    id: "js_s7_e2",
    title: "Chain .then",
    description: "Transformer dans une chaîne.",
    instruction: "À partir de <code>Promise.resolve(5)</code>, ajoutez +10 dans un .then, puis multipliez par 2 dans un second .then, et affichez le résultat.",
    code_template: "// chain\n",
    solution: "Promise.resolve(5).then(v => v + 10).then(v => v * 2).then(v => console.log(v));",
    tests: [{ type: "output", expected: "30" }],
    category: "Promises",
  },
  {
    id: "js_s7_e3",
    title: "Promise rejetée",
    description: "Catch d'une erreur.",
    instruction: "Faites <code>Promise.reject('échec')</code> et capturez l'erreur dans un <code>.catch</code> pour afficher <code>'erreur: échec'</code>.",
    code_template: "// reject + catch\n",
    solution: "Promise.reject('échec').catch(e => console.log('erreur: ' + e));",
    tests: [
      { type: "contains", expected: ".catch" },
      { type: "output", expected: "erreur: échec" },
    ],
    category: "Promises",
  },
  {
    id: "js_s7_e4",
    title: "async/await basique",
    description: "Équivalent moderne du .then.",
    instruction: "Écrivez une fonction async <code>main()</code> qui await <code>Promise.resolve('OK')</code> et affiche le résultat. N'oubliez pas d'appeler <code>main()</code>.",
    code_template: "async function main() {\n  // await\n}\nmain();",
    solution: "async function main() {\n  const r = await Promise.resolve('OK');\n  console.log(r);\n}\nmain();",
    tests: [
      { type: "contains", expected: "await" },
      { type: "output", expected: "OK" },
    ],
    category: "async/await",
  },
  {
    id: "js_s7_e5",
    title: "async + try/catch",
    description: "Gestion d'erreur dans une fonction async.",
    instruction: "Écrivez une fonction async qui await une promesse rejetée avec <code>'fail'</code>. Capturez l'erreur dans un try/catch et affichez <code>'rattrapé: fail'</code>.",
    code_template: "async function main() {\n  try {\n    // await reject\n  } catch (e) {\n    // \n  }\n}\nmain();",
    solution: "async function main() {\n  try {\n    await Promise.reject('fail');\n  } catch (e) {\n    console.log('rattrapé: ' + e);\n  }\n}\nmain();",
    tests: [{ type: "output", expected: "rattrapé: fail" }],
    category: "async/await",
  },
  {
    id: "js_s7_e6",
    title: "Promise.all (séquentiel apparent)",
    description: "Attendre N promesses parallèles.",
    instruction: "Avec <code>Promise.all([Promise.resolve(1), Promise.resolve(2), Promise.resolve(3)])</code>, additionnez les résultats et affichez la somme.",
    code_template: "// Promise.all\n",
    solution: "Promise.all([Promise.resolve(1), Promise.resolve(2), Promise.resolve(3)]).then(arr => console.log(arr.reduce((s, v) => s + v, 0)));",
    tests: [
      { type: "contains", expected: "Promise.all" },
      { type: "output", expected: "6" },
    ],
    category: "Promises",
  },
  {
    id: "js_s7_e7",
    title: "Promise.race",
    description: "Le premier qui termine gagne.",
    instruction: "Avec <code>Promise.race([Promise.resolve('A'), Promise.reject('B')])</code>, affichez le gagnant (A car déjà résolu). Utilisez .then.",
    code_template: "// race\n",
    solution: "Promise.race([Promise.resolve('A'), Promise.reject('B')]).then(v => console.log(v));",
    tests: [
      { type: "contains", expected: "Promise.race" },
      { type: "output", expected: "A" },
    ],
    category: "Promises",
  },
  {
    id: "js_s7_e8",
    title: "Promise.allSettled",
    description: "Attendre la fin de toutes (succès ou échec).",
    instruction: "Avec <code>Promise.allSettled([Promise.resolve(1), Promise.reject('x'), Promise.resolve(3)])</code>, comptez le nombre de promesses <code>fulfilled</code> et affichez le total.",
    code_template: "// allSettled\n",
    solution: "Promise.allSettled([Promise.resolve(1), Promise.reject('x'), Promise.resolve(3)]).then(results => console.log(results.filter(r => r.status === 'fulfilled').length));",
    tests: [{ type: "output", expected: "2" }],
    category: "Promises",
  },
  {
    id: "js_s7_e9",
    title: "Chaine async séquentielle",
    description: "Plusieurs await à la suite.",
    instruction: "Écrivez une fonction async qui : await Promise.resolve(10), puis await Promise.resolve(20), puis affiche leur somme.",
    code_template: "async function main() {\n  // 2 await + log\n}\nmain();",
    solution: "async function main() {\n  const a = await Promise.resolve(10);\n  const b = await Promise.resolve(20);\n  console.log(a + b);\n}\nmain();",
    tests: [{ type: "output", expected: "30" }],
    category: "async/await",
  },
  {
    id: "js_s7_e10",
    title: "Parallel via Promise.all dans async",
    description: "Lancer en parallèle, attendre tout.",
    instruction: "Dans une fonction async, lancez deux promesses <code>Promise.resolve(100)</code> et <code>Promise.resolve(200)</code> en parallèle via <code>Promise.all</code>, puis affichez leur somme.",
    code_template: "async function main() {\n  // Promise.all + await\n}\nmain();",
    solution: "async function main() {\n  const [a, b] = await Promise.all([Promise.resolve(100), Promise.resolve(200)]);\n  console.log(a + b);\n}\nmain();",
    tests: [{ type: "output", expected: "300" }],
    category: "async/await",
  },
  {
    id: "js_s7_e11",
    title: "Wrapper Promise depuis callback",
    description: "Promisifier un pattern à callback.",
    instruction: "Écrivez <code>wrap(cb)</code> qui retourne une promesse résolue par <code>cb(null, valeur)</code>. Testez avec un callback qui passe <code>(null, 42)</code>.",
    code_template: "function wrap(fnAvecCb) {\n  return new Promise((resolve, reject) => {\n    fnAvecCb((err, val) => err ? reject(err) : resolve(val));\n  });\n}\nwrap(cb => cb(null, 42)).then(v => console.log(v));",
    solution: "function wrap(fnAvecCb) {\n  return new Promise((resolve, reject) => {\n    fnAvecCb((err, val) => err ? reject(err) : resolve(val));\n  });\n}\nwrap(cb => cb(null, 42)).then(v => console.log(v));",
    tests: [{ type: "output", expected: "42" }],
    category: "Promises",
  },
  {
    id: "js_s7_e12",
    title: "Compteur via Promise.then",
    description: "Microtask queue.",
    instruction: "Affichez <code>1</code> synchroneement, lancez <code>Promise.resolve().then(() => console.log(2))</code>, puis affichez <code>3</code> synchrone. L'ordre attendu est 1, 3, 2 (le then se résout après le code sync).",
    code_template: "// 3 logs en bon ordre\n",
    solution: "console.log(1);\nPromise.resolve().then(() => console.log(2));\nconsole.log(3);",
    tests: [{ type: "output", expected: "1\n3\n2" }],
    category: "Microtasks",
  },
  {
    id: "js_s7_e13",
    title: "await dans une boucle",
    description: "Séquentiel sur N éléments.",
    instruction: "Sommez les valeurs de <code>[1, 2, 3, 4]</code> où chaque await retourne la valeur via <code>Promise.resolve</code>. Affichez la somme.",
    code_template: "async function main() {\n  const t = [1, 2, 3, 4];\n  let s = 0;\n  // boucle for-of avec await\n  console.log(s);\n}\nmain();",
    solution: "async function main() {\n  const t = [1, 2, 3, 4];\n  let s = 0;\n  for (const v of t) s += await Promise.resolve(v);\n  console.log(s);\n}\nmain();",
    tests: [{ type: "output", expected: "10" }],
    category: "async/await",
  },
  {
    id: "js_s7_e14",
    title: "Promise.all avec map",
    description: "Convertir un tableau en promesses puis attendre.",
    instruction: "À partir de <code>[1, 2, 3]</code>, créez un tableau de promesses qui retournent chacune leur valeur × 10, puis <code>Promise.all</code> et somme.",
    code_template: "Promise.all([1, 2, 3].map(/* ... */))\n  .then(arr => console.log(arr.reduce((s, v) => s + v, 0)));",
    solution: "Promise.all([1, 2, 3].map(v => Promise.resolve(v * 10)))\n  .then(arr => console.log(arr.reduce((s, v) => s + v, 0)));",
    tests: [{ type: "output", expected: "60" }],
    category: "Promises",
  },
  {
    id: "js_s7_e15",
    title: "Erreur dans .then",
    description: "Throw dans then est rattrapé par catch.",
    instruction: "Dans une chaîne, faites <code>Promise.resolve(1).then(() => { throw new Error('boom'); }).catch(e => console.log('attrapé: ' + e.message));</code>.",
    code_template: "// throw + catch\n",
    solution: "Promise.resolve(1).then(() => { throw new Error('boom'); }).catch(e => console.log('attrapé: ' + e.message));",
    tests: [{ type: "output", expected: "attrapé: boom" }],
    category: "Promises",
  },
  {
    id: "js_s7_e16",
    title: "Finally",
    description: "Exécuter du code quelle que soit l'issue.",
    instruction: "Avec <code>Promise.resolve('ok')</code>, chainez .then qui affiche 'résultat: ok', puis .finally qui affiche 'terminé'.",
    code_template: "// then + finally\n",
    solution: "Promise.resolve('ok').then(v => console.log('résultat: ' + v)).finally(() => console.log('terminé'));",
    tests: [
      { type: "contains", expected: ".finally" },
      { type: "output", expected: "résultat: ok\nterminé" },
    ],
    category: "Promises",
  },
  {
    id: "js_s7_e17",
    title: "Sequential reduce",
    description: "Chaîner des promesses dynamiquement avec reduce.",
    instruction: "À partir de <code>[1, 2, 3]</code>, chainez via reduce des promesses qui multiplient l'accumulateur par la valeur (init=1). Affichez le résultat final (6).",
    code_template: "[1, 2, 3].reduce(/* ... */, Promise.resolve(1))\n  .then(v => console.log(v));",
    solution: "[1, 2, 3].reduce((p, v) => p.then(acc => Promise.resolve(acc * v)), Promise.resolve(1))\n  .then(v => console.log(v));",
    tests: [{ type: "output", expected: "6" }],
    category: "Promises",
  },
  {
    id: "js_s7_e18",
    title: "Async IIFE",
    description: "Top-level await alternative.",
    instruction: "Utilisez une IIFE async <code>(async () => { ... })()</code> qui await Promise.resolve('done') et l'affiche.",
    code_template: "// async IIFE\n",
    solution: "(async () => { console.log(await Promise.resolve('done')); })();",
    tests: [
      { type: "regex", expected: "\\(\\s*async" },
      { type: "output", expected: "done" },
    ],
    category: "async/await",
  },
  {
    id: "js_s7_e19",
    title: "Throw async",
    description: "Async function qui throw.",
    instruction: "Écrivez une fonction async qui throw <code>'KO'</code>. Appelez-la et capturez avec .catch pour afficher 'attrapé: KO'.",
    code_template: "async function fail() {\n  throw 'KO';\n}\n// catch\n",
    solution: "async function fail() {\n  throw 'KO';\n}\nfail().catch(e => console.log('attrapé: ' + e));",
    tests: [{ type: "output", expected: "attrapé: KO" }],
    category: "async/await",
  },
  {
    id: "js_s7_e20",
    title: "Promise.any",
    description: "Le premier résolu (ignore les rejected).",
    instruction: "Avec <code>Promise.any([Promise.reject('a'), Promise.resolve('b'), Promise.resolve('c')])</code>, affichez le premier résolu (b).",
    code_template: "// Promise.any\n",
    solution: "Promise.any([Promise.reject('a'), Promise.resolve('b'), Promise.resolve('c')]).then(v => console.log(v));",
    tests: [
      { type: "contains", expected: "Promise.any" },
      { type: "output", expected: "b" },
    ],
    category: "Promises",
  },
  {
    id: "js_s7_e21",
    title: "Map d'objets avec await",
    description: "Async map manuelle.",
    instruction: "Soit <code>[{v:1},{v:2},{v:3}]</code>. Récupérez les <code>v</code> via <code>Promise.all + map</code> + await, puis affichez la somme.",
    code_template: "async function main() {\n  const data = [{v:1},{v:2},{v:3}];\n  // Promise.all\n}\nmain();",
    solution: "async function main() {\n  const data = [{v:1},{v:2},{v:3}];\n  const vals = await Promise.all(data.map(d => Promise.resolve(d.v)));\n  console.log(vals.reduce((s, v) => s + v, 0));\n}\nmain();",
    tests: [{ type: "output", expected: "6" }],
    category: "async/await",
  },
  {
    id: "js_s7_e22",
    title: "Erreur non rattrapée",
    description: "Différencier sync throw d'async reject.",
    instruction: "Une fonction async qui throw retourne une promesse rejected. Testez : <code>async function f() { throw 'e'; }</code>. Vérifiez avec .catch que ça affiche 'caught: e'.",
    code_template: "async function f() { throw 'e'; }\nf().catch(e => console.log('caught: ' + e));",
    solution: "async function f() { throw 'e'; }\nf().catch(e => console.log('caught: ' + e));",
    tests: [{ type: "output", expected: "caught: e" }],
    category: "async/await",
  },
  {
    id: "js_s7_e23",
    title: "Conditions dans une chaîne async",
    description: "Brancher selon le résultat.",
    instruction: "Async function qui await une valeur. Si valeur >= 10, affichez 'grand', sinon 'petit'. Testez avec await Promise.resolve(7).",
    code_template: "async function check(p) {\n  const v = await p;\n  // if/else\n}\ncheck(Promise.resolve(7));",
    solution: "async function check(p) {\n  const v = await p;\n  console.log(v >= 10 ? 'grand' : 'petit');\n}\ncheck(Promise.resolve(7));",
    tests: [{ type: "output", expected: "petit" }],
    category: "async/await",
  },
  {
    id: "js_s7_e24",
    title: "Promesses parallèles vs séquentielles",
    description: "Calculer les 2 résultats.",
    instruction: "Lancez via Promise.all <code>[Promise.resolve(5), Promise.resolve(10)]</code>, puis dans un .then multipliez les 2 et affichez. (Résultat : 50)",
    code_template: "// Promise.all puis multiplier\n",
    solution: "Promise.all([Promise.resolve(5), Promise.resolve(10)]).then(([a, b]) => console.log(a * b));",
    tests: [{ type: "output", expected: "50" }],
    category: "Promises",
  },
  {
    id: "js_s7_e25",
    title: "Fonction utilitaire delay synchrone (simulée)",
    description: "Promesse immédiate.",
    instruction: "Écrivez <code>function delay(val) { return Promise.resolve(val); }</code>. Chainez delay(1).then.delay-chain pour additionner 1+2+3 (utilisez reduce ou 3 then). Affichez 6.",
    code_template: "function delay(val) { return Promise.resolve(val); }\n// chainer 3 valeurs\n",
    solution: "function delay(val) { return Promise.resolve(val); }\nlet p = delay(0);\nfor (const v of [1, 2, 3]) p = p.then(acc => delay(acc + v));\np.then(v => console.log(v));",
    tests: [{ type: "output", expected: "6" }],
    category: "Promises",
  },
];

addExercises("javascript", exercises);
