import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/**
 * Node.js — Part 9 : production patterns, clustering, workers, testing, deployment.
 */
const exercises: Exercise[] = [
  {
    id: "node_196",
    type: "code",
    category: "Process",
    title: "process.env",
    description: "Lire variables d'environnement.",
    instruction: "Lisez <code>process.env.PORT</code>, par défaut 3000 si absente, et loggez le port.",
    code_template: "// process.env\n",
    solution: "const port = process.env.PORT || 3000;\nconsole.log(port);",
    tests: [
      { expected: "process.env.PORT", type: "contains" },
      { expected: "|| 3000", type: "contains" },
    ],
  },
  {
    id: "node_197",
    type: "code",
    category: "Process",
    title: "dotenv",
    description: "Charger .env.",
    instruction: "Avec <code>dotenv</code>, chargez le fichier .env au début et loggez <code>process.env.DATABASE_URL</code>.",
    code_template: "// dotenv\n",
    solution: "require('dotenv').config();\nconsole.log(process.env.DATABASE_URL);",
    tests: [
      { expected: "dotenv", type: "contains" },
      { expected: ".config()", type: "contains" },
    ],
  },
  {
    id: "node_198",
    type: "code",
    category: "Process",
    title: "process.argv",
    description: "Arguments CLI.",
    instruction: "Loggez les args passés au script (sans 'node' ni le path du script).",
    code_template: "// process.argv\n",
    solution: "const args = process.argv.slice(2);\nconsole.log(args);",
    tests: [
      { expected: "process.argv", type: "contains" },
      { expected: ".slice(2)", type: "contains" },
    ],
  },
  {
    id: "node_199",
    type: "code",
    category: "Process",
    title: "Exit code",
    description: "Sortir avec status code.",
    instruction: "Sur erreur, loggez l'erreur puis <code>process.exit(1)</code>.",
    code_template: "function fail(err) {\n  // \n}",
    solution: "function fail(err) {\n  console.error(err);\n  process.exit(1);\n}",
    tests: [
      { expected: "process.exit(1)", type: "contains" },
    ],
  },
  {
    id: "node_200",
    type: "code",
    category: "Clustering",
    title: "cluster basique",
    description: "Forker plusieurs workers.",
    instruction: "Avec <code>cluster</code> : si master, fork <code>os.cpus().length</code> workers. Sinon, log le PID worker.",
    code_template: "const cluster = require('cluster');\nconst os = require('os');\n// cluster\n",
    solution: "const cluster = require('cluster');\nconst os = require('os');\nif (cluster.isPrimary) {\n  for (let i = 0; i < os.cpus().length; i++) cluster.fork();\n} else {\n  console.log('worker', process.pid);\n}",
    tests: [
      { expected: "cluster.isPrimary", type: "contains" },
      { expected: "cluster.fork", type: "contains" },
      { expected: "os.cpus()", type: "contains" },
    ],
  },
  {
    id: "node_201",
    type: "code",
    category: "Workers",
    title: "Worker thread",
    description: "Calcul intensif en parallèle.",
    instruction: "Avec <code>worker_threads</code>, créez un Worker depuis 'worker.js' et écoutez son message.",
    code_template: "const { Worker } = require('worker_threads');\n// Worker\n",
    solution: "const { Worker } = require('worker_threads');\nconst w = new Worker('./worker.js');\nw.on('message', (msg) => console.log('reçu:', msg));",
    tests: [
      { expected: "worker_threads", type: "contains" },
      { expected: "new Worker", type: "contains" },
    ],
  },
  {
    id: "node_202",
    type: "code",
    category: "Workers",
    title: "Worker postMessage",
    description: "Communication parent ↔ worker.",
    instruction: "Dans worker.js, écoutez parentPort, recevez un nombre, et postMessage son carré.",
    code_template: "const { parentPort } = require('worker_threads');\n// \n",
    solution: "const { parentPort } = require('worker_threads');\nparentPort.on('message', (n) => {\n  parentPort.postMessage(n * n);\n});",
    tests: [
      { expected: "parentPort", type: "contains" },
      { expected: "postMessage", type: "contains" },
    ],
  },
  {
    id: "node_203",
    type: "code",
    category: "Child Process",
    title: "exec",
    description: "Lancer une commande shell.",
    instruction: "Exécutez <code>ls -la</code> avec <code>child_process.exec</code> et loggez stdout.",
    code_template: "const { exec } = require('child_process');\n",
    solution: "const { exec } = require('child_process');\nexec('ls -la', (err, stdout, stderr) => {\n  if (err) return console.error(err);\n  console.log(stdout);\n});",
    tests: [
      { expected: "child_process", type: "contains" },
      { expected: "exec(", type: "contains" },
    ],
  },
  {
    id: "node_204",
    type: "code",
    category: "Child Process",
    title: "spawn (streams)",
    description: "Process avec streams stdin/stdout.",
    instruction: "Avec <code>spawn('ls', ['-l'])</code>, pipez le stdout vers process.stdout.",
    code_template: "const { spawn } = require('child_process');\n",
    solution: "const { spawn } = require('child_process');\nconst child = spawn('ls', ['-l']);\nchild.stdout.pipe(process.stdout);",
    tests: [
      { expected: "spawn(", type: "contains" },
      { expected: ".stdout.pipe", type: "contains" },
    ],
  },
  {
    id: "node_205",
    type: "code",
    category: "Events",
    title: "EventEmitter",
    description: "Pub/sub natif.",
    instruction: "Créez une instance d'EventEmitter, abonnez-vous à 'tick' et émettez 'tick' avec valeur 42.",
    code_template: "const { EventEmitter } = require('events');\nconst ee = new EventEmitter();\n// \n",
    solution: "const { EventEmitter } = require('events');\nconst ee = new EventEmitter();\nee.on('tick', (n) => console.log('tick:', n));\nee.emit('tick', 42);",
    tests: [
      { expected: "EventEmitter", type: "contains" },
      { expected: ".on(", type: "contains" },
      { expected: ".emit(", type: "contains" },
    ],
  },
  {
    id: "node_206",
    type: "code",
    category: "Events",
    title: "once",
    description: "Écouter une seule fois.",
    instruction: "Écoutez 'ready' une seule fois avec <code>.once</code>, émettez 3 fois — le listener ne tirera qu'une fois.",
    code_template: "const { EventEmitter } = require('events');\nconst ee = new EventEmitter();\n// \n",
    solution: "const { EventEmitter } = require('events');\nconst ee = new EventEmitter();\nee.once('ready', () => console.log('ready'));\nee.emit('ready');\nee.emit('ready');\nee.emit('ready');",
    tests: [
      { expected: ".once", type: "contains" },
    ],
  },
  {
    id: "node_207",
    type: "code",
    category: "Logging",
    title: "Pino structured logging",
    description: "Logger JSON haute performance.",
    instruction: "Créez un logger pino, loggez en info <code>'hello'</code> et en error une string + objet.",
    code_template: "const pino = require('pino');\nconst log = pino();\n",
    solution: "const pino = require('pino');\nconst log = pino();\nlog.info('hello');\nlog.error({ err: 'oops' }, 'failure');",
    tests: [
      { expected: "pino", type: "contains" },
      { expected: "log.info", type: "contains" },
      { expected: "log.error", type: "contains" },
    ],
  },
  {
    id: "node_208",
    type: "code",
    category: "Testing",
    title: "Test natif (node:test)",
    description: "Runner intégré Node 18+.",
    instruction: "Avec <code>node:test</code>, écrivez un test <code>'add'</code> qui vérifie <code>add(1, 2) === 3</code> avec assert.",
    code_template: "const test = require('node:test');\nconst assert = require('node:assert');\nfunction add(a, b) { return a + b; }\n// test\n",
    solution: "const test = require('node:test');\nconst assert = require('node:assert');\nfunction add(a, b) { return a + b; }\ntest('add', () => {\n  assert.strictEqual(add(1, 2), 3);\n});",
    tests: [
      { expected: "node:test", type: "contains" },
      { expected: "assert.strictEqual", type: "contains" },
    ],
  },
  {
    id: "node_209",
    type: "code",
    category: "Testing",
    title: "Test async",
    description: "Promise dans un test.",
    instruction: "Écrivez un test async qui vérifie qu'une promesse résolue retourne 42.",
    code_template: "const test = require('node:test');\nconst assert = require('node:assert');\n",
    solution: "const test = require('node:test');\nconst assert = require('node:assert');\ntest('async', async () => {\n  const r = await Promise.resolve(42);\n  assert.strictEqual(r, 42);\n});",
    tests: [
      { expected: "async", type: "contains" },
      { expected: "await", type: "contains" },
    ],
  },
  {
    id: "node_210",
    type: "code",
    category: "Testing",
    title: "Supertest (Express)",
    description: "HTTP integration test.",
    instruction: "Avec <code>supertest</code>, testez que GET / renvoie 200 et body 'Hello'.",
    code_template: "const request = require('supertest');\nconst express = require('express');\nconst app = express();\napp.get('/', (req, res) => res.send('Hello'));\n\nasync function main() {\n  // supertest\n}\nmain();",
    solution: "const request = require('supertest');\nconst express = require('express');\nconst app = express();\napp.get('/', (req, res) => res.send('Hello'));\n\nasync function main() {\n  const res = await request(app).get('/');\n  console.log(res.status, res.text);\n}\nmain();",
    tests: [
      { expected: "supertest", type: "contains" },
      { expected: "request(app)", type: "contains" },
    ],
  },
  {
    id: "node_211",
    type: "code",
    category: "DB",
    title: "PostgreSQL avec pg",
    description: "Pool de connexions.",
    instruction: "Avec <code>pg.Pool</code>, exécutez <code>SELECT NOW()</code> et loggez le résultat.",
    code_template: "const { Pool } = require('pg');\nconst pool = new Pool();\nasync function main() {\n  // query\n}\nmain();",
    solution: "const { Pool } = require('pg');\nconst pool = new Pool();\nasync function main() {\n  const r = await pool.query('SELECT NOW()');\n  console.log(r.rows[0]);\n}\nmain();",
    tests: [
      { expected: "new Pool", type: "contains" },
      { expected: "pool.query", type: "contains" },
    ],
  },
  {
    id: "node_212",
    type: "code",
    category: "DB",
    title: "PostgreSQL paramétré",
    description: "Évite l'injection.",
    instruction: "Query <code>SELECT * FROM users WHERE id = $1</code> avec id en param. Loggez la première ligne.",
    code_template: "const { Pool } = require('pg');\nconst pool = new Pool();\nasync function findUser(id) {\n  // \n}",
    solution: "const { Pool } = require('pg');\nconst pool = new Pool();\nasync function findUser(id) {\n  const r = await pool.query('SELECT * FROM users WHERE id = $1', [id]);\n  return r.rows[0];\n}",
    tests: [
      { expected: "$1", type: "contains" },
      { expected: "[id]", type: "contains" },
    ],
  },
  {
    id: "node_213",
    type: "code",
    category: "DB",
    title: "Transaction",
    description: "BEGIN / COMMIT / ROLLBACK.",
    instruction: "Effectuez 2 INSERT dans une transaction. Rollback si erreur.",
    code_template: "async function transfer(client) {\n  // BEGIN, 2 queries, COMMIT, catch ROLLBACK\n}",
    solution: "async function transfer(client) {\n  try {\n    await client.query('BEGIN');\n    await client.query('UPDATE accounts SET balance = balance - 100 WHERE id = 1');\n    await client.query('UPDATE accounts SET balance = balance + 100 WHERE id = 2');\n    await client.query('COMMIT');\n  } catch (e) {\n    await client.query('ROLLBACK');\n    throw e;\n  }\n}",
    tests: [
      { expected: "BEGIN", type: "contains" },
      { expected: "COMMIT", type: "contains" },
      { expected: "ROLLBACK", type: "contains" },
    ],
  },
  {
    id: "node_214",
    type: "code",
    category: "Async",
    title: "Promise.all parallèle",
    description: "Lancer en parallèle.",
    instruction: "Lancez 3 fetch en parallèle via Promise.all et loggez le tableau des résultats.",
    code_template: "async function main() {\n  // 3 fetch\n}\nmain();",
    solution: "async function main() {\n  const urls = ['/a', '/b', '/c'];\n  const results = await Promise.all(urls.map(u => fetch(u).then(r => r.json())));\n  console.log(results);\n}\nmain();",
    tests: [
      { expected: "Promise.all", type: "contains" },
      { expected: ".map", type: "contains" },
    ],
  },
  {
    id: "node_215",
    type: "code",
    category: "Async",
    title: "Promise.allSettled",
    description: "Tolérance aux erreurs.",
    instruction: "Avec Promise.allSettled, filtrez les succès et comptez-les.",
    code_template: "async function main() {\n  const results = await Promise.allSettled([\n    Promise.resolve(1),\n    Promise.reject('x'),\n    Promise.resolve(3)\n  ]);\n  // count fulfilled\n}\nmain();",
    solution: "async function main() {\n  const results = await Promise.allSettled([\n    Promise.resolve(1),\n    Promise.reject('x'),\n    Promise.resolve(3)\n  ]);\n  const ok = results.filter(r => r.status === 'fulfilled').length;\n  console.log(ok);\n}\nmain();",
    tests: [
      { expected: "allSettled", type: "contains" },
      { expected: "fulfilled", type: "contains" },
    ],
  },
  {
    id: "node_216",
    type: "code",
    category: "Architecture",
    title: "Module patterns",
    description: "Exposer une factory.",
    instruction: "Exportez une factory <code>createService(config)</code> qui retourne un objet avec methodes <code>get</code> et <code>set</code>.",
    code_template: "// module.exports\n",
    solution: "module.exports = function createService(config) {\n  const store = new Map();\n  return {\n    get(k) { return store.get(k); },\n    set(k, v) { store.set(k, v); }\n  };\n};",
    tests: [
      { expected: "module.exports", type: "contains" },
      { expected: "createService", type: "contains" },
    ],
  },
  {
    id: "node_217",
    type: "code",
    category: "Architecture",
    title: "Singleton",
    description: "Une instance unique.",
    instruction: "Exportez un singleton Logger via un IIFE.",
    code_template: "// singleton\n",
    solution: "const Logger = (function() {\n  let instance;\n  function create() {\n    return { log: (msg) => console.log('[LOG]', msg) };\n  }\n  return {\n    getInstance() {\n      if (!instance) instance = create();\n      return instance;\n    }\n  };\n})();\nmodule.exports = Logger;",
    tests: [
      { expected: "getInstance", type: "contains" },
      { expected: "instance", type: "contains" },
    ],
  },
  {
    id: "node_218",
    type: "code",
    category: "Déploiement",
    title: "PM2 ecosystem",
    description: "Config PM2 minimaliste.",
    instruction: "Définissez <code>module.exports = {apps: [{name, script, instances, exec_mode}]}</code> avec name 'api', script 'index.js', instances 'max', exec_mode 'cluster'.",
    code_template: "// ecosystem.config.js\n",
    solution: "module.exports = {\n  apps: [{\n    name: 'api',\n    script: 'index.js',\n    instances: 'max',\n    exec_mode: 'cluster'\n  }]\n};",
    tests: [
      { expected: "apps:", type: "contains" },
      { expected: "exec_mode", type: "contains" },
      { expected: "'cluster'", type: "contains" },
    ],
  },
  {
    id: "node_219",
    type: "code",
    category: "Async",
    title: "AbortController + fetch",
    description: "Timeout sur fetch.",
    instruction: "Faites un fetch avec timeout de 3000ms via AbortController + setTimeout.",
    code_template: "async function timeoutFetch(url) {\n  // \n}",
    solution: "async function timeoutFetch(url) {\n  const ctrl = new AbortController();\n  const id = setTimeout(() => ctrl.abort(), 3000);\n  try {\n    const res = await fetch(url, { signal: ctrl.signal });\n    return await res.json();\n  } finally {\n    clearTimeout(id);\n  }\n}",
    tests: [
      { expected: "AbortController", type: "contains" },
      { expected: "ctrl.abort", type: "contains" },
      { expected: "signal:", type: "contains" },
    ],
  },
  {
    id: "node_220",
    type: "code",
    category: "Final",
    title: "Mini-API REST complète",
    description: "Combo final.",
    instruction: "Express + helmet + cors + JSON + 1 route GET /users (renvoie []), 1 route POST /users (echo body), middleware d'erreur, listen 3000.",
    code_template: "// API complète\n",
    solution: "const express = require('express');\nconst helmet = require('helmet');\nconst cors = require('cors');\nconst app = express();\napp.use(helmet());\napp.use(cors());\napp.use(express.json());\napp.get('/users', (req, res) => res.json([]));\napp.post('/users', (req, res) => res.status(201).json(req.body));\napp.use((err, req, res, next) => res.status(500).json({ error: err.message }));\napp.listen(3000, () => console.log('on 3000'));",
    tests: [
      { expected: "helmet", type: "contains" },
      { expected: "cors", type: "contains" },
      { expected: "express.json", type: "contains" },
      { expected: "app.listen", type: "contains" },
    ],
    hint: "Tu viens de finir 220 exos Node. Bravo Lyoko-warrior !",
  },
];

addExercises("nodejs", exercises);
