import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/**
 * Node.js — Part 8 : auth, JWT, bcrypt, OAuth, sécurité, websockets.
 */
const exercises: Exercise[] = [
  {
    id: "node_171",
    type: "code",
    category: "Authentification",
    title: "Hash bcrypt",
    description: "Hasher un mot de passe.",
    instruction: "Avec <code>bcrypt</code>, hashez 'password' avec un cost de 10. Loggez le hash.",
    code_template: "const bcrypt = require('bcrypt');\nasync function main() {\n  // hash\n}\nmain();",
    solution: "const bcrypt = require('bcrypt');\nasync function main() {\n  const hash = await bcrypt.hash('password', 10);\n  console.log(hash);\n}\nmain();",
    tests: [
      { expected: "bcrypt", type: "contains" },
      { expected: ".hash(", type: "contains" },
    ],
  },
  {
    id: "node_172",
    type: "code",
    category: "Authentification",
    title: "Compare bcrypt",
    description: "Vérifier un mot de passe.",
    instruction: "Avec <code>bcrypt.compare</code>, comparez 'pass' au hash et loggez le résultat (true/false).",
    code_template: "const bcrypt = require('bcrypt');\nasync function main() {\n  const hash = await bcrypt.hash('pass', 10);\n  // compare\n}\nmain();",
    solution: "const bcrypt = require('bcrypt');\nasync function main() {\n  const hash = await bcrypt.hash('pass', 10);\n  const ok = await bcrypt.compare('pass', hash);\n  console.log(ok);\n}\nmain();",
    tests: [
      { expected: "bcrypt.compare", type: "contains" },
    ],
  },
  {
    id: "node_173",
    type: "code",
    category: "Authentification",
    title: "JWT sign",
    description: "Émettre un token signé.",
    instruction: "Avec <code>jsonwebtoken</code>, signez <code>{userId: 42}</code> avec la secret 'lyoko' et expiresIn '1h'. Loggez le token.",
    code_template: "const jwt = require('jsonwebtoken');\n// sign\n",
    solution: "const jwt = require('jsonwebtoken');\nconst token = jwt.sign({ userId: 42 }, 'lyoko', { expiresIn: '1h' });\nconsole.log(token);",
    tests: [
      { expected: "jwt.sign", type: "contains" },
      { expected: "expiresIn", type: "contains" },
    ],
  },
  {
    id: "node_174",
    type: "code",
    category: "Authentification",
    title: "JWT verify",
    description: "Vérifier un token.",
    instruction: "Avec <code>jwt.verify(token, 'lyoko')</code>, décodez et loggez le payload. Captez l'erreur.",
    code_template: "const jwt = require('jsonwebtoken');\nconst token = jwt.sign({ id: 1 }, 'lyoko');\ntry {\n  // verify\n} catch (e) {\n  console.error(e.message);\n}",
    solution: "const jwt = require('jsonwebtoken');\nconst token = jwt.sign({ id: 1 }, 'lyoko');\ntry {\n  const payload = jwt.verify(token, 'lyoko');\n  console.log(payload);\n} catch (e) {\n  console.error(e.message);\n}",
    tests: [
      { expected: "jwt.verify", type: "contains" },
      { expected: "try", type: "contains" },
    ],
  },
  {
    id: "node_175",
    type: "code",
    category: "Authentification",
    title: "Middleware JWT",
    description: "Protéger une route.",
    instruction: "Middleware Express qui : lit <code>Authorization: Bearer X</code>, vérifie via jwt, set <code>req.user</code>, appelle next(). Sinon 401.",
    code_template: "const jwt = require('jsonwebtoken');\nfunction auth(req, res, next) {\n  // \n}",
    solution: "const jwt = require('jsonwebtoken');\nfunction auth(req, res, next) {\n  const header = req.headers.authorization;\n  if (!header || !header.startsWith('Bearer ')) return res.status(401).json({ error: 'unauthorized' });\n  try {\n    req.user = jwt.verify(header.slice(7), 'lyoko');\n    next();\n  } catch {\n    res.status(401).json({ error: 'invalid token' });\n  }\n}",
    tests: [
      { expected: "Bearer", type: "contains" },
      { expected: "jwt.verify", type: "contains" },
      { expected: "status(401)", type: "contains" },
    ],
  },
  {
    id: "node_176",
    type: "code",
    category: "Sécurité",
    title: "Helmet",
    description: "Headers HTTP sécurisés.",
    instruction: "Activez le middleware <code>helmet</code> globalement.",
    code_template: "const express = require('express');\nconst helmet = require('helmet');\nconst app = express();\n// helmet\n",
    solution: "const express = require('express');\nconst helmet = require('helmet');\nconst app = express();\napp.use(helmet());",
    tests: [
      { expected: "helmet", type: "contains" },
      { expected: "app.use(helmet", type: "contains" },
    ],
  },
  {
    id: "node_177",
    type: "code",
    category: "Sécurité",
    title: "CORS configuré",
    description: "Limiter aux origines spécifiques.",
    instruction: "Configurez CORS pour autoriser uniquement <code>https://app.example.com</code> avec credentials.",
    code_template: "const cors = require('cors');\n// cors options\n",
    solution: "const cors = require('cors');\napp.use(cors({ origin: 'https://app.example.com', credentials: true }));",
    tests: [
      { expected: "origin:", type: "contains" },
      { expected: "credentials: true", type: "contains" },
    ],
  },
  {
    id: "node_178",
    type: "code",
    category: "Sécurité",
    title: "crypto.randomBytes",
    description: "Token aléatoire sécurisé.",
    instruction: "Générez un token aléatoire de 32 octets en hex avec <code>crypto.randomBytes(32).toString('hex')</code>.",
    code_template: "const crypto = require('crypto');\n",
    solution: "const crypto = require('crypto');\nconst token = crypto.randomBytes(32).toString('hex');\nconsole.log(token);",
    tests: [
      { expected: "crypto.randomBytes", type: "contains" },
      { expected: "'hex'", type: "contains" },
    ],
  },
  {
    id: "node_179",
    type: "code",
    category: "Sécurité",
    title: "crypto.createHash SHA-256",
    description: "Empreinte d'un message.",
    instruction: "Calculez le SHA-256 de <code>'message'</code> en hex.",
    code_template: "const crypto = require('crypto');\n",
    solution: "const crypto = require('crypto');\nconst h = crypto.createHash('sha256').update('message').digest('hex');\nconsole.log(h);",
    tests: [
      { expected: "createHash('sha256'", type: "contains" },
      { expected: ".digest", type: "contains" },
    ],
  },
  {
    id: "node_180",
    type: "code",
    category: "Sécurité",
    title: "HMAC",
    description: "Hash + secret.",
    instruction: "Calculez <code>HMAC-SHA256('lyoko', 'data')</code> en hex.",
    code_template: "const crypto = require('crypto');\n",
    solution: "const crypto = require('crypto');\nconst h = crypto.createHmac('sha256', 'lyoko').update('data').digest('hex');\nconsole.log(h);",
    tests: [
      { expected: "createHmac", type: "contains" },
      { expected: "'sha256'", type: "contains" },
    ],
  },
  {
    id: "node_181",
    type: "code",
    category: "Sécurité",
    title: "AES-256-GCM chiffrer",
    description: "Cryptographie symétrique.",
    instruction: "Chiffrez 'secret' avec AES-256-GCM. Key et IV via randomBytes. Loggez le ciphertext en hex.",
    code_template: "const crypto = require('crypto');\nconst key = crypto.randomBytes(32);\nconst iv = crypto.randomBytes(12);\n// cipher\n",
    solution: "const crypto = require('crypto');\nconst key = crypto.randomBytes(32);\nconst iv = crypto.randomBytes(12);\nconst c = crypto.createCipheriv('aes-256-gcm', key, iv);\nlet enc = c.update('secret', 'utf8', 'hex');\nenc += c.final('hex');\nconsole.log(enc);",
    tests: [
      { expected: "aes-256-gcm", type: "contains" },
      { expected: "createCipheriv", type: "contains" },
    ],
  },
  {
    id: "node_182",
    type: "code",
    category: "WebSocket",
    title: "Serveur WebSocket",
    description: "Avec le package ws.",
    instruction: "Créez un serveur WebSocket sur port 8080 qui echo chaque message reçu.",
    code_template: "const WebSocket = require('ws');\nconst wss = new WebSocket.Server({ port: 8080 });\n// echo\n",
    solution: "const WebSocket = require('ws');\nconst wss = new WebSocket.Server({ port: 8080 });\nwss.on('connection', (ws) => {\n  ws.on('message', (msg) => ws.send(msg));\n});",
    tests: [
      { expected: "WebSocket.Server", type: "contains" },
      { expected: "ws.on('message'", type: "contains" },
      { expected: "ws.send", type: "contains" },
    ],
  },
  {
    id: "node_183",
    type: "code",
    category: "WebSocket",
    title: "Broadcast",
    description: "Diffuser à tous les clients.",
    instruction: "Sur réception d'un message, broadcast à tous les clients connectés (sauf l'envoyeur).",
    code_template: "const WebSocket = require('ws');\nconst wss = new WebSocket.Server({ port: 8080 });\nwss.on('connection', (ws) => {\n  ws.on('message', (msg) => {\n    // broadcast\n  });\n});",
    solution: "const WebSocket = require('ws');\nconst wss = new WebSocket.Server({ port: 8080 });\nwss.on('connection', (ws) => {\n  ws.on('message', (msg) => {\n    wss.clients.forEach((client) => {\n      if (client !== ws && client.readyState === WebSocket.OPEN) {\n        client.send(msg);\n      }\n    });\n  });\n});",
    tests: [
      { expected: "wss.clients", type: "contains" },
      { expected: ".forEach", type: "contains" },
      { expected: "OPEN", type: "contains" },
    ],
  },
  {
    id: "node_184",
    type: "code",
    category: "WebSocket",
    title: "Socket.IO basique",
    description: "Avec namespace.",
    instruction: "Avec <code>socket.io</code>, créez un serveur sur 3000 qui écoute 'chat message' et le réémet à tous.",
    code_template: "const { Server } = require('socket.io');\nconst io = new Server(3000);\n// chat\n",
    solution: "const { Server } = require('socket.io');\nconst io = new Server(3000);\nio.on('connection', (socket) => {\n  socket.on('chat message', (msg) => {\n    io.emit('chat message', msg);\n  });\n});",
    tests: [
      { expected: "socket.io", type: "contains" },
      { expected: "io.emit", type: "contains" },
    ],
  },
  {
    id: "node_185",
    type: "code",
    category: "WebSocket",
    title: "Socket.IO rooms",
    description: "Group de sockets.",
    instruction: "Sur 'join', faites le socket rejoindre la room <code>roomId</code>. Sur 'msg', broadcast dans cette room.",
    code_template: "io.on('connection', (socket) => {\n  // join + msg\n});",
    solution: "io.on('connection', (socket) => {\n  socket.on('join', (roomId) => socket.join(roomId));\n  socket.on('msg', ({ roomId, text }) => {\n    io.to(roomId).emit('msg', text);\n  });\n});",
    tests: [
      { expected: "socket.join", type: "contains" },
      { expected: "io.to(roomId)", type: "contains" },
    ],
  },
  {
    id: "node_186",
    type: "code",
    category: "OAuth",
    title: "Passport Google strategy (concept)",
    description: "Configuration de stratégie.",
    instruction: "Configurez passport avec GoogleStrategy : clientID, clientSecret, callbackURL.",
    code_template: "const passport = require('passport');\nconst GoogleStrategy = require('passport-google-oauth20').Strategy;\n// strategy\n",
    solution: "const passport = require('passport');\nconst GoogleStrategy = require('passport-google-oauth20').Strategy;\npassport.use(new GoogleStrategy({\n  clientID: process.env.GOOGLE_CLIENT_ID,\n  clientSecret: process.env.GOOGLE_CLIENT_SECRET,\n  callbackURL: '/auth/google/callback'\n}, (accessToken, refreshToken, profile, done) => {\n  done(null, profile);\n}));",
    tests: [
      { expected: "GoogleStrategy", type: "contains" },
      { expected: "clientID", type: "contains" },
      { expected: "callbackURL", type: "contains" },
    ],
  },
  {
    id: "node_187",
    type: "code",
    category: "Sécurité",
    title: "Sanitize input — XSS prevention",
    description: "Échapper le HTML.",
    instruction: "Écrivez <code>escapeHtml(str)</code> qui remplace &, &lt;, &gt;, &quot;, ' par leurs entités HTML.",
    code_template: "function escapeHtml(str) {\n  // \n}",
    solution: "function escapeHtml(str) {\n  return str\n    .replace(/&/g, '&amp;')\n    .replace(/</g, '&lt;')\n    .replace(/>/g, '&gt;')\n    .replace(/\"/g, '&quot;')\n    .replace(/'/g, '&#39;');\n}",
    tests: [
      { expected: "&amp;", type: "contains" },
      { expected: "&lt;", type: "contains" },
      { expected: "&gt;", type: "contains" },
    ],
  },
  {
    id: "node_188",
    type: "code",
    category: "Sécurité",
    title: "SQL Injection — paramétré",
    description: "Toujours utiliser des paramètres.",
    instruction: "Avec <code>better-sqlite3</code>, exécutez <code>SELECT * FROM users WHERE id = ?</code> avec id en paramètre (jamais en concaténation).",
    code_template: "const Database = require('better-sqlite3');\nconst db = new Database('app.db');\nfunction findUser(id) {\n  // prepare + run avec param\n}",
    solution: "const Database = require('better-sqlite3');\nconst db = new Database('app.db');\nfunction findUser(id) {\n  return db.prepare('SELECT * FROM users WHERE id = ?').get(id);\n}",
    tests: [
      { expected: ".prepare(", type: "contains" },
      { expected: "?", type: "contains" },
      { expected: ".get(id)", type: "contains" },
    ],
  },
  {
    id: "node_189",
    type: "code",
    category: "Sécurité",
    title: "CSRF token (concept)",
    description: "Avec csurf.",
    instruction: "Activez le middleware <code>csurf</code> et exposez <code>req.csrfToken()</code> dans une route GET /form.",
    code_template: "const csrf = require('csurf');\nconst csrfProtection = csrf({ cookie: true });\napp.use(csrfProtection);\n// route\n",
    solution: "const csrf = require('csurf');\nconst csrfProtection = csrf({ cookie: true });\napp.use(csrfProtection);\napp.get('/form', (req, res) => {\n  res.json({ csrfToken: req.csrfToken() });\n});",
    tests: [
      { expected: "csurf", type: "contains" },
      { expected: "req.csrfToken", type: "contains" },
    ],
  },
  {
    id: "node_190",
    type: "code",
    category: "Authentification",
    title: "Refresh token pattern",
    description: "Access + refresh.",
    instruction: "Définissez deux jwt.sign : un access token (15min) et un refresh token (7 jours), chacun avec une secret différente.",
    code_template: "const jwt = require('jsonwebtoken');\nfunction issueTokens(userId) {\n  // \n}",
    solution: "const jwt = require('jsonwebtoken');\nfunction issueTokens(userId) {\n  const accessToken = jwt.sign({ userId }, 'ACCESS_SECRET', { expiresIn: '15m' });\n  const refreshToken = jwt.sign({ userId }, 'REFRESH_SECRET', { expiresIn: '7d' });\n  return { accessToken, refreshToken };\n}",
    tests: [
      { expected: "accessToken", type: "contains" },
      { expected: "refreshToken", type: "contains" },
      { expected: "'15m'", type: "contains" },
      { expected: "'7d'", type: "contains" },
    ],
  },
  {
    id: "node_191",
    type: "code",
    category: "Authentification",
    title: "Password reset token",
    description: "Token éphémère.",
    instruction: "Générez un token de reset avec crypto.randomBytes(20).toString('hex') et stockez son hash SHA-256 + expiry 1h.",
    code_template: "const crypto = require('crypto');\nfunction createResetToken() {\n  // \n}",
    solution: "const crypto = require('crypto');\nfunction createResetToken() {\n  const token = crypto.randomBytes(20).toString('hex');\n  const hashed = crypto.createHash('sha256').update(token).digest('hex');\n  const expiry = Date.now() + 60 * 60 * 1000;\n  return { token, hashed, expiry };\n}",
    tests: [
      { expected: "randomBytes(20)", type: "contains" },
      { expected: "createHash('sha256'", type: "contains" },
    ],
  },
  {
    id: "node_192",
    type: "code",
    category: "Sécurité",
    title: "Sécuriser cookies",
    description: "httpOnly, secure, sameSite.",
    instruction: "Set un cookie 'sid' avec <code>httpOnly: true, secure: true, sameSite: 'lax'</code>.",
    code_template: "app.get('/login', (req, res) => {\n  res.cookie('sid', 'abc', {\n    // options\n  });\n  res.json({ ok: true });\n});",
    solution: "app.get('/login', (req, res) => {\n  res.cookie('sid', 'abc', {\n    httpOnly: true,\n    secure: true,\n    sameSite: 'lax'\n  });\n  res.json({ ok: true });\n});",
    tests: [
      { expected: "httpOnly: true", type: "contains" },
      { expected: "secure: true", type: "contains" },
      { expected: "sameSite", type: "contains" },
    ],
  },
  {
    id: "node_193",
    type: "code",
    category: "Sécurité",
    title: "Validation avec Zod",
    description: "Schéma typé.",
    instruction: "Avec <code>zod</code>, définissez un schéma user <code>{email: z.string().email(), age: z.number().min(0)}</code> et parsez un objet.",
    code_template: "const { z } = require('zod');\nconst UserSchema = /* */;\nconst result = UserSchema.parse({ email: 'a@b.c', age: 25 });\nconsole.log(result);",
    solution: "const { z } = require('zod');\nconst UserSchema = z.object({\n  email: z.string().email(),\n  age: z.number().min(0)\n});\nconst result = UserSchema.parse({ email: 'a@b.c', age: 25 });\nconsole.log(result);",
    tests: [
      { expected: "z.object", type: "contains" },
      { expected: ".email()", type: "contains" },
      { expected: ".min(0)", type: "contains" },
    ],
  },
  {
    id: "node_194",
    type: "code",
    category: "Sécurité",
    title: "Timing-safe compare",
    description: "Éviter les attaques par timing.",
    instruction: "Avec <code>crypto.timingSafeEqual</code>, comparez deux Buffers en temps constant.",
    code_template: "const crypto = require('crypto');\nfunction safeCompare(a, b) {\n  // \n}",
    solution: "const crypto = require('crypto');\nfunction safeCompare(a, b) {\n  if (a.length !== b.length) return false;\n  return crypto.timingSafeEqual(Buffer.from(a), Buffer.from(b));\n}",
    tests: [
      { expected: "timingSafeEqual", type: "contains" },
    ],
  },
  {
    id: "node_195",
    type: "code",
    category: "Sécurité",
    title: "Content Security Policy (CSP)",
    description: "Via helmet.contentSecurityPolicy.",
    instruction: "Configurez CSP pour autoriser default-src 'self' et img-src 'self' data:.",
    code_template: "const helmet = require('helmet');\n// CSP\n",
    solution: "const helmet = require('helmet');\napp.use(helmet.contentSecurityPolicy({\n  directives: {\n    defaultSrc: [\"'self'\"],\n    imgSrc: [\"'self'\", 'data:']\n  }\n}));",
    tests: [
      { expected: "contentSecurityPolicy", type: "contains" },
      { expected: "defaultSrc", type: "contains" },
    ],
  },
];

addExercises("nodejs", exercises);
