import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/**
 * Node.js — Part 7 : Express avancé, middlewares, routing, validation.
 */
const exercises: Exercise[] = [
  {
    id: "node_146",
    type: "code",
    category: "Express",
    title: "Middleware basique",
    description: "Logger les requêtes.",
    instruction: "Ajoutez un middleware Express qui log la méthode et l'URL de chaque requête puis appelle <code>next()</code>.",
    code_template: "const express = require('express');\nconst app = express();\n// middleware\napp.listen(3000);",
    solution: "const express = require('express');\nconst app = express();\napp.use((req, res, next) => {\n  console.log(req.method, req.url);\n  next();\n});\napp.listen(3000);",
    tests: [
      { expected: "app.use", type: "contains" },
      { expected: "next()", type: "contains" },
      { expected: "req.method", type: "contains" },
    ],
  },
  {
    id: "node_147",
    type: "code",
    category: "Express",
    title: "Middleware d'erreur (4 args)",
    description: "Gestionnaire centralisé.",
    instruction: "Définissez un middleware d'erreur avec 4 arguments <code>(err, req, res, next)</code> qui retourne JSON <code>{error: err.message}</code> avec status 500.",
    code_template: "const express = require('express');\nconst app = express();\n// error middleware\n",
    solution: "const express = require('express');\nconst app = express();\napp.use((err, req, res, next) => {\n  res.status(500).json({ error: err.message });\n});",
    tests: [
      { expected: "(err, req, res, next)", type: "contains" },
      { expected: ".status(500)", type: "contains" },
    ],
  },
  {
    id: "node_148",
    type: "code",
    category: "Express",
    title: "Route param",
    description: "Capter un segment dynamique.",
    instruction: "Définissez <code>GET /users/:id</code> qui retourne JSON <code>{userId: req.params.id}</code>.",
    code_template: "const express = require('express');\nconst app = express();\n// route\n",
    solution: "const express = require('express');\nconst app = express();\napp.get('/users/:id', (req, res) => {\n  res.json({ userId: req.params.id });\n});",
    tests: [
      { expected: "'/users/:id'", type: "contains" },
      { expected: "req.params.id", type: "contains" },
    ],
  },
  {
    id: "node_149",
    type: "code",
    category: "Express",
    title: "Query string",
    description: "req.query.",
    instruction: "Route <code>GET /search</code> qui retourne <code>{q: req.query.q}</code>.",
    code_template: "const express = require('express');\nconst app = express();\n// search\n",
    solution: "const express = require('express');\nconst app = express();\napp.get('/search', (req, res) => {\n  res.json({ q: req.query.q });\n});",
    tests: [
      { expected: "req.query.q", type: "contains" },
    ],
  },
  {
    id: "node_150",
    type: "code",
    category: "Express",
    title: "Body parser JSON",
    description: "express.json().",
    instruction: "Activez <code>express.json()</code> globalement. Route <code>POST /echo</code> renvoie <code>req.body</code>.",
    code_template: "const express = require('express');\nconst app = express();\n// json + echo\n",
    solution: "const express = require('express');\nconst app = express();\napp.use(express.json());\napp.post('/echo', (req, res) => {\n  res.json(req.body);\n});",
    tests: [
      { expected: "express.json()", type: "contains" },
      { expected: "req.body", type: "contains" },
    ],
  },
  {
    id: "node_151",
    type: "code",
    category: "Express",
    title: "Static files",
    description: "Servir un dossier.",
    instruction: "Servez le dossier <code>./public</code> via <code>express.static</code>.",
    code_template: "const express = require('express');\nconst app = express();\n// static\n",
    solution: "const express = require('express');\nconst app = express();\napp.use(express.static('public'));",
    tests: [
      { expected: "express.static", type: "contains" },
    ],
  },
  {
    id: "node_152",
    type: "code",
    category: "Express",
    title: "Router",
    description: "Organiser les routes.",
    instruction: "Créez un <code>userRouter</code> avec une route GET '/'. Montez-le sur <code>/users</code>.",
    code_template: "const express = require('express');\nconst app = express();\n// router\n",
    solution: "const express = require('express');\nconst app = express();\nconst userRouter = express.Router();\nuserRouter.get('/', (req, res) => res.json([]));\napp.use('/users', userRouter);",
    tests: [
      { expected: "express.Router", type: "contains" },
      { expected: "app.use('/users'", type: "contains" },
    ],
  },
  {
    id: "node_153",
    type: "code",
    category: "Express",
    title: "Async route + try/catch",
    description: "Pattern moderne.",
    instruction: "Route async <code>GET /data</code> qui await une promesse. Captez les erreurs avec try/catch + passez au next(err).",
    code_template: "app.get('/data', async (req, res, next) => {\n  // try/catch + next\n});",
    solution: "app.get('/data', async (req, res, next) => {\n  try {\n    const data = await fetchData();\n    res.json(data);\n  } catch (err) {\n    next(err);\n  }\n});",
    tests: [
      { expected: "async", type: "contains" },
      { expected: "try", type: "contains" },
      { expected: "next(err)", type: "contains" },
    ],
  },
  {
    id: "node_154",
    type: "code",
    category: "Express",
    title: "Validation manuelle",
    description: "Refuser corps invalide.",
    instruction: "Route <code>POST /users</code> : si <code>!req.body.email</code>, renvoyer 400 avec <code>{error: 'email requis'}</code>.",
    code_template: "app.post('/users', (req, res) => {\n  // validation\n});",
    solution: "app.post('/users', (req, res) => {\n  if (!req.body.email) return res.status(400).json({ error: 'email requis' });\n  res.json({ ok: true });\n});",
    tests: [
      { expected: ".status(400)", type: "contains" },
      { expected: "'email requis'", type: "contains" },
    ],
  },
  {
    id: "node_155",
    type: "code",
    category: "Express",
    title: "Cookies",
    description: "Lire et set un cookie.",
    instruction: "Avec <code>cookie-parser</code>, route <code>GET /set</code> qui fait <code>res.cookie('user', 'aelita')</code>, et <code>GET /get</code> qui retourne <code>req.cookies.user</code>.",
    code_template: "const express = require('express');\nconst cookieParser = require('cookie-parser');\nconst app = express();\napp.use(cookieParser());\n// routes\n",
    solution: "const express = require('express');\nconst cookieParser = require('cookie-parser');\nconst app = express();\napp.use(cookieParser());\napp.get('/set', (req, res) => res.cookie('user', 'aelita').send('OK'));\napp.get('/get', (req, res) => res.send(req.cookies.user));",
    tests: [
      { expected: "cookie-parser", type: "contains" },
      { expected: "res.cookie", type: "contains" },
      { expected: "req.cookies", type: "contains" },
    ],
  },
  {
    id: "node_156",
    type: "code",
    category: "Express",
    title: "Sessions",
    description: "express-session.",
    instruction: "Activez <code>express-session</code> avec secret 'lyoko'. Route POST /login qui set <code>req.session.user = 'X'</code>.",
    code_template: "const express = require('express');\nconst session = require('express-session');\nconst app = express();\n// session + route\n",
    solution: "const express = require('express');\nconst session = require('express-session');\nconst app = express();\napp.use(session({ secret: 'lyoko', resave: false, saveUninitialized: true }));\napp.post('/login', (req, res) => {\n  req.session.user = 'X';\n  res.json({ ok: true });\n});",
    tests: [
      { expected: "express-session", type: "contains" },
      { expected: "req.session", type: "contains" },
    ],
  },
  {
    id: "node_157",
    type: "code",
    category: "Express",
    title: "Multer (upload)",
    description: "Réception de fichiers.",
    instruction: "Avec <code>multer</code>, route <code>POST /upload</code> qui accepte un fichier 'file' et retourne <code>{name: req.file.originalname}</code>.",
    code_template: "const express = require('express');\nconst multer = require('multer');\nconst upload = multer({ dest: 'uploads/' });\nconst app = express();\n// upload\n",
    solution: "const express = require('express');\nconst multer = require('multer');\nconst upload = multer({ dest: 'uploads/' });\nconst app = express();\napp.post('/upload', upload.single('file'), (req, res) => {\n  res.json({ name: req.file.originalname });\n});",
    tests: [
      { expected: "multer", type: "contains" },
      { expected: "upload.single", type: "contains" },
      { expected: "req.file", type: "contains" },
    ],
  },
  {
    id: "node_158",
    type: "code",
    category: "Express",
    title: "CORS",
    description: "Autoriser cross-origin.",
    instruction: "Avec le package <code>cors</code>, activez CORS globalement.",
    code_template: "const express = require('express');\nconst cors = require('cors');\nconst app = express();\n// cors\n",
    solution: "const express = require('express');\nconst cors = require('cors');\nconst app = express();\napp.use(cors());",
    tests: [
      { expected: "require('cors')", type: "contains" },
      { expected: "app.use(cors", type: "contains" },
    ],
  },
  {
    id: "node_159",
    type: "code",
    category: "Express",
    title: "Status codes",
    description: "Retourner les codes appropriés.",
    instruction: "Route GET /not-found → 404. Route GET /unauthorized → 401. Route GET /ok → 200 + JSON {ok: true}.",
    code_template: "const express = require('express');\nconst app = express();\n// 3 routes\n",
    solution: "const express = require('express');\nconst app = express();\napp.get('/not-found', (req, res) => res.status(404).send('Not Found'));\napp.get('/unauthorized', (req, res) => res.status(401).send('Unauthorized'));\napp.get('/ok', (req, res) => res.status(200).json({ ok: true }));",
    tests: [
      { expected: "status(404)", type: "contains" },
      { expected: "status(401)", type: "contains" },
      { expected: "status(200)", type: "contains" },
    ],
  },
  {
    id: "node_160",
    type: "code",
    category: "Express",
    title: "Redirect",
    description: "Rediriger une URL.",
    instruction: "Route GET /old qui redirige vers /new (status 301).",
    code_template: "// route redirect\n",
    solution: "app.get('/old', (req, res) => res.redirect(301, '/new'));",
    tests: [
      { expected: "res.redirect", type: "contains" },
    ],
  },
  {
    id: "node_161",
    type: "code",
    category: "Express",
    title: "Custom header",
    description: "Lire et set un header.",
    instruction: "Route GET /me : lisez <code>req.headers['x-api-key']</code>, settez <code>res.setHeader('X-Server', 'carthage')</code>, et retournez la clé.",
    code_template: "// route\n",
    solution: "app.get('/me', (req, res) => {\n  const key = req.headers['x-api-key'];\n  res.setHeader('X-Server', 'carthage');\n  res.json({ key });\n});",
    tests: [
      { expected: "req.headers", type: "contains" },
      { expected: "setHeader", type: "contains" },
    ],
  },
  {
    id: "node_162",
    type: "code",
    category: "Express",
    title: "Param middleware",
    description: "app.param() pour pré-charger.",
    instruction: "Avec <code>app.param('id', ...)</code>, pré-chargez un user fictif <code>req.user = {id, name: 'X'}</code> pour toute route avec :id.",
    code_template: "// app.param\n",
    solution: "app.param('id', (req, res, next, id) => {\n  req.user = { id, name: 'X' };\n  next();\n});",
    tests: [
      { expected: "app.param", type: "contains" },
      { expected: "req.user", type: "contains" },
    ],
  },
  {
    id: "node_163",
    type: "code",
    category: "Express",
    title: "Route chainée",
    description: "GET + POST sur même path.",
    instruction: "Avec <code>app.route('/users')</code>, chaînez <code>.get(...)</code> et <code>.post(...)</code>.",
    code_template: "// app.route\n",
    solution: "app.route('/users')\n  .get((req, res) => res.json([]))\n  .post((req, res) => res.status(201).json({ ok: true }));",
    tests: [
      { expected: "app.route", type: "contains" },
      { expected: ".get(", type: "contains" },
      { expected: ".post(", type: "contains" },
    ],
  },
  {
    id: "node_164",
    type: "code",
    category: "Express",
    title: "Wildcard route",
    description: "Catch-all 404.",
    instruction: "Définissez une route catch-all <code>app.use((req, res) => res.status(404).json({error: 'not found'}))</code> à la fin.",
    code_template: "const express = require('express');\nconst app = express();\n// catch-all\n",
    solution: "const express = require('express');\nconst app = express();\napp.use((req, res) => res.status(404).json({ error: 'not found' }));",
    tests: [
      { expected: "status(404)", type: "contains" },
      { expected: "'not found'", type: "contains" },
    ],
  },
  {
    id: "node_165",
    type: "code",
    category: "Express",
    title: "Templating EJS",
    description: "Vue server-side.",
    instruction: "Settez le view engine à 'ejs', view dir './views'. Route <code>GET /</code> qui render 'index' avec <code>{title: 'Carthage'}</code>.",
    code_template: "const express = require('express');\nconst app = express();\n// ejs setup + route\n",
    solution: "const express = require('express');\nconst app = express();\napp.set('view engine', 'ejs');\napp.set('views', './views');\napp.get('/', (req, res) => res.render('index', { title: 'Carthage' }));",
    tests: [
      { expected: "'view engine'", type: "contains" },
      { expected: "res.render", type: "contains" },
    ],
  },
  {
    id: "node_166",
    type: "code",
    category: "Express",
    title: "Rate limit",
    description: "Empêcher le spam.",
    instruction: "Avec <code>express-rate-limit</code>, limitez à 100 requêtes / 15 minutes globalement.",
    code_template: "const express = require('express');\nconst rateLimit = require('express-rate-limit');\nconst app = express();\n// limiter\n",
    solution: "const express = require('express');\nconst rateLimit = require('express-rate-limit');\nconst app = express();\nconst limiter = rateLimit({ windowMs: 15 * 60 * 1000, max: 100 });\napp.use(limiter);",
    tests: [
      { expected: "rateLimit", type: "contains" },
      { expected: "windowMs", type: "contains" },
      { expected: "max:", type: "contains" },
    ],
  },
  {
    id: "node_167",
    type: "code",
    category: "Express",
    title: "Compression gzip",
    description: "Réduire la bande passante.",
    instruction: "Activez le middleware <code>compression</code> globalement.",
    code_template: "const express = require('express');\nconst compression = require('compression');\nconst app = express();\n// compression\n",
    solution: "const express = require('express');\nconst compression = require('compression');\nconst app = express();\napp.use(compression());",
    tests: [
      { expected: "compression", type: "contains" },
      { expected: "app.use(compression", type: "contains" },
    ],
  },
  {
    id: "node_168",
    type: "code",
    category: "Express",
    title: "URL-encoded body",
    description: "Forms HTML.",
    instruction: "Activez <code>express.urlencoded({extended: true})</code> pour les forms HTML.",
    code_template: "const express = require('express');\nconst app = express();\n// urlencoded\n",
    solution: "const express = require('express');\nconst app = express();\napp.use(express.urlencoded({ extended: true }));",
    tests: [
      { expected: "urlencoded", type: "contains" },
      { expected: "extended: true", type: "contains" },
    ],
  },
  {
    id: "node_169",
    type: "code",
    category: "Express",
    title: "Health check",
    description: "Endpoint /health.",
    instruction: "Route GET /health qui retourne 200 + <code>{status: 'ok', uptime: process.uptime()}</code>.",
    code_template: "// /health\n",
    solution: "app.get('/health', (req, res) => res.json({ status: 'ok', uptime: process.uptime() }));",
    tests: [
      { expected: "'/health'", type: "contains" },
      { expected: "process.uptime", type: "contains" },
    ],
  },
  {
    id: "node_170",
    type: "code",
    category: "Express",
    title: "Graceful shutdown",
    description: "Fermer proprement sur SIGTERM.",
    instruction: "Sur SIGTERM, fermez le serveur HTTP avec server.close() puis log 'bye'.",
    code_template: "const server = app.listen(3000);\n// SIGTERM\n",
    solution: "const server = app.listen(3000);\nprocess.on('SIGTERM', () => {\n  server.close(() => {\n    console.log('bye');\n  });\n});",
    tests: [
      { expected: "'SIGTERM'", type: "contains" },
      { expected: "server.close", type: "contains" },
    ],
  },
];

addExercises("nodejs", exercises);
