import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/**
 * Node.js — Part 6 : streams, Buffer, file system avancé.
 */
const exercises: Exercise[] = [
  {
    id: "node_121",
    type: "code",
    category: "Streams",
    title: "Readable stream basique",
    description: "Lire fichier en streaming.",
    instruction: "Avec <code>fs.createReadStream('file.txt')</code>, écoutez l'event <code>'data'</code> qui log chaque chunk reçu et <code>'end'</code> qui log 'terminé'.",
    code_template: "const fs = require('fs');\nconst stream = fs.createReadStream('file.txt');\n// data + end events",
    solution: "const fs = require('fs');\nconst stream = fs.createReadStream('file.txt');\nstream.on('data', chunk => console.log('chunk:', chunk.length));\nstream.on('end', () => console.log('terminé'));",
    tests: [
      { expected: "createReadStream", type: "contains" },
      { expected: "'data'", type: "contains" },
      { expected: "'end'", type: "contains" },
    ],
  },
  {
    id: "node_122",
    type: "code",
    category: "Streams",
    title: "Writable stream",
    description: "Écrire en streaming.",
    instruction: "Créez un writable stream <code>fs.createWriteStream('out.txt')</code>, écrivez 'hello\\n' avec <code>.write</code>, fermez avec <code>.end()</code>.",
    code_template: "const fs = require('fs');\n// createWriteStream\n",
    solution: "const fs = require('fs');\nconst ws = fs.createWriteStream('out.txt');\nws.write('hello\\n');\nws.end();",
    tests: [
      { expected: "createWriteStream", type: "contains" },
      { expected: ".write(", type: "contains" },
      { expected: ".end()", type: "contains" },
    ],
  },
  {
    id: "node_123",
    type: "code",
    category: "Streams",
    title: "pipe (copie de fichier)",
    description: "Brancher read vers write.",
    instruction: "Copiez <code>src.txt</code> vers <code>dst.txt</code> via <code>readStream.pipe(writeStream)</code>.",
    code_template: "const fs = require('fs');\n// pipe\n",
    solution: "const fs = require('fs');\nfs.createReadStream('src.txt').pipe(fs.createWriteStream('dst.txt'));",
    tests: [
      { expected: ".pipe(", type: "contains" },
    ],
  },
  {
    id: "node_124",
    type: "code",
    category: "Streams",
    title: "Transform stream",
    description: "Transformer les chunks au passage.",
    instruction: "Créez un Transform stream qui upper-case les chunks. Branchez stdin → transform → stdout via pipe.",
    code_template: "const { Transform } = require('stream');\n// Transform\n",
    solution: "const { Transform } = require('stream');\nconst upper = new Transform({\n  transform(chunk, _enc, cb) {\n    cb(null, chunk.toString().toUpperCase());\n  }\n});\nprocess.stdin.pipe(upper).pipe(process.stdout);",
    tests: [
      { expected: "Transform", type: "contains" },
      { expected: "toUpperCase", type: "contains" },
      { expected: ".pipe(", type: "contains" },
    ],
  },
  {
    id: "node_125",
    type: "code",
    category: "Streams",
    title: "Pipeline avec error handling",
    description: "Mieux que pipe — détecte les erreurs.",
    instruction: "Avec <code>require('stream').pipeline</code>, copiez src vers dst avec un callback final qui log 'OK' ou l'erreur.",
    code_template: "const fs = require('fs');\nconst { pipeline } = require('stream');\n// pipeline\n",
    solution: "const fs = require('fs');\nconst { pipeline } = require('stream');\npipeline(\n  fs.createReadStream('src.txt'),\n  fs.createWriteStream('dst.txt'),\n  (err) => {\n    if (err) console.error(err);\n    else console.log('OK');\n  }\n);",
    tests: [
      { expected: "pipeline(", type: "contains" },
      { expected: "console.log('OK')", type: "contains" },
    ],
  },
  {
    id: "node_126",
    type: "code",
    category: "Streams",
    title: "Stream highWaterMark",
    description: "Contrôler la taille des chunks.",
    instruction: "Créez un readStream avec <code>highWaterMark: 1024</code> (1 KB chunks).",
    code_template: "const fs = require('fs');\n// readStream avec highWaterMark\n",
    solution: "const fs = require('fs');\nconst stream = fs.createReadStream('big.txt', { highWaterMark: 1024 });",
    tests: [
      { expected: "highWaterMark", type: "contains" },
      { expected: "1024", type: "contains" },
    ],
  },
  {
    id: "node_127",
    type: "code",
    category: "Streams",
    title: "Backpressure",
    description: "Stop / resume du producteur.",
    instruction: "Écrivez en boucle dans un writable. Si <code>.write</code> retourne false, écoutez <code>'drain'</code> pour reprendre.",
    code_template: "const fs = require('fs');\nconst ws = fs.createWriteStream('out.txt');\n// gestion backpressure\n",
    solution: "const fs = require('fs');\nconst ws = fs.createWriteStream('out.txt');\nlet i = 0;\nfunction write() {\n  while (i < 1000) {\n    if (!ws.write(i + '\\n')) return ws.once('drain', write);\n    i++;\n  }\n  ws.end();\n}\nwrite();",
    tests: [
      { expected: "'drain'", type: "contains" },
      { expected: ".once(", type: "contains" },
    ],
  },
  {
    id: "node_128",
    type: "code",
    category: "Streams",
    title: "Stream JSON par ligne",
    description: "Parser un JSONL (chaque ligne = 1 JSON).",
    instruction: "Lisez <code>data.jsonl</code> en streaming. Pour chaque ligne, faites JSON.parse et loggez l'id.",
    code_template: "const fs = require('fs');\nconst readline = require('readline');\n// readline + parse\n",
    solution: "const fs = require('fs');\nconst readline = require('readline');\nconst rl = readline.createInterface({\n  input: fs.createReadStream('data.jsonl'),\n  crlfDelay: Infinity\n});\nrl.on('line', (line) => {\n  const obj = JSON.parse(line);\n  console.log(obj.id);\n});",
    tests: [
      { expected: "readline", type: "contains" },
      { expected: "JSON.parse(line)", type: "contains" },
    ],
  },
  {
    id: "node_129",
    type: "code",
    category: "Buffer",
    title: "Buffer.from",
    description: "Créer un buffer depuis une chaîne.",
    instruction: "Créez un Buffer depuis <code>'Bonjour'</code>, puis affichez sa taille avec <code>.length</code>.",
    code_template: "// Buffer.from\n",
    solution: "const buf = Buffer.from('Bonjour');\nconsole.log(buf.length);",
    tests: [
      { expected: "Buffer.from", type: "contains" },
      { expected: ".length", type: "contains" },
    ],
  },
  {
    id: "node_130",
    type: "code",
    category: "Buffer",
    title: "Buffer toString",
    description: "Décoder en string.",
    instruction: "Créez un buffer puis convertissez-le en string utf8. Loggez la string.",
    code_template: "const buf = Buffer.from([72, 105]);\n// toString\n",
    solution: "const buf = Buffer.from([72, 105]);\nconsole.log(buf.toString('utf8'));",
    tests: [
      { expected: ".toString(", type: "contains" },
    ],
  },
  {
    id: "node_131",
    type: "code",
    category: "Buffer",
    title: "Buffer hex",
    description: "Encoder en hexadécimal.",
    instruction: "Convertissez <code>Buffer.from('AB')</code> en hex avec <code>.toString('hex')</code>.",
    code_template: "const buf = Buffer.from('AB');\n",
    solution: "const buf = Buffer.from('AB');\nconsole.log(buf.toString('hex'));",
    tests: [
      { expected: "'hex'", type: "contains" },
    ],
  },
  {
    id: "node_132",
    type: "code",
    category: "Buffer",
    title: "Buffer base64",
    description: "Encoder en base64.",
    instruction: "Encodez <code>'Hello'</code> en base64.",
    code_template: "// base64\n",
    solution: "const enc = Buffer.from('Hello').toString('base64');\nconsole.log(enc);",
    tests: [
      { expected: "'base64'", type: "contains" },
    ],
  },
  {
    id: "node_133",
    type: "code",
    category: "Buffer",
    title: "Buffer.concat",
    description: "Combiner plusieurs buffers.",
    instruction: "Concaténez <code>Buffer.from('Hello ')</code> et <code>Buffer.from('World')</code> avec <code>Buffer.concat</code>, affichez la string.",
    code_template: "// Buffer.concat\n",
    solution: "const a = Buffer.from('Hello ');\nconst b = Buffer.from('World');\nconsole.log(Buffer.concat([a, b]).toString());",
    tests: [
      { expected: "Buffer.concat", type: "contains" },
    ],
  },
  {
    id: "node_134",
    type: "code",
    category: "Buffer",
    title: "Buffer.alloc",
    description: "Allouer un buffer vide.",
    instruction: "Allouez un buffer de 10 octets initialisés à 0 avec <code>Buffer.alloc(10)</code>. Affichez sa taille.",
    code_template: "// Buffer.alloc\n",
    solution: "const buf = Buffer.alloc(10);\nconsole.log(buf.length);",
    tests: [
      { expected: "Buffer.alloc", type: "contains" },
    ],
  },
  {
    id: "node_135",
    type: "code",
    category: "File System",
    title: "fs.promises.readFile",
    description: "Lecture async moderne.",
    instruction: "Lisez <code>config.json</code> avec <code>fs.promises.readFile</code> + await et parsez en JSON.",
    code_template: "const fs = require('fs/promises');\n\nasync function main() {\n  // \n}\nmain();",
    solution: "const fs = require('fs/promises');\n\nasync function main() {\n  const data = await fs.readFile('config.json', 'utf8');\n  const obj = JSON.parse(data);\n  console.log(obj);\n}\nmain();",
    tests: [
      { expected: "fs.readFile", type: "contains" },
      { expected: "JSON.parse", type: "contains" },
      { expected: "await", type: "contains" },
    ],
  },
  {
    id: "node_136",
    type: "code",
    category: "File System",
    title: "fs.promises.writeFile",
    description: "Écriture async.",
    instruction: "Écrivez <code>'{\"x\":1}'</code> dans <code>data.json</code> avec writeFile + await.",
    code_template: "const fs = require('fs/promises');\nasync function main() {\n  // \n}\nmain();",
    solution: "const fs = require('fs/promises');\nasync function main() {\n  await fs.writeFile('data.json', '{\"x\":1}');\n}\nmain();",
    tests: [
      { expected: "fs.writeFile", type: "contains" },
    ],
  },
  {
    id: "node_137",
    type: "code",
    category: "File System",
    title: "fs.stat",
    description: "Métadonnées d'un fichier.",
    instruction: "Récupérez les stats de <code>file.txt</code> avec <code>fs.promises.stat</code> et loggez la taille.",
    code_template: "const fs = require('fs/promises');\nasync function main() {\n  // \n}\nmain();",
    solution: "const fs = require('fs/promises');\nasync function main() {\n  const s = await fs.stat('file.txt');\n  console.log(s.size);\n}\nmain();",
    tests: [
      { expected: "fs.stat", type: "contains" },
      { expected: ".size", type: "contains" },
    ],
  },
  {
    id: "node_138",
    type: "code",
    category: "File System",
    title: "fs.readdir",
    description: "Lister un dossier.",
    instruction: "Listez les entrées de <code>./</code> avec <code>fs.promises.readdir</code>, loggez chaque nom.",
    code_template: "const fs = require('fs/promises');\nasync function main() {\n  // \n}\nmain();",
    solution: "const fs = require('fs/promises');\nasync function main() {\n  const entries = await fs.readdir('./');\n  for (const e of entries) console.log(e);\n}\nmain();",
    tests: [
      { expected: "fs.readdir", type: "contains" },
    ],
  },
  {
    id: "node_139",
    type: "code",
    category: "File System",
    title: "fs.mkdir recursif",
    description: "Créer une arbo profonde.",
    instruction: "Créez <code>a/b/c</code> avec <code>fs.promises.mkdir(..., { recursive: true })</code>.",
    code_template: "const fs = require('fs/promises');\nasync function main() {\n  // \n}\nmain();",
    solution: "const fs = require('fs/promises');\nasync function main() {\n  await fs.mkdir('a/b/c', { recursive: true });\n}\nmain();",
    tests: [
      { expected: "recursive: true", type: "contains" },
    ],
  },
  {
    id: "node_140",
    type: "code",
    category: "File System",
    title: "fs.unlink",
    description: "Supprimer un fichier.",
    instruction: "Supprimez <code>temp.txt</code> avec <code>fs.promises.unlink</code>. Captez l'erreur si le fichier n'existe pas.",
    code_template: "const fs = require('fs/promises');\nasync function main() {\n  try { /* */ } catch (e) { console.error(e.code); }\n}\nmain();",
    solution: "const fs = require('fs/promises');\nasync function main() {\n  try { await fs.unlink('temp.txt'); } catch (e) { console.error(e.code); }\n}\nmain();",
    tests: [
      { expected: "fs.unlink", type: "contains" },
      { expected: "try", type: "contains" },
    ],
  },
  {
    id: "node_141",
    type: "code",
    category: "Path",
    title: "path.join",
    description: "Construire un chemin portable.",
    instruction: "Joignez <code>'usr', 'local', 'bin'</code> avec <code>path.join</code> et loggez.",
    code_template: "const path = require('path');\n",
    solution: "const path = require('path');\nconsole.log(path.join('usr', 'local', 'bin'));",
    tests: [
      { expected: "path.join", type: "contains" },
    ],
  },
  {
    id: "node_142",
    type: "code",
    category: "Path",
    title: "path.resolve",
    description: "Résoudre en chemin absolu.",
    instruction: "Avec <code>path.resolve('a', 'b', 'c.txt')</code>, obtenez le chemin absolu. Loggez le résultat.",
    code_template: "const path = require('path');\n",
    solution: "const path = require('path');\nconsole.log(path.resolve('a', 'b', 'c.txt'));",
    tests: [
      { expected: "path.resolve", type: "contains" },
    ],
  },
  {
    id: "node_143",
    type: "code",
    category: "Path",
    title: "path.parse",
    description: "Décomposer un chemin.",
    instruction: "Parsez <code>'/foo/bar/baz.txt'</code> avec <code>path.parse</code>. Loggez le résultat (dir, base, name, ext).",
    code_template: "const path = require('path');\n",
    solution: "const path = require('path');\nconsole.log(path.parse('/foo/bar/baz.txt'));",
    tests: [
      { expected: "path.parse", type: "contains" },
    ],
  },
  {
    id: "node_144",
    type: "code",
    category: "Path",
    title: "__dirname / __filename",
    description: "Variables globales du module.",
    instruction: "Loggez <code>__dirname</code> puis <code>__filename</code>.",
    code_template: "// dirname + filename\n",
    solution: "console.log(__dirname);\nconsole.log(__filename);",
    tests: [
      { expected: "__dirname", type: "contains" },
      { expected: "__filename", type: "contains" },
    ],
  },
  {
    id: "node_145",
    type: "code",
    category: "Streams",
    title: "Pipe gzip",
    description: "Compresser en streaming.",
    instruction: "Compressez <code>data.txt</code> en <code>data.txt.gz</code> via <code>zlib.createGzip()</code> dans un pipe.",
    code_template: "const fs = require('fs');\nconst zlib = require('zlib');\n",
    solution: "const fs = require('fs');\nconst zlib = require('zlib');\nfs.createReadStream('data.txt')\n  .pipe(zlib.createGzip())\n  .pipe(fs.createWriteStream('data.txt.gz'));",
    tests: [
      { expected: "createGzip", type: "contains" },
      { expected: ".pipe(", type: "contains" },
    ],
  },
];

addExercises("nodejs", exercises);
