import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/**
 * Python — Part 9 : stdlib (math, json, regex, itertools, os.path) + algorithmes.
 */
const exercises: Exercise[] = [
  {
    id: "py_s9_e1",
    title: "math.sqrt",
    description: "Racine carrée.",
    instruction: "Affichez <code>math.sqrt(144)</code> en entier (utilisez <code>int()</code>).",
    code_template: "import math\n",
    solution: "import math\nprint(int(math.sqrt(144)))",
    tests: [{ type: "output", expected: "12" }],
    category: "math",
  },
  {
    id: "py_s9_e2",
    title: "math.pi",
    description: "Constante.",
    instruction: "Affichez π arrondi à 4 décimales.",
    code_template: "import math\n",
    solution: "import math\nprint(round(math.pi, 4))",
    tests: [{ type: "output", expected: "3.1416" }],
    category: "math",
  },
  {
    id: "py_s9_e3",
    title: "math.gcd",
    description: "Plus grand commun diviseur.",
    instruction: "Affichez <code>math.gcd(48, 36)</code>.",
    code_template: "import math\n",
    solution: "import math\nprint(math.gcd(48, 36))",
    tests: [
      { type: "contains", expected: "math.gcd" },
      { type: "output", expected: "12" },
    ],
    category: "math",
  },
  {
    id: "py_s9_e4",
    title: "math.factorial",
    description: "n!",
    instruction: "Affichez <code>math.factorial(7)</code>.",
    code_template: "import math\n",
    solution: "import math\nprint(math.factorial(7))",
    tests: [{ type: "output", expected: "5040" }],
    category: "math",
  },
  {
    id: "py_s9_e5",
    title: "math.log",
    description: "Logarithme.",
    instruction: "Affichez <code>math.log2(1024)</code> en entier.",
    code_template: "import math\n",
    solution: "import math\nprint(int(math.log2(1024)))",
    tests: [{ type: "output", expected: "10" }],
    category: "math",
  },
  {
    id: "py_s9_e6",
    title: "random.seed + random.random",
    description: "Génération pseudo-aléatoire reproductible.",
    instruction: "Avec <code>random.seed(42)</code>, affichez 3 nombres <code>random.random()</code> arrondis à 4 décimales, séparés par espaces.",
    code_template: "import random\nrandom.seed(42)\n",
    solution: "import random\nrandom.seed(42)\nprint(' '.join(str(round(random.random(), 4)) for _ in range(3)))",
    tests: [
      { type: "contains", expected: "random.seed" },
      { type: "output", expected: "0.6394 0.0251 0.2754" },
    ],
    category: "random",
  },
  {
    id: "py_s9_e7",
    title: "random.choice",
    description: "Élément aléatoire d'une liste.",
    instruction: "Avec <code>random.seed(1)</code>, affichez <code>random.choice(['a', 'b', 'c', 'd'])</code>.",
    code_template: "import random\nrandom.seed(1)\n",
    solution: "import random\nrandom.seed(1)\nprint(random.choice(['a', 'b', 'c', 'd']))",
    tests: [
      { type: "contains", expected: "random.choice" },
      { type: "output", expected: "b" },
    ],
    category: "random",
  },
  {
    id: "py_s9_e8",
    title: "random.shuffle",
    description: "Mélanger en place.",
    instruction: "Avec <code>seed(7)</code>, mélangez <code>[1, 2, 3, 4, 5]</code> et affichez.",
    code_template: "import random\nrandom.seed(7)\nt = [1, 2, 3, 4, 5]\n",
    solution: "import random\nrandom.seed(7)\nt = [1, 2, 3, 4, 5]\nrandom.shuffle(t)\nprint(t)",
    tests: [{ type: "output", expected: "[3, 4, 5, 2, 1]" }],
    category: "random",
  },
  {
    id: "py_s9_e9",
    title: "itertools.count",
    description: "Compteur infini.",
    instruction: "Avec <code>itertools.count(10)</code> + <code>itertools.islice</code>, récupérez les 5 premiers nombres et affichez-les joints par virgule.",
    code_template: "import itertools\n",
    solution: "import itertools\nprint(','.join(str(x) for x in itertools.islice(itertools.count(10), 5)))",
    tests: [{ type: "output", expected: "10,11,12,13,14" }],
    category: "itertools",
  },
  {
    id: "py_s9_e10",
    title: "itertools.cycle",
    description: "Boucler infiniment.",
    instruction: "Avec <code>itertools.cycle</code> sur <code>['rouge', 'vert', 'bleu']</code> et <code>islice(7)</code>, affichez la séquence jointe par virgule.",
    code_template: "import itertools\n",
    solution: "import itertools\nprint(','.join(itertools.islice(itertools.cycle(['rouge', 'vert', 'bleu']), 7)))",
    tests: [{ type: "output", expected: "rouge,vert,bleu,rouge,vert,bleu,rouge" }],
    category: "itertools",
  },
  {
    id: "py_s9_e11",
    title: "itertools.permutations",
    description: "Toutes les permutations.",
    instruction: "Affichez le nombre de permutations de <code>[1, 2, 3]</code> (devrait être 6).",
    code_template: "import itertools\n",
    solution: "import itertools\nprint(len(list(itertools.permutations([1, 2, 3]))))",
    tests: [
      { type: "contains", expected: "permutations" },
      { type: "output", expected: "6" },
    ],
    category: "itertools",
  },
  {
    id: "py_s9_e12",
    title: "itertools.combinations",
    description: "Choix sans remise.",
    instruction: "Combien de combinaisons de 2 parmi <code>[1, 2, 3, 4]</code> ? Affichez le nombre.",
    code_template: "import itertools\n",
    solution: "import itertools\nprint(len(list(itertools.combinations([1, 2, 3, 4], 2))))",
    tests: [
      { type: "contains", expected: "combinations" },
      { type: "output", expected: "6" },
    ],
    category: "itertools",
  },
  {
    id: "py_s9_e13",
    title: "itertools.chain",
    description: "Concaténer plusieurs itérables.",
    instruction: "Chainez <code>[1, 2]</code> et <code>[3, 4, 5]</code>, affichez la liste résultante.",
    code_template: "import itertools\n",
    solution: "import itertools\nprint(list(itertools.chain([1, 2], [3, 4, 5])))",
    tests: [{ type: "output", expected: "[1, 2, 3, 4, 5]" }],
    category: "itertools",
  },
  {
    id: "py_s9_e14",
    title: "json.dumps",
    description: "Sérialiser.",
    instruction: "Sérialisez <code>{'nom': 'Aelita', 'niveau': 100}</code> en JSON et affichez. Note : json met les clés/valeurs entre guillemets doubles.",
    code_template: "import json\n",
    solution: "import json\nprint(json.dumps({'nom': 'Aelita', 'niveau': 100}))",
    tests: [
      { type: "contains", expected: "json.dumps" },
      { type: "output", expected: '{"nom": "Aelita", "niveau": 100}' },
    ],
    category: "json",
  },
  {
    id: "py_s9_e15",
    title: "json.loads",
    description: "Désérialiser.",
    instruction: "Parsez <code>'{\"x\": 10, \"y\": 20}'</code> avec <code>json.loads</code> et affichez la somme x+y.",
    code_template: "import json\ns = '{\"x\": 10, \"y\": 20}'\n",
    solution: "import json\ns = '{\"x\": 10, \"y\": 20}'\nd = json.loads(s)\nprint(d['x'] + d['y'])",
    tests: [{ type: "output", expected: "30" }],
    category: "json",
  },
  {
    id: "py_s9_e16",
    title: "re.match",
    description: "Vérifier le début d'une string.",
    instruction: "Avec <code>re.match(r'\\d+', 'abc123')</code>, vérifiez le retour. Affichez 'None' si pas de match, sinon le match (ici None).",
    code_template: "import re\n",
    solution: "import re\nm = re.match(r'\\d+', 'abc123')\nprint(m if m else None)",
    tests: [{ type: "output", expected: "None" }],
    category: "regex",
  },
  {
    id: "py_s9_e17",
    title: "re.search",
    description: "Chercher n'importe où.",
    instruction: "Avec <code>re.search(r'\\d+', 'abc123def')</code>, extrayez la string matchée (<code>m.group()</code>).",
    code_template: "import re\n",
    solution: "import re\nm = re.search(r'\\d+', 'abc123def')\nprint(m.group())",
    tests: [{ type: "output", expected: "123" }],
    category: "regex",
  },
  {
    id: "py_s9_e18",
    title: "re.findall",
    description: "Toutes les correspondances.",
    instruction: "Trouvez tous les nombres dans <code>'le 21/05/2026 à 14:30'</code> avec <code>re.findall(r'\\d+', ...)</code>. Affichez la liste.",
    code_template: "import re\n",
    solution: "import re\nprint(re.findall(r'\\d+', 'le 21/05/2026 à 14:30'))",
    tests: [{ type: "output", expected: "['21', '05', '2026', '14', '30']" }],
    category: "regex",
  },
  {
    id: "py_s9_e19",
    title: "re.sub",
    description: "Substitution regex.",
    instruction: "Remplacez tous les chiffres de <code>'a1b2c3'</code> par <code>'X'</code>. Affichez le résultat.",
    code_template: "import re\n",
    solution: "import re\nprint(re.sub(r'\\d', 'X', 'a1b2c3'))",
    tests: [{ type: "output", expected: "aXbXcX" }],
    category: "regex",
  },
  {
    id: "py_s9_e20",
    title: "Recherche dichotomique",
    description: "Binary search.",
    instruction: "Implémentez binary search pour trouver l'indice de 23 dans <code>[1, 3, 5, 7, 11, 17, 23, 29, 31]</code>. Affichez l'indice.",
    code_template: "t = [1, 3, 5, 7, 11, 17, 23, 29, 31]\ntarget = 23\nlo, hi = 0, len(t) - 1\n# dichotomie\n",
    solution: "t = [1, 3, 5, 7, 11, 17, 23, 29, 31]\ntarget = 23\nlo, hi = 0, len(t) - 1\nidx = -1\nwhile lo <= hi:\n    mid = (lo + hi) // 2\n    if t[mid] == target:\n        idx = mid\n        break\n    if t[mid] < target:\n        lo = mid + 1\n    else:\n        hi = mid - 1\nprint(idx)",
    tests: [{ type: "output", expected: "6" }],
    category: "Algorithmes",
  },
  {
    id: "py_s9_e21",
    title: "bisect",
    description: "Binary search via stdlib.",
    instruction: "Avec <code>bisect.bisect_left([1, 3, 5, 7, 9], 6)</code>, affichez la position d'insertion. Devrait être 3.",
    code_template: "import bisect\n",
    solution: "import bisect\nprint(bisect.bisect_left([1, 3, 5, 7, 9], 6))",
    tests: [
      { type: "contains", expected: "bisect" },
      { type: "output", expected: "3" },
    ],
    category: "Algorithmes",
  },
  {
    id: "py_s9_e22",
    title: "Tri à bulles",
    description: "Implémentation manuelle.",
    instruction: "Triez <code>[5, 2, 8, 1, 4]</code> avec bubble sort. Affichez le résultat.",
    code_template: "t = [5, 2, 8, 1, 4]\n# bubble\n",
    solution: "t = [5, 2, 8, 1, 4]\nn = len(t)\nfor i in range(n):\n    for j in range(0, n - i - 1):\n        if t[j] > t[j+1]:\n            t[j], t[j+1] = t[j+1], t[j]\nprint(t)",
    tests: [{ type: "output", expected: "[1, 2, 4, 5, 8]" }],
    category: "Algorithmes",
  },
  {
    id: "py_s9_e23",
    title: "Quicksort",
    description: "Diviser pour régner.",
    instruction: "Implémentez quicksort sur <code>[3, 6, 1, 5, 8, 2, 7, 4]</code>. Affichez le résultat.",
    code_template: "def qsort(t):\n    if len(t) <= 1:\n        return t\n    # pivot\n    return t\n\nprint(qsort([3, 6, 1, 5, 8, 2, 7, 4]))\n",
    solution: "def qsort(t):\n    if len(t) <= 1:\n        return t\n    pivot = t[0]\n    rest = t[1:]\n    less = [x for x in rest if x <= pivot]\n    great = [x for x in rest if x > pivot]\n    return qsort(less) + [pivot] + qsort(great)\n\nprint(qsort([3, 6, 1, 5, 8, 2, 7, 4]))",
    tests: [{ type: "output", expected: "[1, 2, 3, 4, 5, 6, 7, 8]" }],
    category: "Algorithmes",
  },
  {
    id: "py_s9_e24",
    title: "Fibonacci itératif",
    description: "Sans récursion exponentielle.",
    instruction: "Calculez fib(30). Réponse : 832040.",
    code_template: "n = 30\na, b = 0, 1\n# itérer\nprint(a)\n",
    solution: "n = 30\na, b = 0, 1\nfor _ in range(n):\n    a, b = b, a + b\nprint(a)",
    tests: [{ type: "output", expected: "832040" }],
    category: "Algorithmes",
  },
  {
    id: "py_s9_e25",
    title: "FizzBuzz Pythonique",
    description: "Classique avec list comprehension.",
    instruction: "Affichez FizzBuzz de 1 à 15 (multiples de 3 → 'Fizz', de 5 → 'Buzz', des deux → 'FizzBuzz') un par ligne.",
    code_template: "# FizzBuzz\n",
    solution: "for i in range(1, 16):\n    if i % 15 == 0:\n        print('FizzBuzz')\n    elif i % 3 == 0:\n        print('Fizz')\n    elif i % 5 == 0:\n        print('Buzz')\n    else:\n        print(i)",
    tests: [{ type: "output", expected: "1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz" }],
    category: "Final",
    hint: "Tu viens de finir 220+ exos Python. Bravo Lyoko-warrior !",
  },
];

addExercises("python", exercises);
