import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/**
 * Python — Part 7 : dictionnaires, sets, fonctions avancées (lambda, decorators).
 */
const exercises: Exercise[] = [
  {
    id: "py_s7_e1",
    title: "Dict basique",
    description: "Créer + accéder.",
    instruction: "Créez le dict <code>{'a': 1, 'b': 2, 'c': 3}</code> et affichez la valeur de la clé 'b'.",
    code_template: "d = {'a': 1, 'b': 2, 'c': 3}\n",
    solution: "d = {'a': 1, 'b': 2, 'c': 3}\nprint(d['b'])",
    tests: [{ type: "output", expected: "2" }],
    category: "Dictionnaires",
  },
  {
    id: "py_s7_e2",
    title: "dict.get avec défaut",
    description: "Accès sûr.",
    instruction: "Pour <code>{'x': 10}</code>, affichez la valeur de 'y' avec <code>.get</code> et un défaut de -1.",
    code_template: "d = {'x': 10}\n",
    solution: "d = {'x': 10}\nprint(d.get('y', -1))",
    tests: [
      { type: "contains", expected: ".get(" },
      { type: "output", expected: "-1" },
    ],
    category: "Dictionnaires",
  },
  {
    id: "py_s7_e3",
    title: "Itérer un dict",
    description: "Items.",
    instruction: "Pour <code>{'a': 1, 'b': 2}</code>, affichez chaque paire <code>clé=valeur</code> sur sa propre ligne (utilisez <code>.items()</code>, ordre d'insertion).",
    code_template: "d = {'a': 1, 'b': 2}\n",
    solution: "d = {'a': 1, 'b': 2}\nfor k, v in d.items():\n    print(f'{k}={v}')",
    tests: [
      { type: "contains", expected: ".items" },
      { type: "output", expected: "a=1\nb=2" },
    ],
    category: "Dictionnaires",
  },
  {
    id: "py_s7_e4",
    title: "Dict comprehension",
    description: "Construire un dict avec une expression.",
    instruction: "Créez <code>{x: x**2 for x in range(1, 6)}</code> et affichez-le.",
    code_template: "# dict comp\n",
    solution: "print({x: x**2 for x in range(1, 6)})",
    tests: [{ type: "output", expected: "{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}" }],
    category: "Dictionnaires",
  },
  {
    id: "py_s7_e5",
    title: "Inverser un dict",
    description: "Échanger clés et valeurs.",
    instruction: "Inversez <code>{'a': 1, 'b': 2, 'c': 3}</code> avec une dict comp pour obtenir <code>{1: 'a', 2: 'b', 3: 'c'}</code>. Affichez le résultat.",
    code_template: "d = {'a': 1, 'b': 2, 'c': 3}\n",
    solution: "d = {'a': 1, 'b': 2, 'c': 3}\nprint({v: k for k, v in d.items()})",
    tests: [{ type: "output", expected: "{1: 'a', 2: 'b', 3: 'c'}" }],
    category: "Dictionnaires",
  },
  {
    id: "py_s7_e6",
    title: "Fusionner deux dicts (Python 3.9+)",
    description: "Operator |.",
    instruction: "Fusionnez <code>{'a': 1, 'b': 2}</code> et <code>{'b': 3, 'c': 4}</code> avec l'opérateur <code>|</code>. Affichez le résultat.",
    code_template: "a = {'a': 1, 'b': 2}\nb = {'b': 3, 'c': 4}\n",
    solution: "a = {'a': 1, 'b': 2}\nb = {'b': 3, 'c': 4}\nprint(a | b)",
    tests: [{ type: "output", expected: "{'a': 1, 'b': 3, 'c': 4}" }],
    category: "Dictionnaires",
  },
  {
    id: "py_s7_e7",
    title: "setdefault",
    description: "Insérer si absent.",
    instruction: "Pour un dict initialement vide, utilisez <code>setdefault('x', 100)</code> deux fois et affichez le dict final (devrait avoir <code>'x': 100</code>).",
    code_template: "d = {}\n",
    solution: "d = {}\nd.setdefault('x', 100)\nd.setdefault('x', 200)\nprint(d)",
    tests: [
      { type: "contains", expected: "setdefault" },
      { type: "output", expected: "{'x': 100}" },
    ],
    category: "Dictionnaires",
  },
  {
    id: "py_s7_e8",
    title: "Compteur naïf",
    description: "Compter les caractères.",
    instruction: "Comptez les occurrences de chaque caractère dans <code>'banana'</code> avec un dict. Affichez le dict final.",
    code_template: "s = 'banana'\nd = {}\n",
    solution: "s = 'banana'\nd = {}\nfor c in s:\n    d[c] = d.get(c, 0) + 1\nprint(d)",
    tests: [{ type: "output", expected: "{'b': 1, 'a': 3, 'n': 2}" }],
    category: "Dictionnaires",
  },
  {
    id: "py_s7_e9",
    title: "collections.Counter",
    description: "Compter en une ligne.",
    instruction: "Comptez les caractères de <code>'banana'</code> avec <code>collections.Counter</code> et affichez le résultat.",
    code_template: "from collections import Counter\n",
    solution: "from collections import Counter\nprint(Counter('banana'))",
    tests: [
      { type: "contains", expected: "Counter" },
      { type: "output", expected: "Counter({'a': 3, 'n': 2, 'b': 1})" },
    ],
    category: "Collections",
  },
  {
    id: "py_s7_e10",
    title: "Counter.most_common",
    description: "Top N éléments.",
    instruction: "Trouvez les 2 caractères les plus fréquents dans <code>'mississippi'</code>. Affichez la liste retournée par <code>most_common(2)</code>.",
    code_template: "from collections import Counter\ns = 'mississippi'\n",
    solution: "from collections import Counter\ns = 'mississippi'\nprint(Counter(s).most_common(2))",
    tests: [{ type: "output", expected: "[('i', 4), ('s', 4)]" }],
    category: "Collections",
  },
  {
    id: "py_s7_e11",
    title: "defaultdict",
    description: "Valeurs par défaut auto.",
    instruction: "Avec <code>defaultdict(list)</code>, groupez ces couples par première lettre : <code>[('apple', 1), ('banana', 2), ('avocado', 3)]</code>. Affichez le dict final via <code>dict()</code>.",
    code_template: "from collections import defaultdict\npairs = [('apple', 1), ('banana', 2), ('avocado', 3)]\n",
    solution: "from collections import defaultdict\npairs = [('apple', 1), ('banana', 2), ('avocado', 3)]\nd = defaultdict(list)\nfor w, n in pairs:\n    d[w[0]].append(n)\nprint(dict(d))",
    tests: [
      { type: "contains", expected: "defaultdict" },
      { type: "output", expected: "{'a': [1, 3], 'b': [2]}" },
    ],
    category: "Collections",
  },
  {
    id: "py_s7_e12",
    title: "Frozenset",
    description: "Set immuable.",
    instruction: "Créez un frozenset depuis <code>[1, 2, 2, 3]</code>, puis affichez sa taille.",
    code_template: "fs = frozenset([1, 2, 2, 3])\n",
    solution: "fs = frozenset([1, 2, 2, 3])\nprint(len(fs))",
    tests: [
      { type: "contains", expected: "frozenset" },
      { type: "output", expected: "3" },
    ],
    category: "Sets",
  },
  {
    id: "py_s7_e13",
    title: "Set symmetric difference",
    description: "A^B = (A∪B) - (A∩B).",
    instruction: "Pour <code>{1, 2, 3}</code> et <code>{3, 4, 5}</code>, affichez la différence symétrique triée croissante (sous forme de liste).",
    code_template: "a = {1, 2, 3}\nb = {3, 4, 5}\n",
    solution: "a = {1, 2, 3}\nb = {3, 4, 5}\nprint(sorted(a ^ b))",
    tests: [{ type: "output", expected: "[1, 2, 4, 5]" }],
    category: "Sets",
  },
  {
    id: "py_s7_e14",
    title: "Lambda simple",
    description: "Fonction anonyme.",
    instruction: "Utilisez une lambda pour calculer le carré de 7 et affichez le résultat.",
    code_template: "carre = lambda x: x ** 2\n",
    solution: "carre = lambda x: x ** 2\nprint(carre(7))",
    tests: [
      { type: "contains", expected: "lambda" },
      { type: "output", expected: "49" },
    ],
    category: "Lambdas",
  },
  {
    id: "py_s7_e15",
    title: "map + lambda",
    description: "Transformer un itérable.",
    instruction: "Avec <code>map</code> et une lambda, doublez chaque élément de <code>[1, 2, 3, 4]</code>. Affichez la liste résultante.",
    code_template: "t = [1, 2, 3, 4]\n",
    solution: "t = [1, 2, 3, 4]\nprint(list(map(lambda x: x * 2, t)))",
    tests: [{ type: "output", expected: "[2, 4, 6, 8]" }],
    category: "Lambdas",
  },
  {
    id: "py_s7_e16",
    title: "filter + lambda",
    description: "Garder les éléments qui passent un test.",
    instruction: "Avec <code>filter</code> et une lambda, gardez les nombres > 5 de <code>[1, 7, 3, 9, 2, 8]</code>. Affichez la liste résultante.",
    code_template: "t = [1, 7, 3, 9, 2, 8]\n",
    solution: "t = [1, 7, 3, 9, 2, 8]\nprint(list(filter(lambda x: x > 5, t)))",
    tests: [{ type: "output", expected: "[7, 9, 8]" }],
    category: "Lambdas",
  },
  {
    id: "py_s7_e17",
    title: "reduce",
    description: "Accumulation.",
    instruction: "Avec <code>functools.reduce</code>, calculez le produit de <code>[1, 2, 3, 4, 5]</code>. Affichez le résultat (120).",
    code_template: "from functools import reduce\nt = [1, 2, 3, 4, 5]\n",
    solution: "from functools import reduce\nt = [1, 2, 3, 4, 5]\nprint(reduce(lambda a, b: a * b, t))",
    tests: [
      { type: "contains", expected: "reduce" },
      { type: "output", expected: "120" },
    ],
    category: "Lambdas",
  },
  {
    id: "py_s7_e18",
    title: "Sort par clé custom",
    description: "Sort par 2e élément du tuple.",
    instruction: "Triez <code>[('a', 3), ('b', 1), ('c', 2)]</code> par le 2e élément. Affichez le résultat.",
    code_template: "t = [('a', 3), ('b', 1), ('c', 2)]\n",
    solution: "t = [('a', 3), ('b', 1), ('c', 2)]\nprint(sorted(t, key=lambda x: x[1]))",
    tests: [{ type: "output", expected: "[('b', 1), ('c', 2), ('a', 3)]" }],
    category: "Tri",
  },
  {
    id: "py_s7_e19",
    title: "Decorator simple",
    description: "Wrapper avant/après.",
    instruction: "Définissez un décorateur <code>@log</code> qui affiche 'avant' avant l'appel et 'après' après. Décorez une fonction <code>hello()</code> qui affiche 'hello' et appelez-la. Sortie attendue sur 3 lignes.",
    code_template: "def log(fn):\n    def wrapper(*a, **kw):\n        # avant + fn + après\n        pass\n    return wrapper\n\n@log\ndef hello():\n    print('hello')\n\nhello()\n",
    solution: "def log(fn):\n    def wrapper(*a, **kw):\n        print('avant')\n        r = fn(*a, **kw)\n        print('après')\n        return r\n    return wrapper\n\n@log\ndef hello():\n    print('hello')\n\nhello()",
    tests: [
      { type: "regex", expected: "@log" },
      { type: "output", expected: "avant\nhello\napres" },
    ],
    category: "Decorators",
    hint: "Note : l'output test est insensible aux accents.",
  },
  {
    id: "py_s7_e20",
    title: "Decorator avec retour",
    description: "Préserver la valeur retournée.",
    instruction: "Définissez un décorateur <code>@double</code> qui multiplie le retour de la fonction par 2. Décorez <code>def f(): return 21</code>. Affichez <code>f()</code>.",
    code_template: "def double(fn):\n    # wrapper\n    pass\n\n@double\ndef f():\n    return 21\n\nprint(f())\n",
    solution: "def double(fn):\n    def wrapper(*a, **kw):\n        return fn(*a, **kw) * 2\n    return wrapper\n\n@double\ndef f():\n    return 21\n\nprint(f())",
    tests: [{ type: "output", expected: "42" }],
    category: "Decorators",
  },
  {
    id: "py_s7_e21",
    title: "*args",
    description: "Nombre variable d'arguments positionnels.",
    instruction: "Définissez <code>def somme_args(*args)</code> qui retourne la somme. Affichez <code>somme_args(1, 2, 3, 4, 5)</code>.",
    code_template: "def somme_args(*args):\n    # \n    pass\n\nprint(somme_args(1, 2, 3, 4, 5))\n",
    solution: "def somme_args(*args):\n    return sum(args)\n\nprint(somme_args(1, 2, 3, 4, 5))",
    tests: [
      { type: "contains", expected: "*args" },
      { type: "output", expected: "15" },
    ],
    category: "Fonctions",
  },
  {
    id: "py_s7_e22",
    title: "**kwargs",
    description: "Arguments nommés variables.",
    instruction: "Définissez <code>def afficher(**kw)</code> qui affiche chaque <code>clé=valeur</code> sur une ligne (ordre d'insertion). Appelez avec <code>afficher(a=1, b=2, c=3)</code>.",
    code_template: "def afficher(**kw):\n    pass\n\nafficher(a=1, b=2, c=3)\n",
    solution: "def afficher(**kw):\n    for k, v in kw.items():\n        print(f'{k}={v}')\n\nafficher(a=1, b=2, c=3)",
    tests: [
      { type: "contains", expected: "**kw" },
      { type: "output", expected: "a=1\nb=2\nc=3" },
    ],
    category: "Fonctions",
  },
  {
    id: "py_s7_e23",
    title: "Argument par défaut",
    description: "Fonction avec valeur par défaut.",
    instruction: "Définissez <code>def saluer(nom='ami')</code> qui retourne <code>'Bonjour ' + nom</code>. Affichez l'appel sans argument, puis avec 'Aelita'.",
    code_template: "def saluer(nom='ami'):\n    pass\n\nprint(saluer())\nprint(saluer('Aelita'))\n",
    solution: "def saluer(nom='ami'):\n    return 'Bonjour ' + nom\n\nprint(saluer())\nprint(saluer('Aelita'))",
    tests: [{ type: "output", expected: "Bonjour ami\nBonjour Aelita" }],
    category: "Fonctions",
  },
  {
    id: "py_s7_e24",
    title: "Mutable default — piège classique",
    description: "Pourquoi ne PAS utiliser [] comme défaut.",
    instruction: "Démontrez le piège : <code>def ajoute(x, t=[])</code> partage la liste entre appels. Appelez 3 fois avec différentes valeurs sans passer t, et affichez t à chaque retour. (Pédagogique : montre que t n'est jamais réinitialisée.)",
    code_template: "def ajoute(x, t=[]):\n    t.append(x)\n    return t\n\nprint(ajoute(1))\nprint(ajoute(2))\nprint(ajoute(3))\n",
    solution: "def ajoute(x, t=[]):\n    t.append(x)\n    return t\n\nprint(ajoute(1))\nprint(ajoute(2))\nprint(ajoute(3))",
    tests: [{ type: "output", expected: "[1]\n[1, 2]\n[1, 2, 3]" }],
    category: "Fonctions",
    hint: "Le bon pattern : t=None puis if t is None: t = []",
  },
  {
    id: "py_s7_e25",
    title: "Closure Python",
    description: "Fonction interne capturant variables.",
    instruction: "Écrivez <code>def make_counter()</code> qui retourne une fonction <code>inc</code>. Chaque appel à <code>inc()</code> incrémente et retourne le compteur (départ 0). Affichez 3 appels.",
    code_template: "def make_counter():\n    n = 0\n    def inc():\n        nonlocal n\n        # \n        return n\n    return inc\n\nc = make_counter()\nprint(c())\nprint(c())\nprint(c())\n",
    solution: "def make_counter():\n    n = 0\n    def inc():\n        nonlocal n\n        n += 1\n        return n\n    return inc\n\nc = make_counter()\nprint(c())\nprint(c())\nprint(c())",
    tests: [
      { type: "contains", expected: "nonlocal" },
      { type: "output", expected: "1\n2\n3" },
    ],
    category: "Fonctions",
  },
];

addExercises("python", exercises);
