import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/**
 * Python — Part 8 : POO, classes, héritage, dataclasses, properties.
 */
const exercises: Exercise[] = [
  {
    id: "py_s8_e1",
    title: "Première classe",
    description: "__init__ et attribut.",
    instruction: "Définissez <code>class Personne</code> avec <code>__init__(self, nom)</code>. Créez <code>p = Personne('Aelita')</code> et affichez <code>p.nom</code>.",
    code_template: "class Personne:\n    pass\n\np = Personne('Aelita')\nprint(p.nom)\n",
    solution: "class Personne:\n    def __init__(self, nom):\n        self.nom = nom\n\np = Personne('Aelita')\nprint(p.nom)",
    tests: [
      { type: "contains", expected: "class Personne" },
      { type: "output", expected: "Aelita" },
    ],
    category: "POO",
  },
  {
    id: "py_s8_e2",
    title: "Méthode d'instance",
    description: "def avec self.",
    instruction: "Ajoutez une méthode <code>saluer()</code> à <code>Personne</code> qui retourne <code>'Bonjour ' + self.nom</code>. Affichez <code>Personne('Yumi').saluer()</code>.",
    code_template: "class Personne:\n    def __init__(self, nom):\n        self.nom = nom\n    # saluer\n\nprint(Personne('Yumi').saluer())\n",
    solution: "class Personne:\n    def __init__(self, nom):\n        self.nom = nom\n    def saluer(self):\n        return 'Bonjour ' + self.nom\n\nprint(Personne('Yumi').saluer())",
    tests: [{ type: "output", expected: "Bonjour Yumi" }],
    category: "POO",
  },
  {
    id: "py_s8_e3",
    title: "__str__",
    description: "Représentation lisible.",
    instruction: "Pour <code>class Point</code> avec x, y, ajoutez <code>__str__</code> qui retourne <code>'(x, y)'</code>. Affichez <code>print(Point(3, 4))</code>.",
    code_template: "class Point:\n    def __init__(self, x, y):\n        self.x, self.y = x, y\n    # __str__\n\nprint(Point(3, 4))\n",
    solution: "class Point:\n    def __init__(self, x, y):\n        self.x, self.y = x, y\n    def __str__(self):\n        return f'({self.x}, {self.y})'\n\nprint(Point(3, 4))",
    tests: [
      { type: "contains", expected: "__str__" },
      { type: "output", expected: "(3, 4)" },
    ],
    category: "POO",
  },
  {
    id: "py_s8_e4",
    title: "Héritage simple",
    description: "extends en Python.",
    instruction: "Définissez <code>class Animal</code> avec <code>parler()</code> retournant 'bruit'. Définissez <code>class Chien(Animal)</code> qui override <code>parler()</code> pour retourner 'wouf'. Affichez <code>Chien().parler()</code>.",
    code_template: "# classes\n",
    solution: "class Animal:\n    def parler(self):\n        return 'bruit'\nclass Chien(Animal):\n    def parler(self):\n        return 'wouf'\nprint(Chien().parler())",
    tests: [
      { type: "regex", expected: "Chien\\s*\\(\\s*Animal\\s*\\)" },
      { type: "output", expected: "wouf" },
    ],
    category: "Héritage",
  },
  {
    id: "py_s8_e5",
    title: "super().__init__",
    description: "Initialiser le parent.",
    instruction: "<code>class Animal</code> a un nom. <code>class Chien(Animal)</code> a en plus une race. Le constructor de Chien doit appeler <code>super().__init__(nom)</code>. Affichez <code>'nom/race'</code> pour <code>Chien('Rex', 'Labrador')</code>.",
    code_template: "# classes\n",
    solution: "class Animal:\n    def __init__(self, nom):\n        self.nom = nom\nclass Chien(Animal):\n    def __init__(self, nom, race):\n        super().__init__(nom)\n        self.race = race\nc = Chien('Rex', 'Labrador')\nprint(f'{c.nom}/{c.race}')",
    tests: [
      { type: "contains", expected: "super()" },
      { type: "output", expected: "Rex/Labrador" },
    ],
    category: "Héritage",
  },
  {
    id: "py_s8_e6",
    title: "Méthode statique",
    description: "@staticmethod.",
    instruction: "Définissez <code>class Math</code> avec une méthode statique <code>somme(a, b)</code>. Affichez <code>Math.somme(7, 8)</code>.",
    code_template: "class Math:\n    # @staticmethod\n    pass\n\nprint(Math.somme(7, 8))\n",
    solution: "class Math:\n    @staticmethod\n    def somme(a, b):\n        return a + b\n\nprint(Math.somme(7, 8))",
    tests: [
      { type: "contains", expected: "@staticmethod" },
      { type: "output", expected: "15" },
    ],
    category: "POO",
  },
  {
    id: "py_s8_e7",
    title: "Classmethod",
    description: "@classmethod.",
    instruction: "Définissez <code>class Date</code> avec une <code>@classmethod from_string(cls, s)</code> qui parse <code>'2026-05-21'</code> et retourne une instance avec attribut <code>year</code>. Affichez <code>Date.from_string('2026-05-21').year</code>.",
    code_template: "class Date:\n    def __init__(self, year):\n        self.year = year\n    # @classmethod from_string\n    \nprint(Date.from_string('2026-05-21').year)\n",
    solution: "class Date:\n    def __init__(self, year):\n        self.year = year\n    @classmethod\n    def from_string(cls, s):\n        return cls(int(s.split('-')[0]))\nprint(Date.from_string('2026-05-21').year)",
    tests: [
      { type: "contains", expected: "@classmethod" },
      { type: "output", expected: "2026" },
    ],
    category: "POO",
  },
  {
    id: "py_s8_e8",
    title: "@property",
    description: "Getter sans parenthèses.",
    instruction: "Définissez <code>class Cercle(rayon)</code> avec une <code>@property aire</code> qui retourne π·r². Affichez <code>Cercle(5).aire</code> arrondi à 2 décimales.",
    code_template: "import math\nclass Cercle:\n    def __init__(self, r):\n        self.r = r\n    # @property\n\nprint(round(Cercle(5).aire, 2))\n",
    solution: "import math\nclass Cercle:\n    def __init__(self, r):\n        self.r = r\n    @property\n    def aire(self):\n        return math.pi * self.r ** 2\n\nprint(round(Cercle(5).aire, 2))",
    tests: [
      { type: "contains", expected: "@property" },
      { type: "output", expected: "78.54" },
    ],
    category: "POO",
  },
  {
    id: "py_s8_e9",
    title: "Property avec setter",
    description: "Validation à l'écriture.",
    instruction: "Définissez <code>class Temperature</code> avec une property <code>celsius</code> qui valide >= -273 dans le setter (sinon ValueError). Testez avec try/except : assignez -300, affichez 'invalide' dans le except.",
    code_template: "class Temperature:\n    def __init__(self):\n        self._c = 0\n    # property + setter\n\ntry:\n    t = Temperature()\n    t.celsius = -300\nexcept ValueError:\n    print('invalide')\n",
    solution: "class Temperature:\n    def __init__(self):\n        self._c = 0\n    @property\n    def celsius(self):\n        return self._c\n    @celsius.setter\n    def celsius(self, v):\n        if v < -273:\n            raise ValueError\n        self._c = v\n\ntry:\n    t = Temperature()\n    t.celsius = -300\nexcept ValueError:\n    print('invalide')",
    tests: [{ type: "output", expected: "invalide" }],
    category: "POO",
  },
  {
    id: "py_s8_e10",
    title: "Variable de classe",
    description: "Attribut partagé par toutes les instances.",
    instruction: "Définissez <code>class Compteur</code> avec un <code>total</code> de classe (départ 0), incrémenté à chaque __init__. Créez 3 instances et affichez <code>Compteur.total</code>.",
    code_template: "class Compteur:\n    total = 0\n    def __init__(self):\n        # \n        pass\n\nfor _ in range(3):\n    Compteur()\nprint(Compteur.total)\n",
    solution: "class Compteur:\n    total = 0\n    def __init__(self):\n        Compteur.total += 1\n\nfor _ in range(3):\n    Compteur()\nprint(Compteur.total)",
    tests: [{ type: "output", expected: "3" }],
    category: "POO",
  },
  {
    id: "py_s8_e11",
    title: "Dataclass",
    description: "Boilerplate auto pour init/repr.",
    instruction: "Définissez <code>@dataclass class Point</code> avec x: int et y: int. Créez <code>Point(3, 4)</code> et affichez sa repr (devrait être <code>Point(x=3, y=4)</code>).",
    code_template: "from dataclasses import dataclass\n# @dataclass\nprint(Point(3, 4))\n",
    solution: "from dataclasses import dataclass\n@dataclass\nclass Point:\n    x: int\n    y: int\nprint(Point(3, 4))",
    tests: [
      { type: "contains", expected: "@dataclass" },
      { type: "output", expected: "Point(x=3, y=4)" },
    ],
    category: "Dataclass",
  },
  {
    id: "py_s8_e12",
    title: "Dataclass avec valeur par défaut",
    description: "Champ optionnel.",
    instruction: "Définissez un dataclass <code>Tache</code> avec <code>nom: str</code> et <code>done: bool = False</code>. Créez <code>Tache('coder')</code> et affichez sa repr.",
    code_template: "from dataclasses import dataclass\n# \n",
    solution: "from dataclasses import dataclass\n@dataclass\nclass Tache:\n    nom: str\n    done: bool = False\nprint(Tache('coder'))",
    tests: [{ type: "output", expected: "Tache(nom='coder', done=False)" }],
    category: "Dataclass",
  },
  {
    id: "py_s8_e13",
    title: "Méthode magique __eq__",
    description: "Égalité personnalisée.",
    instruction: "Définissez <code>class Point</code> avec x, y et <code>__eq__</code> qui compare x et y. Affichez <code>Point(1,2) == Point(1,2)</code>.",
    code_template: "class Point:\n    def __init__(self, x, y):\n        self.x, self.y = x, y\n    # __eq__\n\nprint(Point(1,2) == Point(1,2))\n",
    solution: "class Point:\n    def __init__(self, x, y):\n        self.x, self.y = x, y\n    def __eq__(self, o):\n        return self.x == o.x and self.y == o.y\n\nprint(Point(1,2) == Point(1,2))",
    tests: [{ type: "output", expected: "True" }],
    category: "Méthodes magiques",
  },
  {
    id: "py_s8_e14",
    title: "__len__",
    description: "len() sur un objet custom.",
    instruction: "Définissez <code>class Pile</code> qui contient un attribut <code>items</code> (liste). Implémentez <code>__len__</code>. Créez une pile avec [1,2,3,4,5] et affichez <code>len(pile)</code>.",
    code_template: "class Pile:\n    def __init__(self, items):\n        self.items = items\n    # __len__\n\nprint(len(Pile([1,2,3,4,5])))\n",
    solution: "class Pile:\n    def __init__(self, items):\n        self.items = items\n    def __len__(self):\n        return len(self.items)\n\nprint(len(Pile([1,2,3,4,5])))",
    tests: [{ type: "output", expected: "5" }],
    category: "Méthodes magiques",
  },
  {
    id: "py_s8_e15",
    title: "__contains__",
    description: "in sur un objet custom.",
    instruction: "Pour <code>class Pile</code> (items: list), implémentez <code>__contains__</code>. Testez <code>3 in Pile([1,2,3])</code>. Affichez True.",
    code_template: "class Pile:\n    def __init__(self, items):\n        self.items = items\n    # __contains__\n\nprint(3 in Pile([1,2,3]))\n",
    solution: "class Pile:\n    def __init__(self, items):\n        self.items = items\n    def __contains__(self, v):\n        return v in self.items\n\nprint(3 in Pile([1,2,3]))",
    tests: [{ type: "output", expected: "True" }],
    category: "Méthodes magiques",
  },
  {
    id: "py_s8_e16",
    title: "__getitem__",
    description: "Indexer un objet custom.",
    instruction: "Pour <code>class Pile([1, 2, 3])</code>, implémentez <code>__getitem__(self, i)</code>. Affichez <code>pile[1]</code> (devrait afficher 2).",
    code_template: "class Pile:\n    def __init__(self, items):\n        self.items = items\n    # __getitem__\n\nprint(Pile([1, 2, 3])[1])\n",
    solution: "class Pile:\n    def __init__(self, items):\n        self.items = items\n    def __getitem__(self, i):\n        return self.items[i]\n\nprint(Pile([1, 2, 3])[1])",
    tests: [{ type: "output", expected: "2" }],
    category: "Méthodes magiques",
  },
  {
    id: "py_s8_e17",
    title: "Polymorphisme",
    description: "Méthode commune, comportements différents.",
    instruction: "<code>Animal</code> a une méthode <code>parler()</code> abstraite (return ''). <code>Chien</code> et <code>Chat</code> en héritent et override. Créez une liste <code>[Chien(), Chat()]</code> et affichez parler() pour chacun sur 2 lignes.",
    code_template: "# Animal, Chien, Chat\n",
    solution: "class Animal:\n    def parler(self):\n        return ''\nclass Chien(Animal):\n    def parler(self):\n        return 'wouf'\nclass Chat(Animal):\n    def parler(self):\n        return 'miaou'\n\nfor a in [Chien(), Chat()]:\n    print(a.parler())",
    tests: [{ type: "output", expected: "wouf\nmiaou" }],
    category: "Héritage",
  },
  {
    id: "py_s8_e18",
    title: "Méthode privée (convention _)",
    description: "Préfixe simple souligné.",
    instruction: "Définissez <code>class Compte</code> avec un solde privé <code>_solde</code>. Ajoutez <code>depot(n)</code> et <code>get_solde()</code>. Testez : 2 dépôts de 50, affichez solde.",
    code_template: "class Compte:\n    def __init__(self):\n        self._solde = 0\n    # depot, get_solde\n\nc = Compte()\nc.depot(50)\nc.depot(50)\nprint(c.get_solde())\n",
    solution: "class Compte:\n    def __init__(self):\n        self._solde = 0\n    def depot(self, n):\n        self._solde += n\n    def get_solde(self):\n        return self._solde\n\nc = Compte()\nc.depot(50)\nc.depot(50)\nprint(c.get_solde())",
    tests: [{ type: "output", expected: "100" }],
    category: "POO",
  },
  {
    id: "py_s8_e19",
    title: "Méthode privée (__ name mangling)",
    description: "Double underscore.",
    instruction: "Définissez <code>class Box</code> avec un attribut <code>__secret</code>. Démontrez le name mangling : depuis l'extérieur, on doit utiliser <code>_Box__secret</code>. Affichez la valeur via <code>b._Box__secret</code>.",
    code_template: "class Box:\n    def __init__(self):\n        self.__secret = 42\n\nb = Box()\n# accès via _Box__secret\nprint(b._Box__secret)\n",
    solution: "class Box:\n    def __init__(self):\n        self.__secret = 42\n\nb = Box()\nprint(b._Box__secret)",
    tests: [{ type: "output", expected: "42" }],
    category: "POO",
  },
  {
    id: "py_s8_e20",
    title: "Iterator class",
    description: "Custom iterable avec __iter__/__next__.",
    instruction: "Définissez <code>class Range3</code> qui itère sur 0, 1, 2 via <code>__iter__</code>/<code>__next__</code>. Itérez avec <code>for x in Range3():</code> et affichez chaque valeur.",
    code_template: "class Range3:\n    def __init__(self):\n        self.i = 0\n    def __iter__(self):\n        return self\n    def __next__(self):\n        # \n        pass\n\nfor x in Range3():\n    print(x)\n",
    solution: "class Range3:\n    def __init__(self):\n        self.i = 0\n    def __iter__(self):\n        return self\n    def __next__(self):\n        if self.i >= 3:\n            raise StopIteration\n        v = self.i\n        self.i += 1\n        return v\n\nfor x in Range3():\n    print(x)",
    tests: [{ type: "output", expected: "0\n1\n2" }],
    category: "Iterators",
  },
  {
    id: "py_s8_e21",
    title: "Generator function",
    description: "yield + lazy.",
    instruction: "Définissez <code>def pairs(n)</code> qui yield les pairs de 0 à n-1. Itérez <code>pairs(10)</code> et affichez chaque valeur joint par espace.",
    code_template: "def pairs(n):\n    # yield\n    pass\n\nprint(' '.join(str(x) for x in pairs(10)))\n",
    solution: "def pairs(n):\n    for i in range(n):\n        if i % 2 == 0:\n            yield i\n\nprint(' '.join(str(x) for x in pairs(10)))",
    tests: [
      { type: "contains", expected: "yield" },
      { type: "output", expected: "0 2 4 6 8" },
    ],
    category: "Generators",
  },
  {
    id: "py_s8_e22",
    title: "Context manager (with)",
    description: "__enter__ / __exit__.",
    instruction: "Définissez <code>class Timer</code> qui affiche <code>'start'</code> dans __enter__ et <code>'stop'</code> dans __exit__. Utilisez <code>with Timer() as t:</code> et affichez 'middle' dans le bloc. Output attendu : start, middle, stop.",
    code_template: "class Timer:\n    def __enter__(self):\n        # \n        pass\n    def __exit__(self, *a):\n        # \n        pass\n\nwith Timer() as t:\n    print('middle')\n",
    solution: "class Timer:\n    def __enter__(self):\n        print('start')\n        return self\n    def __exit__(self, *a):\n        print('stop')\n\nwith Timer() as t:\n    print('middle')",
    tests: [{ type: "output", expected: "start\nmiddle\nstop" }],
    category: "Context Manager",
  },
  {
    id: "py_s8_e23",
    title: "isinstance",
    description: "Test de type avec héritage.",
    instruction: "Avec <code>class A</code>, <code>class B(A)</code>, créez <code>b = B()</code>. Affichez <code>isinstance(b, A)</code> et <code>isinstance(b, B)</code> sur 2 lignes (True/True).",
    code_template: "class A: pass\nclass B(A): pass\nb = B()\n",
    solution: "class A: pass\nclass B(A): pass\nb = B()\nprint(isinstance(b, A))\nprint(isinstance(b, B))",
    tests: [{ type: "output", expected: "True\nTrue" }],
    category: "POO",
  },
  {
    id: "py_s8_e24",
    title: "Multiple inheritance",
    description: "Héritage multiple + MRO.",
    instruction: "Définissez <code>class A</code> avec méthode <code>greet()</code> retournant 'A', <code>class B</code> avec <code>greet()</code> retournant 'B', et <code>class C(A, B)</code> sans override. Affichez <code>C().greet()</code> (le MRO dit qu'A gagne).",
    code_template: "# A, B, C(A, B)\n",
    solution: "class A:\n    def greet(self):\n        return 'A'\nclass B:\n    def greet(self):\n        return 'B'\nclass C(A, B):\n    pass\nprint(C().greet())",
    tests: [{ type: "output", expected: "A" }],
    category: "Héritage",
  },
  {
    id: "py_s8_e25",
    title: "Classe abstraite (ABC)",
    description: "Forcer l'implémentation.",
    instruction: "Avec <code>abc.ABC</code> et <code>@abstractmethod</code>, définissez <code>class Forme(ABC)</code> avec méthode abstraite <code>aire</code>. Implémentez <code>class Carre(Forme)</code> avec côté c et <code>aire</code> = c². Affichez <code>Carre(5).aire()</code>.",
    code_template: "from abc import ABC, abstractmethod\n# Forme, Carre\n",
    solution: "from abc import ABC, abstractmethod\nclass Forme(ABC):\n    @abstractmethod\n    def aire(self):\n        pass\nclass Carre(Forme):\n    def __init__(self, c):\n        self.c = c\n    def aire(self):\n        return self.c ** 2\nprint(Carre(5).aire())",
    tests: [
      { type: "contains", expected: "abstractmethod" },
      { type: "output", expected: "25" },
    ],
    category: "Héritage",
  },
];

addExercises("python", exercises);
