import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/**
 * Python — Part 6 : listes, tuples, slicing, comprehensions, itérations.
 */
const exercises: Exercise[] = [
  {
    id: "py_s6_e1",
    title: "List comprehension basique",
    description: "Carrés des 5 premiers entiers.",
    instruction: "Avec une <strong>list comprehension</strong>, créez la liste des carrés de 1 à 5 puis affichez-la (devrait afficher <code>[1, 4, 9, 16, 25]</code>).",
    code_template: "# Votre list comprehension ici\n",
    solution: "print([x**2 for x in range(1, 6)])",
    tests: [
      { type: "regex", expected: "\\[.*for.*in.*\\]" },
      { type: "output", expected: "[1, 4, 9, 16, 25]" },
    ],
    category: "Listes",
    hint: "Syntaxe : [expression for variable in iterable]",
  },
  {
    id: "py_s6_e2",
    title: "Filtrer pairs",
    description: "List comprehension avec condition.",
    instruction: "À partir de <code>range(1, 11)</code>, gardez les nombres pairs avec une list comprehension et affichez la liste.",
    code_template: "print([])\n",
    solution: "print([x for x in range(1, 11) if x % 2 == 0])",
    tests: [{ type: "output", expected: "[2, 4, 6, 8, 10]" }],
    category: "Listes",
  },
  {
    id: "py_s6_e3",
    title: "Slicing arrière",
    description: "Inverser via slice [::-1].",
    instruction: "Inversez <code>[1, 2, 3, 4, 5]</code> avec un slice et affichez-le.",
    code_template: "t = [1, 2, 3, 4, 5]\nprint(t)\n",
    solution: "t = [1, 2, 3, 4, 5]\nprint(t[::-1])",
    tests: [
      { type: "contains", expected: "[::-1]" },
      { type: "output", expected: "[5, 4, 3, 2, 1]" },
    ],
    category: "Slicing",
  },
  {
    id: "py_s6_e4",
    title: "Slicing pas de 2",
    description: "Un élément sur deux.",
    instruction: "Affichez un élément sur deux de <code>[0, 1, 2, 3, 4, 5, 6, 7]</code> (résultat : <code>[0, 2, 4, 6]</code>).",
    code_template: "t = [0, 1, 2, 3, 4, 5, 6, 7]\n",
    solution: "t = [0, 1, 2, 3, 4, 5, 6, 7]\nprint(t[::2])",
    tests: [{ type: "output", expected: "[0, 2, 4, 6]" }],
    category: "Slicing",
  },
  {
    id: "py_s6_e5",
    title: "enumerate",
    description: "Itérer avec index.",
    instruction: "Pour <code>['a', 'b', 'c']</code>, affichez chaque paire <code>index:valeur</code> sur sa propre ligne (ex: <code>0:a</code>).",
    code_template: "t = ['a', 'b', 'c']\n",
    solution: "t = ['a', 'b', 'c']\nfor i, v in enumerate(t):\n    print(f'{i}:{v}')",
    tests: [
      { type: "contains", expected: "enumerate" },
      { type: "output", expected: "0:a\n1:b\n2:c" },
    ],
    category: "Itération",
  },
  {
    id: "py_s6_e6",
    title: "zip",
    description: "Coupler deux listes.",
    instruction: "Avec <code>['Alice', 'Bob']</code> et <code>[25, 30]</code>, affichez chaque paire <code>nom:age</code> sur une ligne.",
    code_template: "noms = ['Alice', 'Bob']\nages = [25, 30]\n",
    solution: "noms = ['Alice', 'Bob']\nages = [25, 30]\nfor n, a in zip(noms, ages):\n    print(f'{n}:{a}')",
    tests: [
      { type: "contains", expected: "zip(" },
      { type: "output", expected: "Alice:25\nBob:30" },
    ],
    category: "Itération",
  },
  {
    id: "py_s6_e7",
    title: "sorted basique",
    description: "Trier une liste sans la modifier.",
    instruction: "Triez <code>[3, 1, 4, 1, 5, 9, 2, 6]</code> via <code>sorted</code> et affichez le résultat.",
    code_template: "t = [3, 1, 4, 1, 5, 9, 2, 6]\n",
    solution: "t = [3, 1, 4, 1, 5, 9, 2, 6]\nprint(sorted(t))",
    tests: [
      { type: "contains", expected: "sorted" },
      { type: "output", expected: "[1, 1, 2, 3, 4, 5, 6, 9]" },
    ],
    category: "Tri",
  },
  {
    id: "py_s6_e8",
    title: "sorted reverse",
    description: "Ordre décroissant.",
    instruction: "Triez <code>[5, 2, 8, 1, 9, 3]</code> en ordre décroissant. Affichez le résultat.",
    code_template: "t = [5, 2, 8, 1, 9, 3]\n",
    solution: "t = [5, 2, 8, 1, 9, 3]\nprint(sorted(t, reverse=True))",
    tests: [
      { type: "regex", expected: "reverse\\s*=\\s*True" },
      { type: "output", expected: "[9, 8, 5, 3, 2, 1]" },
    ],
    category: "Tri",
  },
  {
    id: "py_s6_e9",
    title: "sorted avec key",
    description: "Trier par critère custom.",
    instruction: "Triez <code>['banane', 'kiwi', 'pomme']</code> par longueur de mot. Affichez le résultat.",
    code_template: "t = ['banane', 'kiwi', 'pomme']\n",
    solution: "t = ['banane', 'kiwi', 'pomme']\nprint(sorted(t, key=len))",
    tests: [
      { type: "regex", expected: "key\\s*=" },
      { type: "output", expected: "['kiwi', 'pomme', 'banane']" },
    ],
    category: "Tri",
  },
  {
    id: "py_s6_e10",
    title: "min / max",
    description: "Trouver les extrêmes.",
    instruction: "Pour <code>[7, 2, 9, 1, 5]</code>, affichez le min sur une ligne puis le max sur une autre.",
    code_template: "t = [7, 2, 9, 1, 5]\n",
    solution: "t = [7, 2, 9, 1, 5]\nprint(min(t))\nprint(max(t))",
    tests: [{ type: "output", expected: "1\n9" }],
    category: "Listes",
  },
  {
    id: "py_s6_e11",
    title: "sum + len = moyenne",
    description: "Calcul classique.",
    instruction: "Affichez la moyenne de <code>[10, 20, 30, 40, 50]</code> (résultat : 30.0).",
    code_template: "t = [10, 20, 30, 40, 50]\n",
    solution: "t = [10, 20, 30, 40, 50]\nprint(sum(t) / len(t))",
    tests: [{ type: "output", expected: "30.0" }],
    category: "Listes",
  },
  {
    id: "py_s6_e12",
    title: "any / all",
    description: "Test booléen sur un itérable.",
    instruction: "Pour <code>[2, 4, 6, 8]</code>, affichez si TOUS sont pairs (all) puis si au moins un est > 100 (any). Deux lignes (True/False).",
    code_template: "t = [2, 4, 6, 8]\n",
    solution: "t = [2, 4, 6, 8]\nprint(all(x % 2 == 0 for x in t))\nprint(any(x > 100 for x in t))",
    tests: [{ type: "output", expected: "True\nFalse" }],
    category: "Itération",
  },
  {
    id: "py_s6_e13",
    title: "Tuple unpacking",
    description: "Affecter plusieurs variables.",
    instruction: "Déballez <code>(10, 20, 30)</code> dans <code>a, b, c</code> et affichez <code>a + c</code>.",
    code_template: "t = (10, 20, 30)\n",
    solution: "t = (10, 20, 30)\na, b, c = t\nprint(a + c)",
    tests: [{ type: "output", expected: "40" }],
    category: "Tuples",
  },
  {
    id: "py_s6_e14",
    title: "Swap sans variable temporaire",
    description: "Le tuple-swap classique de Python.",
    instruction: "Échangez <code>a = 1, b = 2</code> en une ligne avec <code>a, b = b, a</code>. Affichez <code>a b</code>.",
    code_template: "a, b = 1, 2\n# swap\nprint(a, b)\n",
    solution: "a, b = 1, 2\na, b = b, a\nprint(a, b)",
    tests: [{ type: "output", expected: "2 1" }],
    category: "Tuples",
  },
  {
    id: "py_s6_e15",
    title: "Tuple immuable",
    description: "Tester l'erreur.",
    instruction: "Essayez de modifier <code>t = (1, 2, 3)</code> avec <code>t[0] = 99</code> dans un try/except TypeError. Affichez <code>erreur</code> dans le except.",
    code_template: "t = (1, 2, 3)\ntry:\n    pass\nexcept TypeError:\n    print('erreur')\n",
    solution: "t = (1, 2, 3)\ntry:\n    t[0] = 99\nexcept TypeError:\n    print('erreur')",
    tests: [{ type: "output", expected: "erreur" }],
    category: "Tuples",
  },
  {
    id: "py_s6_e16",
    title: "Liste imbriquée",
    description: "Aplatir une matrice.",
    instruction: "Aplatissez <code>[[1,2],[3,4],[5,6]]</code> en une liste plate avec une list comprehension. Affichez le résultat (devrait être <code>[1, 2, 3, 4, 5, 6]</code>).",
    code_template: "m = [[1,2],[3,4],[5,6]]\n",
    solution: "m = [[1,2],[3,4],[5,6]]\nprint([x for row in m for x in row])",
    tests: [{ type: "output", expected: "[1, 2, 3, 4, 5, 6]" }],
    category: "Listes",
  },
  {
    id: "py_s6_e17",
    title: "List comprehension if/else",
    description: "Ternaire dans une compréhension.",
    instruction: "À partir de <code>range(1, 6)</code>, créez <code>['pair'/'impair' selon x]</code>. Affichez la liste.",
    code_template: "# list comp avec if/else\n",
    solution: "print(['pair' if x % 2 == 0 else 'impair' for x in range(1, 6)])",
    tests: [{ type: "output", expected: "['impair', 'pair', 'impair', 'pair', 'impair']" }],
    category: "Listes",
  },
  {
    id: "py_s6_e18",
    title: "range avec pas",
    description: "Décompte arrière.",
    instruction: "Affichez les nombres de 10 à 1 (inclus) avec <code>range</code> et un pas négatif, joints par espace.",
    code_template: "# range\n",
    solution: "print(' '.join(str(x) for x in range(10, 0, -1)))",
    tests: [
      { type: "regex", expected: "range\\(\\s*10\\s*,\\s*0\\s*,\\s*-1\\s*\\)" },
      { type: "output", expected: "10 9 8 7 6 5 4 3 2 1" },
    ],
    category: "Itération",
  },
  {
    id: "py_s6_e19",
    title: "in operator",
    description: "Recherche d'appartenance.",
    instruction: "Pour <code>['python', 'js', 'rust']</code>, affichez 'oui' si 'rust' est dedans, sinon 'non'.",
    code_template: "langues = ['python', 'js', 'rust']\n",
    solution: "langues = ['python', 'js', 'rust']\nprint('oui' if 'rust' in langues else 'non')",
    tests: [{ type: "output", expected: "oui" }],
    category: "Listes",
  },
  {
    id: "py_s6_e20",
    title: "list.count",
    description: "Compter une valeur dans une liste.",
    instruction: "Combien de fois 3 apparaît dans <code>[1, 3, 2, 3, 3, 4, 3, 5]</code> ? Affichez le résultat.",
    code_template: "t = [1, 3, 2, 3, 3, 4, 3, 5]\n",
    solution: "t = [1, 3, 2, 3, 3, 4, 3, 5]\nprint(t.count(3))",
    tests: [{ type: "output", expected: "4" }],
    category: "Listes",
  },
  {
    id: "py_s6_e21",
    title: "list.index",
    description: "Trouver l'indice d'une valeur.",
    instruction: "Trouvez l'indice de la première occurrence de <code>'rust'</code> dans <code>['py', 'js', 'rust', 'go']</code>.",
    code_template: "t = ['py', 'js', 'rust', 'go']\n",
    solution: "t = ['py', 'js', 'rust', 'go']\nprint(t.index('rust'))",
    tests: [{ type: "output", expected: "2" }],
    category: "Listes",
  },
  {
    id: "py_s6_e22",
    title: "list.extend",
    description: "Ajouter plusieurs éléments.",
    instruction: "Démarrez avec <code>[1, 2]</code>, étendez avec <code>[3, 4, 5]</code>, et affichez la liste résultante.",
    code_template: "t = [1, 2]\n",
    solution: "t = [1, 2]\nt.extend([3, 4, 5])\nprint(t)",
    tests: [
      { type: "contains", expected: ".extend" },
      { type: "output", expected: "[1, 2, 3, 4, 5]" },
    ],
    category: "Listes",
  },
  {
    id: "py_s6_e23",
    title: "Set basique",
    description: "Set unique.",
    instruction: "À partir de <code>[1, 2, 2, 3, 3, 3, 4]</code>, créez un set, puis affichez sa taille.",
    code_template: "t = [1, 2, 2, 3, 3, 3, 4]\n",
    solution: "t = [1, 2, 2, 3, 3, 3, 4]\nprint(len(set(t)))",
    tests: [{ type: "output", expected: "4" }],
    category: "Sets",
  },
  {
    id: "py_s6_e24",
    title: "Set intersection",
    description: "Éléments communs.",
    instruction: "Pour <code>a = {1, 2, 3, 4}</code> et <code>b = {3, 4, 5, 6}</code>, affichez l'intersection triée par croissant via <code>sorted</code> (résultat : <code>[3, 4]</code>).",
    code_template: "a = {1, 2, 3, 4}\nb = {3, 4, 5, 6}\n",
    solution: "a = {1, 2, 3, 4}\nb = {3, 4, 5, 6}\nprint(sorted(a & b))",
    tests: [{ type: "output", expected: "[3, 4]" }],
    category: "Sets",
  },
  {
    id: "py_s6_e25",
    title: "List comprehension imbriquée — matrice identité",
    description: "Identité 3×3 en une expression.",
    instruction: "Générez la matrice identité 3×3 avec une list comprehension imbriquée. Affichez-la (devrait être <code>[[1, 0, 0], [0, 1, 0], [0, 0, 1]]</code>).",
    code_template: "# nested list comp\n",
    solution: "print([[1 if i == j else 0 for j in range(3)] for i in range(3)])",
    tests: [{ type: "output", expected: "[[1, 0, 0], [0, 1, 0], [0, 0, 1]]" }],
    category: "Listes",
  },
];

addExercises("python", exercises);
