import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/**
 * React — Part 7 : Context, useReducer, custom hooks, state management.
 */
const exercises: Exercise[] = [
  {
    id: "react_146",
    type: "code",
    category: "Context",
    title: "Context basique",
    description: "Créer + Provider.",
    instruction: "Créez <code>ThemeContext = createContext('light')</code>, enveloppez l'app avec <code>ThemeContext.Provider value='dark'</code>.",
    code_template: "import { createContext } from 'react';\n\n// ThemeContext\n\nfunction App({ children }) {\n  return <div>{children}</div>;\n}",
    solution: "import { createContext } from 'react';\n\nconst ThemeContext = createContext('light');\n\nfunction App({ children }) {\n  return <ThemeContext.Provider value=\"dark\">{children}</ThemeContext.Provider>;\n}",
    tests: [
      { expected: "createContext", type: "contains" },
      { expected: "Provider value", type: "contains" },
    ],
  },
  {
    id: "react_147",
    type: "code",
    category: "Context",
    title: "useContext consommateur",
    description: "Lire un contexte.",
    instruction: "Dans un sous-composant, lisez ThemeContext avec <code>useContext</code> et affichez la valeur.",
    code_template: "import { useContext } from 'react';\nimport { ThemeContext } from './ThemeContext';\n\nfunction Display() {\n  // useContext\n  return <div></div>;\n}",
    solution: "import { useContext } from 'react';\nimport { ThemeContext } from './ThemeContext';\n\nfunction Display() {\n  const theme = useContext(ThemeContext);\n  return <div>Thème: {theme}</div>;\n}",
    tests: [
      { expected: "useContext(ThemeContext)", type: "contains" },
      { expected: "{theme}", type: "contains" },
    ],
  },
  {
    id: "react_148",
    type: "code",
    category: "Context",
    title: "Context avec objet d'état",
    description: "Provider qui partage state + setter.",
    instruction: "Créez un AuthContext qui contient <code>{user, setUser}</code>. Le Provider utilise useState pour gérer user.",
    code_template: "import { createContext, useState } from 'react';\n\n// AuthContext + AuthProvider\n\nexport function AuthProvider({ children }) {\n  return <div>{children}</div>;\n}",
    solution: "import { createContext, useState } from 'react';\n\nexport const AuthContext = createContext(null);\n\nexport function AuthProvider({ children }) {\n  const [user, setUser] = useState(null);\n  return <AuthContext.Provider value={{ user, setUser }}>{children}</AuthContext.Provider>;\n}",
    tests: [
      { expected: "createContext", type: "contains" },
      { expected: "value={{ user, setUser }}", type: "contains" },
    ],
  },
  {
    id: "react_149",
    type: "code",
    category: "Context",
    title: "Custom hook useAuth",
    description: "Wrapper autour de useContext.",
    instruction: "Écrivez <code>useAuth()</code> qui retourne le contexte AuthContext et lance une erreur si utilisé hors Provider.",
    code_template: "import { useContext } from 'react';\nimport { AuthContext } from './AuthContext';\n\nexport function useAuth() {\n  // \n}",
    solution: "import { useContext } from 'react';\nimport { AuthContext } from './AuthContext';\n\nexport function useAuth() {\n  const ctx = useContext(AuthContext);\n  if (!ctx) throw new Error('useAuth must be used within AuthProvider');\n  return ctx;\n}",
    tests: [
      { expected: "useContext(AuthContext)", type: "contains" },
      { expected: "throw new Error", type: "contains" },
    ],
  },
  {
    id: "react_150",
    type: "code",
    category: "Context",
    title: "Multi-Context",
    description: "Plusieurs providers imbriqués.",
    instruction: "Enveloppez l'app avec <code>ThemeProvider</code> à l'extérieur et <code>AuthProvider</code> à l'intérieur.",
    code_template: "function App({ children }) {\n  return (\n    <div>\n      {/* Theme + Auth providers */}\n      {children}\n    </div>\n  );\n}",
    solution: "function App({ children }) {\n  return (\n    <ThemeProvider>\n      <AuthProvider>\n        {children}\n      </AuthProvider>\n    </ThemeProvider>\n  );\n}",
    tests: [
      { expected: "ThemeProvider", type: "contains" },
      { expected: "AuthProvider", type: "contains" },
    ],
  },
  {
    id: "react_151",
    type: "code",
    category: "useReducer",
    title: "useReducer basique",
    description: "Alternative à useState pour logique complexe.",
    instruction: "Implémentez un compteur avec useReducer. Actions : 'inc', 'dec', 'reset'. État initial 0.",
    code_template: "import { useReducer } from 'react';\n\nfunction reducer(state, action) {\n  // switch\n}\n\nfunction Counter() {\n  // useReducer\n  return <div></div>;\n}",
    solution: "import { useReducer } from 'react';\n\nfunction reducer(state, action) {\n  switch (action.type) {\n    case 'inc': return state + 1;\n    case 'dec': return state - 1;\n    case 'reset': return 0;\n    default: return state;\n  }\n}\n\nfunction Counter() {\n  const [count, dispatch] = useReducer(reducer, 0);\n  return (\n    <div>\n      <p>{count}</p>\n      <button onClick={() => dispatch({ type: 'inc' })}>+</button>\n      <button onClick={() => dispatch({ type: 'dec' })}>-</button>\n      <button onClick={() => dispatch({ type: 'reset' })}>0</button>\n    </div>\n  );\n}",
    tests: [
      { expected: "useReducer", type: "contains" },
      { expected: "'inc'", type: "contains" },
      { expected: "'dec'", type: "contains" },
      { expected: "dispatch", type: "contains" },
    ],
  },
  {
    id: "react_152",
    type: "code",
    category: "useReducer",
    title: "useReducer avec payload",
    description: "Action avec données.",
    instruction: "Implémentez un reducer pour une todo-list : actions 'ADD' (avec payload text) et 'REMOVE' (avec payload id). État initial [].",
    code_template: "import { useReducer } from 'react';\n\nfunction reducer(state, action) {\n  // switch ADD / REMOVE\n}\n\nfunction Todos() {\n  // useReducer\n  return <ul></ul>;\n}",
    solution: "import { useReducer } from 'react';\n\nfunction reducer(state, action) {\n  switch (action.type) {\n    case 'ADD': return [...state, { id: Date.now(), text: action.payload }];\n    case 'REMOVE': return state.filter(t => t.id !== action.payload);\n    default: return state;\n  }\n}\n\nfunction Todos() {\n  const [todos, dispatch] = useReducer(reducer, []);\n  return (\n    <ul>\n      {todos.map(t => (\n        <li key={t.id} onClick={() => dispatch({ type: 'REMOVE', payload: t.id })}>{t.text}</li>\n      ))}\n    </ul>\n  );\n}",
    tests: [
      { expected: "'ADD'", type: "contains" },
      { expected: "'REMOVE'", type: "contains" },
      { expected: "action.payload", type: "contains" },
    ],
  },
  {
    id: "react_153",
    type: "code",
    category: "useReducer",
    title: "useReducer + dispatch dans Context",
    description: "Pattern Redux-like.",
    instruction: "Combinez useReducer + Context : exposez <code>{state, dispatch}</code> via un provider.",
    code_template: "import { createContext, useReducer } from 'react';\n\nfunction reducer(s, a) { return s; }\n\nexport const StoreContext = createContext(null);\n\nexport function StoreProvider({ children }) {\n  // \n  return <div></div>;\n}",
    solution: "import { createContext, useReducer } from 'react';\n\nfunction reducer(s, a) { return s; }\n\nexport const StoreContext = createContext(null);\n\nexport function StoreProvider({ children }) {\n  const [state, dispatch] = useReducer(reducer, {});\n  return <StoreContext.Provider value={{ state, dispatch }}>{children}</StoreContext.Provider>;\n}",
    tests: [
      { expected: "useReducer(reducer", type: "contains" },
      { expected: "{ state, dispatch }", type: "contains" },
    ],
  },
  {
    id: "react_154",
    type: "code",
    category: "useReducer",
    title: "useReducer init lazy",
    description: "Initialisation calculée.",
    instruction: "useReducer avec 3 arguments : reducer, initialArg, init function. La fonction init prend initialArg=10 et retourne <code>{count: initialArg * 2}</code>.",
    code_template: "import { useReducer } from 'react';\n\nfunction reducer(s, a) { return s; }\nfunction init(initialArg) {\n  // \n}\n\nfunction Counter() {\n  // useReducer avec init\n  return <div></div>;\n}",
    solution: "import { useReducer } from 'react';\n\nfunction reducer(s, a) { return s; }\nfunction init(initialArg) {\n  return { count: initialArg * 2 };\n}\n\nfunction Counter() {\n  const [state] = useReducer(reducer, 10, init);\n  return <div>{state.count}</div>;\n}",
    tests: [
      { expected: "useReducer(reducer, 10, init)", type: "contains" },
      { expected: "initialArg * 2", type: "contains" },
    ],
  },
  {
    id: "react_155",
    type: "code",
    category: "Custom Hooks",
    title: "useToggle",
    description: "Hook bool avec toggle.",
    instruction: "Écrivez <code>useToggle(initial = false)</code> qui retourne <code>[value, toggle]</code> où toggle inverse value.",
    code_template: "import { useState, useCallback } from 'react';\n\nexport function useToggle(initial = false) {\n  // \n}",
    solution: "import { useState, useCallback } from 'react';\n\nexport function useToggle(initial = false) {\n  const [value, setValue] = useState(initial);\n  const toggle = useCallback(() => setValue(v => !v), []);\n  return [value, toggle];\n}",
    tests: [
      { expected: "useToggle", type: "contains" },
      { expected: "!v", type: "contains" },
    ],
  },
  {
    id: "react_156",
    type: "code",
    category: "Custom Hooks",
    title: "useCounter",
    description: "Hook compteur avec inc/dec/reset.",
    instruction: "Écrivez <code>useCounter(initial = 0)</code> qui retourne <code>{count, inc, dec, reset}</code>.",
    code_template: "import { useState, useCallback } from 'react';\n\nexport function useCounter(initial = 0) {\n  // \n}",
    solution: "import { useState, useCallback } from 'react';\n\nexport function useCounter(initial = 0) {\n  const [count, setCount] = useState(initial);\n  const inc = useCallback(() => setCount(c => c + 1), []);\n  const dec = useCallback(() => setCount(c => c - 1), []);\n  const reset = useCallback(() => setCount(initial), [initial]);\n  return { count, inc, dec, reset };\n}",
    tests: [
      { expected: "useCounter", type: "contains" },
      { expected: "inc", type: "contains" },
      { expected: "dec", type: "contains" },
      { expected: "reset", type: "contains" },
    ],
  },
  {
    id: "react_157",
    type: "code",
    category: "Custom Hooks",
    title: "useArray",
    description: "Hook tableau avec helpers.",
    instruction: "Écrivez <code>useArray(initial = [])</code> qui retourne <code>{items, push, remove, clear}</code>.",
    code_template: "import { useState } from 'react';\n\nexport function useArray(initial = []) {\n  // \n}",
    solution: "import { useState } from 'react';\n\nexport function useArray(initial = []) {\n  const [items, setItems] = useState(initial);\n  const push = (v) => setItems(prev => [...prev, v]);\n  const remove = (i) => setItems(prev => prev.filter((_, idx) => idx !== i));\n  const clear = () => setItems([]);\n  return { items, push, remove, clear };\n}",
    tests: [
      { expected: "useArray", type: "contains" },
      { expected: "push", type: "contains" },
      { expected: "remove", type: "contains" },
      { expected: "clear", type: "contains" },
    ],
  },
  {
    id: "react_158",
    type: "code",
    category: "Custom Hooks",
    title: "useWindowSize",
    description: "Suivre la taille de la fenêtre.",
    instruction: "Écrivez <code>useWindowSize()</code> qui retourne <code>{width, height}</code> et écoute l'event resize avec cleanup.",
    code_template: "import { useEffect, useState } from 'react';\n\nexport function useWindowSize() {\n  // \n}",
    solution: "import { useEffect, useState } from 'react';\n\nexport function useWindowSize() {\n  const [size, setSize] = useState({ width: window.innerWidth, height: window.innerHeight });\n  useEffect(() => {\n    const handler = () => setSize({ width: window.innerWidth, height: window.innerHeight });\n    window.addEventListener('resize', handler);\n    return () => window.removeEventListener('resize', handler);\n  }, []);\n  return size;\n}",
    tests: [
      { expected: "useWindowSize", type: "contains" },
      { expected: "addEventListener('resize'", type: "contains" },
      { expected: "removeEventListener", type: "contains" },
    ],
  },
  {
    id: "react_159",
    type: "code",
    category: "Custom Hooks",
    title: "useMediaQuery",
    description: "Match d'une CSS media query.",
    instruction: "Écrivez <code>useMediaQuery(query)</code> qui retourne true/false selon que window.matchMedia(query).matches.",
    code_template: "import { useEffect, useState } from 'react';\n\nexport function useMediaQuery(query) {\n  // \n}",
    solution: "import { useEffect, useState } from 'react';\n\nexport function useMediaQuery(query) {\n  const [matches, setMatches] = useState(false);\n  useEffect(() => {\n    const mql = window.matchMedia(query);\n    const onChange = () => setMatches(mql.matches);\n    onChange();\n    mql.addEventListener('change', onChange);\n    return () => mql.removeEventListener('change', onChange);\n  }, [query]);\n  return matches;\n}",
    tests: [
      { expected: "useMediaQuery", type: "contains" },
      { expected: "matchMedia", type: "contains" },
    ],
  },
  {
    id: "react_160",
    type: "code",
    category: "Custom Hooks",
    title: "useClickOutside",
    description: "Détecter clic en dehors d'un élément.",
    instruction: "Écrivez <code>useClickOutside(ref, handler)</code> qui appelle handler quand on clique en dehors de ref.current.",
    code_template: "import { useEffect } from 'react';\n\nexport function useClickOutside(ref, handler) {\n  // \n}",
    solution: "import { useEffect } from 'react';\n\nexport function useClickOutside(ref, handler) {\n  useEffect(() => {\n    const onClick = (e) => {\n      if (ref.current && !ref.current.contains(e.target)) handler(e);\n    };\n    document.addEventListener('mousedown', onClick);\n    return () => document.removeEventListener('mousedown', onClick);\n  }, [ref, handler]);\n}",
    tests: [
      { expected: "useClickOutside", type: "contains" },
      { expected: ".contains(e.target)", type: "contains" },
    ],
  },
  {
    id: "react_161",
    type: "code",
    category: "Custom Hooks",
    title: "useInterval",
    description: "Wrapper sur setInterval.",
    instruction: "Écrivez <code>useInterval(callback, delay)</code> qui appelle callback toutes les delay ms. Nettoyez avec clearInterval.",
    code_template: "import { useEffect, useRef } from 'react';\n\nexport function useInterval(callback, delay) {\n  // \n}",
    solution: "import { useEffect, useRef } from 'react';\n\nexport function useInterval(callback, delay) {\n  const cbRef = useRef(callback);\n  useEffect(() => { cbRef.current = callback; }, [callback]);\n  useEffect(() => {\n    const id = setInterval(() => cbRef.current(), delay);\n    return () => clearInterval(id);\n  }, [delay]);\n}",
    tests: [
      { expected: "useInterval", type: "contains" },
      { expected: "setInterval", type: "contains" },
      { expected: "clearInterval", type: "contains" },
    ],
  },
  {
    id: "react_162",
    type: "code",
    category: "Custom Hooks",
    title: "useScroll",
    description: "Position de scroll.",
    instruction: "Écrivez <code>useScroll()</code> qui retourne <code>{x, y}</code> (position scroll) avec listener.",
    code_template: "import { useEffect, useState } from 'react';\n\nexport function useScroll() {\n  // \n}",
    solution: "import { useEffect, useState } from 'react';\n\nexport function useScroll() {\n  const [pos, setPos] = useState({ x: 0, y: 0 });\n  useEffect(() => {\n    const handler = () => setPos({ x: window.scrollX, y: window.scrollY });\n    window.addEventListener('scroll', handler);\n    return () => window.removeEventListener('scroll', handler);\n  }, []);\n  return pos;\n}",
    tests: [
      { expected: "useScroll", type: "contains" },
      { expected: "'scroll'", type: "contains" },
    ],
  },
  {
    id: "react_163",
    type: "code",
    category: "Custom Hooks",
    title: "useHover",
    description: "Détecter survol.",
    instruction: "Écrivez <code>useHover()</code> qui retourne <code>[ref, isHovered]</code>. Le ref s'applique à un élément, et isHovered est true quand la souris est dessus.",
    code_template: "import { useEffect, useRef, useState } from 'react';\n\nexport function useHover() {\n  // \n}",
    solution: "import { useEffect, useRef, useState } from 'react';\n\nexport function useHover() {\n  const ref = useRef(null);\n  const [hovered, setHovered] = useState(false);\n  useEffect(() => {\n    const el = ref.current;\n    if (!el) return;\n    const on = () => setHovered(true);\n    const off = () => setHovered(false);\n    el.addEventListener('mouseenter', on);\n    el.addEventListener('mouseleave', off);\n    return () => {\n      el.removeEventListener('mouseenter', on);\n      el.removeEventListener('mouseleave', off);\n    };\n  }, []);\n  return [ref, hovered];\n}",
    tests: [
      { expected: "useHover", type: "contains" },
      { expected: "mouseenter", type: "contains" },
      { expected: "mouseleave", type: "contains" },
    ],
  },
  {
    id: "react_164",
    type: "code",
    category: "Custom Hooks",
    title: "useKeyPress",
    description: "Détecter une touche.",
    instruction: "Écrivez <code>useKeyPress(targetKey)</code> qui retourne true quand la touche est enfoncée.",
    code_template: "import { useEffect, useState } from 'react';\n\nexport function useKeyPress(targetKey) {\n  // \n}",
    solution: "import { useEffect, useState } from 'react';\n\nexport function useKeyPress(targetKey) {\n  const [pressed, setPressed] = useState(false);\n  useEffect(() => {\n    const down = (e) => { if (e.key === targetKey) setPressed(true); };\n    const up = (e) => { if (e.key === targetKey) setPressed(false); };\n    window.addEventListener('keydown', down);\n    window.addEventListener('keyup', up);\n    return () => {\n      window.removeEventListener('keydown', down);\n      window.removeEventListener('keyup', up);\n    };\n  }, [targetKey]);\n  return pressed;\n}",
    tests: [
      { expected: "useKeyPress", type: "contains" },
      { expected: "'keydown'", type: "contains" },
      { expected: "'keyup'", type: "contains" },
    ],
  },
  {
    id: "react_165",
    type: "code",
    category: "Custom Hooks",
    title: "useOnline",
    description: "Statut online/offline.",
    instruction: "Écrivez <code>useOnline()</code> qui retourne true/false selon navigator.onLine et écoute online/offline events.",
    code_template: "import { useEffect, useState } from 'react';\n\nexport function useOnline() {\n  // \n}",
    solution: "import { useEffect, useState } from 'react';\n\nexport function useOnline() {\n  const [online, setOnline] = useState(navigator.onLine);\n  useEffect(() => {\n    const on = () => setOnline(true);\n    const off = () => setOnline(false);\n    window.addEventListener('online', on);\n    window.addEventListener('offline', off);\n    return () => {\n      window.removeEventListener('online', on);\n      window.removeEventListener('offline', off);\n    };\n  }, []);\n  return online;\n}",
    tests: [
      { expected: "useOnline", type: "contains" },
      { expected: "navigator.onLine", type: "contains" },
    ],
  },
  {
    id: "react_166",
    type: "code",
    category: "Custom Hooks",
    title: "useTitle",
    description: "Set document.title.",
    instruction: "Écrivez <code>useTitle(title)</code> qui met à jour document.title.",
    code_template: "import { useEffect } from 'react';\n\nexport function useTitle(title) {\n  // \n}",
    solution: "import { useEffect } from 'react';\n\nexport function useTitle(title) {\n  useEffect(() => {\n    document.title = title;\n  }, [title]);\n}",
    tests: [
      { expected: "useTitle", type: "contains" },
      { expected: "document.title", type: "contains" },
    ],
  },
  {
    id: "react_167",
    type: "code",
    category: "Custom Hooks",
    title: "useCopyToClipboard",
    description: "Copier dans le presse-papiers.",
    instruction: "Écrivez <code>useCopyToClipboard()</code> qui retourne <code>[copied, copy]</code>. copy(text) utilise navigator.clipboard.writeText.",
    code_template: "import { useState } from 'react';\n\nexport function useCopyToClipboard() {\n  // \n}",
    solution: "import { useState } from 'react';\n\nexport function useCopyToClipboard() {\n  const [copied, setCopied] = useState(false);\n  const copy = async (text) => {\n    await navigator.clipboard.writeText(text);\n    setCopied(true);\n  };\n  return [copied, copy];\n}",
    tests: [
      { expected: "useCopyToClipboard", type: "contains" },
      { expected: "navigator.clipboard.writeText", type: "contains" },
    ],
  },
  {
    id: "react_168",
    type: "code",
    category: "Custom Hooks",
    title: "useDocumentVisibility",
    description: "Détecter visibilité de l'onglet.",
    instruction: "Écrivez <code>useDocumentVisibility()</code> qui retourne document.visibilityState ('visible' ou 'hidden'), avec listener.",
    code_template: "import { useEffect, useState } from 'react';\n\nexport function useDocumentVisibility() {\n  // \n}",
    solution: "import { useEffect, useState } from 'react';\n\nexport function useDocumentVisibility() {\n  const [vis, setVis] = useState(document.visibilityState);\n  useEffect(() => {\n    const handler = () => setVis(document.visibilityState);\n    document.addEventListener('visibilitychange', handler);\n    return () => document.removeEventListener('visibilitychange', handler);\n  }, []);\n  return vis;\n}",
    tests: [
      { expected: "useDocumentVisibility", type: "contains" },
      { expected: "visibilitychange", type: "contains" },
    ],
  },
  {
    id: "react_169",
    type: "code",
    category: "useReducer",
    title: "useReducer pour form",
    description: "Gérer plusieurs champs.",
    instruction: "Reducer avec actions 'set' (payload {field, value}) et 'reset'. État initial {nom: '', email: ''}.",
    code_template: "import { useReducer } from 'react';\n\nconst initial = { nom: '', email: '' };\n\nfunction reducer(state, action) {\n  // switch\n}\n\nfunction Form() {\n  // useReducer\n  return <form></form>;\n}",
    solution: "import { useReducer } from 'react';\n\nconst initial = { nom: '', email: '' };\n\nfunction reducer(state, action) {\n  switch (action.type) {\n    case 'set': return { ...state, [action.payload.field]: action.payload.value };\n    case 'reset': return initial;\n    default: return state;\n  }\n}\n\nfunction Form() {\n  const [state, dispatch] = useReducer(reducer, initial);\n  return (\n    <form>\n      <input value={state.nom} onChange={e => dispatch({ type: 'set', payload: { field: 'nom', value: e.target.value } })} />\n      <input value={state.email} onChange={e => dispatch({ type: 'set', payload: { field: 'email', value: e.target.value } })} />\n    </form>\n  );\n}",
    tests: [
      { expected: "'set'", type: "contains" },
      { expected: "'reset'", type: "contains" },
      { expected: "action.payload", type: "contains" },
    ],
  },
  {
    id: "react_170",
    type: "code",
    category: "Context",
    title: "Optimiser Context",
    description: "Split state et dispatcher.",
    instruction: "Séparez <code>StateContext</code> et <code>DispatchContext</code> pour éviter les re-renders inutiles.",
    code_template: "import { createContext, useReducer } from 'react';\n\nfunction reducer(s, a) { return s; }\n\n// 2 Contexts\n\nexport function StoreProvider({ children }) {\n  // \n}",
    solution: "import { createContext, useReducer } from 'react';\n\nfunction reducer(s, a) { return s; }\n\nexport const StateContext = createContext(null);\nexport const DispatchContext = createContext(null);\n\nexport function StoreProvider({ children }) {\n  const [state, dispatch] = useReducer(reducer, {});\n  return (\n    <DispatchContext.Provider value={dispatch}>\n      <StateContext.Provider value={state}>\n        {children}\n      </StateContext.Provider>\n    </DispatchContext.Provider>\n  );\n}",
    tests: [
      { expected: "StateContext", type: "contains" },
      { expected: "DispatchContext", type: "contains" },
    ],
  },
];

addExercises("react", exercises);
