import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/**
 * React — Part 8 : performance, Suspense, React 19 features (useTransition, useOptimistic, use()).
 */
const exercises: Exercise[] = [
  {
    id: "react_171",
    type: "code",
    category: "Performance",
    title: "React.memo",
    description: "Éviter les re-renders inutiles.",
    instruction: "Wrap <code>Child</code> avec <code>React.memo</code> pour qu'il ne re-render que si ses props changent.",
    code_template: "import React from 'react';\n\nfunction Child({ value }) {\n  return <p>{value}</p>;\n}\n\n// memo\nexport default Child;",
    solution: "import React from 'react';\n\nfunction Child({ value }) {\n  return <p>{value}</p>;\n}\n\nexport default React.memo(Child);",
    tests: [
      { expected: "React.memo", type: "contains" },
    ],
  },
  {
    id: "react_172",
    type: "code",
    category: "Performance",
    title: "memo avec comparateur custom",
    description: "Contrôler la comparaison des props.",
    instruction: "Utilisez <code>React.memo(Component, (prev, next) => prev.id === next.id)</code> pour ne re-render que si l'id change.",
    code_template: "import React from 'react';\n\nfunction Card({ id, value }) {\n  return <p>{value}</p>;\n}\n\n// memo avec comparateur\n",
    solution: "import React from 'react';\n\nfunction Card({ id, value }) {\n  return <p>{value}</p>;\n}\n\nexport default React.memo(Card, (prev, next) => prev.id === next.id);",
    tests: [
      { expected: "React.memo(Card,", type: "contains" },
      { expected: "prev.id === next.id", type: "contains" },
    ],
  },
  {
    id: "react_173",
    type: "code",
    category: "Performance",
    title: "useMemo pour filtrage cher",
    description: "Recalculer seulement quand nécessaire.",
    instruction: "Filtrez <code>items</code> par <code>search</code> avec <code>useMemo</code> dépendant des deux.",
    code_template: "import { useMemo } from 'react';\n\nfunction Filtered({ items, search }) {\n  // useMemo\n  return <ul></ul>;\n}",
    solution: "import { useMemo } from 'react';\n\nfunction Filtered({ items, search }) {\n  const filtered = useMemo(() => items.filter(i => i.includes(search)), [items, search]);\n  return <ul>{filtered.map((i, idx) => <li key={idx}>{i}</li>)}</ul>;\n}",
    tests: [
      { expected: "useMemo", type: "contains" },
      { expected: "[items, search]", type: "contains" },
    ],
  },
  {
    id: "react_174",
    type: "code",
    category: "Performance",
    title: "useCallback pour child memoïsé",
    description: "Stabiliser la fonction passée en prop.",
    instruction: "<code>onClick</code> est stabilisé avec useCallback et passé à un Child memoïsé.",
    code_template: "import { useCallback } from 'react';\nimport Child from './Child';\n\nfunction Parent({ id }) {\n  // useCallback\n  return <Child onClick={null} />;\n}",
    solution: "import { useCallback } from 'react';\nimport Child from './Child';\n\nfunction Parent({ id }) {\n  const onClick = useCallback(() => console.log('clic', id), [id]);\n  return <Child onClick={onClick} />;\n}",
    tests: [
      { expected: "useCallback", type: "contains" },
      { expected: "[id]", type: "contains" },
    ],
  },
  {
    id: "react_175",
    type: "code",
    category: "Performance",
    title: "React.lazy",
    description: "Lazy loading d'un composant.",
    instruction: "Importez <code>HeavyComponent</code> de façon paresseuse avec <code>React.lazy</code> et enveloppez dans <code>Suspense</code> avec un fallback.",
    code_template: "import React, { Suspense } from 'react';\n\n// lazy\n\nfunction App() {\n  return <div></div>;\n}",
    solution: "import React, { Suspense } from 'react';\n\nconst HeavyComponent = React.lazy(() => import('./HeavyComponent'));\n\nfunction App() {\n  return (\n    <Suspense fallback={<p>Chargement...</p>}>\n      <HeavyComponent />\n    </Suspense>\n  );\n}",
    tests: [
      { expected: "React.lazy", type: "contains" },
      { expected: "Suspense", type: "contains" },
      { expected: "fallback=", type: "contains" },
    ],
  },
  {
    id: "react_176",
    type: "code",
    category: "Suspense",
    title: "Suspense pour data fetching",
    description: "React 19 — use() avec Suspense.",
    instruction: "Utilisez <code>use(promise)</code> de React 19 pour suspendre jusqu'à résolution. Enveloppez dans Suspense.",
    code_template: "import { Suspense, use } from 'react';\n\nfunction Display({ promise }) {\n  // use\n  return <p></p>;\n}\n\nfunction App() {\n  const p = fetch('/api').then(r => r.json());\n  return <div></div>;\n}",
    solution: "import { Suspense, use } from 'react';\n\nfunction Display({ promise }) {\n  const data = use(promise);\n  return <p>{data.name}</p>;\n}\n\nfunction App() {\n  const p = fetch('/api').then(r => r.json());\n  return (\n    <Suspense fallback={<p>...</p>}>\n      <Display promise={p} />\n    </Suspense>\n  );\n}",
    tests: [
      { expected: "use(promise)", type: "contains" },
      { expected: "Suspense", type: "contains" },
    ],
  },
  {
    id: "react_177",
    type: "code",
    category: "React 19",
    title: "useTransition",
    description: "Marquer une mise à jour comme non urgente.",
    instruction: "Utilisez <code>useTransition</code> : au clic, mettre à jour <code>filter</code> en transition pendant l'affichage de <code>isPending</code>.",
    code_template: "import { useState, useTransition } from 'react';\n\nfunction List({ items }) {\n  const [filter, setFilter] = useState('');\n  // useTransition\n  return <input />;\n}",
    solution: "import { useState, useTransition } from 'react';\n\nfunction List({ items }) {\n  const [filter, setFilter] = useState('');\n  const [isPending, startTransition] = useTransition();\n  const onChange = (e) => {\n    startTransition(() => setFilter(e.target.value));\n  };\n  return (\n    <div>\n      <input onChange={onChange} />\n      {isPending && <p>Calcul...</p>}\n    </div>\n  );\n}",
    tests: [
      { expected: "useTransition", type: "contains" },
      { expected: "startTransition", type: "contains" },
      { expected: "isPending", type: "contains" },
    ],
  },
  {
    id: "react_178",
    type: "code",
    category: "React 19",
    title: "useDeferredValue",
    description: "Différer une valeur pour rendu prioritaire.",
    instruction: "Utilisez <code>useDeferredValue</code> pour différer <code>search</code> et n'utiliser la version différée que pour le filtrage.",
    code_template: "import { useDeferredValue, useState } from 'react';\n\nfunction Search({ items }) {\n  const [search, setSearch] = useState('');\n  // useDeferredValue\n  return <input />;\n}",
    solution: "import { useDeferredValue, useState } from 'react';\n\nfunction Search({ items }) {\n  const [search, setSearch] = useState('');\n  const deferred = useDeferredValue(search);\n  const filtered = items.filter(i => i.includes(deferred));\n  return (\n    <div>\n      <input value={search} onChange={e => setSearch(e.target.value)} />\n      <ul>{filtered.map((i, idx) => <li key={idx}>{i}</li>)}</ul>\n    </div>\n  );\n}",
    tests: [
      { expected: "useDeferredValue", type: "contains" },
    ],
  },
  {
    id: "react_179",
    type: "code",
    category: "React 19",
    title: "useOptimistic",
    description: "Mise à jour optimiste pendant l'attente serveur.",
    instruction: "<code>const [optimistic, addOptimistic] = useOptimistic(state, (state, newItem) => [...state, newItem])</code>. Au submit, addOptimistic puis fetch.",
    code_template: "import { useOptimistic, useState } from 'react';\n\nfunction Todos({ initial }) {\n  const [todos, setTodos] = useState(initial);\n  // useOptimistic\n  return <ul></ul>;\n}",
    solution: "import { useOptimistic, useState } from 'react';\n\nfunction Todos({ initial }) {\n  const [todos, setTodos] = useState(initial);\n  const [optimistic, addOptimistic] = useOptimistic(todos, (state, newItem) => [...state, newItem]);\n  return <ul>{optimistic.map((t, i) => <li key={i}>{t}</li>)}</ul>;\n}",
    tests: [
      { expected: "useOptimistic", type: "contains" },
      { expected: "addOptimistic", type: "contains" },
    ],
  },
  {
    id: "react_180",
    type: "code",
    category: "React 19",
    title: "useFormStatus",
    description: "Statut d'un form en cours.",
    instruction: "Dans un bouton submit interne à un form, lisez <code>useFormStatus().pending</code> pour désactiver pendant l'envoi.",
    code_template: "import { useFormStatus } from 'react-dom';\n\nfunction SubmitButton() {\n  // useFormStatus\n  return <button>Envoyer</button>;\n}",
    solution: "import { useFormStatus } from 'react-dom';\n\nfunction SubmitButton() {\n  const { pending } = useFormStatus();\n  return <button disabled={pending}>{pending ? 'Envoi...' : 'Envoyer'}</button>;\n}",
    tests: [
      { expected: "useFormStatus", type: "contains" },
      { expected: "pending", type: "contains" },
    ],
  },
  {
    id: "react_181",
    type: "code",
    category: "React 19",
    title: "useActionState",
    description: "État retourné par une action serveur.",
    instruction: "Utilisez <code>useActionState(action, initialState)</code> pour gérer le retour d'une action.",
    code_template: "import { useActionState } from 'react';\n\nasync function submit(prev, formData) {\n  return { ok: true };\n}\n\nfunction Form() {\n  // useActionState\n  return <form></form>;\n}",
    solution: "import { useActionState } from 'react';\n\nasync function submit(prev, formData) {\n  return { ok: true };\n}\n\nfunction Form() {\n  const [state, formAction] = useActionState(submit, { ok: false });\n  return <form action={formAction}>{state.ok && <p>OK</p>}</form>;\n}",
    tests: [
      { expected: "useActionState", type: "contains" },
      { expected: "formAction", type: "contains" },
    ],
  },
  {
    id: "react_182",
    type: "code",
    category: "Error Boundaries",
    title: "Error Boundary classique",
    description: "Capturer les erreurs descendantes.",
    instruction: "Implémentez <code>class ErrorBoundary</code> avec <code>componentDidCatch</code> et <code>getDerivedStateFromError</code>. Affichez 'Erreur' au render si hasError.",
    code_template: "import React from 'react';\n\nexport class ErrorBoundary extends React.Component {\n  state = { hasError: false };\n  // getDerivedStateFromError, componentDidCatch\n  render() {\n    return this.props.children;\n  }\n}",
    solution: "import React from 'react';\n\nexport class ErrorBoundary extends React.Component {\n  state = { hasError: false };\n  static getDerivedStateFromError() {\n    return { hasError: true };\n  }\n  componentDidCatch(error, info) {\n    console.error(error, info);\n  }\n  render() {\n    if (this.state.hasError) return <p>Erreur</p>;\n    return this.props.children;\n  }\n}",
    tests: [
      { expected: "getDerivedStateFromError", type: "contains" },
      { expected: "componentDidCatch", type: "contains" },
    ],
  },
  {
    id: "react_183",
    type: "code",
    category: "Error Boundaries",
    title: "Reset error boundary",
    description: "Permettre une nouvelle tentative.",
    instruction: "Ajoutez un bouton 'Réessayer' qui appelle <code>setState({hasError: false})</code> dans ErrorBoundary.",
    code_template: "import React from 'react';\n\nexport class ErrorBoundary extends React.Component {\n  state = { hasError: false };\n  static getDerivedStateFromError() { return { hasError: true }; }\n  render() {\n    if (this.state.hasError) {\n      // bouton retry\n      return null;\n    }\n    return this.props.children;\n  }\n}",
    solution: "import React from 'react';\n\nexport class ErrorBoundary extends React.Component {\n  state = { hasError: false };\n  static getDerivedStateFromError() { return { hasError: true }; }\n  render() {\n    if (this.state.hasError) {\n      return (\n        <div>\n          <p>Erreur</p>\n          <button onClick={() => this.setState({ hasError: false })}>Réessayer</button>\n        </div>\n      );\n    }\n    return this.props.children;\n  }\n}",
    tests: [
      { expected: "setState({ hasError: false })", type: "contains" },
      { expected: "Réessayer", type: "contains" },
    ],
  },
  {
    id: "react_184",
    type: "code",
    category: "Portals",
    title: "createPortal",
    description: "Rendu dans un noeud DOM différent.",
    instruction: "Affichez un modal avec <code>createPortal</code> dans <code>document.body</code>.",
    code_template: "import { createPortal } from 'react-dom';\n\nfunction Modal({ children }) {\n  // createPortal\n}",
    solution: "import { createPortal } from 'react-dom';\n\nfunction Modal({ children }) {\n  return createPortal(\n    <div className=\"modal\">{children}</div>,\n    document.body\n  );\n}",
    tests: [
      { expected: "createPortal", type: "contains" },
      { expected: "document.body", type: "contains" },
    ],
  },
  {
    id: "react_185",
    type: "code",
    category: "Suspense",
    title: "Suspense avec boundaries imbriquées",
    description: "Différentes parties de l'UI ont leur propre fallback.",
    instruction: "Enveloppez <code>UserHeader</code> et <code>UserPosts</code> dans 2 Suspense séparés avec leur propre fallback.",
    code_template: "import { Suspense } from 'react';\n\nfunction Profile() {\n  return (\n    <div>\n      {/* 2 Suspense */}\n    </div>\n  );\n}",
    solution: "import { Suspense } from 'react';\n\nfunction Profile() {\n  return (\n    <div>\n      <Suspense fallback={<p>Header...</p>}>\n        <UserHeader />\n      </Suspense>\n      <Suspense fallback={<p>Posts...</p>}>\n        <UserPosts />\n      </Suspense>\n    </div>\n  );\n}",
    tests: [
      { expected: "<Suspense", type: "contains" },
      { expected: "UserHeader", type: "contains" },
      { expected: "UserPosts", type: "contains" },
    ],
  },
  {
    id: "react_186",
    type: "code",
    category: "Performance",
    title: "Virtualization concept",
    description: "Ne rendre que les éléments visibles.",
    instruction: "Affichez seulement les éléments entre <code>startIndex</code> et <code>endIndex</code> d'un tableau de 1000 items.",
    code_template: "function VirtualList({ items, startIndex, endIndex }) {\n  // slice\n  return <ul></ul>;\n}",
    solution: "function VirtualList({ items, startIndex, endIndex }) {\n  const visible = items.slice(startIndex, endIndex);\n  return (\n    <ul>\n      {visible.map((item, idx) => (\n        <li key={startIndex + idx}>{item}</li>\n      ))}\n    </ul>\n  );\n}",
    tests: [
      { expected: ".slice(startIndex, endIndex)", type: "contains" },
      { expected: "startIndex + idx", type: "contains" },
    ],
  },
  {
    id: "react_187",
    type: "code",
    category: "Performance",
    title: "Lazy initial state",
    description: "Calcul cher pour init useState.",
    instruction: "Initialisez useState avec une fonction au lieu d'une valeur, pour éviter le calcul à chaque render.",
    code_template: "import { useState } from 'react';\n\nfunction App() {\n  // useState lazy\n  return <div></div>;\n}",
    solution: "import { useState } from 'react';\n\nfunction App() {\n  const [items] = useState(() => {\n    const arr = [];\n    for (let i = 0; i < 1000; i++) arr.push(i);\n    return arr;\n  });\n  return <div>{items.length}</div>;\n}",
    tests: [
      { expected: "useState(() =>", type: "contains" },
    ],
  },
  {
    id: "react_188",
    type: "code",
    category: "Performance",
    title: "Split du Context",
    description: "Éviter les re-renders du tree entier.",
    instruction: "Au lieu d'un seul Context qui contient state+dispatch+config, divisez en 2 contextes séparés.",
    code_template: "import { createContext } from 'react';\n\n// 2 Contexts\n",
    solution: "import { createContext } from 'react';\n\nexport const StateContext = createContext(null);\nexport const DispatchContext = createContext(null);",
    tests: [
      { expected: "StateContext", type: "contains" },
      { expected: "DispatchContext", type: "contains" },
    ],
  },
  {
    id: "react_189",
    type: "code",
    category: "React 19",
    title: "Server Component (notion)",
    description: "Composant rendu côté serveur (App Router).",
    instruction: "Définissez une fonction async <code>UserList</code> qui fetch et retourne du JSX (Server Component Next.js / React 19).",
    code_template: "async function UserList() {\n  // fetch + return JSX\n}",
    solution: "async function UserList() {\n  const res = await fetch('/api/users');\n  const users = await res.json();\n  return (\n    <ul>\n      {users.map(u => <li key={u.id}>{u.name}</li>)}\n    </ul>\n  );\n}",
    tests: [
      { expected: "async function UserList", type: "contains" },
      { expected: "await fetch", type: "contains" },
    ],
  },
  {
    id: "react_190",
    type: "code",
    category: "React 19",
    title: "'use client' directive",
    description: "Marquer un Client Component dans App Router.",
    instruction: "Ajoutez la directive <code>'use client'</code> en haut d'un composant qui utilise useState.",
    code_template: "// directive ici\nimport { useState } from 'react';\n\nexport function Counter() {\n  const [n, setN] = useState(0);\n  return <button onClick={() => setN(n + 1)}>{n}</button>;\n}",
    solution: "'use client';\nimport { useState } from 'react';\n\nexport function Counter() {\n  const [n, setN] = useState(0);\n  return <button onClick={() => setN(n + 1)}>{n}</button>;\n}",
    tests: [
      { expected: "'use client'", type: "contains" },
    ],
  },
  {
    id: "react_191",
    type: "code",
    category: "React 19",
    title: "'use server'",
    description: "Server action dans un module dédié.",
    instruction: "Définissez une fonction <code>save(data)</code> avec la directive <code>'use server'</code> en haut de la fonction.",
    code_template: "// fonction save\n",
    solution: "export async function save(data) {\n  'use server';\n  console.log('saving', data);\n}",
    tests: [
      { expected: "'use server'", type: "contains" },
      { expected: "async function save", type: "contains" },
    ],
  },
  {
    id: "react_192",
    type: "code",
    category: "Performance",
    title: "Key stable",
    description: "Index comme key — anti-pattern.",
    instruction: "Pour une liste d'objets <code>{id, text}</code>, utilisez <code>item.id</code> comme key au lieu de l'index.",
    code_template: "function List({ items }) {\n  return (\n    <ul>\n      {items.map((item, idx) => (\n        <li key={null}>{item.text}</li>\n      ))}\n    </ul>\n  );\n}",
    solution: "function List({ items }) {\n  return (\n    <ul>\n      {items.map((item) => (\n        <li key={item.id}>{item.text}</li>\n      ))}\n    </ul>\n  );\n}",
    tests: [
      { expected: "key={item.id}", type: "contains" },
    ],
  },
  {
    id: "react_193",
    type: "code",
    category: "Performance",
    title: "Concurrent rendering check",
    description: "useTransition pour gros calcul.",
    instruction: "Quand on clique sur Tab2, utilisez <code>startTransition</code> pour mettre à jour <code>currentTab</code> en transition.",
    code_template: "import { useState, useTransition } from 'react';\n\nfunction Tabs() {\n  const [tab, setTab] = useState(1);\n  // useTransition\n  return <button>Tab 2</button>;\n}",
    solution: "import { useState, useTransition } from 'react';\n\nfunction Tabs() {\n  const [tab, setTab] = useState(1);\n  const [pending, startTransition] = useTransition();\n  return (\n    <button onClick={() => startTransition(() => setTab(2))}>\n      {pending ? '...' : 'Tab 2'}\n    </button>\n  );\n}",
    tests: [
      { expected: "useTransition", type: "contains" },
      { expected: "startTransition", type: "contains" },
    ],
  },
  {
    id: "react_194",
    type: "code",
    category: "React 19",
    title: "ref as prop",
    description: "React 19 : ref n'est plus une prop spéciale.",
    instruction: "Acceptez <code>ref</code> directement en prop de <code>Input</code> (sans forwardRef) avec React 19.",
    code_template: "function Input({ ref, ...props }) {\n  // \n}",
    solution: "function Input({ ref, ...props }) {\n  return <input ref={ref} {...props} />;\n}",
    tests: [
      { expected: "{ ref,", type: "contains" },
      { expected: "ref={ref}", type: "contains" },
    ],
  },
  {
    id: "react_195",
    type: "code",
    category: "Performance",
    title: "Profiler",
    description: "Mesurer les renders d'un sous-arbre.",
    instruction: "Enveloppez un sous-arbre avec <code>React.Profiler id=\"List\"</code> et un callback onRender qui log la durée.",
    code_template: "import { Profiler } from 'react';\n\nfunction onRender(id, phase, duration) {\n  // log\n}\n\nfunction App() {\n  // Profiler\n  return <div></div>;\n}",
    solution: "import { Profiler } from 'react';\n\nfunction onRender(id, phase, duration) {\n  console.log(id, phase, duration);\n}\n\nfunction App() {\n  return (\n    <Profiler id=\"List\" onRender={onRender}>\n      <ul></ul>\n    </Profiler>\n  );\n}",
    tests: [
      { expected: "Profiler", type: "contains" },
      { expected: "onRender", type: "contains" },
    ],
  },
];

addExercises("react", exercises);
