import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/**
 * React — Part 9 : patterns avancés (HOC, render props, compound components, controlled).
 */
const exercises: Exercise[] = [
  {
    id: "react_196",
    type: "code",
    category: "HOC",
    title: "Higher-Order Component",
    description: "Fonction qui retourne un composant.",
    instruction: "Écrivez <code>withLogger(Component)</code> qui retourne un composant loggant 'render' à chaque rendu.",
    code_template: "function withLogger(Component) {\n  // \n}",
    solution: "function withLogger(Component) {\n  return function Wrapped(props) {\n    console.log('render');\n    return <Component {...props} />;\n  };\n}",
    tests: [{ expected: "withLogger", type: "contains" }, { expected: "{...props}", type: "contains" }],
  },
  {
    id: "react_197",
    type: "code",
    category: "HOC",
    title: "HOC withAuth",
    description: "Garde d'authentification.",
    instruction: "Écrivez <code>withAuth(Component)</code> qui affiche 'Veuillez vous connecter' si <code>props.user</code> est null, sinon rend Component.",
    code_template: "function withAuth(Component) {\n  // \n}",
    solution: "function withAuth(Component) {\n  return function (props) {\n    if (!props.user) return <p>Veuillez vous connecter</p>;\n    return <Component {...props} />;\n  };\n}",
    tests: [{ expected: "withAuth", type: "contains" }, { expected: "!props.user", type: "contains" }],
  },
  {
    id: "react_198",
    type: "code",
    category: "Render Props",
    title: "Render props pattern",
    description: "Passer une fonction au lieu de children.",
    instruction: "Écrivez <code>MouseTracker</code> qui passe <code>{x, y}</code> à un <code>props.render</code>.",
    code_template: "import { useState } from 'react';\n\nfunction MouseTracker({ render }) {\n  const [pos, setPos] = useState({x: 0, y: 0});\n  return <div onMouseMove={null}>{render(pos)}</div>;\n}",
    solution: "import { useState } from 'react';\n\nfunction MouseTracker({ render }) {\n  const [pos, setPos] = useState({x: 0, y: 0});\n  return (\n    <div onMouseMove={e => setPos({x: e.clientX, y: e.clientY})}>\n      {render(pos)}\n    </div>\n  );\n}",
    tests: [{ expected: "render(pos)", type: "contains" }, { expected: "onMouseMove", type: "contains" }],
  },
  {
    id: "react_199",
    type: "code",
    category: "Compound",
    title: "Compound components — Tabs",
    description: "Composants qui partagent un context implicite.",
    instruction: "Créez <code>Tabs</code>, <code>TabList</code>, <code>Tab</code>, <code>TabPanels</code>, <code>TabPanel</code> partageant un Context interne (active index).",
    code_template: "import { createContext, useContext, useState } from 'react';\n\nconst TabsContext = createContext(null);\n\nfunction Tabs({ children }) {\n  // \n}",
    solution: "import { createContext, useContext, useState } from 'react';\n\nconst TabsContext = createContext(null);\n\nfunction Tabs({ children }) {\n  const [active, setActive] = useState(0);\n  return <TabsContext.Provider value={{active, setActive}}>{children}</TabsContext.Provider>;\n}\nfunction Tab({ index, children }) {\n  const { active, setActive } = useContext(TabsContext);\n  return <button onClick={() => setActive(index)}>{children}</button>;\n}",
    tests: [{ expected: "TabsContext", type: "contains" }, { expected: "setActive", type: "contains" }],
  },
  {
    id: "react_200",
    type: "code",
    category: "Controlled",
    title: "Input contrôlé",
    description: "Source de vérité dans React.",
    instruction: "Créez un input dont la valeur vient d'un useState et qui appelle onChange.",
    code_template: "import { useState } from 'react';\n\nfunction NameInput() {\n  // useState + input contrôlé\n  return <input />;\n}",
    solution: "import { useState } from 'react';\n\nfunction NameInput() {\n  const [name, setName] = useState('');\n  return <input value={name} onChange={e => setName(e.target.value)} />;\n}",
    tests: [{ expected: "value={name}", type: "contains" }, { expected: "onChange", type: "contains" }],
  },
  {
    id: "react_201",
    type: "code",
    category: "Controlled",
    title: "Checkbox contrôlée",
    description: "checked + onChange.",
    instruction: "Créez une checkbox contrôlée par <code>useState(false)</code>.",
    code_template: "import { useState } from 'react';\n\nfunction Check() {\n  // \n  return <input type=\"checkbox\" />;\n}",
    solution: "import { useState } from 'react';\n\nfunction Check() {\n  const [checked, setChecked] = useState(false);\n  return <input type=\"checkbox\" checked={checked} onChange={e => setChecked(e.target.checked)} />;\n}",
    tests: [{ expected: "checked={checked}", type: "contains" }, { expected: "e.target.checked", type: "contains" }],
  },
  {
    id: "react_202",
    type: "code",
    category: "Uncontrolled",
    title: "Input non contrôlé",
    description: "defaultValue + useRef.",
    instruction: "Créez un input non contrôlé avec <code>defaultValue=\"hello\"</code> et lisez sa valeur via ref au submit.",
    code_template: "import { useRef } from 'react';\n\nfunction Form() {\n  // useRef + defaultValue\n  return <form><input /></form>;\n}",
    solution: "import { useRef } from 'react';\n\nfunction Form() {\n  const ref = useRef(null);\n  const onSubmit = (e) => { e.preventDefault(); console.log(ref.current.value); };\n  return <form onSubmit={onSubmit}><input ref={ref} defaultValue=\"hello\" /></form>;\n}",
    tests: [{ expected: "defaultValue", type: "contains" }, { expected: "ref.current.value", type: "contains" }],
  },
  {
    id: "react_203",
    type: "code",
    category: "Forms",
    title: "Submit handler",
    description: "preventDefault.",
    instruction: "Empêchez la soumission par défaut du form et loggez 'submitted' au lieu.",
    code_template: "function Form() {\n  const onSubmit = (e) => {\n    // \n  };\n  return <form onSubmit={onSubmit}></form>;\n}",
    solution: "function Form() {\n  const onSubmit = (e) => {\n    e.preventDefault();\n    console.log('submitted');\n  };\n  return <form onSubmit={onSubmit}></form>;\n}",
    tests: [{ expected: "preventDefault", type: "contains" }, { expected: "'submitted'", type: "contains" }],
  },
  {
    id: "react_204",
    type: "code",
    category: "Forms",
    title: "Validation simple",
    description: "Vérifier avant soumission.",
    instruction: "Validez que <code>email</code> contient '@' avant submit, sinon afficher 'invalide' dans un state error.",
    code_template: "import { useState } from 'react';\n\nfunction Form() {\n  const [email, setEmail] = useState('');\n  const [error, setError] = useState('');\n  // submit + validation\n  return <form></form>;\n}",
    solution: "import { useState } from 'react';\n\nfunction Form() {\n  const [email, setEmail] = useState('');\n  const [error, setError] = useState('');\n  const submit = (e) => {\n    e.preventDefault();\n    if (!email.includes('@')) setError('invalide');\n    else setError('');\n  };\n  return (\n    <form onSubmit={submit}>\n      <input value={email} onChange={e => setEmail(e.target.value)} />\n      {error && <p>{error}</p>}\n    </form>\n  );\n}",
    tests: [{ expected: "includes('@')", type: "contains" }, { expected: "setError", type: "contains" }],
  },
  {
    id: "react_205",
    type: "code",
    category: "Children",
    title: "Children helper",
    description: "Itérer sur children avec React.Children.",
    instruction: "Comptez le nombre d'enfants avec <code>React.Children.count(children)</code>.",
    code_template: "import React from 'react';\n\nfunction Counter({ children }) {\n  // \n  return <div></div>;\n}",
    solution: "import React from 'react';\n\nfunction Counter({ children }) {\n  return <p>Enfants: {React.Children.count(children)}</p>;\n}",
    tests: [{ expected: "React.Children.count", type: "contains" }],
  },
  {
    id: "react_206",
    type: "code",
    category: "Children",
    title: "cloneElement",
    description: "Cloner avec props supplémentaires.",
    instruction: "Wrappez chaque child avec <code>React.cloneElement(child, {className: 'item'})</code>.",
    code_template: "import React from 'react';\n\nfunction List({ children }) {\n  // \n  return <div></div>;\n}",
    solution: "import React from 'react';\n\nfunction List({ children }) {\n  return (\n    <div>\n      {React.Children.map(children, child => React.cloneElement(child, { className: 'item' }))}\n    </div>\n  );\n}",
    tests: [{ expected: "cloneElement", type: "contains" }, { expected: "className: 'item'", type: "contains" }],
  },
  {
    id: "react_207",
    type: "code",
    category: "Refs",
    title: "useImperativeHandle",
    description: "Exposer méthodes via ref.",
    instruction: "Avec forwardRef + useImperativeHandle, exposez <code>{focus, blur}</code> sur un input.",
    code_template: "import { forwardRef, useImperativeHandle, useRef } from 'react';\n\nconst CustomInput = forwardRef((props, ref) => {\n  // \n});",
    solution: "import { forwardRef, useImperativeHandle, useRef } from 'react';\n\nconst CustomInput = forwardRef((props, ref) => {\n  const inputRef = useRef(null);\n  useImperativeHandle(ref, () => ({\n    focus: () => inputRef.current.focus(),\n    blur: () => inputRef.current.blur()\n  }));\n  return <input ref={inputRef} {...props} />;\n});",
    tests: [{ expected: "useImperativeHandle", type: "contains" }, { expected: "focus:", type: "contains" }],
  },
  {
    id: "react_208",
    type: "code",
    category: "Refs",
    title: "Callback ref",
    description: "Ref via fonction.",
    instruction: "Au lieu de useRef, passez une callback <code>ref={el => element = el}</code> qui stocke la référence DOM.",
    code_template: "function MyInput() {\n  let element = null;\n  return <input />;\n}",
    solution: "function MyInput() {\n  let element = null;\n  return <input ref={el => { element = el; }} />;\n}",
    tests: [{ expected: "ref={el =>", type: "contains" }],
  },
  {
    id: "react_209",
    type: "code",
    category: "Patterns",
    title: "Component injection",
    description: "Recevoir un composant en prop.",
    instruction: "<code>List</code> accepte une prop <code>Item</code> (composant). Il map les items et rend <code>Item</code> pour chacun.",
    code_template: "function List({ items, Item }) {\n  // \n  return <ul></ul>;\n}",
    solution: "function List({ items, Item }) {\n  return (\n    <ul>\n      {items.map((item, idx) => (\n        <Item key={idx} data={item} />\n      ))}\n    </ul>\n  );\n}",
    tests: [{ expected: "<Item", type: "contains" }, { expected: "data={item}", type: "contains" }],
  },
  {
    id: "react_210",
    type: "code",
    category: "Patterns",
    title: "Slot pattern",
    description: "Plusieurs zones via props nommées.",
    instruction: "Créez <code>Card</code> qui prend <code>header</code>, <code>body</code>, <code>footer</code> en props.",
    code_template: "function Card({ header, body, footer }) {\n  // \n  return <div></div>;\n}",
    solution: "function Card({ header, body, footer }) {\n  return (\n    <div className=\"card\">\n      <header>{header}</header>\n      <section>{body}</section>\n      <footer>{footer}</footer>\n    </div>\n  );\n}",
    tests: [{ expected: "{header}", type: "contains" }, { expected: "{body}", type: "contains" }, { expected: "{footer}", type: "contains" }],
  },
  {
    id: "react_211",
    type: "code",
    category: "Patterns",
    title: "State Reducer pattern",
    description: "Permettre au consommateur d'override le reducer.",
    instruction: "<code>useToggle</code> accepte en option un <code>reducer</code> custom qui peut modifier le comportement par défaut.",
    code_template: "import { useReducer } from 'react';\n\nfunction defaultReducer(state, action) {\n  return action.type === 'toggle' ? { on: !state.on } : state;\n}\n\nexport function useToggle({ reducer = defaultReducer } = {}) {\n  // \n}",
    solution: "import { useReducer } from 'react';\n\nfunction defaultReducer(state, action) {\n  return action.type === 'toggle' ? { on: !state.on } : state;\n}\n\nexport function useToggle({ reducer = defaultReducer } = {}) {\n  const [state, dispatch] = useReducer(reducer, { on: false });\n  const toggle = () => dispatch({ type: 'toggle' });\n  return [state.on, toggle];\n}",
    tests: [{ expected: "reducer = defaultReducer", type: "contains" }, { expected: "useReducer(reducer", type: "contains" }],
  },
  {
    id: "react_212",
    type: "code",
    category: "Routing",
    title: "Lien Next.js",
    description: "Navigation interne.",
    instruction: "Utilisez <code>Link</code> de next/link pour pointer vers <code>/about</code>.",
    code_template: "import Link from 'next/link';\n\nfunction Nav() {\n  // \n  return <nav></nav>;\n}",
    solution: "import Link from 'next/link';\n\nfunction Nav() {\n  return (\n    <nav>\n      <Link href=\"/about\">À propos</Link>\n    </nav>\n  );\n}",
    tests: [{ expected: "import Link from 'next/link'", type: "contains" }, { expected: "<Link href=\"/about\"", type: "contains" }],
  },
  {
    id: "react_213",
    type: "code",
    category: "Routing",
    title: "useRouter",
    description: "Lire la route courante.",
    instruction: "Avec <code>useRouter</code> de next/navigation, affichez le pathname actuel.",
    code_template: "'use client';\nimport { usePathname } from 'next/navigation';\n\nfunction Path() {\n  // \n}",
    solution: "'use client';\nimport { usePathname } from 'next/navigation';\n\nfunction Path() {\n  const path = usePathname();\n  return <p>Page: {path}</p>;\n}",
    tests: [{ expected: "usePathname", type: "contains" }],
  },
  {
    id: "react_214",
    type: "code",
    category: "Routing",
    title: "Navigation programmatique",
    description: "router.push().",
    instruction: "Au clic d'un bouton, naviguez vers <code>/dashboard</code> via <code>useRouter().push</code>.",
    code_template: "'use client';\nimport { useRouter } from 'next/navigation';\n\nfunction Btn() {\n  // \n  return <button>Go</button>;\n}",
    solution: "'use client';\nimport { useRouter } from 'next/navigation';\n\nfunction Btn() {\n  const router = useRouter();\n  return <button onClick={() => router.push('/dashboard')}>Go</button>;\n}",
    tests: [{ expected: "useRouter", type: "contains" }, { expected: "router.push('/dashboard')", type: "contains" }],
  },
  {
    id: "react_215",
    type: "code",
    category: "Patterns",
    title: "Composition over inheritance",
    description: "Pas de class extension entre composants.",
    instruction: "Au lieu d'étendre, composez : <code>SpecialButton</code> wrap <code>Button</code>.",
    code_template: "function Button({ children, ...props }) {\n  return <button {...props}>{children}</button>;\n}\nfunction SpecialButton(props) {\n  // \n}",
    solution: "function Button({ children, ...props }) {\n  return <button {...props}>{children}</button>;\n}\nfunction SpecialButton(props) {\n  return <Button {...props} className=\"special\" />;\n}",
    tests: [{ expected: "<Button {...props}", type: "contains" }, { expected: "className=\"special\"", type: "contains" }],
  },
  {
    id: "react_216",
    type: "code",
    category: "Patterns",
    title: "Provider pattern",
    description: "Encapsuler la logique d'un Context dans un Provider dédié.",
    instruction: "Créez <code>CountProvider</code> qui expose <code>count, inc</code> via Context.",
    code_template: "import { createContext, useState, useContext } from 'react';\n\nconst CountContext = createContext(null);\n\nexport function CountProvider({ children }) {\n  // \n}\nexport function useCount() {\n  return useContext(CountContext);\n}",
    solution: "import { createContext, useState, useContext } from 'react';\n\nconst CountContext = createContext(null);\n\nexport function CountProvider({ children }) {\n  const [count, setCount] = useState(0);\n  const inc = () => setCount(c => c + 1);\n  return <CountContext.Provider value={{count, inc}}>{children}</CountContext.Provider>;\n}\nexport function useCount() {\n  return useContext(CountContext);\n}",
    tests: [{ expected: "CountProvider", type: "contains" }, { expected: "{count, inc}", type: "contains" }],
  },
  {
    id: "react_217",
    type: "code",
    category: "Patterns",
    title: "Provider composer",
    description: "Combiner plusieurs Providers proprement.",
    instruction: "Composez 3 providers avec une fonction <code>compose</code> qui prend une liste de providers.",
    code_template: "function compose(providers, children) {\n  // reduceRight\n}",
    solution: "function compose(providers, children) {\n  return providers.reduceRight((acc, Provider) => <Provider>{acc}</Provider>, children);\n}",
    tests: [{ expected: "reduceRight", type: "contains" }, { expected: "<Provider>{acc}</Provider>", type: "contains" }],
  },
  {
    id: "react_218",
    type: "code",
    category: "Testing",
    title: "Test simple via assertion",
    description: "Vérifier un comportement avec une simple console.assert.",
    instruction: "Écrivez une fonction <code>add(a, b) = a + b</code> et 3 console.asserts pour la tester avec différentes valeurs.",
    code_template: "function add(a, b) {\n  return a + b;\n}\n\n// 3 console.assert\n",
    solution: "function add(a, b) {\n  return a + b;\n}\n\nconsole.assert(add(1, 2) === 3, 'add(1,2) === 3');\nconsole.assert(add(-1, 1) === 0, 'add(-1,1) === 0');\nconsole.assert(add(0, 0) === 0, 'add(0,0) === 0');",
    tests: [{ expected: "console.assert", type: "contains" }],
  },
  {
    id: "react_219",
    type: "code",
    category: "Patterns",
    title: "Render delegate",
    description: "Pattern UI/data séparée.",
    instruction: "<code>DataLoader</code> fetch les données et passe via <code>props.children</code> qui est une fonction <code>(data, loading) => JSX</code>.",
    code_template: "import { useEffect, useState } from 'react';\n\nfunction DataLoader({ url, children }) {\n  // useState + fetch + return children({data, loading})\n}",
    solution: "import { useEffect, useState } from 'react';\n\nfunction DataLoader({ url, children }) {\n  const [data, setData] = useState(null);\n  const [loading, setLoading] = useState(true);\n  useEffect(() => {\n    fetch(url).then(r => r.json()).then(d => { setData(d); setLoading(false); });\n  }, [url]);\n  return children(data, loading);\n}",
    tests: [{ expected: "children(data, loading)", type: "contains" }, { expected: "setLoading", type: "contains" }],
  },
  {
    id: "react_220",
    type: "code",
    category: "Final",
    title: "Mission React",
    description: "Combo final tous concepts.",
    instruction: "Créez <code>TodoApp</code> avec : useReducer pour état, custom hook useLocalStorage pour persistence, Context pour le thème, React.memo sur les items, useTransition pour le filter.",
    code_template: "import { useReducer, useState, createContext, useContext, useTransition, useMemo, useEffect } from 'react';\nimport React from 'react';\n\n// votre composition\n\nfunction TodoApp() {\n  return <div></div>;\n}",
    solution: "import { useReducer, useState, createContext, useContext, useTransition, useMemo, useEffect } from 'react';\nimport React from 'react';\n\nconst ThemeContext = createContext('light');\n\nfunction useLocalStorage(key, init) {\n  const [v, setV] = useState(() => {\n    try { return JSON.parse(localStorage.getItem(key)) ?? init; } catch { return init; }\n  });\n  useEffect(() => { localStorage.setItem(key, JSON.stringify(v)); }, [key, v]);\n  return [v, setV];\n}\n\nfunction reducer(state, action) {\n  switch (action.type) {\n    case 'add': return [...state, { id: Date.now(), text: action.payload }];\n    case 'remove': return state.filter(t => t.id !== action.payload);\n    default: return state;\n  }\n}\n\nconst Item = React.memo(function Item({ todo, onRemove }) {\n  return <li onClick={() => onRemove(todo.id)}>{todo.text}</li>;\n});\n\nfunction TodoApp() {\n  const [todos, dispatch] = useReducer(reducer, []);\n  const [filter, setFilter] = useState('');\n  const [pending, startTransition] = useTransition();\n  const filtered = useMemo(() => todos.filter(t => t.text.includes(filter)), [todos, filter]);\n  return (\n    <ThemeContext.Provider value=\"dark\">\n      <input onChange={e => startTransition(() => setFilter(e.target.value))} />\n      {pending && <p>...</p>}\n      <ul>{filtered.map(t => <Item key={t.id} todo={t} onRemove={(id) => dispatch({type:'remove', payload: id})} />)}</ul>\n    </ThemeContext.Provider>\n  );\n}",
    tests: [
      { expected: "useReducer", type: "contains" },
      { expected: "useTransition", type: "contains" },
      { expected: "React.memo", type: "contains" },
      { expected: "ThemeContext", type: "contains" },
    ],
    hint: "Tu viens de finir 220 exos React. Bravo Lyoko-warrior !",
  },
];

addExercises("react", exercises);
