import { addExercises } from "./registry";
import type { Exercise } from "./registry";

/**
 * React — Part 6 : hooks fondamentaux approfondis (useState, useEffect, useRef, useMemo, useCallback).
 */
const exercises: Exercise[] = [
  {
    id: "react_121",
    type: "code",
    category: "Hooks avancés",
    title: "useState avec objet",
    description: "Mettre à jour partiellement un état complexe.",
    instruction: "Créez <code>Form</code> avec un useState <code>{nom: '', email: ''}</code>. Implémentez <code>handleChange(field, value)</code> qui utilise le spread : <code>setForm(prev => ({...prev, [field]: value}))</code>. Affichez 2 inputs.",
    code_template: "import { useState } from 'react';\n\nfunction Form() {\n  const [form, setForm] = useState({nom: '', email: ''});\n  // handleChange\n  return (\n    <div>\n      <input value={form.nom} />\n      <input value={form.email} />\n    </div>\n  );\n}",
    solution: "import { useState } from 'react';\n\nfunction Form() {\n  const [form, setForm] = useState({nom: '', email: ''});\n  const handleChange = (field, value) => setForm(prev => ({...prev, [field]: value}));\n  return (\n    <div>\n      <input value={form.nom} onChange={e => handleChange('nom', e.target.value)} />\n      <input value={form.email} onChange={e => handleChange('email', e.target.value)} />\n    </div>\n  );\n}",
    tests: [
      { expected: "useState", type: "contains" },
      { expected: "...prev", type: "contains" },
      { expected: "[field]:", type: "contains" },
    ],
  },
  {
    id: "react_122",
    type: "code",
    category: "Hooks avancés",
    title: "useState lazy init",
    description: "Initialisation coûteuse uniquement au premier render.",
    instruction: "Utilisez <code>useState(() => expensiveCalc())</code> où expensiveCalc est appelée seulement au premier render. Définissez expensiveCalc comme une fonction qui retourne un objet avec compteur=0.",
    code_template: "import { useState } from 'react';\n\nfunction expensiveCalc() {\n  console.log('calcul cher');\n  return { compteur: 0 };\n}\n\nfunction App() {\n  // useState lazy\n  return <div></div>;\n}",
    solution: "import { useState } from 'react';\n\nfunction expensiveCalc() {\n  console.log('calcul cher');\n  return { compteur: 0 };\n}\n\nfunction App() {\n  const [state] = useState(() => expensiveCalc());\n  return <div>{state.compteur}</div>;\n}",
    tests: [
      { expected: "useState(() =>", type: "contains" },
      { expected: "expensiveCalc()", type: "contains" },
    ],
  },
  {
    id: "react_123",
    type: "code",
    category: "Hooks avancés",
    title: "useState fonctionnel",
    description: "Mise à jour basée sur la valeur précédente.",
    instruction: "Créez un compteur qui utilise <code>setCount(prev => prev + 1)</code> au clic du bouton. Affichez la valeur.",
    code_template: "import { useState } from 'react';\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n  // \n  return (\n    <div>\n      <p>{count}</p>\n      <button>+</button>\n    </div>\n  );\n}",
    solution: "import { useState } from 'react';\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n  return (\n    <div>\n      <p>{count}</p>\n      <button onClick={() => setCount(prev => prev + 1)}>+</button>\n    </div>\n  );\n}",
    tests: [
      { expected: "prev => prev + 1", type: "contains" },
      { expected: "onClick", type: "contains" },
    ],
  },
  {
    id: "react_124",
    type: "code",
    category: "Hooks avancés",
    title: "useEffect dépendances vides",
    description: "Exécution unique au mount.",
    instruction: "Dans un composant, utilisez useEffect avec une liste de dépendances <code>[]</code> pour afficher 'mounted' une seule fois en console.",
    code_template: "import { useEffect } from 'react';\n\nfunction App() {\n  // useEffect\n  return <div></div>;\n}",
    solution: "import { useEffect } from 'react';\n\nfunction App() {\n  useEffect(() => {\n    console.log('mounted');\n  }, []);\n  return <div></div>;\n}",
    tests: [
      { expected: "useEffect", type: "contains" },
      { expected: "[]", type: "contains" },
      { expected: "'mounted'", type: "contains" },
    ],
  },
  {
    id: "react_125",
    type: "code",
    category: "Hooks avancés",
    title: "useEffect cleanup",
    description: "Retourner une fonction de nettoyage.",
    instruction: "Dans useEffect, utilisez <code>setInterval</code> pour incrémenter un compteur toutes les secondes. Retournez une fonction qui appelle <code>clearInterval</code>.",
    code_template: "import { useEffect, useState } from 'react';\n\nfunction Timer() {\n  const [s, setS] = useState(0);\n  // useEffect avec cleanup\n  return <p>{s}</p>;\n}",
    solution: "import { useEffect, useState } from 'react';\n\nfunction Timer() {\n  const [s, setS] = useState(0);\n  useEffect(() => {\n    const id = setInterval(() => setS(prev => prev + 1), 1000);\n    return () => clearInterval(id);\n  }, []);\n  return <p>{s}</p>;\n}",
    tests: [
      { expected: "setInterval", type: "contains" },
      { expected: "clearInterval", type: "contains" },
      { expected: "return () =>", type: "contains" },
    ],
  },
  {
    id: "react_126",
    type: "code",
    category: "Hooks avancés",
    title: "useEffect avec dépendance",
    description: "Re-run sur changement.",
    instruction: "Créez un useEffect qui log 'changement' chaque fois que la prop <code>userId</code> change. Listez userId dans les dépendances.",
    code_template: "import { useEffect } from 'react';\n\nfunction Profile({ userId }) {\n  // useEffect avec [userId]\n  return <div></div>;\n}",
    solution: "import { useEffect } from 'react';\n\nfunction Profile({ userId }) {\n  useEffect(() => {\n    console.log('changement');\n  }, [userId]);\n  return <div></div>;\n}",
    tests: [
      { expected: "[userId]", type: "contains" },
      { expected: "'changement'", type: "contains" },
    ],
  },
  {
    id: "react_127",
    type: "code",
    category: "Hooks avancés",
    title: "useEffect async pattern",
    description: "Fetch dans useEffect — fonction interne async.",
    instruction: "Dans useEffect, définissez une fonction async interne <code>load()</code>, appelez-la, et nettoyez avec AbortController.",
    code_template: "import { useEffect, useState } from 'react';\n\nfunction Data() {\n  const [data, setData] = useState(null);\n  // useEffect avec fetch et AbortController\n  return <div></div>;\n}",
    solution: "import { useEffect, useState } from 'react';\n\nfunction Data() {\n  const [data, setData] = useState(null);\n  useEffect(() => {\n    const ctrl = new AbortController();\n    async function load() {\n      const res = await fetch('/api/data', { signal: ctrl.signal });\n      setData(await res.json());\n    }\n    load();\n    return () => ctrl.abort();\n  }, []);\n  return <div></div>;\n}",
    tests: [
      { expected: "AbortController", type: "contains" },
      { expected: "async function load", type: "contains" },
      { expected: "ctrl.abort", type: "contains" },
    ],
  },
  {
    id: "react_128",
    type: "code",
    category: "Hooks avancés",
    title: "useRef accès DOM",
    description: "Donner le focus à un input au mount.",
    instruction: "Créez un input et donnez-lui le focus au montage via useRef + useEffect.",
    code_template: "import { useEffect, useRef } from 'react';\n\nfunction FocusInput() {\n  // useRef + focus\n  return <input />;\n}",
    solution: "import { useEffect, useRef } from 'react';\n\nfunction FocusInput() {\n  const ref = useRef(null);\n  useEffect(() => {\n    ref.current.focus();\n  }, []);\n  return <input ref={ref} />;\n}",
    tests: [
      { expected: "useRef", type: "contains" },
      { expected: ".current.focus", type: "contains" },
      { expected: "ref={ref}", type: "contains" },
    ],
  },
  {
    id: "react_129",
    type: "code",
    category: "Hooks avancés",
    title: "useRef stocker une valeur mutable",
    description: "Compter les renders sans déclencher de re-render.",
    instruction: "Utilisez useRef pour stocker un compteur <code>renderCount</code> incrémenté à chaque render (sans setState).",
    code_template: "import { useRef } from 'react';\n\nfunction RenderCounter() {\n  // useRef compteur\n  return <p></p>;\n}",
    solution: "import { useRef } from 'react';\n\nfunction RenderCounter() {\n  const renderCount = useRef(0);\n  renderCount.current++;\n  return <p>Renders: {renderCount.current}</p>;\n}",
    tests: [
      { expected: "useRef(0)", type: "contains" },
      { expected: "renderCount.current", type: "contains" },
    ],
  },
  {
    id: "react_130",
    type: "code",
    category: "Hooks avancés",
    title: "useMemo calcul coûteux",
    description: "Mémoriser un résultat.",
    instruction: "Avec une prop <code>items</code> (tableau), calculez la somme avec <code>useMemo</code> en dépendance de <code>items</code>.",
    code_template: "import { useMemo } from 'react';\n\nfunction Total({ items }) {\n  // useMemo\n  return <p></p>;\n}",
    solution: "import { useMemo } from 'react';\n\nfunction Total({ items }) {\n  const sum = useMemo(() => items.reduce((s, v) => s + v, 0), [items]);\n  return <p>Total : {sum}</p>;\n}",
    tests: [
      { expected: "useMemo", type: "contains" },
      { expected: ".reduce", type: "contains" },
      { expected: "[items]", type: "contains" },
    ],
  },
  {
    id: "react_131",
    type: "code",
    category: "Hooks avancés",
    title: "useCallback",
    description: "Stabiliser une fonction.",
    instruction: "Définissez un <code>handleClick</code> avec useCallback dépendant de <code>id</code>. Au clic il affiche 'clic ' + id.",
    code_template: "import { useCallback } from 'react';\n\nfunction Button({ id }) {\n  // useCallback\n  return <button>Cliquer</button>;\n}",
    solution: "import { useCallback } from 'react';\n\nfunction Button({ id }) {\n  const handleClick = useCallback(() => {\n    console.log('clic ' + id);\n  }, [id]);\n  return <button onClick={handleClick}>Cliquer</button>;\n}",
    tests: [
      { expected: "useCallback", type: "contains" },
      { expected: "[id]", type: "contains" },
    ],
  },
  {
    id: "react_132",
    type: "code",
    category: "Hooks avancés",
    title: "useState booléen pour toggle",
    description: "Pattern classique.",
    instruction: "Créez un bouton qui toggle un état <code>open</code> (boolean). Affichez 'OPEN' ou 'CLOSED'.",
    code_template: "import { useState } from 'react';\n\nfunction Toggle() {\n  // useState\n  return <div></div>;\n}",
    solution: "import { useState } from 'react';\n\nfunction Toggle() {\n  const [open, setOpen] = useState(false);\n  return (\n    <div>\n      <button onClick={() => setOpen(prev => !prev)}>Toggle</button>\n      <p>{open ? 'OPEN' : 'CLOSED'}</p>\n    </div>\n  );\n}",
    tests: [
      { expected: "useState(false)", type: "contains" },
      { expected: "!prev", type: "contains" },
    ],
  },
  {
    id: "react_133",
    type: "code",
    category: "Hooks avancés",
    title: "useState tableau — push",
    description: "Ajouter via spread, jamais .push().",
    instruction: "Maintenez un état <code>items: []</code>. Le bouton 'Ajouter' append <code>{id: Date.now(), text: 'nouveau'}</code> sans muter.",
    code_template: "import { useState } from 'react';\n\nfunction List() {\n  const [items, setItems] = useState([]);\n  // bouton\n  return <ul></ul>;\n}",
    solution: "import { useState } from 'react';\n\nfunction List() {\n  const [items, setItems] = useState([]);\n  const add = () => setItems(prev => [...prev, { id: Date.now(), text: 'nouveau' }]);\n  return (\n    <div>\n      <button onClick={add}>Ajouter</button>\n      <ul>{items.map(i => <li key={i.id}>{i.text}</li>)}</ul>\n    </div>\n  );\n}",
    tests: [
      { expected: "[...prev,", type: "contains" },
      { expected: "Date.now()", type: "contains" },
      { expected: "key={i.id}", type: "contains" },
    ],
  },
  {
    id: "react_134",
    type: "code",
    category: "Hooks avancés",
    title: "useState tableau — remove",
    description: "Filtrer pour retirer.",
    instruction: "Avec un état <code>items: [{id:1,text:'a'},{id:2,text:'b'}]</code>, retirez un item par id via filter, sans muter l'original.",
    code_template: "import { useState } from 'react';\n\nfunction List() {\n  const [items, setItems] = useState([{id:1,text:'a'},{id:2,text:'b'}]);\n  // remove\n  return <ul></ul>;\n}",
    solution: "import { useState } from 'react';\n\nfunction List() {\n  const [items, setItems] = useState([{id:1,text:'a'},{id:2,text:'b'}]);\n  const remove = (id) => setItems(prev => prev.filter(i => i.id !== id));\n  return (\n    <ul>\n      {items.map(i => (\n        <li key={i.id}>{i.text} <button onClick={() => remove(i.id)}>×</button></li>\n      ))}\n    </ul>\n  );\n}",
    tests: [
      { expected: ".filter(i =>", type: "contains" },
      { expected: "i.id !== id", type: "contains" },
    ],
  },
  {
    id: "react_135",
    type: "code",
    category: "Hooks avancés",
    title: "useState tableau — update",
    description: "Modifier un élément.",
    instruction: "Avec une liste de todos <code>[{id:1,done:false}]</code>, écrivez <code>toggle(id)</code> qui inverse done via <code>map</code>.",
    code_template: "import { useState } from 'react';\n\nfunction Todos() {\n  const [todos, setTodos] = useState([{id:1,done:false,text:'a'}]);\n  // toggle\n  return <ul></ul>;\n}",
    solution: "import { useState } from 'react';\n\nfunction Todos() {\n  const [todos, setTodos] = useState([{id:1,done:false,text:'a'}]);\n  const toggle = (id) => setTodos(prev => prev.map(t => t.id === id ? {...t, done: !t.done} : t));\n  return (\n    <ul>\n      {todos.map(t => (\n        <li key={t.id} onClick={() => toggle(t.id)}>{t.text}{t.done ? ' ✓' : ''}</li>\n      ))}\n    </ul>\n  );\n}",
    tests: [
      { expected: ".map(t =>", type: "contains" },
      { expected: "{...t,", type: "contains" },
      { expected: "!t.done", type: "contains" },
    ],
  },
  {
    id: "react_136",
    type: "code",
    category: "Hooks avancés",
    title: "useEffect dépendances multiples",
    description: "Plusieurs valeurs dans le tableau.",
    instruction: "useEffect doit re-run quand <code>page</code> OU <code>query</code> change. Affichez les 2 dans le log.",
    code_template: "import { useEffect } from 'react';\n\nfunction Search({ page, query }) {\n  // useEffect [page, query]\n  return <div></div>;\n}",
    solution: "import { useEffect } from 'react';\n\nfunction Search({ page, query }) {\n  useEffect(() => {\n    console.log('search', page, query);\n  }, [page, query]);\n  return <div></div>;\n}",
    tests: [{ expected: "[page, query]", type: "contains" }],
  },
  {
    id: "react_137",
    type: "code",
    category: "Hooks avancés",
    title: "useEffect — pas de cleanup nécessaire",
    description: "Effet idempotent.",
    instruction: "Loggez <code>document.title</code> chaque fois que la prop <code>title</code> change, et settez <code>document.title = title</code>.",
    code_template: "import { useEffect } from 'react';\n\nfunction TitleSetter({ title }) {\n  // \n  return <div></div>;\n}",
    solution: "import { useEffect } from 'react';\n\nfunction TitleSetter({ title }) {\n  useEffect(() => {\n    document.title = title;\n  }, [title]);\n  return <div></div>;\n}",
    tests: [
      { expected: "document.title", type: "contains" },
      { expected: "[title]", type: "contains" },
    ],
  },
  {
    id: "react_138",
    type: "code",
    category: "Hooks avancés",
    title: "useState dérivé — éviter",
    description: "Calculer pendant le render, pas stocker.",
    instruction: "Avec une prop <code>items</code>, NE PAS stocker la longueur dans un useState. Affichez simplement <code>items.length</code>.",
    code_template: "function Counter({ items }) {\n  // pas de useState pour items.length\n  return <p></p>;\n}",
    solution: "function Counter({ items }) {\n  const count = items.length;\n  return <p>Total: {count}</p>;\n}",
    tests: [
      { expected: "items.length", type: "contains" },
      { expected: "{count}", type: "contains" },
    ],
  },
  {
    id: "react_139",
    type: "code",
    category: "Hooks avancés",
    title: "useMemo pour objet stable",
    description: "Référence stable d'un objet.",
    instruction: "Créez un objet <code>config = useMemo(() => ({ theme: 'dark' }), [])</code> stable entre renders. Passez-le à un sous-composant.",
    code_template: "import { useMemo } from 'react';\n\nfunction App() {\n  // useMemo config\n  return <div></div>;\n}",
    solution: "import { useMemo } from 'react';\n\nfunction App() {\n  const config = useMemo(() => ({ theme: 'dark' }), []);\n  return <div>{config.theme}</div>;\n}",
    tests: [
      { expected: "useMemo", type: "contains" },
      { expected: "theme:", type: "contains" },
    ],
  },
  {
    id: "react_140",
    type: "code",
    category: "Hooks avancés",
    title: "useState avec Map",
    description: "Stocker un Map dans useState.",
    instruction: "Utilisez useState avec une <code>new Map()</code> initiale. Ajoutez l'entrée ('a', 1) au clic, et affichez la taille.",
    code_template: "import { useState } from 'react';\n\nfunction MapState() {\n  // useState Map\n  return <div></div>;\n}",
    solution: "import { useState } from 'react';\n\nfunction MapState() {\n  const [m, setM] = useState(new Map());\n  const add = () => setM(prev => new Map(prev).set('a', 1));\n  return (\n    <div>\n      <button onClick={add}>+</button>\n      <p>Taille: {m.size}</p>\n    </div>\n  );\n}",
    tests: [
      { expected: "new Map()", type: "contains" },
      { expected: "m.size", type: "contains" },
    ],
  },
  {
    id: "react_141",
    type: "code",
    category: "Hooks avancés",
    title: "useState avec Set",
    description: "Set immuable.",
    instruction: "Avec useState(new Set()), ajoutez 'item' au clic. Affichez taille du Set.",
    code_template: "import { useState } from 'react';\n\nfunction SetState() {\n  // useState Set\n  return <div></div>;\n}",
    solution: "import { useState } from 'react';\n\nfunction SetState() {\n  const [s, setS] = useState(new Set());\n  const add = () => setS(prev => new Set(prev).add('item'));\n  return (\n    <div>\n      <button onClick={add}>+</button>\n      <p>Taille: {s.size}</p>\n    </div>\n  );\n}",
    tests: [
      { expected: "new Set", type: "contains" },
      { expected: "s.size", type: "contains" },
    ],
  },
  {
    id: "react_142",
    type: "code",
    category: "Hooks avancés",
    title: "useEffect ordre d'exécution",
    description: "Effects s'exécutent après render.",
    instruction: "Démontrez l'ordre : log 'render' dans le corps, log 'effect' dans useEffect avec [] de dépendance.",
    code_template: "import { useEffect } from 'react';\n\nfunction Order() {\n  console.log('render');\n  // useEffect 'effect'\n  return <div></div>;\n}",
    solution: "import { useEffect } from 'react';\n\nfunction Order() {\n  console.log('render');\n  useEffect(() => { console.log('effect'); }, []);\n  return <div></div>;\n}",
    tests: [
      { expected: "'render'", type: "contains" },
      { expected: "'effect'", type: "contains" },
    ],
  },
  {
    id: "react_143",
    type: "code",
    category: "Hooks avancés",
    title: "Plusieurs useState",
    description: "Diviser le state en variables indépendantes.",
    instruction: "Au lieu d'un seul objet d'état, utilisez 3 useState séparés : <code>nom</code>, <code>age</code>, <code>email</code>. Pas d'objet imbriqué.",
    code_template: "import { useState } from 'react';\n\nfunction Profile() {\n  // 3 useState\n  return <div></div>;\n}",
    solution: "import { useState } from 'react';\n\nfunction Profile() {\n  const [nom, setNom] = useState('');\n  const [age, setAge] = useState(0);\n  const [email, setEmail] = useState('');\n  return <div>{nom} {age} {email}</div>;\n}",
    tests: [
      { expected: "setNom", type: "contains" },
      { expected: "setAge", type: "contains" },
      { expected: "setEmail", type: "contains" },
    ],
  },
  {
    id: "react_144",
    type: "code",
    category: "Hooks avancés",
    title: "useRef pour valeur previous",
    description: "Pattern usePrevious.",
    instruction: "Implémentez le hook <code>usePrevious(value)</code> qui retourne la valeur du render précédent en utilisant useRef + useEffect.",
    code_template: "import { useEffect, useRef } from 'react';\n\nfunction usePrevious(value) {\n  // \n}",
    solution: "import { useEffect, useRef } from 'react';\n\nfunction usePrevious(value) {\n  const ref = useRef();\n  useEffect(() => { ref.current = value; });\n  return ref.current;\n}",
    tests: [
      { expected: "usePrevious", type: "contains" },
      { expected: "useRef", type: "contains" },
      { expected: "ref.current = value", type: "contains" },
    ],
  },
  {
    id: "react_145",
    type: "code",
    category: "Hooks avancés",
    title: "useEffect avec timer",
    description: "Debounce simple.",
    instruction: "Quand <code>search</code> change, attendez 300ms avant de logger 'search:' + search. Annulez avec clearTimeout dans le cleanup.",
    code_template: "import { useEffect } from 'react';\n\nfunction Search({ search }) {\n  // useEffect debounce\n  return <div></div>;\n}",
    solution: "import { useEffect } from 'react';\n\nfunction Search({ search }) {\n  useEffect(() => {\n    const id = setTimeout(() => console.log('search:', search), 300);\n    return () => clearTimeout(id);\n  }, [search]);\n  return <div></div>;\n}",
    tests: [
      { expected: "setTimeout", type: "contains" },
      { expected: "clearTimeout", type: "contains" },
      { expected: "[search]", type: "contains" },
    ],
  },
];

addExercises("react", exercises);
