import type { Metadata, Viewport } from "next";
import { Inter, Orbitron, Share_Tech_Mono } from "next/font/google";
import { Navbar } from "@/components/layout/navbar";
import { Footer } from "@/components/layout/footer";
import { AuthProvider } from "@/lib/auth-context";
import { VideoTransitionProvider } from "@/components/video-transition";
import { SoundProvider } from "@/lib/sound-manager";
import { ThemeProvider } from "next-themes";
import { SITE } from "@/lib/constants";
import "./globals.css";

/* ═══ FONTS ═══ */
const inter = Inter({
  subsets: ["latin", "latin-ext"],
  variable: "--font-inter",
  display: "swap",
});

const orbitron = Orbitron({
  subsets: ["latin"],
  variable: "--font-orbitron",
  display: "swap",
  weight: ["400", "500", "600", "700", "800", "900"],
});

const shareTechMono = Share_Tech_Mono({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-share-tech-mono",
  display: "swap",
});

/* ═══ SEO METADATA ═══ */
export const metadata: Metadata = {
  metadataBase: new URL(SITE.url),
  title: {
    default: SITE.title,
    template: `%s | ${SITE.name}`,
  },
  description: SITE.description,
  keywords: SITE.keywords,
  authors: [{ name: SITE.creator }],
  creator: SITE.creator,
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-video-preview": -1, "max-image-preview": "large", "max-snippet": -1 },
  },
  openGraph: {
    type: "website",
    locale: SITE.locale,
    url: SITE.url,
    siteName: SITE.name,
    title: SITE.title,
    description: SITE.description,
    // Auto-generated by opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: SITE.title,
    description: SITE.description,
    // Auto-generated by opengraph-image.tsx
  },
  alternates: { canonical: SITE.url },
  manifest: "/manifest.json",
  icons: {
    icon: "/images/favicon.png",
    apple: "/images/favicon.png",
  },
};

export const viewport: Viewport = {
  themeColor: "#00d4ff",
  width: "device-width",
  initialScale: 1,
};

/* ═══ JSON-LD ═══ */
function JsonLd() {
  const data = {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: SITE.name,
    url: SITE.url,
    description: SITE.description,
    inLanguage: "fr",
    publisher: {
      "@type": "Organization",
      name: SITE.name,
      logo: { "@type": "ImageObject", url: `${SITE.url}/images/carthage_logo.png` },
    },
    potentialAction: {
      "@type": "SearchAction",
      target: `${SITE.url}/exercises/{search_term_string}`,
      "query-input": "required name=search_term_string",
    },
  };
  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }}
    />
  );
}

function CourseJsonLd() {
  const courses = [
    { name: "Formation Front-End (HTML, CSS, Bootstrap, SCSS)", desc: "250 exercices interactifs" },
    { name: "Formation JavaScript", desc: "Maîtrisez le langage du web moderne" },
    { name: "Formation Python", desc: "IA, data science et automatisation" },
    { name: "Formation C# .NET", desc: "Applications desktop et serveur" },
    { name: "Formation Dart & Flutter", desc: "Applications mobiles multiplateformes" },
  ];
  const data = {
    "@context": "https://schema.org",
    "@type": "ItemList",
    itemListElement: courses.map((c, i) => ({
      "@type": "Course",
      position: i + 1,
      name: c.name,
      description: c.desc,
      provider: { "@type": "Organization", name: SITE.name },
      isAccessibleForFree: true,
      inLanguage: "fr",
    })),
  };
  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }}
    />
  );
}

/* ═══ ROOT LAYOUT ═══ */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" suppressHydrationWarning>
      <head />
      <body
        className={`${inter.variable} ${orbitron.variable} ${shareTechMono.variable} scanlines font-sans antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem={false} themes={["dark", "light"]}>
          <AuthProvider>
            <SoundProvider>
              <VideoTransitionProvider>
                <Navbar />
                <main>{children}</main>
                <Footer />
              </VideoTransitionProvider>
            </SoundProvider>
          </AuthProvider>
        </ThemeProvider>
        <JsonLd />
        <CourseJsonLd />
      </body>
    </html>
  );
}
